@0xbec81a95d81e7e95;

# Code generated by protoc-gen-buffers. DO NOT EDIT.
# versions:
# 	protoc-gen-buffers dev
# 	protoc (unknown)
# source: protobuf/covesa/vdm/charging_points/v1/instance_tag.proto
#
# target: capnp
# field slots below are recorded in buffers.lock; edit the .proto, not this file
#
# https://github.com/the-protobuf-project/buffers
using Cxx = import "/capnp/c++.capnp";
$Cxx.namespace("protobuf::covesa::vdm::charging_points::v1");

# AreaInStation is an allowed-value set from the specification.
#
# VSS: ChargingStation.ChargingPoints.InstanceTag.Area.
# (buffers.v1.enumeration).underlying asked for 32 bits. A Cap'n Proto enum is
# always 16, with no way to declare otherwise; the narrowing is honoured by
# the FlatBuffers target only.
enum AreaInStation @0xece311efd23952e7 {
  # Not specified.
  unspecified @0;
  # Underground.
  underground @1;
  # Outdoor.
  outdoor @2;
}

# ChargingPointLabel is an allowed-value set from the specification.
#
# VSS: ChargingStation.ChargingPoints.InstanceTag.Label.
# (buffers.v1.enumeration).underlying asked for 32 bits. A Cap'n Proto enum is
# always 16, with no way to declare otherwise; the narrowing is honoured by
# the FlatBuffers target only.
enum ChargingPointLabel @0xd821e4841ac8fb2a {
  # Not specified.
  unspecified @0;
  # Point a.
  pointA @1;
  # Point b.
  pointB @2;
  # Point c.
  pointC @3;
}

# InstanceTag is a node of the COVESA Vehicle Signal Specification.
#
# VSS: ChargingStation.ChargingPoints.InstanceTag.
#
# Reference: COVESA Vehicle Signal Specification.
# https://covesa.github.io/vehicle_signal_specification/
struct InstanceTag @0x9eb1415eab0f7d9c {
  # Area.
  #
  # VSS: ChargingStation.ChargingPoints.InstanceTag.Area (actuator).
  area @0 :AreaInStation;
  # Label.
  #
  # VSS: ChargingStation.ChargingPoints.InstanceTag.Label (actuator).
  label @1 :ChargingPointLabel;
}
