@0xc85b523b0cbca120;

# Code generated by protoc-gen-buffers. DO NOT EDIT.
# versions:
# 	protoc-gen-buffers dev
# 	protoc (unknown)
# source: protobuf/covesa/vdm/charging_points/v1/location.proto
#
# target: capnp
# field slots below are recorded in buffers.lock; edit the .proto, not this file
#
# https://github.com/the-protobuf-project/buffers
using Cxx = import "/capnp/c++.capnp";
$Cxx.namespace("protobuf::covesa::vdm::charging_points::v1");

# Location is a node of the COVESA Vehicle Signal Specification.
#
# VSS: ChargingStation.ChargingPoints.Location.
#
# Reference: COVESA Vehicle Signal Specification.
# https://covesa.github.io/vehicle_signal_specification/
struct Location @0x8222e3514740ae01 {
  # Street.
  #
  # VSS: ChargingStation.ChargingPoints.Location.Street (actuator).
  street @0 :Text;
  # City.
  #
  # VSS: ChargingStation.ChargingPoints.Location.City (actuator).
  city @1 :Text;
  # Administrative area.
  #
  # VSS: ChargingStation.ChargingPoints.Location.State (actuator).
  administrativeArea @2 :Text;
  # Region code.
  #
  # An ISO 3166-1 alpha-2 country code, e.g. "SE".
  #
  # A string rather than an enum, per AIP-143 <https://aip.dev/143>: the
  # code list belongs to ISO and changes without reference to this schema.
  #
  # VSS: ChargingStation.ChargingPoints.Location.Country (actuator).
  regionCode @3 :Text;
  # Zip code.
  #
  # VSS: ChargingStation.ChargingPoints.Location.ZipCode (actuator).
  zipCode @4 :Text;
}
