@0xd506f32b823bf401;

# Code generated by protoc-gen-buffers. DO NOT EDIT.
# versions:
# 	protoc-gen-buffers dev
# 	protoc (unknown)
# source: protobuf/covesa/vdm/charging_points/v1/service.proto
#
# target: capnp
# field slots below are recorded in buffers.lock; edit the .proto, not this file
#
# https://github.com/the-protobuf-project/buffers
using Cxx = import "/capnp/c++.capnp";
$Cxx.namespace("protobuf::covesa::vdm::charging_points::v1");

using ChargingPoints = import "/protobuf/covesa/vdm/charging_points/v1/charging_points.capnp";
using Messages = import "/protobuf/covesa/vdm/charging_points/v1/messages.capnp";

# ChargingPointses manages the ChargingPoints branch of a vehicle.
#
# A vehicle may hold several, so this is an ordinary collection with the
# AIP-131..135 standard methods plus AIP-164 <https://aip.dev/164> undelete.
#
# Reference: COVESA Vehicle Signal Specification.
# https://covesa.github.io/vehicle_signal_specification/
interface ChargingPointses @0x9002b203ee394fb6 {
  # Retrieves one ChargingPoints.
  #
  # GET /v1/{name=chargingStations/*/chargingPointses/*}
  #
  # Safe and idempotent. Read the `etag` here and pass it back on update to
  # make the write conditional.
  #
  # NOT_FOUND no such ChargingPoints
  # INVALID_ARGUMENT name does not match the resource pattern
  # PERMISSION_DENIED caller may not read it
  # AIP-131 standard method.
  getChargingPoints @0 (request :Messages.GetChargingPointsRequest) -> (response :ChargingPoints.ChargingPoints);

  # Lists the chargingPointses of one vehicle.
  #
  # GET /v1/{parent=chargingStations/*}/chargingPointses
  #
  # Paginated per AIP-158 <https://aip.dev/158>: pass `page_size` (defaults
  # to 50, capped at 1000) and the `next_page_token` from the previous
  # response. Page tokens are opaque and may expire; do not construct or
  # store them.
  #
  # INVALID_ARGUMENT malformed filter, or page_size out of range
  # PERMISSION_DENIED caller may not list this collection
  # AIP-132 standard method.
  listChargingPointses @1 (request :Messages.ListChargingPointsesRequest) -> (response :Messages.ListChargingPointsesResponse);

  # Creates a ChargingPoints.
  #
  # POST /v1/{parent=chargingStations/*}/chargingPointses
  # body: the ChargingPoints itself
  #
  # Server-assigned fields on the request body are ignored: `name`, `uid`,
  # `etag` and the server timestamps are set regardless of what is sent.
  #
  # Not idempotent. Retrying after a timeout may create a second
  # ChargingPoints; supply `charging_points_id` if the caller needs retry
  # safety.
  #
  # ALREADY_EXISTS that id is taken
  # INVALID_ARGUMENT a field violates its buf.validate constraint
  # PERMISSION_DENIED caller may not create here
  # AIP-133 standard method.
  createChargingPoints @2 (request :Messages.CreateChargingPointsRequest) -> (response :ChargingPoints.ChargingPoints);

  # Updates a ChargingPoints.
  #
  # PATCH /v1/{charging_points.name=chargingStations/*/chargingPointses/*}
  # body: the ChargingPoints itself
  #
  # A partial update: only fields named in `update_mask` are written. An
  # empty mask writes every mutable field, which will clear anything the
  # caller left unset -- pass a mask unless that is the intent.
  #
  # **Only an actuator is writable.** VSS marks each signal an attribute, a
  # sensor or an actuator; the first two are OUTPUT_ONLY here, because a
  # vehicle reports them and no API call can change them. A mask naming one
  # is rejected rather than silently ignored.
  #
  # Idempotent. Pass the `etag` read from Get to make the write conditional.
  #
  # NOT_FOUND no such ChargingPoints
  # ABORTED etag does not match the stored resource
  # INVALID_ARGUMENT mask names an unknown, immutable or read-only field
  # PERMISSION_DENIED caller may not modify it
  # AIP-134 standard method.
  updateChargingPoints @3 (request :Messages.UpdateChargingPointsRequest) -> (response :ChargingPoints.ChargingPoints);

  # Deletes a ChargingPoints.
  #
  # DELETE /v1/{name=chargingStations/*/chargingPointses/*}
  #
  # Soft delete: the ChargingPoints is marked deleted, disappears from List
  # unless `show_deleted` is set, and is purged at `expire_time`. Recover it
  # with UndeleteChargingPoints before then.
  #
  # Idempotent in effect but not in reporting: a second delete returns
  # NOT_FOUND rather than succeeding silently.
  #
  # NOT_FOUND no such ChargingPoints
  # ABORTED etag does not match
  # PERMISSION_DENIED caller may not delete it
  # AIP-135 standard method.
  deleteChargingPoints @4 (request :Messages.DeleteChargingPointsRequest) -> ();

  # Restores a soft-deleted ChargingPoints.
  #
  # POST /v1/{name=chargingStations/*/chargingPointses/*}:undelete
  #
  # Valid only before `expire_time`; after that the ChargingPoints is gone
  # and this returns NOT_FOUND. Clears `delete_time` and `expire_time`.
  #
  # NOT_FOUND no such ChargingPoints, or already purged
  # ALREADY_EXISTS the ChargingPoints is not deleted
  # PERMISSION_DENIED caller may not restore it
  # AIP-164 standard method.
  undeleteChargingPoints @5 (request :Messages.UndeleteChargingPointsRequest) -> (response :ChargingPoints.ChargingPoints);
}
