@0xe147b0b0e2194e57;

# Code generated by protoc-gen-buffers. DO NOT EDIT.
# versions:
# 	protoc-gen-buffers dev
# 	protoc (unknown)
# source: protobuf/covesa/vss/platform/diagnostics/v1/messages.proto
#
# target: capnp
# field slots below are recorded in buffers.lock; edit the .proto, not this file
#
# https://github.com/the-protobuf-project/buffers
using Cxx = import "/capnp/c++.capnp";
$Cxx.namespace("protobuf::covesa::vss::platform::diagnostics::v1");

using Diagnostics = import "/protobuf/covesa/vss/platform/diagnostics/v1/diagnostics.capnp";

# Request message for DiagnosticsService.GetDiagnostics, AIP-131
# <https://aip.dev/131>.
struct GetDiagnosticsRequest @0xbe20e6dc485fe9a1 {
  # Name of the Diagnostics to retrieve, "vehicles/{vehicle}/diagnostics".
  # REQUIRED (AIP-203); Cap'n Proto cannot enforce it.
  name @0 :Text;
}

# Request message for DiagnosticsService.UpdateDiagnostics, AIP-134
# <https://aip.dev/134>.
struct UpdateDiagnosticsRequest @0x92415b07ac9a806c {
  # The Diagnostics to update. Its name field identifies the resource.
  # REQUIRED (AIP-203); Cap'n Proto cannot enforce it.
  diagnostics @0 :Diagnostics.Diagnostics;
  # Fields to update. An empty mask updates all mutable fields.
  #
  # Only an actuator is writable. A sensor or attribute named in the mask is
  # rejected: both are OUTPUT_ONLY, because a vehicle reports them and an
  # API cannot set them.
  updateMask @1 :List(Text);
}
