@0xf212c06647d811e0;

# Code generated by protoc-gen-buffers. DO NOT EDIT.
# versions:
# 	protoc-gen-buffers dev
# 	protoc (unknown)
# source: protobuf/covesa/vss/propulsion/charging_port/v1/charging_port.proto
#
# target: capnp
# field slots below are recorded in buffers.lock; edit the .proto, not this file
#
# https://github.com/the-protobuf-project/buffers
using Cxx = import "/capnp/c++.capnp";
$Cxx.namespace("protobuf::covesa::vss::propulsion::charging_port::v1");

using Wellknown = import "/buffers/wellknown.capnp";

# A list of the supported (i.e., available) charging inlets in a particular
# charging port. IEC types refer to IEC 62196, GBT refers to GB/T 20234.
#
# VSS:
# Vehicle.Powertrain.TractionBattery.Charging.ChargingPort.SupportedInletTypes.
# (buffers.v1.enumeration).underlying asked for 32 bits. A Cap'n Proto enum is
# always 16, with no way to declare otherwise; the narrowing is honoured by
# the FlatBuffers target only.
enum SupportedInletTypes @0xc65bb397fd0fd6da {
  # Not specified.
  unspecified @0;
  # Iec type 1 ac.
  iecType1Ac @1;
  # Iec type 2 ac.
  iecType2Ac @2;
  # Iec type 3 ac.
  iecType3Ac @3;
  # Iec type 4 dc.
  iecType4Dc @4;
  # Iec type 1 ccs dc.
  iecType1CcsDc @5;
  # Iec type 2 ccs dc.
  iecType2CcsDc @6;
  # Tesla roadster.
  teslaRoadster @7;
  # Tesla hpwc.
  teslaHpwc @8;
  # Tesla supercharger.
  teslaSupercharger @9;
  # Gbt ac.
  gbtAc @10;
  # Gbt dc.
  gbtDc @11;
  # Other.
  other @12;
}

# Properties related to a particular charging port available in the vehicle.
#
# If a vehicle has a single charging port, then use the instance
# AnyPosition.
#
# VSS: Vehicle.Powertrain.TractionBattery.Charging.ChargingPort.
#
# Instanced: FrontLeft, FrontMiddle, FrontRight, RearLeft, RearMiddle,
# RearRight, AnyPosition. The axes together name one occurrence, which is
# why each is a resource of its own rather than a repeated field.
#
# A child resource of Powertrain, named
# "vehicles/{vehicle}/chargingPorts/{charging_port}". Its parent is a
# declared resource in protobuf.covesa.vss.propulsion.powertrain.v1, which
# is what makes this pattern legal rather than a reference to a collection
# nothing can create.
#
# Reference: COVESA Vehicle Signal Specification.
# https://covesa.github.io/vehicle_signal_specification/
struct ChargingPort @0xea2087a34de82730 {
  # Resource name, "vehicles/{vehicle}/chargingPorts/{charging_port}".
  # Assigned by the server.
  name @0 :Text;
  # Server-assigned unique id.
  uid @1 :Text;
  # Weak validator for optimistic concurrency, AIP-154
  # <https://aip.dev/154>.
  etag @2 :Text;
  # When this resource was soft-deleted, unset while it is live. AIP-164
  # <https://aip.dev/164>.
  deleteTime @3 :Wellknown.Timestamp;
  # When a soft-deleted resource is purged for good. AIP-164
  # <https://aip.dev/164>.
  expireTime @4 :Wellknown.Timestamp;
  # When this resource was created.
  createTime @5 :Wellknown.Timestamp;
  # When this resource was last modified.
  updateTime @6 :Wellknown.Timestamp;
  # proto field 8 was removed and reserved; this holds its ordinal.
  removed8 @7 :Void;
  # proto field 9 was removed and reserved; this holds its ordinal.
  removed9 @8 :Void;
  # proto field 10 was removed and reserved; this holds its ordinal.
  removed10 @9 :Void;
  # proto field 11 was removed and reserved; this holds its ordinal.
  removed11 @10 :Void;
  # proto field 12 was removed and reserved; this holds its ordinal.
  removed12 @11 :Void;
  # proto field 13 was removed and reserved; this holds its ordinal.
  removed13 @12 :Void;
  # proto field 14 was removed and reserved; this holds its ordinal.
  removed14 @13 :Void;
  # proto field 15 was removed and reserved; this holds its ordinal.
  removed15 @14 :Void;
  # A list of the supported (i.e., available) charging inlets in a
  # particular charging port. IEC types refer to IEC 62196, GBT refers to
  # GB/T 20234.
  #
  # A vehicle may have multiple charging ports. IEC_TYPE_1_AC refers to Type
  # 1 as defined in IEC 62196-2. Also known as Yazaki or J1772 connector.
  # IEC_TYPE_2_AC refers to Type 2 as defined in IEC 62196-2. Also known as
  # Mennekes connector. IEC_TYPE_3_AC refers to Type 3 as defined in IEC
  # 62196-2. Also known as Scame connector. IEC_TYPE_4_DC refers to AA
  # configuration as defined in IEC 62196-3. Also known as Type 4 or CHAdeMO
  # connector. IEC_TYPE_1_CCS_DC refers to EE Configuration as defined in
  # IEC 62196-3. Also known as CCS1 or Combo1 connector. IEC_TYPE_2_CCS_DC
  # refers to FF Configuration as defined in IEC 62196-3. Also known as CCS2
  # or Combo2 connector. TESLA_ROADSTER, TESLA_HPWC (High Power Wall
  # Connector) and TESLA_SUPERCHARGER refer to non-standardized charging
  # ports/methods used by Tesla. GBT_AC refers to connector specified in
  # GB/T 20234.2. GBT_DC refers to connector specified in GB/T 20234.3. Also
  # specified as BB Configuration in IEC 62196-3. OTHER shall be used for
  # charging ports not included in the list above. For additional
  # information see https://en.wikipedia.org/wiki/IEC_62196.
  #
  # VSS:
  # Vehicle.Powertrain.TractionBattery.Charging.ChargingPort.SupportedInletTypes
  # (attribute).
  supportedInletTypes @15 :List(SupportedInletTypes);
  # Status of the charging port flap(s).
  #
  # True = at least one flap of this port is open, False = All flaps of this
  # port are closed.
  #
  # VSS: Vehicle.Powertrain.TractionBattery.Charging.ChargingPort.IsFlapOpen
  # (actuator).
  isFlapOpen @16 :Bool;
  # Indicates whether a charging cable is physically connected to a
  # particular charging port or not.
  #
  # VSS:
  # Vehicle.Powertrain.TractionBattery.Charging.ChargingPort.IsChargingCableConnected
  # (sensor).
  isChargingCableConnected @17 :Bool;
  # Is charging cable locked to prevent removal.
  #
  # Locking of charging cable can be used to prevent unintentional removing
  # during charging.
  #
  # VSS:
  # Vehicle.Powertrain.TractionBattery.Charging.ChargingPort.IsChargingCableLocked
  # (actuator).
  isChargingCableLocked @18 :Bool;
}
