@0xfad475c79e660945;

# Code generated by protoc-gen-buffers. DO NOT EDIT.
# versions:
# 	protoc-gen-buffers dev
# 	protoc (unknown)
# source: protobuf/covesa/vss/propulsion/charging_port/v1/messages.proto
#
# target: capnp
# field slots below are recorded in buffers.lock; edit the .proto, not this file
#
# https://github.com/the-protobuf-project/buffers
using Cxx = import "/capnp/c++.capnp";
$Cxx.namespace("protobuf::covesa::vss::propulsion::charging_port::v1");

using ChargingPort = import "/protobuf/covesa/vss/propulsion/charging_port/v1/charging_port.capnp";

# Request message for ChargingPorts.GetChargingPort, AIP-131
# <https://aip.dev/131>.
struct GetChargingPortRequest @0xccb874078ecbf3ef {
  # Name of the ChargingPort to retrieve,
  # "vehicles/{vehicle}/chargingPorts/{charging_port}".
  # REQUIRED (AIP-203); Cap'n Proto cannot enforce it.
  name @0 :Text;
}

# Request message for ChargingPorts.ListChargingPorts, AIP-132
# <https://aip.dev/132>.
struct ListChargingPortsRequest @0x990b0746300be4a7 {
  # The Vehicle whose chargingPorts to list, "vehicles/{vehicle}".
  # REQUIRED (AIP-203); Cap'n Proto cannot enforce it.
  parent @0 :Text;
  # Maximum chargingPorts to return. Defaults to 50, capped at 1000.
  pageSize @1 :Int32;
  # Page token from a previous ListChargingPortsResponse.next_page_token.
  pageToken @2 :Text;
  # Filter expression, AIP-160 <https://aip.dev/160>.
  filter @3 :Text;
  # Include soft-deleted chargingPorts. AIP-164 <https://aip.dev/164>.
  showDeleted @4 :Bool;
}

# Response message for ChargingPorts.ListChargingPorts, AIP-132
# <https://aip.dev/132>.
struct ListChargingPortsResponse @0x9e90165a8fe95859 {
  # The chargingPorts on this page.
  chargingPorts @0 :List(ChargingPort.ChargingPort);
  # Token for the next page, empty when this is the last page.
  nextPageToken @1 :Text;
}

# Request message for ChargingPorts.CreateChargingPort, AIP-133
# <https://aip.dev/133>.
struct CreateChargingPortRequest @0xc53ca23d9b5b9efd {
  # The Vehicle to create the ChargingPort under, "vehicles/{vehicle}".
  # REQUIRED (AIP-203); Cap'n Proto cannot enforce it.
  parent @0 :Text;
  # The ChargingPort to create.
  # REQUIRED (AIP-203); Cap'n Proto cannot enforce it.
  chargingPort @1 :ChargingPort.ChargingPort;
  # Client-assigned id, becoming the last segment of the resource name. The
  # server generates one when empty.
  chargingPortId @2 :Text;
}

# Request message for ChargingPorts.UpdateChargingPort, AIP-134
# <https://aip.dev/134>.
struct UpdateChargingPortRequest @0xd0e9293dab858fb0 {
  # The ChargingPort to update. Its name field identifies the resource.
  # REQUIRED (AIP-203); Cap'n Proto cannot enforce it.
  chargingPort @0 :ChargingPort.ChargingPort;
  # Fields to update. An empty mask updates all mutable fields.
  #
  # Only an actuator is writable. A sensor or attribute named in the mask is
  # rejected: both are OUTPUT_ONLY, because a vehicle reports them and an
  # API cannot set them.
  updateMask @1 :List(Text);
}

# Request message for ChargingPorts.DeleteChargingPort, AIP-135
# <https://aip.dev/135>.
struct DeleteChargingPortRequest @0xad9b5be6891890d2 {
  # Name of the ChargingPort to delete,
  # "vehicles/{vehicle}/chargingPorts/{charging_port}".
  # REQUIRED (AIP-203); Cap'n Proto cannot enforce it.
  name @0 :Text;
}

# Request message for ChargingPorts.UndeleteChargingPort, AIP-164
# <https://aip.dev/164>.
struct UndeleteChargingPortRequest @0xf41a23d1a431c50e {
  # Name of the soft-deleted ChargingPort to restore,
  # "vehicles/{vehicle}/chargingPorts/{charging_port}".
  # REQUIRED (AIP-203); Cap'n Proto cannot enforce it.
  name @0 :Text;
}
