@0xc30f01c81312e14c;

# Code generated by protoc-gen-buffers. DO NOT EDIT.
# versions:
# 	protoc-gen-buffers dev
# 	protoc (unknown)
# source: protobuf/covesa/vss/motion/electric_axle/v1/electric_axle.proto
#
# target: capnp
# field slots below are recorded in buffers.lock; edit the .proto, not this file
#
# https://github.com/the-protobuf-project/buffers
using Cxx = import "/capnp/c++.capnp";
$Cxx.namespace("protobuf::covesa::vss::motion::electric_axle::v1");

using Wellknown = import "/buffers/wellknown.capnp";

# MotionManagement for a specific electric axle.
#
# VSS: Vehicle.MotionManagement.ElectricAxle.
#
# Instanced: Row1, Row2. The axes together name one occurrence, which is why
# each is a resource of its own rather than a repeated field.
#
# A child resource of MotionManagement, named
# "vehicles/{vehicle}/electricAxles/{electric_axle}". Its parent is a
# declared resource in protobuf.covesa.vss.motion.motion_management.v1,
# which is what makes this pattern legal rather than a reference to a
# collection nothing can create.
#
# Reference: COVESA Vehicle Signal Specification.
# https://covesa.github.io/vehicle_signal_specification/
struct ElectricAxle @0xe07cd8e5b17184e3 {
  # Resource name, "vehicles/{vehicle}/electricAxles/{electric_axle}".
  # Assigned by the server.
  name @0 :Text;
  # Server-assigned unique id.
  uid @1 :Text;
  # Weak validator for optimistic concurrency, AIP-154
  # <https://aip.dev/154>.
  etag @2 :Text;
  # When this resource was soft-deleted, unset while it is live. AIP-164
  # <https://aip.dev/164>.
  deleteTime @3 :Wellknown.Timestamp;
  # When a soft-deleted resource is purged for good. AIP-164
  # <https://aip.dev/164>.
  expireTime @4 :Wellknown.Timestamp;
  # When this resource was created.
  createTime @5 :Wellknown.Timestamp;
  # When this resource was last modified.
  updateTime @6 :Wellknown.Timestamp;
  # proto field 8 was removed and reserved; this holds its ordinal.
  removed8 @7 :Void;
  # proto field 9 was removed and reserved; this holds its ordinal.
  removed9 @8 :Void;
  # proto field 10 was removed and reserved; this holds its ordinal.
  removed10 @9 :Void;
  # proto field 11 was removed and reserved; this holds its ordinal.
  removed11 @10 :Void;
  # proto field 12 was removed and reserved; this holds its ordinal.
  removed12 @11 :Void;
  # proto field 13 was removed and reserved; this holds its ordinal.
  removed13 @12 :Void;
  # proto field 14 was removed and reserved; this holds its ordinal.
  removed14 @13 :Void;
  # proto field 15 was removed and reserved; this holds its ordinal.
  removed15 @14 :Void;
  # Axle torque, positive sign for torque in forward direction, negative
  # sign for torque in backward direction.
  #
  # Unit: Nm. VSS: Vehicle.MotionManagement.ElectricAxle.Torque (sensor).
  torque @15 :Int32;
  # Target axle torque in torque control mode, positive sign for torque in
  # forward direction, negative sign for torque in backward direction
  # (ISO8855).
  #
  # Unit: Nm. VSS: Vehicle.MotionManagement.ElectricAxle.TorqueTarget
  # (actuator).
  torqueTarget @16 :Int32;
  # Maximum momentarily available eAxle torque, positive sign for torque in
  # forward direction, negative sign for torque in backward direction.
  #
  # Unit: Nm. VSS: Vehicle.MotionManagement.ElectricAxle.TorqueMaximum
  # (sensor).
  torqueMaximum @17 :Int32;
  # Minimum momentarily available eAxle torque, positive sign for torque in
  # forward direction, negative sign for torque in backward direction.
  #
  # Unit: Nm. VSS: Vehicle.MotionManagement.ElectricAxle.TorqueMinimum
  # (sensor).
  torqueMinimum @18 :Int32;
  # Maximum allowed eAxle torque in rotation speed control mode, positive
  # sign for torque in forward direction, negative sign unused.
  #
  # Unit: Nm. VSS: Vehicle.MotionManagement.ElectricAxle.TorqueMaximumLimit
  # (actuator).
  torqueMaximumLimit @19 :Int32;
  # Minimum allowed axle torque in rotation speed control mode, positive
  # sign unused, negative sign for torque in backward direction (ISO8855).
  #
  # Unit: Nm. VSS: Vehicle.MotionManagement.ElectricAxle.TorqueMinimumLimit
  # (actuator).
  torqueMinimumLimit @20 :Int32;
  # Rotational speed for the specified axle, positive sign for rotation in
  # forward direction, negative sign for rotation in backward direction.
  #
  # Unit: rpm. VSS: Vehicle.MotionManagement.ElectricAxle.RotationalSpeed
  # (sensor).
  rotationalSpeed @21 :Int32;
  # Target axle rotational speed in rotation speed control mode, positive
  # sign for rotation in forward direction, negative sign for rotation in
  # backward direction.
  #
  # Unit: rpm. VSS:
  # Vehicle.MotionManagement.ElectricAxle.RotationalSpeedTarget (actuator).
  rotationalSpeedTarget @22 :Int32;
  # Maximum allowed axle rotational speed in torque control mode, positive
  # sign for rotation in forward direction, negative sign for rotation in
  # backward direction.
  #
  # Unit: rpm. VSS:
  # Vehicle.MotionManagement.ElectricAxle.RotationalSpeedMaximumLimit
  # (actuator).
  rotationalSpeedMaximumLimit @23 :Int32;
  # Minimum allowed axle rotational speed in torque control mode, positive
  # sign for rotation in forward direction, negative sign for rotation in
  # backward direction.
  #
  # Unit: rpm. VSS:
  # Vehicle.MotionManagement.ElectricAxle.RotationalSpeedMinimumLimit
  # (actuator).
  rotationalSpeedMinimumLimit @24 :Int32;
}
