@0xa58950e975436054;

# Code generated by protoc-gen-buffers. DO NOT EDIT.
# versions:
# 	protoc-gen-buffers dev
# 	protoc (unknown)
# source: protobuf/covesa/vss/platform/service/v1/messages.proto
#
# target: capnp
# field slots below are recorded in buffers.lock; edit the .proto, not this file
#
# https://github.com/the-protobuf-project/buffers
using Cxx = import "/capnp/c++.capnp";
$Cxx.namespace("protobuf::covesa::vss::platform::service::v1");

using ServiceResource = import "/protobuf/covesa/vss/platform/service/v1/service_resource.capnp";

# Request message for Services.GetService, AIP-131 <https://aip.dev/131>.
struct GetServiceRequest @0x9d63897e9f0e9ef9 {
  # Name of the Service to retrieve, "vehicles/{vehicle}/service".
  # REQUIRED (AIP-203); Cap'n Proto cannot enforce it.
  name @0 :Text;
}

# Request message for Services.UpdateService, AIP-134 <https://aip.dev/134>.
struct UpdateServiceRequest @0xc7621b082cc03f17 {
  # The Service to update. Its name field identifies the resource.
  # REQUIRED (AIP-203); Cap'n Proto cannot enforce it.
  service @0 :ServiceResource.Service;
  # Fields to update. An empty mask updates all mutable fields.
  #
  # Only an actuator is writable. A sensor or attribute named in the mask is
  # rejected: both are OUTPUT_ONLY, because a vehicle reports them and an
  # API cannot set them.
  updateMask @1 :List(Text);
}
