@0x88583da52ba716b7;

# Code generated by protoc-gen-buffers. DO NOT EDIT.
# versions:
# 	protoc-gen-buffers dev
# 	protoc (unknown)
# source: protobuf/covesa/vss/platform/service/v1/service_resource.proto
#
# target: capnp
# field slots below are recorded in buffers.lock; edit the .proto, not this file
#
# https://github.com/the-protobuf-project/buffers
using Cxx = import "/capnp/c++.capnp";
$Cxx.namespace("protobuf::covesa::vss::platform::service::v1");

using Wellknown = import "/buffers/wellknown.capnp";

# Service data.
#
# VSS: Vehicle.Service.
#
# A singleton child resource of Vehicle, AIP-156 <https://aip.dev/156>,
# named "vehicles/{vehicle}/service". Its parent is a declared resource in
# protobuf.covesa.vss.vehicle.v1, which is what makes this pattern legal
# rather than a reference to a collection nothing can create.
#
# Reference: COVESA Vehicle Signal Specification.
# https://covesa.github.io/vehicle_signal_specification/
struct Service @0xea0f0abd2603649a {
  # Resource name, "vehicles/{vehicle}/service". Assigned by the server.
  name @0 :Text;
  # Server-assigned unique id.
  uid @1 :Text;
  # Weak validator for optimistic concurrency, AIP-154
  # <https://aip.dev/154>.
  etag @2 :Text;
  # When this resource was soft-deleted, unset while it is live. AIP-164
  # <https://aip.dev/164>.
  deleteTime @3 :Wellknown.Timestamp;
  # When a soft-deleted resource is purged for good. AIP-164
  # <https://aip.dev/164>.
  expireTime @4 :Wellknown.Timestamp;
  # When this resource was created.
  createTime @5 :Wellknown.Timestamp;
  # When this resource was last modified.
  updateTime @6 :Wellknown.Timestamp;
  # proto field 8 was removed and reserved; this holds its ordinal.
  removed8 @7 :Void;
  # proto field 9 was removed and reserved; this holds its ordinal.
  removed9 @8 :Void;
  # proto field 10 was removed and reserved; this holds its ordinal.
  removed10 @9 :Void;
  # proto field 11 was removed and reserved; this holds its ordinal.
  removed11 @10 :Void;
  # proto field 12 was removed and reserved; this holds its ordinal.
  removed12 @11 :Void;
  # proto field 13 was removed and reserved; this holds its ordinal.
  removed13 @12 :Void;
  # proto field 14 was removed and reserved; this holds its ordinal.
  removed14 @13 :Void;
  # proto field 15 was removed and reserved; this holds its ordinal.
  removed15 @14 :Void;
  # Indicates if vehicle needs service (of any kind). True = Service needed
  # now or in the near future. False = No known need for service.
  #
  # VSS: Vehicle.Service.IsServiceDue (sensor).
  isServiceDue @15 :Bool;
  # Remaining distance to service (of any kind). Negative values indicate
  # service overdue.
  #
  # Unit: km. VSS: Vehicle.Service.DistanceToService (sensor).
  serviceDistance @16 :Float64;
  # Remaining time to service (of any kind). Negative values indicate
  # service overdue.
  #
  # Unit: s. VSS: Vehicle.Service.TimeToService (sensor).
  serviceDuration @17 :Wellknown.Duration;
}
