@0xfc7b8b08a911fe9e;

# Code generated by protoc-gen-buffers. DO NOT EDIT.
# versions:
# 	protoc-gen-buffers dev
# 	protoc (unknown)
# source: protobuf/covesa/vss/exterior/trunk/v1/messages.proto
#
# target: capnp
# field slots below are recorded in buffers.lock; edit the .proto, not this file
#
# https://github.com/the-protobuf-project/buffers
using Cxx = import "/capnp/c++.capnp";
$Cxx.namespace("protobuf::covesa::vss::exterior::trunk::v1");

using Trunk = import "/protobuf/covesa/vss/exterior/trunk/v1/trunk.capnp";

# Request message for Trunks.GetTrunk, AIP-131 <https://aip.dev/131>.
struct GetTrunkRequest @0xcef2333005e5b975 {
  # Name of the Trunk to retrieve, "vehicles/{vehicle}/trunks/{trunk}".
  # REQUIRED (AIP-203); Cap'n Proto cannot enforce it.
  name @0 :Text;
}

# Request message for Trunks.ListTrunks, AIP-132 <https://aip.dev/132>.
struct ListTrunksRequest @0x977d6da75b21749b {
  # The Vehicle whose trunks to list, "vehicles/{vehicle}".
  # REQUIRED (AIP-203); Cap'n Proto cannot enforce it.
  parent @0 :Text;
  # Maximum trunks to return. Defaults to 50, capped at 1000.
  pageSize @1 :Int32;
  # Page token from a previous ListTrunksResponse.next_page_token.
  pageToken @2 :Text;
  # Filter expression, AIP-160 <https://aip.dev/160>.
  filter @3 :Text;
  # Include soft-deleted trunks. AIP-164 <https://aip.dev/164>.
  showDeleted @4 :Bool;
}

# Response message for Trunks.ListTrunks, AIP-132 <https://aip.dev/132>.
struct ListTrunksResponse @0xfa11e5779b080dbf {
  # The trunks on this page.
  trunks @0 :List(Trunk.Trunk);
  # Token for the next page, empty when this is the last page.
  nextPageToken @1 :Text;
}

# Request message for Trunks.CreateTrunk, AIP-133 <https://aip.dev/133>.
struct CreateTrunkRequest @0xde1e88726ef0005b {
  # The Vehicle to create the Trunk under, "vehicles/{vehicle}".
  # REQUIRED (AIP-203); Cap'n Proto cannot enforce it.
  parent @0 :Text;
  # The Trunk to create.
  # REQUIRED (AIP-203); Cap'n Proto cannot enforce it.
  trunk @1 :Trunk.Trunk;
  # Client-assigned id, becoming the last segment of the resource name. The
  # server generates one when empty.
  trunkId @2 :Text;
}

# Request message for Trunks.UpdateTrunk, AIP-134 <https://aip.dev/134>.
struct UpdateTrunkRequest @0xab6632580dc498d9 {
  # The Trunk to update. Its name field identifies the resource.
  # REQUIRED (AIP-203); Cap'n Proto cannot enforce it.
  trunk @0 :Trunk.Trunk;
  # Fields to update. An empty mask updates all mutable fields.
  #
  # Only an actuator is writable. A sensor or attribute named in the mask is
  # rejected: both are OUTPUT_ONLY, because a vehicle reports them and an
  # API cannot set them.
  updateMask @1 :List(Text);
}

# Request message for Trunks.DeleteTrunk, AIP-135 <https://aip.dev/135>.
struct DeleteTrunkRequest @0xeb4a827ef2bedb56 {
  # Name of the Trunk to delete, "vehicles/{vehicle}/trunks/{trunk}".
  # REQUIRED (AIP-203); Cap'n Proto cannot enforce it.
  name @0 :Text;
}

# Request message for Trunks.UndeleteTrunk, AIP-164 <https://aip.dev/164>.
struct UndeleteTrunkRequest @0x949d8f91e3a52f18 {
  # Name of the soft-deleted Trunk to restore,
  # "vehicles/{vehicle}/trunks/{trunk}".
  # REQUIRED (AIP-203); Cap'n Proto cannot enforce it.
  name @0 :Text;
}
