@0xd56c3e510b972698;

# Code generated by protoc-gen-buffers. DO NOT EDIT.
# versions:
# 	protoc-gen-buffers dev
# 	protoc (unknown)
# source: protobuf/covesa/vss/exterior/trunk/v1/trunk.proto
#
# target: capnp
# field slots below are recorded in buffers.lock; edit the .proto, not this file
#
# https://github.com/the-protobuf-project/buffers
using Cxx = import "/capnp/c++.capnp";
$Cxx.namespace("protobuf::covesa::vss::exterior::trunk::v1");

using Wellknown = import "/buffers/wellknown.capnp";

# Switch controlling sliding action such as window, sunroof, or blind.
#
# VSS: Vehicle.Body.Trunk.Switch.
# (buffers.v1.enumeration).underlying asked for 32 bits. A Cap'n Proto enum is
# always 16, with no way to declare otherwise; the narrowing is honoured by
# the FlatBuffers target only.
enum Switch @0x94581865dc2c8495 {
  # Not specified.
  unspecified @0;
  # Inactive.
  inactive @1;
  # Close.
  close @2;
  # Open.
  open @3;
  # One shot close.
  oneShotClose @4;
  # One shot open.
  oneShotOpen @5;
}

# Trunk status. Start position for Trunk is Closed.
#
# A trunk is a luggage compartment in a vehicle. Depending on vehicle, it
# can be either in the front or back of the vehicle. Some vehicles may have
# trunks both at the front and at the rear of the vehicle.
#
# VSS: Vehicle.Body.Trunk.
#
# Instanced: Front, Rear. The axes together name one occurrence, which is
# why each is a resource of its own rather than a repeated field.
#
# A child resource of Body, named "vehicles/{vehicle}/trunks/{trunk}". Its
# parent is a declared resource in protobuf.covesa.vss.exterior.body.v1,
# which is what makes this pattern legal rather than a reference to a
# collection nothing can create.
#
# Reference: COVESA Vehicle Signal Specification.
# https://covesa.github.io/vehicle_signal_specification/
struct Trunk @0xd78edfc479c27191 {
  # Resource name, "vehicles/{vehicle}/trunks/{trunk}". Assigned by the
  # server.
  name @0 :Text;
  # Server-assigned unique id.
  uid @1 :Text;
  # Weak validator for optimistic concurrency, AIP-154
  # <https://aip.dev/154>.
  etag @2 :Text;
  # When this resource was soft-deleted, unset while it is live. AIP-164
  # <https://aip.dev/164>.
  deleteTime @3 :Wellknown.Timestamp;
  # When a soft-deleted resource is purged for good. AIP-164
  # <https://aip.dev/164>.
  expireTime @4 :Wellknown.Timestamp;
  # When this resource was created.
  createTime @5 :Wellknown.Timestamp;
  # When this resource was last modified.
  updateTime @6 :Wellknown.Timestamp;
  # proto field 8 was removed and reserved; this holds its ordinal.
  removed8 @7 :Void;
  # proto field 9 was removed and reserved; this holds its ordinal.
  removed9 @8 :Void;
  # proto field 10 was removed and reserved; this holds its ordinal.
  removed10 @9 :Void;
  # proto field 11 was removed and reserved; this holds its ordinal.
  removed11 @10 :Void;
  # proto field 12 was removed and reserved; this holds its ordinal.
  removed12 @11 :Void;
  # proto field 13 was removed and reserved; this holds its ordinal.
  removed13 @12 :Void;
  # proto field 14 was removed and reserved; this holds its ordinal.
  removed14 @13 :Void;
  # proto field 15 was removed and reserved; this holds its ordinal.
  removed15 @14 :Void;
  # Is trunk light on
  #
  # V4.0 Moved from Vehicle.Cabin.Lights.IsTrunkOn because Trunk is not
  # defined as part of the Cabin.
  #
  # VSS: Vehicle.Body.Trunk.IsLightOn (actuator).
  isLightOn @15 :Bool;
  # Is item locked or unlocked. True = Locked. False = Unlocked.
  #
  # VSS: Vehicle.Body.Trunk.IsLocked (actuator).
  isLocked @16 :Bool;
  # Is item open or closed? True = Fully or partially open. False = Fully
  # closed.
  #
  # VSS: Vehicle.Body.Trunk.IsOpen (actuator).
  isOpen @17 :Bool;
  # Item position. 0 = Start position 100 = End position.
  #
  # Relationship between Open/Close and Start/End position is item
  # dependent.
  #
  # Unit: percent. VSS: Vehicle.Body.Trunk.Position (actuator).
  position @18 :Int32;
  # Switch controlling sliding action such as window, sunroof, or blind.
  #
  # VSS: Vehicle.Body.Trunk.Switch (actuator).
  switchControl @19 :Switch;
}
