@0xbe20dc33385b268c;

# Code generated by protoc-gen-buffers. DO NOT EDIT.
# versions:
# 	protoc-gen-buffers dev
# 	protoc (unknown)
# source: protobuf/covesa/vss/exterior/fog/v1/messages.proto
#
# target: capnp
# field slots below are recorded in buffers.lock; edit the .proto, not this file
#
# https://github.com/the-protobuf-project/buffers
using Cxx = import "/capnp/c++.capnp";
$Cxx.namespace("protobuf::covesa::vss::exterior::fog::v1");

using Fog = import "/protobuf/covesa/vss/exterior/fog/v1/fog.capnp";

# Request message for Fogs.GetFog, AIP-131 <https://aip.dev/131>.
struct GetFogRequest @0xdb2895ff96be9dbc {
  # Name of the Fog to retrieve, "vehicles/{vehicle}/fogs/{fog}".
  # REQUIRED (AIP-203); Cap'n Proto cannot enforce it.
  name @0 :Text;
}

# Request message for Fogs.ListFogs, AIP-132 <https://aip.dev/132>.
struct ListFogsRequest @0xd02b464ec26c2cf7 {
  # The Vehicle whose fogs to list, "vehicles/{vehicle}".
  # REQUIRED (AIP-203); Cap'n Proto cannot enforce it.
  parent @0 :Text;
  # Maximum fogs to return. Defaults to 50, capped at 1000.
  pageSize @1 :Int32;
  # Page token from a previous ListFogsResponse.next_page_token.
  pageToken @2 :Text;
  # Filter expression, AIP-160 <https://aip.dev/160>.
  filter @3 :Text;
  # Include soft-deleted fogs. AIP-164 <https://aip.dev/164>.
  showDeleted @4 :Bool;
}

# Response message for Fogs.ListFogs, AIP-132 <https://aip.dev/132>.
struct ListFogsResponse @0xaffd6e1052780615 {
  # The fogs on this page.
  fogs @0 :List(Fog.Fog);
  # Token for the next page, empty when this is the last page.
  nextPageToken @1 :Text;
}

# Request message for Fogs.CreateFog, AIP-133 <https://aip.dev/133>.
struct CreateFogRequest @0xd195b9d9c95ffff8 {
  # The Vehicle to create the Fog under, "vehicles/{vehicle}".
  # REQUIRED (AIP-203); Cap'n Proto cannot enforce it.
  parent @0 :Text;
  # The Fog to create.
  # REQUIRED (AIP-203); Cap'n Proto cannot enforce it.
  fog @1 :Fog.Fog;
  # Client-assigned id, becoming the last segment of the resource name. The
  # server generates one when empty.
  fogId @2 :Text;
}

# Request message for Fogs.UpdateFog, AIP-134 <https://aip.dev/134>.
struct UpdateFogRequest @0xaeb824a597431c9d {
  # The Fog to update. Its name field identifies the resource.
  # REQUIRED (AIP-203); Cap'n Proto cannot enforce it.
  fog @0 :Fog.Fog;
  # Fields to update. An empty mask updates all mutable fields.
  #
  # Only an actuator is writable. A sensor or attribute named in the mask is
  # rejected: both are OUTPUT_ONLY, because a vehicle reports them and an
  # API cannot set them.
  updateMask @1 :List(Text);
}

# Request message for Fogs.DeleteFog, AIP-135 <https://aip.dev/135>.
struct DeleteFogRequest @0xc55843325afee7ac {
  # Name of the Fog to delete, "vehicles/{vehicle}/fogs/{fog}".
  # REQUIRED (AIP-203); Cap'n Proto cannot enforce it.
  name @0 :Text;
}

# Request message for Fogs.UndeleteFog, AIP-164 <https://aip.dev/164>.
struct UndeleteFogRequest @0x9a2fd3261b7c9e63 {
  # Name of the soft-deleted Fog to restore,
  # "vehicles/{vehicle}/fogs/{fog}".
  # REQUIRED (AIP-203); Cap'n Proto cannot enforce it.
  name @0 :Text;
}
