@0x8a60cf067658e4d9;

# Code generated by protoc-gen-buffers. DO NOT EDIT.
# versions:
# 	protoc-gen-buffers dev
# 	protoc (unknown)
# source: protobuf/covesa/vss/motion/suspension_axle/v1/messages.proto
#
# target: capnp
# field slots below are recorded in buffers.lock; edit the .proto, not this file
#
# https://github.com/the-protobuf-project/buffers
using Cxx = import "/capnp/c++.capnp";
$Cxx.namespace("protobuf::covesa::vss::motion::suspension_axle::v1");

using SuspensionAxle = import "/protobuf/covesa/vss/motion/suspension_axle/v1/suspension_axle.capnp";

# Request message for SuspensionAxles.GetSuspensionAxle, AIP-131
# <https://aip.dev/131>.
struct GetSuspensionAxleRequest @0x9d0fad62ba430c30 {
  # Name of the SuspensionAxle to retrieve,
  # "vehicles/{vehicle}/suspensionAxles/{suspension_axle}".
  # REQUIRED (AIP-203); Cap'n Proto cannot enforce it.
  name @0 :Text;
}

# Request message for SuspensionAxles.ListSuspensionAxles, AIP-132
# <https://aip.dev/132>.
struct ListSuspensionAxlesRequest @0xff441a777f196aaf {
  # The Vehicle whose suspensionAxles to list, "vehicles/{vehicle}".
  # REQUIRED (AIP-203); Cap'n Proto cannot enforce it.
  parent @0 :Text;
  # Maximum suspensionAxles to return. Defaults to 50, capped at 1000.
  pageSize @1 :Int32;
  # Page token from a previous ListSuspensionAxlesResponse.next_page_token.
  pageToken @2 :Text;
  # Filter expression, AIP-160 <https://aip.dev/160>.
  filter @3 :Text;
  # Include soft-deleted suspensionAxles. AIP-164 <https://aip.dev/164>.
  showDeleted @4 :Bool;
}

# Response message for SuspensionAxles.ListSuspensionAxles, AIP-132
# <https://aip.dev/132>.
struct ListSuspensionAxlesResponse @0xd6d693fa70422b11 {
  # The suspensionAxles on this page.
  suspensionAxles @0 :List(SuspensionAxle.SuspensionAxle);
  # Token for the next page, empty when this is the last page.
  nextPageToken @1 :Text;
}

# Request message for SuspensionAxles.CreateSuspensionAxle, AIP-133
# <https://aip.dev/133>.
struct CreateSuspensionAxleRequest @0xc7253f85253353a3 {
  # The Vehicle to create the SuspensionAxle under, "vehicles/{vehicle}".
  # REQUIRED (AIP-203); Cap'n Proto cannot enforce it.
  parent @0 :Text;
  # The SuspensionAxle to create.
  # REQUIRED (AIP-203); Cap'n Proto cannot enforce it.
  suspensionAxle @1 :SuspensionAxle.SuspensionAxle;
  # Client-assigned id, becoming the last segment of the resource name. The
  # server generates one when empty.
  suspensionAxleId @2 :Text;
}

# Request message for SuspensionAxles.UpdateSuspensionAxle, AIP-134
# <https://aip.dev/134>.
struct UpdateSuspensionAxleRequest @0xd6beefd5416393cf {
  # The SuspensionAxle to update. Its name field identifies the resource.
  # REQUIRED (AIP-203); Cap'n Proto cannot enforce it.
  suspensionAxle @0 :SuspensionAxle.SuspensionAxle;
  # Fields to update. An empty mask updates all mutable fields.
  #
  # Only an actuator is writable. A sensor or attribute named in the mask is
  # rejected: both are OUTPUT_ONLY, because a vehicle reports them and an
  # API cannot set them.
  updateMask @1 :List(Text);
}

# Request message for SuspensionAxles.DeleteSuspensionAxle, AIP-135
# <https://aip.dev/135>.
struct DeleteSuspensionAxleRequest @0xd0b2762c04e3b93b {
  # Name of the SuspensionAxle to delete,
  # "vehicles/{vehicle}/suspensionAxles/{suspension_axle}".
  # REQUIRED (AIP-203); Cap'n Proto cannot enforce it.
  name @0 :Text;
}

# Request message for SuspensionAxles.UndeleteSuspensionAxle, AIP-164
# <https://aip.dev/164>.
struct UndeleteSuspensionAxleRequest @0xd57cb7c448c72a5d {
  # Name of the soft-deleted SuspensionAxle to restore,
  # "vehicles/{vehicle}/suspensionAxles/{suspension_axle}".
  # REQUIRED (AIP-203); Cap'n Proto cannot enforce it.
  name @0 :Text;
}
