@0xe16dfc7526385990;

# Code generated by protoc-gen-buffers. DO NOT EDIT.
# versions:
# 	protoc-gen-buffers dev
# 	protoc (unknown)
# source: protobuf/covesa/vss/vehicle/v1/messages.proto
#
# target: capnp
# field slots below are recorded in buffers.lock; edit the .proto, not this file
#
# https://github.com/the-protobuf-project/buffers
using Cxx = import "/capnp/c++.capnp";
$Cxx.namespace("protobuf::covesa::vss::vehicle::v1");

using Vehicle = import "/protobuf/covesa/vss/vehicle/v1/vehicle.capnp";

# Request message for Vehicles.GetVehicle, AIP-131 <https://aip.dev/131>.
struct GetVehicleRequest @0xc574b729f035d8ec {
  # Name of the Vehicle to retrieve, "vehicles/{vehicle}".
  # REQUIRED (AIP-203); Cap'n Proto cannot enforce it.
  name @0 :Text;
}

# Request message for Vehicles.ListVehicles, AIP-132 <https://aip.dev/132>.
struct ListVehiclesRequest @0xe2623aa29d066920 {
  # Maximum vehicles to return. Defaults to 50, capped at 1000.
  pageSize @0 :Int32;
  # Page token from a previous ListVehiclesResponse.next_page_token.
  pageToken @1 :Text;
  # Filter expression, AIP-160 <https://aip.dev/160>.
  filter @2 :Text;
  # Include soft-deleted vehicles. AIP-164 <https://aip.dev/164>.
  showDeleted @3 :Bool;
}

# Response message for Vehicles.ListVehicles, AIP-132 <https://aip.dev/132>.
struct ListVehiclesResponse @0xfb2e105cedf30569 {
  # The vehicles on this page.
  vehicles @0 :List(Vehicle.Vehicle);
  # Token for the next page, empty when this is the last page.
  nextPageToken @1 :Text;
}

# Request message for Vehicles.CreateVehicle, AIP-133 <https://aip.dev/133>.
struct CreateVehicleRequest @0x925a80ad2ea99e36 {
  # The Vehicle to create.
  # REQUIRED (AIP-203); Cap'n Proto cannot enforce it.
  vehicle @0 :Vehicle.Vehicle;
  # Client-assigned id, becoming the last segment of the resource name. The
  # server generates one when empty.
  vehicleId @1 :Text;
}

# Request message for Vehicles.UpdateVehicle, AIP-134 <https://aip.dev/134>.
struct UpdateVehicleRequest @0xdd6ce93d2e537a9f {
  # The Vehicle to update. Its name field identifies the resource.
  # REQUIRED (AIP-203); Cap'n Proto cannot enforce it.
  vehicle @0 :Vehicle.Vehicle;
  # Fields to update. An empty mask updates all mutable fields.
  #
  # Only an actuator is writable. A sensor or attribute named in the mask is
  # rejected: both are OUTPUT_ONLY, because a vehicle reports them and an
  # API cannot set them.
  updateMask @1 :List(Text);
}

# Request message for Vehicles.DeleteVehicle, AIP-135 <https://aip.dev/135>.
struct DeleteVehicleRequest @0xf819c25a301f5817 {
  # Name of the Vehicle to delete, "vehicles/{vehicle}".
  # REQUIRED (AIP-203); Cap'n Proto cannot enforce it.
  name @0 :Text;
}

# Request message for Vehicles.UndeleteVehicle, AIP-164
# <https://aip.dev/164>.
struct UndeleteVehicleRequest @0xc4c159544f73dcb8 {
  # Name of the soft-deleted Vehicle to restore, "vehicles/{vehicle}".
  # REQUIRED (AIP-203); Cap'n Proto cannot enforce it.
  name @0 :Text;
}
