@0x899e37dc40e0e0ed;

# Code generated by protoc-gen-buffers. DO NOT EDIT.
# versions:
# 	protoc-gen-buffers dev
# 	protoc (unknown)
# source: protobuf/covesa/vss/vehicle/v1/vehicle.proto
#
# target: capnp
# field slots below are recorded in buffers.lock; edit the .proto, not this file
#
# https://github.com/the-protobuf-project/buffers
using Cxx = import "/capnp/c++.capnp";
$Cxx.namespace("protobuf::covesa::vss::vehicle::v1");

using VehicleTypes = import "/protobuf/covesa/vss/vehicle/v1/vehicle_types.capnp";
using Wellknown = import "/buffers/wellknown.capnp";

# High-level vehicle data.
#
# VSS: Vehicle.
#
# The root resource of the vehicle tree, named "vehicles/{vehicle}".
#
# It carries only its own signals. Each branch beneath it -- the cabin, the
# powertrain, the chassis -- is a resource of its own in its own package,
# because AIP-215 <https://aip.dev/215> forbids a field naming a message in
# another package. Navigate to one by resource name.
#
# Reference: COVESA Vehicle Signal Specification.
# https://covesa.github.io/vehicle_signal_specification/
struct Vehicle @0xa8468003012cd1b4 {
  # Resource name, "vehicles/{vehicle}". Assigned by the server.
  name @0 :Text;
  # Server-assigned unique id.
  uid @1 :Text;
  # Weak validator for optimistic concurrency, AIP-154
  # <https://aip.dev/154>.
  etag @2 :Text;
  # When this resource was soft-deleted, unset while it is live. AIP-164
  # <https://aip.dev/164>.
  deleteTime @3 :Wellknown.Timestamp;
  # When a soft-deleted resource is purged for good. AIP-164
  # <https://aip.dev/164>.
  expireTime @4 :Wellknown.Timestamp;
  # When this resource was created.
  createTime @5 :Wellknown.Timestamp;
  # When this resource was last modified.
  updateTime @6 :Wellknown.Timestamp;
  # proto field 8 was removed and reserved; this holds its ordinal.
  removed8 @7 :Void;
  # proto field 9 was removed and reserved; this holds its ordinal.
  removed9 @8 :Void;
  # proto field 10 was removed and reserved; this holds its ordinal.
  removed10 @9 :Void;
  # proto field 11 was removed and reserved; this holds its ordinal.
  removed11 @10 :Void;
  # proto field 12 was removed and reserved; this holds its ordinal.
  removed12 @11 :Void;
  # proto field 13 was removed and reserved; this holds its ordinal.
  removed13 @12 :Void;
  # proto field 14 was removed and reserved; this holds its ordinal.
  removed14 @13 :Void;
  # proto field 15 was removed and reserved; this holds its ordinal.
  removed15 @14 :Void;
  # State of the supply voltage of the control units (usually 12V).
  #
  # VSS: Vehicle.LowVoltageSystemState (sensor).
  lowVoltageSystemState @15 :VehicleTypes.LowVoltageSystemState;
  # Vehicle speed.
  #
  # Unit: km/h. VSS: Vehicle.Speed (sensor).
  speed @16 :Float64;
  # Odometer reading, total distance traveled during the lifetime of the
  # vehicle.
  #
  # Unit: m. VSS: Vehicle.TraveledDistance (sensor).
  traveledDistance @17 :Int64;
  # Distance traveled since start of current trip.
  #
  # A new trip is considered to start when engine gets enabled (e.g.
  # LowVoltageSystemState in ON or START mode). A trip is considered to end
  # when engine is no longer enabled. The signal may however keep the value
  # of the last trip until a new trip is started.
  #
  # Unit: m. VSS: Vehicle.TraveledDistanceSinceStart (sensor).
  tripTraveledDistance @18 :Int64;
  # Start time of current or latest trip, formatted according to ISO 8601
  # with UTC time zone.
  #
  # This signal is supposed to be set whenever a new trip starts. A new trip
  # is considered to start when engine gets enabled (e.g.
  # LowVoltageSystemState in ON or START mode). A trip is considered to end
  # when engine is no longer enabled. The default value indicates that the
  # vehicle never has been started, or that latest start time is unknown.
  #
  # Unit: iso8601. VSS: Vehicle.StartTime (attribute).
  startTime @19 :Wellknown.Timestamp;
  # Duration of latest trip.
  #
  # This signal is not assumed to be continuously updated, but instead set
  # to 0 when a trip starts and set to the actual duration of the trip when
  # a trip ends. A new trip is considered to start when engine gets enabled
  # (e.g. LowVoltageSystemState in ON or START mode). A trip is considered
  # to end when engine is no longer enabled.
  #
  # Unit: s. VSS: Vehicle.TripDuration (sensor).
  tripDuration @20 :Float64;
  # Trip meter reading.
  #
  # The trip meter is an odometer that can be manually reset by the driver
  #
  # Unit: m. VSS: Vehicle.TripMeterReading (actuator).
  tripMeterReading @21 :Int64;
  # Vehicle breakdown or any similar event causing vehicle to stop on the
  # road, that might pose a risk to other road users. True = Vehicle broken
  # down on the road, due to e.g. engine problems, flat tire, out of gas,
  # brake problems. False = Vehicle not broken down.
  #
  # Actual criteria and method used to decide if a vehicle is broken down is
  # implementation specific.
  #
  # VSS: Vehicle.IsBrokenDown (sensor).
  isBrokenDown @22 :Bool;
  # Indicates whether the vehicle is stationary or moving.
  #
  # VSS: Vehicle.IsMoving (sensor).
  isMoving @23 :Bool;
  # Average speed for the current trip.
  #
  # A new trip is considered to start when engine gets enabled (e.g.
  # LowVoltageSystemState in ON or START mode). A trip is considered to end
  # when engine is no longer enabled. The signal may however keep the value
  # of the last trip until a new trip is started. Calculation of average
  # speed may exclude periods when the vehicle for example is not moving or
  # transmission is in neutral.
  #
  # Unit: km/h. VSS: Vehicle.AverageSpeed (sensor).
  averageSpeed @24 :Float64;
  # The permitted total weight of cargo and installations (e.g. a roof rack)
  # on top of the vehicle.
  #
  # Unit: kg. VSS: Vehicle.RoofLoad (attribute).
  roofLoad @25 :Int32;
  # The available volume for cargo or luggage. For automobiles, this is
  # usually the trunk volume.
  #
  # Unit: l. VSS: Vehicle.CargoVolume (attribute).
  cargoVolume @26 :Float64;
  # The CO2 emissions.
  #
  # Unit: g/km. VSS: Vehicle.EmissionsCO2 (attribute).
  emissionsCo2 @27 :Int32;
  # Current overall Vehicle weight. Including passengers, cargo and other
  # load inside the car.
  #
  # Unit: kg. VSS: Vehicle.CurrentOverallWeight (sensor).
  currentOverallWeight @28 :Int32;
  # Vehicle curb weight, including all liquids and full tank of fuel, but no
  # cargo or passengers.
  #
  # Unit: kg. VSS: Vehicle.CurbWeight (attribute).
  curbWeight @29 :Int32;
  # Curb weight of vehicle, including all liquids and full tank of fuel and
  # full load of cargo and passengers.
  #
  # Unit: kg. VSS: Vehicle.GrossWeight (attribute).
  grossWeight @30 :Int32;
  # Maximum weight of trailer.
  #
  # Unit: kg. VSS: Vehicle.MaxTowWeight (attribute).
  maxTowWeight @31 :Int32;
  # Maximum vertical weight on the tow ball of a trailer.
  #
  # Unit: kg. VSS: Vehicle.MaxTowBallWeight (attribute).
  maxTowBallWeight @32 :Int32;
  # Overall vehicle length.
  #
  # Unit: mm. VSS: Vehicle.Length (attribute).
  length @33 :Int32;
  # Overall vehicle height.
  #
  # Unit: mm. VSS: Vehicle.Height (attribute).
  height @34 :Int32;
  # Overall vehicle width excluding mirrors, as defined by SAE J1100-2009
  # W103.
  #
  # Unit: mm. VSS: Vehicle.WidthExcludingMirrors (attribute).
  widthExcludingMirrors @35 :Int32;
  # Overall vehicle width including mirrors, as defined by SAE J1100-2009
  # W144.
  #
  # Unit: mm. VSS: Vehicle.WidthIncludingMirrors (attribute).
  widthMirrorsIncluded @36 :Int32;
  # Overall vehicle width with mirrors folded, as defined by SAE J1100-2009
  # W145.
  #
  # Unit: mm. VSS: Vehicle.WidthFoldedMirrors (attribute).
  widthFoldedMirrors @37 :Int32;
  # Minimum turning diameter, Wall-to-Wall, as defined by SAE J1100-2009
  # D102.
  #
  # Unit: mm. VSS: Vehicle.TurningDiameter (attribute).
  turningDiameter @38 :Int32;
  # Power optimization level for this branch/subsystem. A higher number
  # indicates more aggressive power optimization. Level 0 indicates that all
  # functionality is enabled, no power optimization enabled. Level 10
  # indicates most aggressive power optimization mode, only essential
  # functionality enabled.
  #
  # VSS: Vehicle.PowerOptimizeLevel (actuator).
  powerOptimizeLevel @39 :Int32;
  # Auto Power Optimization Flag When set to 'true', the system enables
  # automatic power optimization, dynamically adjusting the power
  # optimization level based on runtime conditions or features managed by
  # the OEM. When set to 'false', manual control of the power optimization
  # level is allowed.
  #
  # VSS: Vehicle.IsAutoPowerOptimize (actuator).
  isAutoPowerOptimize @40 :Bool;
}
