@0xe440e25dfae5cbcb;

# Code generated by protoc-gen-buffers. DO NOT EDIT.
# versions:
# 	protoc-gen-buffers dev
# 	protoc (unknown)
# source: protobuf/covesa/vss/vehicle/v1/vehicle_types.proto
#
# target: capnp
# field slots below are recorded in buffers.lock; edit the .proto, not this file
#
# https://github.com/the-protobuf-project/buffers
using Cxx = import "/capnp/c++.capnp";
$Cxx.namespace("protobuf::covesa::vss::vehicle::v1");

# State of the supply voltage of the control units (usually 12V).
#
# VSS: Vehicle.LowVoltageSystemState.
# (buffers.v1.enumeration).underlying asked for 32 bits. A Cap'n Proto enum is
# always 16, with no way to declare otherwise; the narrowing is honoured by
# the FlatBuffers target only.
enum LowVoltageSystemState @0xb5e6cfd5a6fbe058 {
  # Not specified.
  unspecified @0;
  # Not specified.
  undefined @1;
  # Lock.
  lock @2;
  # Off.
  off @3;
  # Acc.
  acc @4;
  # On.
  onValue @5;
  # Start.
  start @6;
}
