@0xb0eeb861b3c4d1d7;

# Code generated by protoc-gen-buffers. DO NOT EDIT.
# versions:
# 	protoc-gen-buffers dev
# 	protoc (unknown)
# source: protobuf/covesa/vss/interior/spotlight/v1/messages.proto
#
# target: capnp
# field slots below are recorded in buffers.lock; edit the .proto, not this file
#
# https://github.com/the-protobuf-project/buffers
using Cxx = import "/capnp/c++.capnp";
$Cxx.namespace("protobuf::covesa::vss::interior::spotlight::v1");

using Spotlight = import "/protobuf/covesa/vss/interior/spotlight/v1/spotlight.capnp";

# Request message for Spotlights.GetSpotlight, AIP-131
# <https://aip.dev/131>.
struct GetSpotlightRequest @0x831801d2d04fb730 {
  # Name of the Spotlight to retrieve,
  # "vehicles/{vehicle}/spotlights/{spotlight}".
  # REQUIRED (AIP-203); Cap'n Proto cannot enforce it.
  name @0 :Text;
}

# Request message for Spotlights.ListSpotlights, AIP-132
# <https://aip.dev/132>.
struct ListSpotlightsRequest @0xf1982482bf9fd774 {
  # The Vehicle whose spotlights to list, "vehicles/{vehicle}".
  # REQUIRED (AIP-203); Cap'n Proto cannot enforce it.
  parent @0 :Text;
  # Maximum spotlights to return. Defaults to 50, capped at 1000.
  pageSize @1 :Int32;
  # Page token from a previous ListSpotlightsResponse.next_page_token.
  pageToken @2 :Text;
  # Filter expression, AIP-160 <https://aip.dev/160>.
  filter @3 :Text;
  # Include soft-deleted spotlights. AIP-164 <https://aip.dev/164>.
  showDeleted @4 :Bool;
}

# Response message for Spotlights.ListSpotlights, AIP-132
# <https://aip.dev/132>.
struct ListSpotlightsResponse @0xc25e306ef0b73a1d {
  # The spotlights on this page.
  spotlights @0 :List(Spotlight.Spotlight);
  # Token for the next page, empty when this is the last page.
  nextPageToken @1 :Text;
}

# Request message for Spotlights.CreateSpotlight, AIP-133
# <https://aip.dev/133>.
struct CreateSpotlightRequest @0xa27bd17bf04cca8f {
  # The Vehicle to create the Spotlight under, "vehicles/{vehicle}".
  # REQUIRED (AIP-203); Cap'n Proto cannot enforce it.
  parent @0 :Text;
  # The Spotlight to create.
  # REQUIRED (AIP-203); Cap'n Proto cannot enforce it.
  spotlight @1 :Spotlight.Spotlight;
  # Client-assigned id, becoming the last segment of the resource name. The
  # server generates one when empty.
  spotlightId @2 :Text;
}

# Request message for Spotlights.UpdateSpotlight, AIP-134
# <https://aip.dev/134>.
struct UpdateSpotlightRequest @0xd0311a5de3439987 {
  # The Spotlight to update. Its name field identifies the resource.
  # REQUIRED (AIP-203); Cap'n Proto cannot enforce it.
  spotlight @0 :Spotlight.Spotlight;
  # Fields to update. An empty mask updates all mutable fields.
  #
  # Only an actuator is writable. A sensor or attribute named in the mask is
  # rejected: both are OUTPUT_ONLY, because a vehicle reports them and an
  # API cannot set them.
  updateMask @1 :List(Text);
}

# Request message for Spotlights.DeleteSpotlight, AIP-135
# <https://aip.dev/135>.
struct DeleteSpotlightRequest @0xb44e4f03436facac {
  # Name of the Spotlight to delete,
  # "vehicles/{vehicle}/spotlights/{spotlight}".
  # REQUIRED (AIP-203); Cap'n Proto cannot enforce it.
  name @0 :Text;
}

# Request message for Spotlights.UndeleteSpotlight, AIP-164
# <https://aip.dev/164>.
struct UndeleteSpotlightRequest @0x8915fb629b3d6e5e {
  # Name of the soft-deleted Spotlight to restore,
  # "vehicles/{vehicle}/spotlights/{spotlight}".
  # REQUIRED (AIP-203); Cap'n Proto cannot enforce it.
  name @0 :Text;
}
