@0x96db4c546633e356;

# Code generated by protoc-gen-buffers. DO NOT EDIT.
# versions:
# 	protoc-gen-buffers dev
# 	protoc (unknown)
# source: protobuf/covesa/vss/interior/spotlight/v1/service.proto
#
# target: capnp
# field slots below are recorded in buffers.lock; edit the .proto, not this file
#
# https://github.com/the-protobuf-project/buffers
using Cxx = import "/capnp/c++.capnp";
$Cxx.namespace("protobuf::covesa::vss::interior::spotlight::v1");

using Messages = import "/protobuf/covesa/vss/interior/spotlight/v1/messages.capnp";
using Spotlight = import "/protobuf/covesa/vss/interior/spotlight/v1/spotlight.capnp";

# Spotlights manages the Spotlight branch of a vehicle.
#
# A vehicle may hold several, so this is an ordinary collection with the
# AIP-131..135 standard methods plus AIP-164 <https://aip.dev/164> undelete.
#
# Reference: COVESA Vehicle Signal Specification.
# https://covesa.github.io/vehicle_signal_specification/
interface Spotlights @0xd46d918632a92945 {
  # Retrieves one Spotlight.
  #
  # GET /v1/{name=vehicles/*/spotlights/*}
  #
  # Safe and idempotent. Read the `etag` here and pass it back on update to
  # make the write conditional.
  #
  # NOT_FOUND no such Spotlight
  # INVALID_ARGUMENT name does not match the resource pattern
  # PERMISSION_DENIED caller may not read it
  # AIP-131 standard method.
  getSpotlight @0 (request :Messages.GetSpotlightRequest) -> (response :Spotlight.Spotlight);

  # Lists the spotlights of one vehicle.
  #
  # GET /v1/{parent=vehicles/*}/spotlights
  #
  # Paginated per AIP-158 <https://aip.dev/158>: pass `page_size` (defaults
  # to 50, capped at 1000) and the `next_page_token` from the previous
  # response. Page tokens are opaque and may expire; do not construct or
  # store them.
  #
  # INVALID_ARGUMENT malformed filter, or page_size out of range
  # PERMISSION_DENIED caller may not list this collection
  # AIP-132 standard method.
  listSpotlights @1 (request :Messages.ListSpotlightsRequest) -> (response :Messages.ListSpotlightsResponse);

  # Creates a Spotlight.
  #
  # POST /v1/{parent=vehicles/*}/spotlights
  # body: the Spotlight itself
  #
  # Server-assigned fields on the request body are ignored: `name`, `uid`,
  # `etag` and the server timestamps are set regardless of what is sent.
  #
  # Not idempotent. Retrying after a timeout may create a second Spotlight;
  # supply `spotlight_id` if the caller needs retry safety.
  #
  # ALREADY_EXISTS that id is taken
  # INVALID_ARGUMENT a field violates its buf.validate constraint
  # PERMISSION_DENIED caller may not create here
  # AIP-133 standard method.
  createSpotlight @2 (request :Messages.CreateSpotlightRequest) -> (response :Spotlight.Spotlight);

  # Updates a Spotlight.
  #
  # PATCH /v1/{spotlight.name=vehicles/*/spotlights/*}
  # body: the Spotlight itself
  #
  # A partial update: only fields named in `update_mask` are written. An
  # empty mask writes every mutable field, which will clear anything the
  # caller left unset -- pass a mask unless that is the intent.
  #
  # **Only an actuator is writable.** VSS marks each signal an attribute, a
  # sensor or an actuator; the first two are OUTPUT_ONLY here, because a
  # vehicle reports them and no API call can change them. A mask naming one
  # is rejected rather than silently ignored.
  #
  # Idempotent. Pass the `etag` read from Get to make the write conditional.
  #
  # NOT_FOUND no such Spotlight
  # ABORTED etag does not match the stored resource
  # INVALID_ARGUMENT mask names an unknown, immutable or read-only field
  # PERMISSION_DENIED caller may not modify it
  # AIP-134 standard method.
  updateSpotlight @3 (request :Messages.UpdateSpotlightRequest) -> (response :Spotlight.Spotlight);

  # Deletes a Spotlight.
  #
  # DELETE /v1/{name=vehicles/*/spotlights/*}
  #
  # Soft delete: the Spotlight is marked deleted, disappears from List
  # unless `show_deleted` is set, and is purged at `expire_time`. Recover it
  # with UndeleteSpotlight before then.
  #
  # Idempotent in effect but not in reporting: a second delete returns
  # NOT_FOUND rather than succeeding silently.
  #
  # NOT_FOUND no such Spotlight
  # ABORTED etag does not match
  # PERMISSION_DENIED caller may not delete it
  # AIP-135 standard method.
  deleteSpotlight @4 (request :Messages.DeleteSpotlightRequest) -> ();

  # Restores a soft-deleted Spotlight.
  #
  # POST /v1/{name=vehicles/*/spotlights/*}:undelete
  #
  # Valid only before `expire_time`; after that the Spotlight is gone and
  # this returns NOT_FOUND. Clears `delete_time` and `expire_time`.
  #
  # NOT_FOUND no such Spotlight, or already purged
  # ALREADY_EXISTS the Spotlight is not deleted
  # PERMISSION_DENIED caller may not restore it
  # AIP-164 standard method.
  undeleteSpotlight @5 (request :Messages.UndeleteSpotlightRequest) -> (response :Spotlight.Spotlight);
}
