// Copyright 2026 The Protobuf Project authors.
// SPDX-License-Identifier: Apache-2.0

// Package spec reads the pin naming which revision of the COVESA Vehicle Data
// Model a generated schema was produced from.
//
// # Why the revision is dated
//
// Revisions are dated, not numbered, the way the Model Context Protocol
// versions its specification. The upstream model publishes no release
// numbers -- COVESA's vdm repository carries a single placeholder tag and
// nothing else -- so a version invented here would mean nothing to a reader.
// A date is directly comparable against the source repository's history, and
// it sorts.
//
// # Why it is read rather than assumed
//
// The pin travels with the output: every generated file's banner names it,
// which makes "which specification is this from?" answerable from any single
// .proto a consumer happens to be holding, without access to this
// repository's git history.
package spec

import (
	"fmt"
	"os"
	"strings"
)

// dateLen is the length of a YYYY-MM-DD version string.
const dateLen = 10

// Spec is the contents of sync/spec.yaml.
type Spec struct {
	// Version is the revision date, YYYY-MM-DD. It is the date of Commit.
	Version string

	// Commit is the upstream revision actually read.
	//
	// The authority: Version is a human-placeable label for it, and
	// scripts/check-spec.sh verifies the two agree with the checkout.
	Commit string

	// Source is the upstream repository.
	Source string

	// Path is where the specification is checked out, relative to the
	// repository root.
	Path string
}

// Short renders the commit at the length git logs it.
func (s Spec) Short() string {
	const shortLen = 7
	if len(s.Commit) > shortLen {
		return s.Commit[:shortLen]
	}
	return s.Commit
}

// Banner is the header every generated file carries.
//
// One function rather than the same lines repeated in each emitter, so the
// revision cannot appear in one target's output and not another's.
func (s Spec) Banner() string {
	return "// Copyright 2026 The Protobuf Project authors.\n" +
		"// SPDX-License-Identifier: Apache-2.0\n" +
		"//\n" +
		"// Generated by sync from the COVESA Vehicle Data Model,\n" +
		"// spec revision " + s.Version + " (" + s.Short() + "). DO NOT EDIT.\n" +
		"//\n" +
		"// Regenerate with: just sync\n" +
		"// Revision history: docs/spec.md\n\n"
}

// Load reads the pin at path.
//
// Hand-parsed rather than unmarshalled: the file is four scalar keys, and a
// YAML library would be this generator's only dependency. Anything the parser
// does not recognise is an error -- a typo in a key must not silently leave a
// field empty and stamp a blank revision into every generated banner.
func Load(path string) (Spec, error) {
	raw, err := os.ReadFile(path)
	if err != nil {
		return Spec{}, err
	}
	var s Spec
	for n, line := range strings.Split(string(raw), "\n") {
		text := strings.TrimSpace(line)
		if text == "" || strings.HasPrefix(text, "#") {
			continue
		}
		key, value, ok := strings.Cut(text, ":")
		if !ok {
			return Spec{}, fmt.Errorf("%s:%d: not a key/value line: %q", path, n+1, text)
		}
		if err := s.set(strings.TrimSpace(key), strings.TrimSpace(value)); err != nil {
			return Spec{}, fmt.Errorf("%s:%d: %w", path, n+1, err)
		}
	}
	return s, s.validate(path)
}

// set assigns one key/value pair, rejecting a key the schema does not know.
func (s *Spec) set(key, value string) error {
	switch key {
	case "version":
		s.Version = value
	case "commit":
		s.Commit = value
	case "source":
		s.Source = value
	case "path":
		s.Path = value
	default:
		return fmt.Errorf("unknown key %q", key)
	}
	return nil
}

// validate reports a pin that is missing a field or carries a malformed date.
func (s Spec) validate(path string) error {
	for _, f := range []struct{ name, value string }{
		{"version", s.Version},
		{"commit", s.Commit},
		{"source", s.Source},
		{"path", s.Path},
	} {
		if f.value == "" {
			return fmt.Errorf("%s: %s is empty", path, f.name)
		}
	}
	if len(s.Version) != dateLen || strings.Count(s.Version, "-") != 2 {
		return fmt.Errorf("%s: version %q is not a YYYY-MM-DD date", path, s.Version)
	}
	return nil
}
