@0x991b06a01447ccaf;

# Code generated by protoc-gen-buffers. DO NOT EDIT.
# versions:
# 	protoc-gen-buffers dev
# 	protoc (unknown)
# source: protobuf/covesa/vss/assistance/safety/v1/messages.proto
#
# target: capnp
# field slots below are recorded in buffers.lock; edit the .proto, not this file
#
# https://github.com/the-protobuf-project/buffers
using Cxx = import "/capnp/c++.capnp";
$Cxx.namespace("protobuf::covesa::vss::assistance::safety::v1");

using Safety = import "/protobuf/covesa/vss/assistance/safety/v1/safety.capnp";

# Request message for Safeties.GetSafety, AIP-131 <https://aip.dev/131>.
struct GetSafetyRequest @0xb14f5f0154cc95af {
  # Name of the Safety to retrieve, "vehicles/{vehicle}/safety".
  # REQUIRED (AIP-203); Cap'n Proto cannot enforce it.
  name @0 :Text;
}

# Request message for Safeties.UpdateSafety, AIP-134 <https://aip.dev/134>.
struct UpdateSafetyRequest @0xe9c9e23432896660 {
  # The Safety to update. Its name field identifies the resource.
  # REQUIRED (AIP-203); Cap'n Proto cannot enforce it.
  safety @0 :Safety.Safety;
  # Fields to update. An empty mask updates all mutable fields.
  #
  # Only an actuator is writable. A sensor or attribute named in the mask is
  # rejected: both are OUTPUT_ONLY, because a vehicle reports them and an
  # API cannot set them.
  updateMask @1 :List(Text);
}
