@0xda6e5489a80825f5;

# Code generated by protoc-gen-buffers. DO NOT EDIT.
# versions:
# 	protoc-gen-buffers dev
# 	protoc (unknown)
# source: protobuf/covesa/vss/location/current_location/v1/current_location.proto
#
# target: capnp
# field slots below are recorded in buffers.lock; edit the .proto, not this file
#
# https://github.com/the-protobuf-project/buffers
using Cxx = import "/capnp/c++.capnp";
$Cxx.namespace("protobuf::covesa::vss::location::current_location::v1");

using GnssReceiver = import "/protobuf/covesa/vss/location/current_location/v1/gnss_receiver.capnp";
using Wellknown = import "/buffers/wellknown.capnp";

# The current latitude and longitude of the vehicle.
#
# VSS: Vehicle.CurrentLocation.
#
# A singleton child resource of Vehicle, AIP-156 <https://aip.dev/156>,
# named "vehicles/{vehicle}/currentLocation". Its parent is a declared
# resource in protobuf.covesa.vss.vehicle.v1, which is what makes this
# pattern legal rather than a reference to a collection nothing can create.
#
# Reference: COVESA Vehicle Signal Specification.
# https://covesa.github.io/vehicle_signal_specification/
struct CurrentLocation @0xa44aee08618a4828 {
  # Resource name, "vehicles/{vehicle}/currentLocation". Assigned by the
  # server.
  name @0 :Text;
  # Server-assigned unique id.
  uid @1 :Text;
  # Weak validator for optimistic concurrency, AIP-154
  # <https://aip.dev/154>.
  etag @2 :Text;
  # When this resource was soft-deleted, unset while it is live. AIP-164
  # <https://aip.dev/164>.
  deleteTime @3 :Wellknown.Timestamp;
  # When a soft-deleted resource is purged for good. AIP-164
  # <https://aip.dev/164>.
  expireTime @4 :Wellknown.Timestamp;
  # When this resource was created.
  createTime @5 :Wellknown.Timestamp;
  # When this resource was last modified.
  updateTime @6 :Wellknown.Timestamp;
  # proto field 8 was removed and reserved; this holds its ordinal.
  removed8 @7 :Void;
  # proto field 9 was removed and reserved; this holds its ordinal.
  removed9 @8 :Void;
  # proto field 10 was removed and reserved; this holds its ordinal.
  removed10 @9 :Void;
  # proto field 11 was removed and reserved; this holds its ordinal.
  removed11 @10 :Void;
  # proto field 12 was removed and reserved; this holds its ordinal.
  removed12 @11 :Void;
  # proto field 13 was removed and reserved; this holds its ordinal.
  removed13 @12 :Void;
  # proto field 14 was removed and reserved; this holds its ordinal.
  removed14 @13 :Void;
  # proto field 15 was removed and reserved; this holds its ordinal.
  removed15 @14 :Void;
  # Timestamp from GNSS system for current location, formatted according to
  # ISO 8601 with UTC time zone.
  #
  # Unit: iso8601. VSS: Vehicle.CurrentLocation.Timestamp (sensor).
  observationTime @15 :Wellknown.Timestamp;
  # Current latitude of vehicle in WGS 84 geodetic coordinates, as measured
  # at the position of GNSS receiver antenna.
  #
  # Unit: degrees. VSS: Vehicle.CurrentLocation.Latitude (sensor).
  latitude @16 :Float64;
  # Current longitude of vehicle in WGS 84 geodetic coordinates, as measured
  # at the position of GNSS receiver antenna.
  #
  # Unit: degrees. VSS: Vehicle.CurrentLocation.Longitude (sensor).
  longitude @17 :Float64;
  # Current heading relative to geographic north. 0 = North, 90 = East, 180
  # = South, 270 = West.
  #
  # Unit: degrees. VSS: Vehicle.CurrentLocation.Heading (sensor).
  heading @18 :Float64;
  # Accuracy of the latitude and longitude coordinates.
  #
  # Unit: m. VSS: Vehicle.CurrentLocation.HorizontalAccuracy (sensor).
  horizontalAccuracy @19 :Float64;
  # Current altitude relative to WGS 84 reference ellipsoid, as measured at
  # the position of GNSS receiver antenna.
  #
  # Unit: m. VSS: Vehicle.CurrentLocation.Altitude (sensor).
  altitude @20 :Float64;
  # Accuracy of altitude.
  #
  # Unit: m. VSS: Vehicle.CurrentLocation.VerticalAccuracy (sensor).
  verticalAccuracy @21 :Float64;
  # Information on the GNSS receiver used for determining current location.
  #
  # VSS: Vehicle.CurrentLocation.GNSSReceiver.
  gnssReceiver @22 :GnssReceiver.GnssReceiver;
}
