@0xe6f117b173ea1234;

# Code generated by protoc-gen-buffers. DO NOT EDIT.
# versions:
# 	protoc-gen-buffers dev
# 	protoc (unknown)
# source: protobuf/covesa/vss/location/current_location/v1/gnss_receiver.proto
#
# target: capnp
# field slots below are recorded in buffers.lock; edit the .proto, not this file
#
# https://github.com/the-protobuf-project/buffers
using Cxx = import "/capnp/c++.capnp";
$Cxx.namespace("protobuf::covesa::vss::location::current_location::v1");

using MountingPosition = import "/protobuf/covesa/vss/location/current_location/v1/mounting_position.capnp";

# Fix status of GNSS receiver.
#
# VSS: Vehicle.CurrentLocation.GNSSReceiver.FixType.
# (buffers.v1.enumeration).underlying asked for 32 bits. A Cap'n Proto enum is
# always 16, with no way to declare otherwise; the narrowing is honoured by
# the FlatBuffers target only.
enum FixType @0xb68b30808e9fee16 {
  # Not specified.
  unspecified @0;
  # None.
  none @1;
  # Two d.
  twoD @2;
  # Two d satellite based augmentation.
  twoDSatelliteBasedAugmentation @3;
  # Two d ground based augmentation.
  twoDGroundBasedAugmentation @4;
  # Two d satellite and ground based augmentation.
  twoDSatelliteAndGroundBasedAugmentation @5;
  # Three d.
  threeD @6;
  # Three d satellite based augmentation.
  threeDSatelliteBasedAugmentation @7;
  # Three d ground based augmentation.
  threeDGroundBasedAugmentation @8;
  # Three d satellite and ground based augmentation.
  threeDSatelliteAndGroundBasedAugmentation @9;
}

# Information on the GNSS receiver used for determining current location.
#
# VSS: Vehicle.CurrentLocation.GNSSReceiver.
#
# Reference: COVESA Vehicle Signal Specification.
# https://covesa.github.io/vehicle_signal_specification/
struct GnssReceiver @0xa9729138d5b5ac46 {
  # Fix status of GNSS receiver.
  #
  # VSS: Vehicle.CurrentLocation.GNSSReceiver.FixType (sensor).
  fixType @0 :FixType;
  # Mounting position of GNSS receiver antenna relative to vehicle
  # coordinate system. Axis definitions according to ISO 8855. Origin at
  # center of (first) rear axle.
  #
  # VSS: Vehicle.CurrentLocation.GNSSReceiver.MountingPosition.
  mountingPosition @1 :MountingPosition.MountingPosition;
}
