@0x8b48fd74bf3a6d3c;

# Code generated by protoc-gen-buffers. DO NOT EDIT.
# versions:
# 	protoc-gen-buffers dev
# 	protoc (unknown)
# source: protobuf/covesa/vss/exterior/mirrors/v1/mirrors.proto
#
# target: capnp
# field slots below are recorded in buffers.lock; edit the .proto, not this file
#
# https://github.com/the-protobuf-project/buffers
using Cxx = import "/capnp/c++.capnp";
$Cxx.namespace("protobuf::covesa::vss::exterior::mirrors::v1");

using Wellknown = import "/buffers/wellknown.capnp";

# All mirrors.
#
# VSS: Vehicle.Body.Mirrors.
#
# Instanced: DriverSide, PassengerSide. The axes together name one
# occurrence, which is why each is a resource of its own rather than a
# repeated field.
#
# A child resource of Body, named "vehicles/{vehicle}/mirrors/{mirrors}".
# Its parent is a declared resource in protobuf.covesa.vss.exterior.body.v1,
# which is what makes this pattern legal rather than a reference to a
# collection nothing can create.
#
# Reference: COVESA Vehicle Signal Specification.
# https://covesa.github.io/vehicle_signal_specification/
struct Mirrors @0xd7bf60ec73e9704f {
  # Resource name, "vehicles/{vehicle}/mirrors/{mirrors}". Assigned by the
  # server.
  name @0 :Text;
  # Server-assigned unique id.
  uid @1 :Text;
  # Weak validator for optimistic concurrency, AIP-154
  # <https://aip.dev/154>.
  etag @2 :Text;
  # When this resource was soft-deleted, unset while it is live. AIP-164
  # <https://aip.dev/164>.
  deleteTime @3 :Wellknown.Timestamp;
  # When a soft-deleted resource is purged for good. AIP-164
  # <https://aip.dev/164>.
  expireTime @4 :Wellknown.Timestamp;
  # When this resource was created.
  createTime @5 :Wellknown.Timestamp;
  # When this resource was last modified.
  updateTime @6 :Wellknown.Timestamp;
  # proto field 8 was removed and reserved; this holds its ordinal.
  removed8 @7 :Void;
  # proto field 9 was removed and reserved; this holds its ordinal.
  removed9 @8 :Void;
  # proto field 10 was removed and reserved; this holds its ordinal.
  removed10 @9 :Void;
  # proto field 11 was removed and reserved; this holds its ordinal.
  removed11 @10 :Void;
  # proto field 12 was removed and reserved; this holds its ordinal.
  removed12 @11 :Void;
  # proto field 13 was removed and reserved; this holds its ordinal.
  removed13 @12 :Void;
  # proto field 14 was removed and reserved; this holds its ordinal.
  removed14 @13 :Void;
  # proto field 15 was removed and reserved; this holds its ordinal.
  removed15 @14 :Void;
  # Mirror tilt as a percent. 0 = Center Position. 100 = Fully Upward
  # Position. -100 = Fully Downward Position.
  #
  # Unit: percent. VSS: Vehicle.Body.Mirrors.Tilt (actuator).
  tilt @15 :Int32;
  # Deprecated: v6.0 Replaced with Yaw - Note that direction changes!
  #
  # Mirror pan as a percent. 0 = Center Position. 100 = Fully Left Position.
  # -100 = Fully Right Position.
  #
  # Unit: percent. VSS: Vehicle.Body.Mirrors.Pan (actuator).
  pan @16 :Int32;
  # Relative mirror yaw angle, measured from the vehicle sprung mass X-axis
  # as defined by ISO 23150:2023 to the mirror X-axis, around the vehicle
  # Z-axis (right-hand rule). 0 = Mirror in default position. Exact position
  # (yaw relative to vehicle X-axis) is vehicle dependent. 100 = Maximum
  # yaw. Mirror rotated clockwise as much as possible around Z-axis. -100 =
  # Minimum yaw. Mirror rotated counter-clockwise as much as possible around
  # Z-axis.
  #
  # A positive yaw indicates that the mirror has been adjusted to get a
  # better view on objects on the right side of the vehicle.
  #
  # Unit: percent. VSS: Vehicle.Body.Mirrors.Yaw (actuator).
  yaw @17 :Int32;
  # Mirror Heater on or off. True = Heater On. False = Heater Off.
  #
  # VSS: Vehicle.Body.Mirrors.IsHeatingOn (actuator).
  isHeatingOn @18 :Bool;
  # Is mirror movement locked? True = Locked, mirror will not react to
  # Tilt/Pan change. False = Unlocked.
  #
  # VSS: Vehicle.Body.Mirrors.IsLocked (actuator).
  isLocked @19 :Bool;
  # Is mirror folded? True = Fully or partially folded. False = Fully
  # unfolded.
  #
  # VSS: Vehicle.Body.Mirrors.IsFolded (actuator).
  isFolded @20 :Bool;
}
