@0xf2429c28d51e1389;

# Code generated by protoc-gen-buffers. DO NOT EDIT.
# versions:
# 	protoc-gen-buffers dev
# 	protoc (unknown)
# source: protobuf/covesa/vdm/person/v1/messages.proto
#
# target: capnp
# field slots below are recorded in buffers.lock; edit the .proto, not this file
#
# https://github.com/the-protobuf-project/buffers
using Cxx = import "/capnp/c++.capnp";
$Cxx.namespace("protobuf::covesa::vdm::person::v1");

using Person = import "/protobuf/covesa/vdm/person/v1/person.capnp";

# Request message for People.GetPerson, AIP-131 <https://aip.dev/131>.
struct GetPersonRequest @0x8999f34bdf0f5906 {
  # Name of the Person to retrieve, "people/{person}".
  # REQUIRED (AIP-203); Cap'n Proto cannot enforce it.
  name @0 :Text;
}

# Request message for People.ListPeople, AIP-132 <https://aip.dev/132>.
struct ListPeopleRequest @0xb931683e48f0300a {
  # Maximum people to return. Defaults to 50, capped at 1000.
  pageSize @0 :Int32;
  # Page token from a previous ListPeopleResponse.next_page_token.
  pageToken @1 :Text;
  # Filter expression, AIP-160 <https://aip.dev/160>.
  filter @2 :Text;
  # Include soft-deleted people. AIP-164 <https://aip.dev/164>.
  showDeleted @3 :Bool;
}

# Response message for People.ListPeople, AIP-132 <https://aip.dev/132>.
struct ListPeopleResponse @0xa56fd822dba65670 {
  # The people on this page.
  people @0 :List(Person.Person);
  # Token for the next page, empty when this is the last page.
  nextPageToken @1 :Text;
}

# Request message for People.CreatePerson, AIP-133 <https://aip.dev/133>.
struct CreatePersonRequest @0xe89c4b94e5953813 {
  # The Person to create.
  # REQUIRED (AIP-203); Cap'n Proto cannot enforce it.
  person @0 :Person.Person;
  # Client-assigned id, becoming the last segment of the resource name. The
  # server generates one when empty.
  personId @1 :Text;
}

# Request message for People.UpdatePerson, AIP-134 <https://aip.dev/134>.
struct UpdatePersonRequest @0xcbcd328dc29bb46d {
  # The Person to update. Its name field identifies the resource.
  # REQUIRED (AIP-203); Cap'n Proto cannot enforce it.
  person @0 :Person.Person;
  # Fields to update. An empty mask updates all mutable fields.
  #
  # Only an actuator is writable. A sensor or attribute named in the mask is
  # rejected: both are OUTPUT_ONLY, because a vehicle reports them and an
  # API cannot set them.
  updateMask @1 :List(Text);
}

# Request message for People.DeletePerson, AIP-135 <https://aip.dev/135>.
struct DeletePersonRequest @0x8bf3c49421ecfbf5 {
  # Name of the Person to delete, "people/{person}".
  # REQUIRED (AIP-203); Cap'n Proto cannot enforce it.
  name @0 :Text;
}

# Request message for People.UndeletePerson, AIP-164 <https://aip.dev/164>.
struct UndeletePersonRequest @0xe82349ef3df944c8 {
  # Name of the soft-deleted Person to restore, "people/{person}".
  # REQUIRED (AIP-203); Cap'n Proto cannot enforce it.
  name @0 :Text;
}
