@0x9eb18f74e638c264;

# Code generated by protoc-gen-buffers. DO NOT EDIT.
# versions:
# 	protoc-gen-buffers dev
# 	protoc (unknown)
# source: protobuf/covesa/vss/platform/vehicle_identification/v1/date.proto
#
# target: capnp
# field slots below are recorded in buffers.lock; edit the .proto, not this file
#
# https://github.com/the-protobuf-project/buffers
using Cxx = import "/capnp/c++.capnp";
$Cxx.namespace("protobuf::covesa::vss::platform::vehicle_identification::v1");

# Date is a calendar date: a year, a month and a day.
#
# The specification states these as ISO 8601 strings. A string cannot be
# validated or compared without parsing it first, and it carries a time zone
# the value does not have -- a production date is the same date everywhere.
# The components are stated instead.
#
# Modelled on google.type.Date, which this schema does not use: the
# serialization targets drop it silently. See docs/decisions.md.
#
# VSS: Vehicle.VehicleIdentification.Date.
#
# Reference: COVESA Vehicle Signal Specification.
# https://covesa.github.io/vehicle_signal_specification/
struct Date @0xf3b51bec04b91897 {
  # Year of the date.
  #
  # VSS: Vehicle.VehicleIdentification.Date.Year (attribute).
  year @0 :Int32;
  # Month of the year.
  #
  # VSS: Vehicle.VehicleIdentification.Date.Month (attribute).
  month @1 :Int32;
  # Day of the month, valid for the year and month.
  #
  # VSS: Vehicle.VehicleIdentification.Date.Day (attribute).
  day @2 :Int32;
}
