@0xf9476c72a5e3677f;

# Code generated by protoc-gen-buffers. DO NOT EDIT.
# versions:
# 	protoc-gen-buffers dev
# 	protoc (unknown)
# source: protobuf/covesa/vss/platform/vehicle_identification/v1/messages.proto
#
# target: capnp
# field slots below are recorded in buffers.lock; edit the .proto, not this file
#
# https://github.com/the-protobuf-project/buffers
using Cxx = import "/capnp/c++.capnp";
$Cxx.namespace("protobuf::covesa::vss::platform::vehicle_identification::v1");

using VehicleIdentification = import "/protobuf/covesa/vss/platform/vehicle_identification/v1/vehicle_identification.capnp";

# Request message for VehicleIdentificationService.GetVehicleIdentification,
# AIP-131 <https://aip.dev/131>.
struct GetVehicleIdentificationRequest @0xd4be31c8a0f9dbbb {
  # Name of the VehicleIdentification to retrieve,
  # "vehicles/{vehicle}/vehicleIdentification".
  # REQUIRED (AIP-203); Cap'n Proto cannot enforce it.
  name @0 :Text;
}

# Request message for
# VehicleIdentificationService.UpdateVehicleIdentification, AIP-134
# <https://aip.dev/134>.
struct UpdateVehicleIdentificationRequest @0x83d321ea6663b844 {
  # The VehicleIdentification to update. Its name field identifies the
  # resource.
  # REQUIRED (AIP-203); Cap'n Proto cannot enforce it.
  vehicleIdentification @0 :VehicleIdentification.VehicleIdentification;
  # Fields to update. An empty mask updates all mutable fields.
  #
  # Only an actuator is writable. A sensor or attribute named in the mask is
  # rejected: both are OUTPUT_ONLY, because a vehicle reports them and an
  # API cannot set them.
  updateMask @1 :List(Text);
}
