@0xe6a55be84a185d8a;

# Code generated by protoc-gen-buffers. DO NOT EDIT.
# versions:
# 	protoc-gen-buffers dev
# 	protoc (unknown)
# source: protobuf/covesa/vss/platform/vehicle_identification/v1/vehicle_identification.proto
#
# target: capnp
# field slots below are recorded in buffers.lock; edit the .proto, not this file
#
# https://github.com/the-protobuf-project/buffers
using Cxx = import "/capnp/c++.capnp";
$Cxx.namespace("protobuf::covesa::vss::platform::vehicle_identification::v1");

using Date = import "/protobuf/covesa/vss/platform/vehicle_identification/v1/date.capnp";
using Wellknown = import "/buffers/wellknown.capnp";

# Attributes that identify a vehicle.
#
# VSS: Vehicle.VehicleIdentification.
#
# A singleton child resource of Vehicle, AIP-156 <https://aip.dev/156>,
# named "vehicles/{vehicle}/vehicleIdentification". Its parent is a declared
# resource in protobuf.covesa.vss.vehicle.v1, which is what makes this
# pattern legal rather than a reference to a collection nothing can create.
#
# Reference: COVESA Vehicle Signal Specification.
# https://covesa.github.io/vehicle_signal_specification/
struct VehicleIdentification @0xa2bf9ed86aef0fad {
  # Resource name, "vehicles/{vehicle}/vehicleIdentification". Assigned by
  # the server.
  name @0 :Text;
  # Server-assigned unique id.
  uid @1 :Text;
  # Weak validator for optimistic concurrency, AIP-154
  # <https://aip.dev/154>.
  etag @2 :Text;
  # When this resource was soft-deleted, unset while it is live. AIP-164
  # <https://aip.dev/164>.
  deleteTime @3 :Wellknown.Timestamp;
  # When a soft-deleted resource is purged for good. AIP-164
  # <https://aip.dev/164>.
  expireTime @4 :Wellknown.Timestamp;
  # When this resource was created.
  createTime @5 :Wellknown.Timestamp;
  # When this resource was last modified.
  updateTime @6 :Wellknown.Timestamp;
  # proto field 8 was removed and reserved; this holds its ordinal.
  removed8 @7 :Void;
  # proto field 9 was removed and reserved; this holds its ordinal.
  removed9 @8 :Void;
  # proto field 10 was removed and reserved; this holds its ordinal.
  removed10 @9 :Void;
  # proto field 11 was removed and reserved; this holds its ordinal.
  removed11 @10 :Void;
  # proto field 12 was removed and reserved; this holds its ordinal.
  removed12 @11 :Void;
  # proto field 13 was removed and reserved; this holds its ordinal.
  removed13 @12 :Void;
  # proto field 14 was removed and reserved; this holds its ordinal.
  removed14 @13 :Void;
  # proto field 15 was removed and reserved; this holds its ordinal.
  removed15 @14 :Void;
  # 17-character Vehicle Identification Number (VIN) as defined by ISO 3779.
  #
  # VSS: Vehicle.VehicleIdentification.VIN (attribute).
  vin @15 :Text;
  # 3-character World Manufacturer Identification (WMI) as defined by ISO
  # 3780.
  #
  # VSS: Vehicle.VehicleIdentification.WMI (attribute).
  wmi @16 :Text;
  # Vehicle brand or manufacturer.
  #
  # VSS: Vehicle.VehicleIdentification.Brand (attribute).
  brand @17 :Text;
  # Vehicle model.
  #
  # VSS: Vehicle.VehicleIdentification.Model (attribute).
  model @18 :Text;
  # Model year of the vehicle.
  #
  # VSS: Vehicle.VehicleIdentification.Year (attribute).
  year @19 :Int32;
  # The ACRISS Car Classification Code is a code used by many car rental
  # companies.
  #
  # VSS: Vehicle.VehicleIdentification.AcrissCode (attribute).
  acrissCode @20 :Text;
  # Indicates the design and body style of the vehicle (e.g. station wagon,
  # hatchback, etc.).
  #
  # VSS: Vehicle.VehicleIdentification.BodyType (attribute).
  bodyType @21 :Text;
  # The date in ISO 8601 format of the first registration of the vehicle
  # with the respective public authorities.
  #
  # Unit: iso8601. VSS:
  # Vehicle.VehicleIdentification.DateVehicleFirstRegistered (attribute).
  firstRegistration @22 :Date.Date;
  # The license plate of the vehicle.
  #
  # Depending on the context, this attribute might not be up to date or
  # might be misconfigured, and therefore should be considered untrustworthy
  # in the absence of another method of verification.
  #
  # VSS: Vehicle.VehicleIdentification.LicensePlate (attribute).
  licensePlate @23 :Text;
  # Indicates that the vehicle meets the respective emission standard.
  #
  # VSS: Vehicle.VehicleIdentification.MeetsEmissionStandard (attribute).
  meetsEmissionStandard @24 :Text;
  # The date in ISO 8601 format of production of the item, e.g. vehicle.
  #
  # Unit: iso8601. VSS: Vehicle.VehicleIdentification.ProductionDate
  # (attribute).
  production @25 :Date.Date;
  # The date in ISO 8601 format of the item e.g. vehicle was purchased by
  # the current owner.
  #
  # Unit: iso8601. VSS: Vehicle.VehicleIdentification.PurchaseDate
  # (attribute).
  purchase @26 :Date.Date;
  # The release date in ISO 8601 format of a vehicle model (often used to
  # differentiate versions of the same make and model).
  #
  # Unit: iso8601. VSS: Vehicle.VehicleIdentification.VehicleModelDate
  # (attribute).
  modelRelease @27 :Date.Date;
  # A short text indicating the configuration of the vehicle, e.g. '5dr
  # hatchback ST 2.5 MT 225 hp' or 'limited edition'.
  #
  # VSS: Vehicle.VehicleIdentification.VehicleConfiguration (attribute).
  vehicleConfig @28 :Text;
  # The number of passengers that can be seated in the vehicle, both in
  # terms of the physical space available, and in terms of limitations set
  # by law.
  #
  # VSS: Vehicle.VehicleIdentification.VehicleSeatingCapacity (attribute).
  vehicleSeatingCapacity @29 :Int32;
  # Indicates whether the vehicle has been used for special purposes, like
  # commercial rental, driving school.
  #
  # VSS: Vehicle.VehicleIdentification.VehicleSpecialUsage (attribute).
  vehicleSpecialUsage @30 :Text;
  # The main color of the exterior within the basic color palette (eg. red,
  # blue, black, white, ...).
  #
  # VSS: Vehicle.VehicleIdentification.VehicleExteriorColor (attribute).
  vehicleExteriorColor @31 :Text;
  # The color or color combination of the interior of the vehicle.
  #
  # VSS: Vehicle.VehicleIdentification.VehicleInteriorColor (attribute).
  vehicleInteriorColor @32 :Text;
  # The type or material of the interior of the vehicle (e.g. synthetic
  # fabric, leather, wood, etc.).
  #
  # VSS: Vehicle.VehicleIdentification.VehicleInteriorType (attribute).
  vehicleInteriorType @33 :Text;
  # A textual description of known damages, both repaired and unrepaired.
  #
  # VSS: Vehicle.VehicleIdentification.KnownVehicleDamages (attribute).
  knownVehicleDamages @34 :Text;
  # Optional extras refers to all car equipment options that are not
  # installed as standard by the manufacturer.
  #
  # Allowed values are not standardized, each OEM can specify detail
  # descriptions of array elements.
  #
  # VSS: Vehicle.VehicleIdentification.OptionalExtras (attribute).
  optionalExtras @35 :List(Text);
}
