@0x8d2b1fa591d1dcff;

# Code generated by protoc-gen-buffers. DO NOT EDIT.
# versions:
# 	protoc-gen-buffers dev
# 	protoc (unknown)
# source: protobuf/covesa/vss/interior/cabin/v1/air_quality.proto
#
# target: capnp
# field slots below are recorded in buffers.lock; edit the .proto, not this file
#
# https://github.com/the-protobuf-project/buffers
using Cxx = import "/capnp/c++.capnp";
$Cxx.namespace("protobuf::covesa::vss::interior::cabin::v1");

# Signals describing the composition of the air inside the vehicle cabin.
#
# VSS: Vehicle.Cabin.AirQuality.
#
# Reference: COVESA Vehicle Signal Specification.
# https://covesa.github.io/vehicle_signal_specification/
struct AirQuality @0xdca95a04a31784a5 {
  # Mass concentration of particulate matter with aerodynamic diameter of 1
  # micrometer or less (PM1.0).
  #
  # Unit: ug/m^3. VSS: Vehicle.Cabin.AirQuality.PM1 (sensor).
  pm1 @0 :Float64;
  # Mass concentration of particulate matter with aerodynamic diameter of
  # 2.5 micrometers or less (PM2.5).
  #
  # Unit: ug/m^3. VSS: Vehicle.Cabin.AirQuality.PM25 (sensor).
  pm25 @1 :Float64;
  # Mass concentration of particulate matter with aerodynamic diameter of 10
  # micrometers or less (PM10).
  #
  # Unit: ug/m^3. VSS: Vehicle.Cabin.AirQuality.PM10 (sensor).
  pm10 @2 :Float64;
  # Carbon dioxide (CO2) concentration.
  #
  # If the sensor reports an estimated CO2 level (eCO2/CO2eq) derived from
  # other gas measurements rather than a direct CO2 measurement, the
  # estimated value may be reported here.
  #
  # Unit: ppm. VSS: Vehicle.Cabin.AirQuality.CO2 (sensor).
  co2 @3 :Float64;
  # Nitrogen dioxide (NO2) concentration.
  #
  # Unit: ppb. VSS: Vehicle.Cabin.AirQuality.NO2 (sensor).
  no2 @4 :Float64;
  # Ozone (O3) concentration.
  #
  # Unit: ppb. VSS: Vehicle.Cabin.AirQuality.Ozone (sensor).
  ozone @5 :Float64;
  # Total volatile organic compounds (TVOC) concentration.
  #
  # Unit: ppb. VSS: Vehicle.Cabin.AirQuality.TVOC (sensor).
  tvoc @6 :Float64;
}
