@0xf78be81751c82594;

# Code generated by protoc-gen-buffers. DO NOT EDIT.
# versions:
# 	protoc-gen-buffers dev
# 	protoc (unknown)
# source: protobuf/covesa/vss/interior/cabin/v1/convertible.proto
#
# target: capnp
# field slots below are recorded in buffers.lock; edit the .proto, not this file
#
# https://github.com/the-protobuf-project/buffers
using Cxx = import "/capnp/c++.capnp";
$Cxx.namespace("protobuf::covesa::vss::interior::cabin::v1");

# Roof status on convertible vehicles.
#
# VSS: Vehicle.Cabin.Convertible.Status.
# (buffers.v1.enumeration).underlying asked for 32 bits. A Cap'n Proto enum is
# always 16, with no way to declare otherwise; the narrowing is honoured by
# the FlatBuffers target only.
enum CabinConvertibleState @0xcb529a4092ad53b1 {
  # Not specified.
  unspecified @0;
  # Not specified.
  undefined @1;
  # Closed.
  closed @2;
  # Open.
  open @3;
  # Closing.
  closing @4;
  # Opening.
  opening @5;
  # Stalled.
  stalled @6;
}

# Convertible roof.
#
# VSS: Vehicle.Cabin.Convertible.
#
# Reference: COVESA Vehicle Signal Specification.
# https://covesa.github.io/vehicle_signal_specification/
struct Convertible @0xa9358b0c75876984 {
  # Roof status on convertible vehicles.
  #
  # VSS: Vehicle.Cabin.Convertible.Status (sensor).
  roofPosition @0 :CabinConvertibleState;
}
