@0xbb70658588c50611;

# Code generated by protoc-gen-buffers. DO NOT EDIT.
# versions:
# 	protoc-gen-buffers dev
# 	protoc (unknown)
# source: protobuf/covesa/vss/interior/cabin/v1/destination_set.proto
#
# target: capnp
# field slots below are recorded in buffers.lock; edit the .proto, not this file
#
# https://github.com/the-protobuf-project/buffers
using Cxx = import "/capnp/c++.capnp";
$Cxx.namespace("protobuf::covesa::vss::interior::cabin::v1");

# A navigation has been selected.
#
# VSS: Vehicle.Cabin.Infotainment.Navigation.DestinationSet.
#
# Reference: COVESA Vehicle Signal Specification.
# https://covesa.github.io/vehicle_signal_specification/
struct DestinationSet @0xa44508bf9e5b7e2d {
  # Latitude of destination in WGS 84 geodetic coordinates.
  #
  # Unit: degrees. VSS:
  # Vehicle.Cabin.Infotainment.Navigation.DestinationSet.Latitude
  # (actuator).
  latitude @0 :Float64;
  # Longitude of destination in WGS 84 geodetic coordinates.
  #
  # Unit: degrees. VSS:
  # Vehicle.Cabin.Infotainment.Navigation.DestinationSet.Longitude
  # (actuator).
  longitude @1 :Float64;
}
