@0xa9db9c1d38991332;

# Code generated by protoc-gen-buffers. DO NOT EDIT.
# versions:
# 	protoc-gen-buffers dev
# 	protoc (unknown)
# source: protobuf/covesa/vss/interior/cabin/v1/hmi.proto
#
# target: capnp
# field slots below are recorded in buffers.lock; edit the .proto, not this file
#
# https://github.com/the-protobuf-project/buffers
using Cxx = import "/capnp/c++.capnp";
$Cxx.namespace("protobuf::covesa::vss::interior::cabin::v1");

using HmiTypes = import "/protobuf/covesa/vss/interior/cabin/v1/hmi_types.capnp";
using Wellknown = import "/buffers/wellknown.capnp";

# HMI related signals
#
# VSS: Vehicle.Cabin.Infotainment.HMI.
#
# Reference: COVESA Vehicle Signal Specification.
# https://covesa.github.io/vehicle_signal_specification/
struct Hmi @0x97cc45f75f6d5ca1 {
  # ISO 639-1 standard language code for the current HMI
  #
  # VSS: Vehicle.Cabin.Infotainment.HMI.CurrentLanguage (sensor).
  currentLanguage @0 :Text;
  # Font size used in the current HMI
  #
  # VSS: Vehicle.Cabin.Infotainment.HMI.FontSize (actuator).
  fontSize @1 :HmiTypes.InfotainmentHmiFontSize;
  # Date format used in the current HMI
  #
  # VSS: Vehicle.Cabin.Infotainment.HMI.DateFormat (actuator).
  dateFormat @2 :HmiTypes.InfotainmentHmiDateFormat;
  # Time format used in the current HMI
  #
  # VSS: Vehicle.Cabin.Infotainment.HMI.TimeFormat (actuator).
  timeFormat @3 :HmiTypes.InfotainmentHmiTimeFormat;
  # Distance unit used in the current HMI
  #
  # VSS: Vehicle.Cabin.Infotainment.HMI.DistanceUnit (actuator).
  distanceUnit @4 :HmiTypes.InfotainmentHmiDistanceUnit;
  # Fuel volume unit used in the current HMI
  #
  # VSS: Vehicle.Cabin.Infotainment.HMI.FuelVolumeUnit (actuator).
  fuelVolumeUnit @5 :HmiTypes.InfotainmentHmiFuelVolumeUnit;
  # Fuel economy unit used in the current HMI
  #
  # VSS: Vehicle.Cabin.Infotainment.HMI.FuelEconomyUnits (actuator).
  fuelEconomyUnits @6 :HmiTypes.InfotainmentHmiFuelEconomyUnits;
  # EV fuel economy unit used in the current HMI
  #
  # VSS: Vehicle.Cabin.Infotainment.HMI.EVEconomyUnits (actuator).
  evEconomyUnits @7 :HmiTypes.InfotainmentHmiEvEconomyUnits;
  # Temperature unit used in the current HMI
  #
  # VSS: Vehicle.Cabin.Infotainment.HMI.TemperatureUnit (actuator).
  temperatureUnit @8 :HmiTypes.InfotainmentHmiTemperatureUnit;
  # Tire pressure unit used in the current HMI
  #
  # VSS: Vehicle.Cabin.Infotainment.HMI.TirePressureUnit (actuator).
  tirePressureUnit @9 :HmiTypes.InfotainmentHmiTirePressureUnit;
  # Speed unit used in the current HMI
  #
  # VSS: Vehicle.Cabin.Infotainment.HMI.SpeedUnit (actuator).
  speedUnit @10 :HmiTypes.InfotainmentHmiSpeedUnit;
  # EV energy unit used in the current HMI
  #
  # Ampere hours is by definition not an energy unit, but can be used as a
  # measurement of energy if the voltage, like nominal voltage of the
  # battery, is known.
  #
  # VSS: Vehicle.Cabin.Infotainment.HMI.EVEnergyUnits (actuator).
  evEnergyUnits @11 :HmiTypes.InfotainmentHmiEvEnergyUnits;
  # Brightness of the HMI, relative to supported range. 0 = Lowest
  # brightness possible. 100 = Maximum Brightness possible.
  #
  # The value 0 does not necessarily correspond to a turned off HMI, as it
  # may not be allowed/supported to turn off the HMI completely.
  #
  # Unit: percent. VSS: Vehicle.Cabin.Infotainment.HMI.Brightness
  # (actuator).
  brightness @12 :Float64;
  # Current display theme
  #
  # VSS: Vehicle.Cabin.Infotainment.HMI.DayNightMode (actuator).
  dayNightMode @13 :HmiTypes.InfotainmentHmiDayNightMode;
  # Used to prevent the screen going black if no action placed.
  #
  # VSS: Vehicle.Cabin.Infotainment.HMI.IsScreenAlwaysOn (actuator).
  isScreenAlwaysOn @14 :Bool;
  # Time for last hmi action, formatted according to ISO 8601 with UTC time
  # zone.
  #
  # Unit: iso8601. VSS: Vehicle.Cabin.Infotainment.HMI.LastActionTime
  # (sensor).
  lastActionTime @15 :Wellknown.Timestamp;
  # Duration in seconds before the display is turned off. Value shall be 0
  # if screen never shall turn off.
  #
  # Display shall be turned off at HMI.LastActionTime +
  # HMI.DisplayOffDuration, unless HMI.IsScreenAlwaysOn==True.
  #
  # Unit: s. VSS: Vehicle.Cabin.Infotainment.HMI.DisplayOffDuration
  # (actuator).
  displayOffDuration @16 :Int32;
}
