@0xd53076ec3dfc533e;

# Code generated by protoc-gen-buffers. DO NOT EDIT.
# versions:
# 	protoc-gen-buffers dev
# 	protoc (unknown)
# source: protobuf/covesa/vss/interior/cabin/v1/hmi_types.proto
#
# target: capnp
# field slots below are recorded in buffers.lock; edit the .proto, not this file
#
# https://github.com/the-protobuf-project/buffers
using Cxx = import "/capnp/c++.capnp";
$Cxx.namespace("protobuf::covesa::vss::interior::cabin::v1");

# Font size used in the current HMI
#
# VSS: Vehicle.Cabin.Infotainment.HMI.FontSize.
# (buffers.v1.enumeration).underlying asked for 32 bits. A Cap'n Proto enum is
# always 16, with no way to declare otherwise; the narrowing is honoured by
# the FlatBuffers target only.
enum InfotainmentHmiFontSize @0xf98afc43d576c198 {
  # Not specified.
  unspecified @0;
  # Standard.
  standard @1;
  # Large.
  large @2;
  # Extra large.
  extraLarge @3;
}

# Date format used in the current HMI
#
# VSS: Vehicle.Cabin.Infotainment.HMI.DateFormat.
# (buffers.v1.enumeration).underlying asked for 32 bits. A Cap'n Proto enum is
# always 16, with no way to declare otherwise; the narrowing is honoured by
# the FlatBuffers target only.
enum InfotainmentHmiDateFormat @0xc9be73b7e3e0f4d1 {
  # Not specified.
  unspecified @0;
  # Yyyy mm dd.
  yyyyMmDd @1;
  # Dd mm yyyy.
  ddMmYyyy @2;
  # Mm dd yyyy.
  mmDdYyyy @3;
  # Yy mm dd.
  yyMmDd @4;
  # Dd mm yy.
  ddMmYy @5;
  # Mm dd yy.
  mmDdYy @6;
}

# Time format used in the current HMI
#
# VSS: Vehicle.Cabin.Infotainment.HMI.TimeFormat.
# (buffers.v1.enumeration).underlying asked for 32 bits. A Cap'n Proto enum is
# always 16, with no way to declare otherwise; the narrowing is honoured by
# the FlatBuffers target only.
enum InfotainmentHmiTimeFormat @0xb1490c6d8c4d8806 {
  # Not specified.
  unspecified @0;
  # Hr 12.
  hr12 @1;
  # Hr 24.
  hr24 @2;
}

# Distance unit used in the current HMI
#
# VSS: Vehicle.Cabin.Infotainment.HMI.DistanceUnit.
# (buffers.v1.enumeration).underlying asked for 32 bits. A Cap'n Proto enum is
# always 16, with no way to declare otherwise; the narrowing is honoured by
# the FlatBuffers target only.
enum InfotainmentHmiDistanceUnit @0xd44401f6aad855b9 {
  # Not specified.
  unspecified @0;
  # Miles.
  miles @1;
  # Kilometers.
  kilometers @2;
}

# Fuel volume unit used in the current HMI
#
# VSS: Vehicle.Cabin.Infotainment.HMI.FuelVolumeUnit.
# (buffers.v1.enumeration).underlying asked for 32 bits. A Cap'n Proto enum is
# always 16, with no way to declare otherwise; the narrowing is honoured by
# the FlatBuffers target only.
enum InfotainmentHmiFuelVolumeUnit @0xeb685eb8194d72c2 {
  # Not specified.
  unspecified @0;
  # Liter.
  liter @1;
  # Gallon us.
  gallonUs @2;
  # Gallon uk.
  gallonUk @3;
}

# Fuel economy unit used in the current HMI
#
# VSS: Vehicle.Cabin.Infotainment.HMI.FuelEconomyUnits.
# (buffers.v1.enumeration).underlying asked for 32 bits. A Cap'n Proto enum is
# always 16, with no way to declare otherwise; the narrowing is honoured by
# the FlatBuffers target only.
enum InfotainmentHmiFuelEconomyUnits @0xeb6378f50cbdfaa8 {
  # Not specified.
  unspecified @0;
  # Mpg uk.
  mpgUk @1;
  # Mpg us.
  mpgUs @2;
  # Miles per liter.
  milesPerLiter @3;
  # Kilometers per liter.
  kilometersPerLiter @4;
  # Liters per 100 kilometers.
  litersPer100Kilometers @5;
}

# EV fuel economy unit used in the current HMI
#
# VSS: Vehicle.Cabin.Infotainment.HMI.EVEconomyUnits.
# (buffers.v1.enumeration).underlying asked for 32 bits. A Cap'n Proto enum is
# always 16, with no way to declare otherwise; the narrowing is honoured by
# the FlatBuffers target only.
enum InfotainmentHmiEvEconomyUnits @0xa4b4da6acf83c7d4 {
  # Not specified.
  unspecified @0;
  # Miles per kilowatt hour.
  milesPerKilowattHour @1;
  # Kilometers per kilowatt hour.
  kilometersPerKilowattHour @2;
  # Kilowatt hours per 100 miles.
  kilowattHoursPer100Miles @3;
  # Kilowatt hours per 100 kilometers.
  kilowattHoursPer100Kilometers @4;
  # Watt hours per mile.
  wattHoursPerMile @5;
  # Watt hours per kilometer.
  wattHoursPerKilometer @6;
}

# Temperature unit used in the current HMI
#
# VSS: Vehicle.Cabin.Infotainment.HMI.TemperatureUnit.
# (buffers.v1.enumeration).underlying asked for 32 bits. A Cap'n Proto enum is
# always 16, with no way to declare otherwise; the narrowing is honoured by
# the FlatBuffers target only.
enum InfotainmentHmiTemperatureUnit @0xf4e83634f30c3c76 {
  # Not specified.
  unspecified @0;
  # C.
  c @1;
  # F.
  f @2;
}

# Tire pressure unit used in the current HMI
#
# VSS: Vehicle.Cabin.Infotainment.HMI.TirePressureUnit.
# (buffers.v1.enumeration).underlying asked for 32 bits. A Cap'n Proto enum is
# always 16, with no way to declare otherwise; the narrowing is honoured by
# the FlatBuffers target only.
enum InfotainmentHmiTirePressureUnit @0xe0b0859241630287 {
  # Not specified.
  unspecified @0;
  # Psi.
  psi @1;
  # Kpa.
  kpa @2;
  # Bar.
  bar @3;
}

# Speed unit used in the current HMI
#
# VSS: Vehicle.Cabin.Infotainment.HMI.SpeedUnit.
# (buffers.v1.enumeration).underlying asked for 32 bits. A Cap'n Proto enum is
# always 16, with no way to declare otherwise; the narrowing is honoured by
# the FlatBuffers target only.
enum InfotainmentHmiSpeedUnit @0xb0c4db97feb73c69 {
  # Not specified.
  unspecified @0;
  # Meters per second.
  metersPerSecond @1;
  # Miles per hour.
  milesPerHour @2;
  # Kilometers per hour.
  kilometersPerHour @3;
}

# EV energy unit used in the current HMI
#
# VSS: Vehicle.Cabin.Infotainment.HMI.EVEnergyUnits.
# (buffers.v1.enumeration).underlying asked for 32 bits. A Cap'n Proto enum is
# always 16, with no way to declare otherwise; the narrowing is honoured by
# the FlatBuffers target only.
enum InfotainmentHmiEvEnergyUnits @0xb7af89c0c9d29954 {
  # Not specified.
  unspecified @0;
  # Watt hours.
  wattHours @1;
  # Ampere hours.
  ampereHours @2;
  # Kilowatt hours.
  kilowattHours @3;
}

# Current display theme
#
# VSS: Vehicle.Cabin.Infotainment.HMI.DayNightMode.
# (buffers.v1.enumeration).underlying asked for 32 bits. A Cap'n Proto enum is
# always 16, with no way to declare otherwise; the narrowing is honoured by
# the FlatBuffers target only.
enum InfotainmentHmiDayNightMode @0xaaf7dae1f702b87e {
  # Not specified.
  unspecified @0;
  # Day.
  day @1;
  # Night.
  night @2;
}
