@0xb6afaa9c8427c7f3;

# Code generated by protoc-gen-buffers. DO NOT EDIT.
# versions:
# 	protoc-gen-buffers dev
# 	protoc (unknown)
# source: protobuf/covesa/vss/interior/cabin/v1/hvac.proto
#
# target: capnp
# field slots below are recorded in buffers.lock; edit the .proto, not this file
#
# https://github.com/the-protobuf-project/buffers
using Cxx = import "/capnp/c++.capnp";
$Cxx.namespace("protobuf::covesa::vss::interior::cabin::v1");

# Climate control
#
# VSS: Vehicle.Cabin.HVAC.
#
# Reference: COVESA Vehicle Signal Specification.
# https://covesa.github.io/vehicle_signal_specification/
struct Hvac @0xe81ad713d6e57ce1 {
  # Is recirculation active.
  #
  # VSS: Vehicle.Cabin.HVAC.IsRecirculationActive (actuator).
  isRecirculationActive @0 :Bool;
  # Is front defroster active.
  #
  # VSS: Vehicle.Cabin.HVAC.IsFrontDefrosterActive (actuator).
  isFrontDefrosterActive @1 :Bool;
  # Is rear defroster active.
  #
  # VSS: Vehicle.Cabin.HVAC.IsRearDefrosterActive (actuator).
  isRearDefrosterActive @2 :Bool;
  # Is Air conditioning active.
  #
  # VSS: Vehicle.Cabin.HVAC.IsAirConditioningActive (actuator).
  isAirConditioningActive @3 :Bool;
  # Ambient air temperature inside the vehicle.
  #
  # Unit: Celsius. VSS: Vehicle.Cabin.HVAC.AmbientAirTemperature (sensor).
  ambientAirTemperature @4 :Float64;
  # Power optimization level for this branch/subsystem. A higher number
  # indicates more aggressive power optimization. Level 0 indicates that all
  # functionality is enabled, no power optimization enabled. Level 10
  # indicates most aggressive power optimization mode, only essential
  # functionality enabled.
  #
  # VSS: Vehicle.Cabin.HVAC.PowerOptimizeLevel (actuator).
  powerOptimizeLevel @5 :Int32;
  # Auto Power Optimization Flag When set to 'true', the system enables
  # automatic power optimization, dynamically adjusting the power
  # optimization level based on runtime conditions or features managed by
  # the OEM. When set to 'false', manual control of the power optimization
  # level is allowed.
  #
  # VSS: Vehicle.Cabin.HVAC.IsAutoPowerOptimize (actuator).
  isAutoPowerOptimize @6 :Bool;
}
