@0xeeb86c96674a08e4;

# Code generated by protoc-gen-buffers. DO NOT EDIT.
# versions:
# 	protoc-gen-buffers dev
# 	protoc (unknown)
# source: protobuf/covesa/vss/interior/cabin/v1/messages.proto
#
# target: capnp
# field slots below are recorded in buffers.lock; edit the .proto, not this file
#
# https://github.com/the-protobuf-project/buffers
using Cxx = import "/capnp/c++.capnp";
$Cxx.namespace("protobuf::covesa::vss::interior::cabin::v1");

using Cabin = import "/protobuf/covesa/vss/interior/cabin/v1/cabin.capnp";

# Request message for Cabins.GetCabin, AIP-131 <https://aip.dev/131>.
struct GetCabinRequest @0x909f2a1d00e7d677 {
  # Name of the Cabin to retrieve, "vehicles/{vehicle}/cabin".
  # REQUIRED (AIP-203); Cap'n Proto cannot enforce it.
  name @0 :Text;
}

# Request message for Cabins.UpdateCabin, AIP-134 <https://aip.dev/134>.
struct UpdateCabinRequest @0xade82a1ac92e41f3 {
  # The Cabin to update. Its name field identifies the resource.
  # REQUIRED (AIP-203); Cap'n Proto cannot enforce it.
  cabin @0 :Cabin.Cabin;
  # Fields to update. An empty mask updates all mutable fields.
  #
  # Only an actuator is writable. A sensor or attribute named in the mask is
  # rejected: both are OUTPUT_ONLY, because a vehicle reports them and an
  # API cannot set them.
  updateMask @1 :List(Text);
}
