@0xf18c95b87b07b7a8;

# Code generated by protoc-gen-buffers. DO NOT EDIT.
# versions:
# 	protoc-gen-buffers dev
# 	protoc (unknown)
# source: protobuf/covesa/vss/interior/cabin/v1/played.proto
#
# target: capnp
# field slots below are recorded in buffers.lock; edit the .proto, not this file
#
# https://github.com/the-protobuf-project/buffers
using Cxx = import "/capnp/c++.capnp";
$Cxx.namespace("protobuf::covesa::vss::interior::cabin::v1");

# Media selected for playback
#
# VSS: Vehicle.Cabin.Infotainment.Media.Played.Source.
# (buffers.v1.enumeration).underlying asked for 32 bits. A Cap'n Proto enum is
# always 16, with no way to declare otherwise; the narrowing is honoured by
# the FlatBuffers target only.
enum MediaPlayedSource @0xb99650da53531fd7 {
  # Not specified.
  unspecified @0;
  # Not specified.
  unknown @1;
  # Sirius xm.
  siriusXm @2;
  # Am.
  am @3;
  # Fm.
  fm @4;
  # Dab.
  dab @5;
  # Tv.
  tv @6;
  # Cd.
  cd @7;
  # Dvd.
  dvd @8;
  # Aux.
  aux @9;
  # Usb.
  usb @10;
  # Disk.
  disk @11;
  # Bluetooth.
  bluetooth @12;
  # Internet.
  internet @13;
  # Voice.
  voice @14;
  # Beep.
  beep @15;
}

# Collection of signals updated in concert when a new media is played
#
# VSS: Vehicle.Cabin.Infotainment.Media.Played.
#
# Reference: COVESA Vehicle Signal Specification.
# https://covesa.github.io/vehicle_signal_specification/
struct Played @0xf69ff2d6a30ee44a {
  # Media selected for playback
  #
  # VSS: Vehicle.Cabin.Infotainment.Media.Played.Source (actuator).
  source @0 :MediaPlayedSource;
  # Name of genre being played
  #
  # VSS: Vehicle.Cabin.Infotainment.Media.Played.Genre (sensor).
  genre @1 :Text;
  # Name of artist being played
  #
  # VSS: Vehicle.Cabin.Infotainment.Media.Played.Artist (sensor).
  artist @2 :Text;
  # Name of album being played
  #
  # VSS: Vehicle.Cabin.Infotainment.Media.Played.Album (sensor).
  album @3 :Text;
  # Name of track being played
  #
  # VSS: Vehicle.Cabin.Infotainment.Media.Played.Track (sensor).
  track @4 :Text;
  # User Resource associated with the media
  #
  # VSS: Vehicle.Cabin.Infotainment.Media.Played.URI (sensor).
  uri @5 :Text;
  # Current playback rate of media being played.
  #
  # The normal playback rate is multiplied by this value to obtain the
  # current rate, so a value of 1.0 indicates normal speed. Values of lower
  # than 1.0 make the media play slower than normal. Values of higher than
  # 1.0 make the media play faster than normal.
  #
  # VSS: Vehicle.Cabin.Infotainment.Media.Played.PlaybackRate (actuator).
  playbackRate @6 :Float64;
}
