@0xc4ae8318f1b5d200;

# Code generated by protoc-gen-buffers. DO NOT EDIT.
# versions:
# 	protoc-gen-buffers dev
# 	protoc (unknown)
# source: protobuf/covesa/vss/interior/cabin/v1/rearview_mirror.proto
#
# target: capnp
# field slots below are recorded in buffers.lock; edit the .proto, not this file
#
# https://github.com/the-protobuf-project/buffers
using Cxx = import "/capnp/c++.capnp";
$Cxx.namespace("protobuf::covesa::vss::interior::cabin::v1");

# Rear-view mirror.
#
# VSS: Vehicle.Cabin.RearviewMirror.
#
# Reference: COVESA Vehicle Signal Specification.
# https://covesa.github.io/vehicle_signal_specification/
struct RearviewMirror @0xec8a77397105df78 {
  # Dimming level of rear-view mirror. 0 = Undimmed. 100 = Fully dimmed.
  #
  # Unit: percent. VSS: Vehicle.Cabin.RearviewMirror.DimmingLevel
  # (actuator).
  dimmingLevel @0 :Int32;
}
