@0x974779d5ccb47313;

# Code generated by protoc-gen-buffers. DO NOT EDIT.
# versions:
# 	protoc-gen-buffers dev
# 	protoc (unknown)
# source: protobuf/covesa/vss/interior/cabin/v1/service.proto
#
# target: capnp
# field slots below are recorded in buffers.lock; edit the .proto, not this file
#
# https://github.com/the-protobuf-project/buffers
using Cxx = import "/capnp/c++.capnp";
$Cxx.namespace("protobuf::covesa::vss::interior::cabin::v1");

using Cabin = import "/protobuf/covesa/vss/interior/cabin/v1/cabin.capnp";
using Messages = import "/protobuf/covesa/vss/interior/cabin/v1/messages.capnp";

# Cabins manages the Cabin branch of a vehicle.
#
# A **singleton**, AIP-156 <https://aip.dev/156>: a vehicle has exactly one,
# its name has no id segment, and it cannot be created or deleted
# independently of the vehicle. Get and Update are the whole surface.
#
# Reference: COVESA Vehicle Signal Specification.
# https://covesa.github.io/vehicle_signal_specification/
interface Cabins @0x89f2d628c900a774 {
  # Retrieves one Cabin.
  #
  # GET /v1/{name=vehicles/*/cabin}
  #
  # Safe and idempotent. Read the `etag` here and pass it back on update to
  # make the write conditional.
  #
  # NOT_FOUND no such Cabin
  # INVALID_ARGUMENT name does not match the resource pattern
  # PERMISSION_DENIED caller may not read it
  # AIP-131 standard method.
  getCabin @0 (request :Messages.GetCabinRequest) -> (response :Cabin.Cabin);

  # Updates a Cabin.
  #
  # PATCH /v1/{cabin.name=vehicles/*/cabin}
  # body: the Cabin itself
  #
  # A partial update: only fields named in `update_mask` are written. An
  # empty mask writes every mutable field, which will clear anything the
  # caller left unset -- pass a mask unless that is the intent.
  #
  # **Only an actuator is writable.** VSS marks each signal an attribute, a
  # sensor or an actuator; the first two are OUTPUT_ONLY here, because a
  # vehicle reports them and no API call can change them. A mask naming one
  # is rejected rather than silently ignored.
  #
  # Idempotent. Pass the `etag` read from Get to make the write conditional.
  #
  # NOT_FOUND no such Cabin
  # ABORTED etag does not match the stored resource
  # INVALID_ARGUMENT mask names an unknown, immutable or read-only field
  # PERMISSION_DENIED caller may not modify it
  # AIP-134 standard method.
  updateCabin @1 (request :Messages.UpdateCabinRequest) -> (response :Cabin.Cabin);
}
