@0xc6972949f0258ef7;

# Code generated by protoc-gen-buffers. DO NOT EDIT.
# versions:
# 	protoc-gen-buffers dev
# 	protoc (unknown)
# source: protobuf/covesa/vss/interior/cabin/v1/shade.proto
#
# target: capnp
# field slots below are recorded in buffers.lock; edit the .proto, not this file
#
# https://github.com/the-protobuf-project/buffers
using Cxx = import "/capnp/c++.capnp";
$Cxx.namespace("protobuf::covesa::vss::interior::cabin::v1");

# Switch controlling sliding action such as window, sunroof, or blind.
#
# VSS: Vehicle.Cabin.Sunroof.Shade.Switch.
# (buffers.v1.enumeration).underlying asked for 32 bits. A Cap'n Proto enum is
# always 16, with no way to declare otherwise; the narrowing is honoured by
# the FlatBuffers target only.
enum SunroofShadeSwitch @0xa9f86794fe6b1f9d {
  # Not specified.
  unspecified @0;
  # Inactive.
  inactive @1;
  # Close.
  close @2;
  # Open.
  open @3;
  # One shot close.
  oneShotClose @4;
  # One shot open.
  oneShotOpen @5;
}

# Sun roof shade status. Open = Retracted, Closed = Deployed. Start position
# for Sunroof.Shade is Open/Retracted.
#
# VSS: Vehicle.Cabin.Sunroof.Shade.
#
# Reference: COVESA Vehicle Signal Specification.
# https://covesa.github.io/vehicle_signal_specification/
struct Shade @0xc3acc122c6d8a8ce {
  # Is item open or closed? True = Fully or partially open. False = Fully
  # closed.
  #
  # VSS: Vehicle.Cabin.Sunroof.Shade.IsOpen (actuator).
  isOpen @0 :Bool;
  # Item position. 0 = Start position 100 = End position.
  #
  # Relationship between Open/Close and Start/End position is item
  # dependent.
  #
  # Unit: percent. VSS: Vehicle.Cabin.Sunroof.Shade.Position (actuator).
  position @1 :Int32;
  # Switch controlling sliding action such as window, sunroof, or blind.
  #
  # VSS: Vehicle.Cabin.Sunroof.Shade.Switch (actuator).
  switchControl @2 :SunroofShadeSwitch;
}
