@0xf8878103f823ee39;

# Code generated by protoc-gen-buffers. DO NOT EDIT.
# versions:
# 	protoc-gen-buffers dev
# 	protoc (unknown)
# source: protobuf/covesa/vss/interior/cabin/v1/smartphone_projection.proto
#
# target: capnp
# field slots below are recorded in buffers.lock; edit the .proto, not this file
#
# https://github.com/the-protobuf-project/buffers
using Cxx = import "/capnp/c++.capnp";
$Cxx.namespace("protobuf::covesa::vss::interior::cabin::v1");

# Projection activation info.
#
# VSS: Vehicle.Cabin.Infotainment.SmartphoneProjection.Active.
# (buffers.v1.enumeration).underlying asked for 32 bits. A Cap'n Proto enum is
# always 16, with no way to declare otherwise; the narrowing is honoured by
# the FlatBuffers target only.
enum InfotainmentSmartphoneProjectionActive @0xd25ad6af9d39af90 {
  # Not specified.
  unspecified @0;
  # None.
  none @1;
  # Active.
  active @2;
  # Inactive.
  inactive @3;
}

# Connectivity source selected for projection.
#
# VSS: Vehicle.Cabin.Infotainment.SmartphoneProjection.Source.
# (buffers.v1.enumeration).underlying asked for 32 bits. A Cap'n Proto enum is
# always 16, with no way to declare otherwise; the narrowing is honoured by
# the FlatBuffers target only.
enum InfotainmentSmartphoneProjectionSource @0xd3acbfd6b825f196 {
  # Not specified.
  unspecified @0;
  # Usb.
  usb @1;
  # Bluetooth.
  bluetooth @2;
  # Wifi.
  wifi @3;
}

# Supportable list for projection.
#
# VSS: Vehicle.Cabin.Infotainment.SmartphoneProjection.SupportedMode.
# (buffers.v1.enumeration).underlying asked for 32 bits. A Cap'n Proto enum is
# always 16, with no way to declare otherwise; the narrowing is honoured by
# the FlatBuffers target only.
enum InfotainmentSmartphoneProjectionSupportedMode @0xde81bd7fd8837c30 {
  # Not specified.
  unspecified @0;
  # Android auto.
  androidAuto @1;
  # Apple carplay.
  appleCarplay @2;
  # Mirror link.
  mirrorLink @3;
  # Other.
  other @4;
}

# All smartphone projection actions.
#
# Smartphone projection exposes or controls specific applications on the
# Smartphone on the vehicle infotainment system.
#
# VSS: Vehicle.Cabin.Infotainment.SmartphoneProjection.
#
# Reference: COVESA Vehicle Signal Specification.
# https://covesa.github.io/vehicle_signal_specification/
struct SmartphoneProjection @0xb1246595539a526e {
  # Projection activation info.
  #
  # NONE indicates that projection is not supported.
  #
  # VSS: Vehicle.Cabin.Infotainment.SmartphoneProjection.Active (actuator).
  active @0 :InfotainmentSmartphoneProjectionActive;
  # Connectivity source selected for projection.
  #
  # Smartphone projection exposes or controls specific applications on the
  # Smartphone on the vehicle infotainment system.
  #
  # VSS: Vehicle.Cabin.Infotainment.SmartphoneProjection.Source (actuator).
  source @1 :InfotainmentSmartphoneProjectionSource;
  # Supportable list for projection.
  #
  # VSS: Vehicle.Cabin.Infotainment.SmartphoneProjection.SupportedMode
  # (attribute).
  supportedMode @2 :List(InfotainmentSmartphoneProjectionSupportedMode);
}
