@0xb4ea61b556f881ca;

# Code generated by protoc-gen-buffers. DO NOT EDIT.
# versions:
# 	protoc-gen-buffers dev
# 	protoc (unknown)
# source: protobuf/covesa/vss/interior/cabin/v1/sunroof.proto
#
# target: capnp
# field slots below are recorded in buffers.lock; edit the .proto, not this file
#
# https://github.com/the-protobuf-project/buffers
using Cxx = import "/capnp/c++.capnp";
$Cxx.namespace("protobuf::covesa::vss::interior::cabin::v1");

using Shade = import "/protobuf/covesa/vss/interior/cabin/v1/shade.capnp";

# Switch controlling sliding action such as window, sunroof, or shade.
#
# VSS: Vehicle.Cabin.Sunroof.Switch.
# (buffers.v1.enumeration).underlying asked for 32 bits. A Cap'n Proto enum is
# always 16, with no way to declare otherwise; the narrowing is honoured by
# the FlatBuffers target only.
enum CabinSunroofSwitch @0xcccd230a72a8e905 {
  # Not specified.
  unspecified @0;
  # Inactive.
  inactive @1;
  # Close.
  close @2;
  # Open.
  open @3;
  # One shot close.
  oneShotClose @4;
  # One shot open.
  oneShotOpen @5;
  # Tilt up.
  tiltUp @6;
  # Tilt down.
  tiltDown @7;
}

# Sun roof status.
#
# VSS: Vehicle.Cabin.Sunroof.
#
# Reference: COVESA Vehicle Signal Specification.
# https://covesa.github.io/vehicle_signal_specification/
struct Sunroof @0xb3fc3073496f2ba1 {
  # Sunroof position. 0 = Fully closed 100 = Fully opened. -100 = Fully
  # tilted.
  #
  # Unit: percent. VSS: Vehicle.Cabin.Sunroof.Position (sensor).
  position @0 :Int32;
  # Switch controlling sliding action such as window, sunroof, or shade.
  #
  # VSS: Vehicle.Cabin.Sunroof.Switch (actuator).
  switchControl @1 :CabinSunroofSwitch;
  # Sun roof shade status. Open = Retracted, Closed = Deployed. Start
  # position for Sunroof.Shade is Open/Retracted.
  #
  # VSS: Vehicle.Cabin.Sunroof.Shade.
  shade @2 :Shade.Shade;
}
