@0x8a66ff3ede4672ae;

# Code generated by protoc-gen-buffers. DO NOT EDIT.
# versions:
# 	protoc-gen-buffers dev
# 	protoc (unknown)
# source: protobuf/covesa/vdm/name/v1/messages.proto
#
# target: capnp
# field slots below are recorded in buffers.lock; edit the .proto, not this file
#
# https://github.com/the-protobuf-project/buffers
using Cxx = import "/capnp/c++.capnp";
$Cxx.namespace("protobuf::covesa::vdm::name::v1");

using Name = import "/protobuf/covesa/vdm/name/v1/name.capnp";

# Request message for Names.GetName, AIP-131 <https://aip.dev/131>.
struct GetNameRequest @0x958eeb1958bf8fda {
  # Name of the Name to retrieve, "people/{person}/name".
  # REQUIRED (AIP-203); Cap'n Proto cannot enforce it.
  name @0 :Text;
}

# Request message for Names.UpdateName, AIP-134 <https://aip.dev/134>.
struct UpdateNameRequest @0xd3ca7011cbfa79cc {
  # The Name to update. Its name field identifies the resource.
  # REQUIRED (AIP-203); Cap'n Proto cannot enforce it.
  name @0 :Name.Name;
  # Fields to update. An empty mask updates all mutable fields.
  #
  # Only an actuator is writable. A sensor or attribute named in the mask is
  # rejected: both are OUTPUT_ONLY, because a vehicle reports them and an
  # API cannot set them.
  updateMask @1 :List(Text);
}
