@0x855c3b963ad12f32;

# Code generated by protoc-gen-buffers. DO NOT EDIT.
# versions:
# 	protoc-gen-buffers dev
# 	protoc (unknown)
# source: protobuf/covesa/vdm/name/v1/service.proto
#
# target: capnp
# field slots below are recorded in buffers.lock; edit the .proto, not this file
#
# https://github.com/the-protobuf-project/buffers
using Cxx = import "/capnp/c++.capnp";
$Cxx.namespace("protobuf::covesa::vdm::name::v1");

using Messages = import "/protobuf/covesa/vdm/name/v1/messages.capnp";
using Name = import "/protobuf/covesa/vdm/name/v1/name.capnp";

# Names manages the Name branch of a vehicle.
#
# A **singleton**, AIP-156 <https://aip.dev/156>: a vehicle has exactly one,
# its name has no id segment, and it cannot be created or deleted
# independently of the vehicle. Get and Update are the whole surface.
#
# Reference: COVESA Vehicle Signal Specification.
# https://covesa.github.io/vehicle_signal_specification/
interface Names @0xb76c7d496bd56de8 {
  # Retrieves one Name.
  #
  # GET /v1/{name=people/*/name}
  #
  # Safe and idempotent. Read the `etag` here and pass it back on update to
  # make the write conditional.
  #
  # NOT_FOUND no such Name
  # INVALID_ARGUMENT name does not match the resource pattern
  # PERMISSION_DENIED caller may not read it
  # AIP-131 standard method.
  getName @0 (request :Messages.GetNameRequest) -> (response :Name.Name);

  # Updates a Name.
  #
  # PATCH /v1/{name.name=people/*/name}
  # body: the Name itself
  #
  # A partial update: only fields named in `update_mask` are written. An
  # empty mask writes every mutable field, which will clear anything the
  # caller left unset -- pass a mask unless that is the intent.
  #
  # **Only an actuator is writable.** VSS marks each signal an attribute, a
  # sensor or an actuator; the first two are OUTPUT_ONLY here, because a
  # vehicle reports them and no API call can change them. A mask naming one
  # is rejected rather than silently ignored.
  #
  # Idempotent. Pass the `etag` read from Get to make the write conditional.
  #
  # NOT_FOUND no such Name
  # ABORTED etag does not match the stored resource
  # INVALID_ARGUMENT mask names an unknown, immutable or read-only field
  # PERMISSION_DENIED caller may not modify it
  # AIP-134 standard method.
  updateName @1 (request :Messages.UpdateNameRequest) -> (response :Name.Name);
}
