@0xf81df34de9c504fd;

# Code generated by protoc-gen-buffers. DO NOT EDIT.
# versions:
# 	protoc-gen-buffers dev
# 	protoc (unknown)
# source: protobuf/covesa/vss/motion/chassis_axle/v1/chassis_axle.proto
#
# target: capnp
# field slots below are recorded in buffers.lock; edit the .proto, not this file
#
# https://github.com/the-protobuf-project/buffers
using Cxx = import "/capnp/c++.capnp";
$Cxx.namespace("protobuf::covesa::vss::motion::chassis_axle::v1");

using Wellknown = import "/buffers/wellknown.capnp";

# Axle signals
#
# VSS: Vehicle.Chassis.Axle.
#
# Instanced: Row1, Row2. The axes together name one occurrence, which is why
# each is a resource of its own rather than a repeated field.
#
# A child resource of Chassis, named
# "vehicles/{vehicle}/chassisAxles/{chassis_axle}". Its parent is a declared
# resource in protobuf.covesa.vss.motion.chassis.v1, which is what makes
# this pattern legal rather than a reference to a collection nothing can
# create.
#
# Reference: COVESA Vehicle Signal Specification.
# https://covesa.github.io/vehicle_signal_specification/
struct ChassisAxle @0xc8a5fe796fee84d9 {
  # Resource name, "vehicles/{vehicle}/chassisAxles/{chassis_axle}".
  # Assigned by the server.
  name @0 :Text;
  # Server-assigned unique id.
  uid @1 :Text;
  # Weak validator for optimistic concurrency, AIP-154
  # <https://aip.dev/154>.
  etag @2 :Text;
  # When this resource was soft-deleted, unset while it is live. AIP-164
  # <https://aip.dev/164>.
  deleteTime @3 :Wellknown.Timestamp;
  # When a soft-deleted resource is purged for good. AIP-164
  # <https://aip.dev/164>.
  expireTime @4 :Wellknown.Timestamp;
  # When this resource was created.
  createTime @5 :Wellknown.Timestamp;
  # When this resource was last modified.
  updateTime @6 :Wellknown.Timestamp;
  # proto field 8 was removed and reserved; this holds its ordinal.
  removed8 @7 :Void;
  # proto field 9 was removed and reserved; this holds its ordinal.
  removed9 @8 :Void;
  # proto field 10 was removed and reserved; this holds its ordinal.
  removed10 @9 :Void;
  # proto field 11 was removed and reserved; this holds its ordinal.
  removed11 @10 :Void;
  # proto field 12 was removed and reserved; this holds its ordinal.
  removed12 @11 :Void;
  # proto field 13 was removed and reserved; this holds its ordinal.
  removed13 @12 :Void;
  # proto field 14 was removed and reserved; this holds its ordinal.
  removed14 @13 :Void;
  # proto field 15 was removed and reserved; this holds its ordinal.
  removed15 @14 :Void;
  # The lateral distance between the centerlines of the base tires at
  # ground, including camber angle. If there are dual rear wheels, measure
  # from the midway points between the inner and outer tires.
  #
  # Corresponds to SAE J1100-2009 W101.
  #
  # Unit: mm. VSS: Vehicle.Chassis.Axle.TreadWidth (attribute).
  treadWidth @15 :Int32;
  # The lateral distance between the centers of the wheels, measured along
  # the spindle, or axle axis. If there are dual rear wheels, measure from
  # the midway points between the inner and outer tires.
  #
  # Corresponds to SAE J1100-2009 W102.
  #
  # Unit: mm. VSS: Vehicle.Chassis.Axle.TrackWidth (attribute).
  trackWidth @16 :Int32;
  # The lateral distance between the wheel mounting faces, measured along
  # the spindle axis.
  #
  # Corresponds to SAE J1100-2009 W113.
  #
  # Unit: mm. VSS: Vehicle.Chassis.Axle.AxleWidth (attribute).
  axleWidth @17 :Int32;
  # Number of wheels on the axle
  #
  # VSS: Vehicle.Chassis.Axle.WheelCount (attribute).
  wheelCount @18 :Int32;
  # Diameter of wheels (rims without tires), in inches, as per ETRTO / TRA
  # standard.
  #
  # Unit: inch. VSS: Vehicle.Chassis.Axle.WheelDiameter (attribute).
  wheelDiameter @19 :Float64;
  # Width of wheels (rims without tires), in inches, as per ETRTO / TRA
  # standard.
  #
  # Unit: inch. VSS: Vehicle.Chassis.Axle.WheelWidth (attribute).
  wheelWidth @20 :Float64;
  # Single track two-axle model steering angle. Angle according to ISO 8855.
  # Positive = degrees to the left. Negative = degrees to the right.
  #
  # Single track two-axle model steering angle refers to the angle that a
  # centrally mounted wheel would have.
  #
  # Unit: degrees. VSS: Vehicle.Chassis.Axle.SteeringAngle (sensor).
  steeringAngle @21 :Float64;
  # Outer diameter of tires, in inches, as per ETRTO / TRA standard.
  #
  # Unit: inch. VSS: Vehicle.Chassis.Axle.TireDiameter (attribute).
  tireDiameter @22 :Float64;
  # Nominal section width of tires, in mm, as per ETRTO / TRA standard.
  #
  # Unit: mm. VSS: Vehicle.Chassis.Axle.TireWidth (attribute).
  tireWidth @23 :Int32;
  # Aspect ratio between tire section height and tire section width, as per
  # ETRTO / TRA standard.
  #
  # Unit: percent. VSS: Vehicle.Chassis.Axle.TireAspectRatio (attribute).
  tireAspectRatio @24 :Int32;
  # Incoming axle torque to differential. Negative values indicate regen
  # mode.
  #
  # For combustion engine this typically corresponds to the output torque of
  # the multi-speed gearbox. For electrical motor this typically corresponds
  # to the output torque of the single-speed reduction-gear. This signal is
  # typically not used if there is separate electrical motors for left and
  # right wheels.
  #
  # Unit: Nm. VSS: Vehicle.Chassis.Axle.Torque (sensor).
  torque @25 :Int32;
}
