@0xd9fd831235fa09c1;

# Code generated by protoc-gen-buffers. DO NOT EDIT.
# versions:
# 	protoc-gen-buffers dev
# 	protoc (unknown)
# source: protobuf/covesa/vss/motion/chassis_axle/v1/messages.proto
#
# target: capnp
# field slots below are recorded in buffers.lock; edit the .proto, not this file
#
# https://github.com/the-protobuf-project/buffers
using Cxx = import "/capnp/c++.capnp";
$Cxx.namespace("protobuf::covesa::vss::motion::chassis_axle::v1");

using ChassisAxle = import "/protobuf/covesa/vss/motion/chassis_axle/v1/chassis_axle.capnp";

# Request message for ChassisAxles.GetChassisAxle, AIP-131
# <https://aip.dev/131>.
struct GetChassisAxleRequest @0xbe3a4ccb39901428 {
  # Name of the ChassisAxle to retrieve,
  # "vehicles/{vehicle}/chassisAxles/{chassis_axle}".
  # REQUIRED (AIP-203); Cap'n Proto cannot enforce it.
  name @0 :Text;
}

# Request message for ChassisAxles.ListChassisAxles, AIP-132
# <https://aip.dev/132>.
struct ListChassisAxlesRequest @0x873f2f9ac6001e18 {
  # The Vehicle whose chassisAxles to list, "vehicles/{vehicle}".
  # REQUIRED (AIP-203); Cap'n Proto cannot enforce it.
  parent @0 :Text;
  # Maximum chassisAxles to return. Defaults to 50, capped at 1000.
  pageSize @1 :Int32;
  # Page token from a previous ListChassisAxlesResponse.next_page_token.
  pageToken @2 :Text;
  # Filter expression, AIP-160 <https://aip.dev/160>.
  filter @3 :Text;
  # Include soft-deleted chassisAxles. AIP-164 <https://aip.dev/164>.
  showDeleted @4 :Bool;
}

# Response message for ChassisAxles.ListChassisAxles, AIP-132
# <https://aip.dev/132>.
struct ListChassisAxlesResponse @0x9ed00e839fffaa4d {
  # The chassisAxles on this page.
  chassisAxles @0 :List(ChassisAxle.ChassisAxle);
  # Token for the next page, empty when this is the last page.
  nextPageToken @1 :Text;
}

# Request message for ChassisAxles.CreateChassisAxle, AIP-133
# <https://aip.dev/133>.
struct CreateChassisAxleRequest @0x97aa9fb63bc7dda5 {
  # The Vehicle to create the ChassisAxle under, "vehicles/{vehicle}".
  # REQUIRED (AIP-203); Cap'n Proto cannot enforce it.
  parent @0 :Text;
  # The ChassisAxle to create.
  # REQUIRED (AIP-203); Cap'n Proto cannot enforce it.
  chassisAxle @1 :ChassisAxle.ChassisAxle;
  # Client-assigned id, becoming the last segment of the resource name. The
  # server generates one when empty.
  chassisAxleId @2 :Text;
}

# Request message for ChassisAxles.UpdateChassisAxle, AIP-134
# <https://aip.dev/134>.
struct UpdateChassisAxleRequest @0xccf7d26103dd31bb {
  # The ChassisAxle to update. Its name field identifies the resource.
  # REQUIRED (AIP-203); Cap'n Proto cannot enforce it.
  chassisAxle @0 :ChassisAxle.ChassisAxle;
  # Fields to update. An empty mask updates all mutable fields.
  #
  # Only an actuator is writable. A sensor or attribute named in the mask is
  # rejected: both are OUTPUT_ONLY, because a vehicle reports them and an
  # API cannot set them.
  updateMask @1 :List(Text);
}

# Request message for ChassisAxles.DeleteChassisAxle, AIP-135
# <https://aip.dev/135>.
struct DeleteChassisAxleRequest @0xfa910d95afce3557 {
  # Name of the ChassisAxle to delete,
  # "vehicles/{vehicle}/chassisAxles/{chassis_axle}".
  # REQUIRED (AIP-203); Cap'n Proto cannot enforce it.
  name @0 :Text;
}

# Request message for ChassisAxles.UndeleteChassisAxle, AIP-164
# <https://aip.dev/164>.
struct UndeleteChassisAxleRequest @0xa08d9343e8d06b6d {
  # Name of the soft-deleted ChassisAxle to restore,
  # "vehicles/{vehicle}/chassisAxles/{chassis_axle}".
  # REQUIRED (AIP-203); Cap'n Proto cannot enforce it.
  name @0 :Text;
}
