@0xbf03a9de0769bb90;

# Code generated by protoc-gen-buffers. DO NOT EDIT.
# versions:
# 	protoc-gen-buffers dev
# 	protoc (unknown)
# source: protobuf/covesa/vss/exterior/exterior/v1/exterior.proto
#
# target: capnp
# field slots below are recorded in buffers.lock; edit the .proto, not this file
#
# https://github.com/the-protobuf-project/buffers
using Cxx = import "/capnp/c++.capnp";
$Cxx.namespace("protobuf::covesa::vss::exterior::exterior::v1");

using AirQuality = import "/protobuf/covesa/vss/exterior/exterior/v1/air_quality.capnp";
using ExteriorTypes = import "/protobuf/covesa/vss/exterior/exterior/v1/exterior_types.capnp";
using Wellknown = import "/buffers/wellknown.capnp";

# Information about exterior measured by vehicle.
#
# VSS: Vehicle.Exterior.
#
# A singleton child resource of Vehicle, AIP-156 <https://aip.dev/156>,
# named "vehicles/{vehicle}/exterior". Its parent is a declared resource in
# protobuf.covesa.vss.vehicle.v1, which is what makes this pattern legal
# rather than a reference to a collection nothing can create.
#
# Reference: COVESA Vehicle Signal Specification.
# https://covesa.github.io/vehicle_signal_specification/
struct Exterior @0x864263da6b9818fe {
  # Resource name, "vehicles/{vehicle}/exterior". Assigned by the server.
  name @0 :Text;
  # Server-assigned unique id.
  uid @1 :Text;
  # Weak validator for optimistic concurrency, AIP-154
  # <https://aip.dev/154>.
  etag @2 :Text;
  # When this resource was soft-deleted, unset while it is live. AIP-164
  # <https://aip.dev/164>.
  deleteTime @3 :Wellknown.Timestamp;
  # When a soft-deleted resource is purged for good. AIP-164
  # <https://aip.dev/164>.
  expireTime @4 :Wellknown.Timestamp;
  # When this resource was created.
  createTime @5 :Wellknown.Timestamp;
  # When this resource was last modified.
  updateTime @6 :Wellknown.Timestamp;
  # proto field 8 was removed and reserved; this holds its ordinal.
  removed8 @7 :Void;
  # proto field 9 was removed and reserved; this holds its ordinal.
  removed9 @8 :Void;
  # proto field 10 was removed and reserved; this holds its ordinal.
  removed10 @9 :Void;
  # proto field 11 was removed and reserved; this holds its ordinal.
  removed11 @10 :Void;
  # proto field 12 was removed and reserved; this holds its ordinal.
  removed12 @11 :Void;
  # proto field 13 was removed and reserved; this holds its ordinal.
  removed13 @12 :Void;
  # proto field 14 was removed and reserved; this holds its ordinal.
  removed14 @13 :Void;
  # proto field 15 was removed and reserved; this holds its ordinal.
  removed15 @14 :Void;
  # Air temperature outside the vehicle.
  #
  # Unit: Celsius. VSS: Vehicle.Exterior.AirTemperature (sensor).
  airTemperature @15 :Float64;
  # Relative humidity outside the vehicle. 0 = Dry, 100 = Air fully
  # saturated.
  #
  # Unit: percent. VSS: Vehicle.Exterior.Humidity (sensor).
  humidity @16 :Float64;
  # Light intensity outside the vehicle. 0 = No light detected, 100 = Fully
  # lit.
  #
  # Mapping to physical units and calculation method is sensor specific.
  #
  # Unit: percent. VSS: Vehicle.Exterior.LightIntensity (sensor).
  lightIntensity @17 :Float64;
  # Assessed condition of the road surface beneath or ahead of the vehicle.
  #
  # Determination method is implementation specific. May be derived from
  # sensor fusion of Vehicle.ADAS.ESC.RoadFriction.MostProbable,
  # Vehicle.Exterior.AirTemperature, Vehicle.Body.Raindetection.Intensity,
  # and optional camera-based road surface classification. UNKNOWN (0) shall
  # be used when the system cannot assess the road surface condition.
  # Primary consumers: navigation and ADAS safety systems. Related to VSS
  # issue #877 (Connected Safety signals).
  #
  # VSS: Vehicle.Exterior.RoadSurfaceCondition (sensor).
  roadSurfaceCondition @18 :ExteriorTypes.RoadSurfaceCondition;
  # Temperature of the road surface beneath or ahead of the vehicle.
  #
  # Distinct from Vehicle.Exterior.AirTemperature: the road surface can sit
  # several degrees below the air, most notably on bridge decks and in
  # shaded cuttings, so surface temperature is the determining input for
  # icing risk when the air reads above freezing while the road is still
  # frozen. A natural fusion input to Vehicle.Exterior.RoadSurfaceCondition
  # alongside air temperature and
  # Vehicle.ADAS.ESC.RoadFriction.MostProbable, and to
  # Vehicle.Safety.RoadIcingState where available. Measurement method is
  # implementation specific (typically infrared pyrometer) and the value may
  # also originate from external road-weather infrastructure. Related to VSS
  # issue #877 (Connected Safety signals).
  #
  # Unit: Celsius. VSS: Vehicle.Exterior.RoadSurfaceTemperature (sensor).
  roadSurfaceTemperature @19 :Float64;
  # Detected non-weather surface contaminant on the road beneath or ahead of
  # the vehicle.
  #
  # Reports road surface contaminants that are distinct from weather-related
  # surface state (covered by Vehicle.Exterior.RoadSurfaceCondition) and
  # road obstruction objects (tree, rockfall, etc.). UNKNOWN (0) shall be
  # used when the system cannot assess surface contamination. NONE (5)
  # indicates no surface contaminant detected. MUD (1) indicates wet dirt.
  # CHIPPINGS (2) indicates loose aggregate (tire damage risk, reduced road
  # holding). OIL (3) and FUEL (4) indicate liquid hydrocarbon contamination
  # (slip hazard and fire risk). Values 1-4 are aligned with SENSORIS v1.6
  # RoadSurfaceCondition.TypeAndConfidence. Determination method is
  # implementation specific.
  #
  # VSS: Vehicle.Exterior.RoadSurfaceContaminant (sensor).
  roadSurfaceContaminant @20 :ExteriorTypes.RoadSurfaceContaminant;
  # Type of road obstruction detected ahead of the vehicle.
  #
  # Reports the category of road obstruction detected by the vehicle's
  # perception systems. UNKNOWN (0) shall be used when obstruction type
  # cannot be classified. NONE (9) indicates no obstruction detected.
  # SHED_LOAD (4) covers cargo fallen from another vehicle. LAND_SLIP (5) or
  # landslide is ground material that has slid down slope into road. ANIMAL
  # (6) covers small animals (cat, dog); ANIMAL_LARGE (7) covers large
  # animals (deer, horse, livestock); ANIMAL_HERD (8) covers groups of
  # animals on road. FLOODING (10) indicates standing water sufficient to
  # obstruct passage (distinct from WET surface state in
  # Vehicle.Exterior.RoadSurfaceCondition). Values 1-8 are aligned with
  # SENSORIS v1.6 RoadObstructionCondition.TypeAndConfidence and TPEG-TEC
  # road obstruction taxonomy. Determination method is implementation
  # specific (camera, radar, lidar). Primary consumers: navigation systems
  # (dynamic re-routing), ADAS safety systems, and emergency dispatch
  # systems.
  #
  # VSS: Vehicle.Exterior.RoadObstruction (sensor).
  roadObstruction @21 :ExteriorTypes.RoadObstruction;
  # Assessed visibility condition outside the vehicle.
  #
  # Reports the dominant cause of reduced visibility. UNKNOWN (0) shall be
  # used when visibility condition cannot be assessed (e.g., camera
  # unavailable or confidence below threshold). CLEAR (1) indicates no
  # significant visibility reduction. LOW_* values indicate conditions that
  # materially reduce driver or sensor visibility range. Values are aligned
  # with SENSORIS v1.6 VisibilityCondition.TypeAndConfidence. Determination
  # method is implementation specific. May be derived from camera-based
  # classification, Vehicle.Body.Raindetection.Intensity,
  # Vehicle.Exterior.AirTemperature, and
  # Vehicle.Body.Windshield.Wiping.Mode. Complements
  # Vehicle.Exterior.VisibilityDistance for quantitative range. Primary
  # consumers: ADAS systems, navigation (dynamic re-routing), and emergency
  # dispatch systems.
  #
  # VSS: Vehicle.Exterior.VisibilityCondition (sensor).
  visibilityCondition @22 :ExteriorTypes.VisibilityCondition;
  # Estimated visible distance ahead of the vehicle in current conditions.
  #
  # Forward visibility range in meters as assessed by the vehicle's sensing
  # systems. 0 indicates near-zero visibility. Value may be limited by
  # sensor range rather than actual atmospheric visibility; see
  # VisibilityCondition for the qualitative assessment. Determination method
  # is implementation specific. May be derived from camera-based visibility
  # estimation, lidar range reduction, or radar clutter analysis.
  #
  # Unit: m. VSS: Vehicle.Exterior.VisibilityDistance (sensor).
  visibilityDistance @23 :Float64;
  # Type of precipitation currently detected outside the vehicle.
  #
  # Discriminates precipitation type from
  # Vehicle.Body.Raindetection.Intensity, which reports intensity for rain
  # only. UNKNOWN (0) shall be used when precipitation type cannot be
  # assessed. NONE (1) indicates no precipitation detected. HAIL (5)
  # includes sleet and freezing rain as a precipitation type (distinct from
  # black ice formation on the road surface, which is reported by
  # Vehicle.Safety.RoadIcingState when available). Values are aligned with
  # SENSORIS v1.6 Precipitation.TypeAndConfidence. Determination method is
  # implementation specific.
  #
  # VSS: Vehicle.Exterior.PrecipitationType (sensor).
  precipitationType @24 :ExteriorTypes.PrecipitationType;
  # Precipitation intensity in millimeters per hour.
  #
  # Provides an absolute intensity measurement complementing
  # Vehicle.Body.Raindetection.Intensity (which is a relative 0-100 percent
  # scale). Applies to all precipitation types reported by
  # Vehicle.Exterior.PrecipitationType; value is 0 when PrecipitationType is
  # NONE. Measurement method is sensor specific.
  #
  # Unit: mm/h. VSS: Vehicle.Exterior.PrecipitationIntensity (sensor).
  precipitationIntensity @25 :Float64;
  # Atmospheric air pressure outside the vehicle.
  #
  # Static ambient air pressure measured by the vehicle's barometric sensor.
  # May be used for altitude estimation, weather trend detection, and HVAC
  # pressurization management. Related to SENSORIS v1.6
  # AtmosphereCondition.static_air_pressure.
  #
  # Unit: hPa. VSS: Vehicle.Exterior.AirPressure (sensor).
  airPressure @26 :Float64;
  # Surface wind speed outside the vehicle.
  #
  # Measured or estimated wind speed in meters per second. May be derived
  # from anemometer sensors, aerodynamic load estimation, or external
  # weather service input.
  #
  # Unit: m/s. VSS: Vehicle.Exterior.WindSpeed (sensor).
  windSpeed @27 :Float64;
  # Wind direction in degrees (meteorological convention, 0 = North, 90 =
  # East).
  #
  # Wind direction from which wind is blowing, using meteorological
  # convention (0 = from North, 90 = from East, 180 = from South, 270 = from
  # West). Only meaningful when WindSpeed is above a minimum threshold;
  # value when WindSpeed is near 0 is implementation specific.
  #
  # Unit: degrees. VSS: Vehicle.Exterior.WindDirection (sensor).
  windDirection @28 :Float64;
  # Signals describing the composition of the ambient air outside the
  # vehicle.
  #
  # VSS: Vehicle.Exterior.AirQuality.
  airQuality @29 :AirQuality.AirQuality;
}
