@0x915e743592e032f6;

# Code generated by protoc-gen-buffers. DO NOT EDIT.
# versions:
# 	protoc-gen-buffers dev
# 	protoc (unknown)
# source: protobuf/covesa/vss/exterior/exterior/v1/exterior_types.proto
#
# target: capnp
# field slots below are recorded in buffers.lock; edit the .proto, not this file
#
# https://github.com/the-protobuf-project/buffers
using Cxx = import "/capnp/c++.capnp";
$Cxx.namespace("protobuf::covesa::vss::exterior::exterior::v1");

# Assessed condition of the road surface beneath or ahead of the vehicle.
#
# VSS: Vehicle.Exterior.RoadSurfaceCondition.
# (buffers.v1.enumeration).underlying asked for 32 bits. A Cap'n Proto enum is
# always 16, with no way to declare otherwise; the narrowing is honoured by
# the FlatBuffers target only.
enum RoadSurfaceCondition @0xf31d311f2e62ba60 {
  # Not specified.
  unknown @0;
  # Dry.
  dry @1;
  # Wet.
  wet @2;
  # Snow.
  snow @3;
  # Ice.
  ice @4;
  # Slush.
  slush @5;
  # Wet ice.
  wetIce @6;
  # Loose gravel.
  looseGravel @7;
}

# Detected non-weather surface contaminant on the road beneath or ahead of
# the vehicle.
#
# VSS: Vehicle.Exterior.RoadSurfaceContaminant.
# (buffers.v1.enumeration).underlying asked for 32 bits. A Cap'n Proto enum is
# always 16, with no way to declare otherwise; the narrowing is honoured by
# the FlatBuffers target only.
enum RoadSurfaceContaminant @0x94815f79f9329bd9 {
  # Not specified.
  unknown @0;
  # Mud.
  mud @1;
  # Chippings.
  chippings @2;
  # Oil.
  oil @3;
  # Fuel.
  fuel @4;
  # None.
  none @5;
}

# Type of road obstruction detected ahead of the vehicle.
#
# VSS: Vehicle.Exterior.RoadObstruction.
# (buffers.v1.enumeration).underlying asked for 32 bits. A Cap'n Proto enum is
# always 16, with no way to declare otherwise; the narrowing is honoured by
# the FlatBuffers target only.
enum RoadObstruction @0xc063381a8de738f4 {
  # Not specified.
  unknown @0;
  # Tree.
  tree @1;
  # Avalanche.
  avalanche @2;
  # Rockfalls.
  rockfalls @3;
  # Shed load.
  shedLoad @4;
  # Land slip.
  landSlip @5;
  # Animal.
  animal @6;
  # Animal large.
  animalLarge @7;
  # Animal herd.
  animalHerd @8;
  # None.
  none @9;
  # Flooding.
  flooding @10;
}

# Assessed visibility condition outside the vehicle.
#
# VSS: Vehicle.Exterior.VisibilityCondition.
# (buffers.v1.enumeration).underlying asked for 32 bits. A Cap'n Proto enum is
# always 16, with no way to declare otherwise; the narrowing is honoured by
# the FlatBuffers target only.
enum VisibilityCondition @0xfa96985b24e9ada5 {
  # Not specified.
  unknown @0;
  # Clear.
  clear @1;
  # Mist.
  mist @2;
  # Low heavy rain.
  lowHeavyRain @3;
  # Low heavy snow.
  lowHeavySnow @4;
  # Low smoke.
  lowSmoke @5;
  # Low fog.
  lowFog @6;
  # Low sun glare.
  lowSunGlare @7;
}

# Type of precipitation currently detected outside the vehicle.
#
# VSS: Vehicle.Exterior.PrecipitationType.
# (buffers.v1.enumeration).underlying asked for 32 bits. A Cap'n Proto enum is
# always 16, with no way to declare otherwise; the narrowing is honoured by
# the FlatBuffers target only.
enum PrecipitationType @0xe57eb83d47b4f71e {
  # Not specified.
  unknown @0;
  # None.
  none @1;
  # Rain.
  rain @2;
  # Mixed rain snow.
  mixedRainSnow @3;
  # Snow.
  snow @4;
  # Hail.
  hail @5;
}
