@0x981a1611f9ed8bcd;

# Code generated by protoc-gen-buffers. DO NOT EDIT.
# versions:
# 	protoc-gen-buffers dev
# 	protoc (unknown)
# source: protobuf/covesa/vss/exterior/exterior/v1/messages.proto
#
# target: capnp
# field slots below are recorded in buffers.lock; edit the .proto, not this file
#
# https://github.com/the-protobuf-project/buffers
using Cxx = import "/capnp/c++.capnp";
$Cxx.namespace("protobuf::covesa::vss::exterior::exterior::v1");

using Exterior = import "/protobuf/covesa/vss/exterior/exterior/v1/exterior.capnp";

# Request message for ExteriorService.GetExterior, AIP-131
# <https://aip.dev/131>.
struct GetExteriorRequest @0xd08a385f0ad659a2 {
  # Name of the Exterior to retrieve, "vehicles/{vehicle}/exterior".
  # REQUIRED (AIP-203); Cap'n Proto cannot enforce it.
  name @0 :Text;
}

# Request message for ExteriorService.UpdateExterior, AIP-134
# <https://aip.dev/134>.
struct UpdateExteriorRequest @0xa91a8dfdcda0a3d2 {
  # The Exterior to update. Its name field identifies the resource.
  # REQUIRED (AIP-203); Cap'n Proto cannot enforce it.
  exterior @0 :Exterior.Exterior;
  # Fields to update. An empty mask updates all mutable fields.
  #
  # Only an actuator is writable. A sensor or attribute named in the mask is
  # rejected: both are OUTPUT_ONLY, because a vehicle reports them and an
  # API cannot set them.
  updateMask @1 :List(Text);
}
