@0xc991b114ac838a9f;

# Code generated by protoc-gen-buffers. DO NOT EDIT.
# versions:
# 	protoc-gen-buffers dev
# 	protoc (unknown)
# source: protobuf/covesa/vss/propulsion/powertrain/v1/cell_voltage.proto
#
# target: capnp
# field slots below are recorded in buffers.lock; edit the .proto, not this file
#
# https://github.com/the-protobuf-project/buffers
using Cxx = import "/capnp/c++.capnp";
$Cxx.namespace("protobuf::covesa::vss::propulsion::powertrain::v1");

# Voltage information for cells in the battery pack.
#
# VSS: Vehicle.Powertrain.TractionBattery.CellVoltage.
#
# Reference: COVESA Vehicle Signal Specification.
# https://covesa.github.io/vehicle_signal_specification/
struct CellVoltage @0xd944db7d17710c29 {
  # Current voltage of the battery cell with lowest voltage.
  #
  # Unit: V. VSS: Vehicle.Powertrain.TractionBattery.CellVoltage.Min
  # (sensor).
  min @0 :Float64;
  # Identifier of the battery cell with lowest voltage.
  #
  # Identifier is supposed to be relative index of the cell, starting with 0
  # the first cell.
  #
  # VSS: Vehicle.Powertrain.TractionBattery.CellVoltage.IdMin (sensor).
  idMin @1 :Int32;
  # Current voltage of the battery cell with highest voltage.
  #
  # Unit: V. VSS: Vehicle.Powertrain.TractionBattery.CellVoltage.Max
  # (sensor).
  max @2 :Float64;
  # Identifier of the battery cell with highest voltage.
  #
  # Identifier is supposed to be relative index of the cell, starting with 0
  # the first cell.
  #
  # VSS: Vehicle.Powertrain.TractionBattery.CellVoltage.IdMax (sensor).
  idMax @3 :Int32;
  # Array of cell voltages. Length or array shall correspond to number of
  # cells in vehicle.
  #
  # Cells are identified by relative position in array.
  #
  # VSS: Vehicle.Powertrain.TractionBattery.CellVoltage.CellVoltages
  # (sensor).
  cellVoltages @4 :List(Float64);
}
