@0xc60d650ff27ef929;

# Code generated by protoc-gen-buffers. DO NOT EDIT.
# versions:
# 	protoc-gen-buffers dev
# 	protoc (unknown)
# source: protobuf/covesa/vss/propulsion/powertrain/v1/charging.proto
#
# target: capnp
# field slots below are recorded in buffers.lock; edit the .proto, not this file
#
# https://github.com/the-protobuf-project/buffers
using Cxx = import "/capnp/c++.capnp";
$Cxx.namespace("protobuf::covesa::vss::propulsion::powertrain::v1");

using ChargeCurrent = import "/protobuf/covesa/vss/propulsion/powertrain/v1/charge_current.capnp";
using ChargeVoltage = import "/protobuf/covesa/vss/propulsion/powertrain/v1/charge_voltage.capnp";
using Location = import "/protobuf/covesa/vss/propulsion/powertrain/v1/location.capnp";
using MaximumChargingCurrent = import "/protobuf/covesa/vss/propulsion/powertrain/v1/maximum_charging_current.capnp";
using Timer = import "/protobuf/covesa/vss/propulsion/powertrain/v1/timer.capnp";
using Wellknown = import "/buffers/wellknown.capnp";

# Start or stop the charging process.
#
# VSS: Vehicle.Powertrain.TractionBattery.Charging.StartStopCharging.
# (buffers.v1.enumeration).underlying asked for 32 bits. A Cap'n Proto enum is
# always 16, with no way to declare otherwise; the narrowing is honoured by
# the FlatBuffers target only.
enum ChargingStartStopCharging @0xe87e0b484c56e576 {
  # Not specified.
  unspecified @0;
  # Start.
  start @1;
  # Stop.
  stop @2;
}

# Properties related to battery charging.
#
# VSS: Vehicle.Powertrain.TractionBattery.Charging.
#
# Reference: COVESA Vehicle Signal Specification.
# https://covesa.github.io/vehicle_signal_specification/
struct Charging @0xb2c8548626cb5be1 {
  # Target charge limit (state of charge) for battery.
  #
  # Unit: percent. VSS:
  # Vehicle.Powertrain.TractionBattery.Charging.ChargeLimit (actuator).
  chargeLimit @0 :Int32;
  # Maximum charging current that can be accepted by the system, as measured
  # at the charging inlet.
  #
  # VSS: Vehicle.Powertrain.TractionBattery.Charging.MaximumChargingCurrent.
  maximumChargingCurrent @1 :MaximumChargingCurrent.MaximumChargingCurrent;
  # True if charging is ongoing. Charging is considered to be ongoing if
  # energy is flowing from charger to vehicle.
  #
  # VSS: Vehicle.Powertrain.TractionBattery.Charging.IsCharging (sensor).
  isCharging @2 :Bool;
  # True if discharging (vehicle to grid) is ongoing. Discharging is
  # considered to be ongoing if energy is flowing from vehicle to
  # charger/grid.
  #
  # VSS: Vehicle.Powertrain.TractionBattery.Charging.IsDischarging (sensor).
  isDischarging @3 :Bool;
  # Start or stop the charging process.
  #
  # VSS: Vehicle.Powertrain.TractionBattery.Charging.StartStopCharging
  # (actuator).
  startStopCharging @4 :ChargingStartStopCharging;
  # Current charging current.
  #
  # VSS: Vehicle.Powertrain.TractionBattery.Charging.ChargeCurrent.
  chargeCurrent @5 :ChargeCurrent.ChargeCurrent;
  # Current charging voltage, as measured at the charging inlet.
  #
  # VSS: Vehicle.Powertrain.TractionBattery.Charging.ChargeVoltage.
  chargeVoltage @6 :ChargeVoltage.ChargeVoltage;
  # Average charging power of last or current charging event.
  #
  # Unit: kW. VSS: Vehicle.Powertrain.TractionBattery.Charging.AveragePower
  # (sensor).
  averagePower @7 :Float64;
  # Maximum charging power of last or current charging event.
  #
  # Unit: kW. VSS: Vehicle.Powertrain.TractionBattery.Charging.MaxPower
  # (sensor).
  maxPower @8 :Float64;
  # EVSE charging point ID (without separators) of last or current charging
  # event according to ISO 15118-2 Annex H.
  #
  # Length of id between 7 and 37 characters. ZZ00000 to be used if SECC
  # cannot provide id
  #
  # VSS: Vehicle.Powertrain.TractionBattery.Charging.EvseId (sensor).
  evseId @9 :Text;
  # Location of last or current charging event.
  #
  # This may depending on implementation represent the location of (the
  # charge port of) the vehicle during charging, or the actual location of
  # the charger/load connected to the vehicle.
  #
  # VSS: Vehicle.Powertrain.TractionBattery.Charging.Location.
  location @10 :Location.Location;
  # Electrical energy lost by power dissipation to heat inside the AC/DC
  # converter.
  #
  # Unit: W. VSS: Vehicle.Powertrain.TractionBattery.Charging.PowerLoss
  # (sensor).
  powerLoss @11 :Float64;
  # Current temperature of AC/DC converter converting grid voltage to
  # battery voltage.
  #
  # Unit: Celsius. VSS:
  # Vehicle.Powertrain.TractionBattery.Charging.Temperature (sensor).
  temperature @12 :Float64;
  # Current charging rate, as in kilometers of range added per hour.
  #
  # Unit: km/h. VSS: Vehicle.Powertrain.TractionBattery.Charging.ChargeRate
  # (sensor).
  chargeRate @13 :Float64;
  # The time needed for the current charging process to reach
  # Charging.ChargeLimit. 0 if charging is complete or no charging process
  # is active or planned.
  #
  # Shall consider time set by Charging.Timer.Time. E.g. if charging shall
  # start in 3 hours and 2 hours of charging is needed, then
  # Charging.TimeToComplete shall report 5 hours.
  #
  # Unit: s. VSS: Vehicle.Powertrain.TractionBattery.Charging.TimeToComplete
  # (sensor).
  completionDuration @14 :Wellknown.Duration;
  # Properties related to timing of battery charging sessions.
  #
  # VSS: Vehicle.Powertrain.TractionBattery.Charging.Timer.
  timer @15 :Timer.Timer;
}
