@0x919809be0ab80fc0;

# Code generated by protoc-gen-buffers. DO NOT EDIT.
# versions:
# 	protoc-gen-buffers dev
# 	protoc (unknown)
# source: protobuf/covesa/vss/propulsion/powertrain/v1/charge_depleting.proto
#
# target: capnp
# field slots below are recorded in buffers.lock; edit the .proto, not this file
#
# https://github.com/the-protobuf-project/buffers
using Cxx = import "/capnp/c++.capnp";
$Cxx.namespace("protobuf::covesa::vss::propulsion::powertrain::v1");

# Signals related to Charge Depleting (CD) mode operation.
#
# CD mode represents the electric-only or electric-primary operation of the
# EREV. During this mode, the vehicle maximizes the use of battery energy
# before the engine is engaged.
#
# VSS: Vehicle.Powertrain.RangeExtender.ChargeDepleting.
#
# Reference: COVESA Vehicle Signal Specification.
# https://covesa.github.io/vehicle_signal_specification/
struct ChargeDepleting @0xd26b820bb79ee511 {
  # Current electric energy consumption rate during Charge Depleting mode
  # operation.
  #
  # This value represents the instantaneous or short-term average electric
  # energy consumption while the vehicle is operating in CD mode. It is
  # calculated based on the electrical energy drawn from the traction
  # battery per distance traveled. This metric is analogous to fuel
  # consumption but measured in electrical energy units. A lower value
  # indicates more efficient electric operation.
  #
  # Unit: kWh/100km. VSS:
  # Vehicle.Powertrain.RangeExtender.ChargeDepleting.EnergyConsumption
  # (sensor).
  energyConsumption @0 :Float64;
  # Estimated remaining distance that can be traveled in Charge Depleting
  # mode using available battery energy.
  #
  # This range estimate is calculated based on the current battery state of
  # charge and the recent energy consumption patterns in CD mode. The
  # estimate may vary based on driving conditions, terrain, climate control
  # usage, and other factors affecting battery consumption. When this range
  # approaches zero, the vehicle will typically transition to Charge
  # Sustaining mode.
  #
  # Unit: m. VSS: Vehicle.Powertrain.RangeExtender.ChargeDepleting.Range
  # (sensor).
  rangeControl @1 :Int64;
}
