@0x9cc329c1cc9afcf6;

# Code generated by protoc-gen-buffers. DO NOT EDIT.
# versions:
# 	protoc-gen-buffers dev
# 	protoc (unknown)
# source: protobuf/covesa/vss/propulsion/powertrain/v1/charge_current.proto
#
# target: capnp
# field slots below are recorded in buffers.lock; edit the .proto, not this file
#
# https://github.com/the-protobuf-project/buffers
using Cxx = import "/capnp/c++.capnp";
$Cxx.namespace("protobuf::covesa::vss::propulsion::powertrain::v1");

# Current charging current.
#
# VSS: Vehicle.Powertrain.TractionBattery.Charging.ChargeCurrent.
#
# Reference: COVESA Vehicle Signal Specification.
# https://covesa.github.io/vehicle_signal_specification/
struct ChargeCurrent @0xcbfbbafb68cc9226 {
  # Current DC charging current at inlet. Negative if returning energy to
  # grid.
  #
  # Unit: A. VSS:
  # Vehicle.Powertrain.TractionBattery.Charging.ChargeCurrent.DC (sensor).
  dc @0 :Float64;
  # Current AC charging current (rms) at inlet for Phase 1. Negative if
  # returning energy to grid.
  #
  # Unit: A. VSS:
  # Vehicle.Powertrain.TractionBattery.Charging.ChargeCurrent.Phase1
  # (sensor).
  phase1 @1 :Float64;
  # Current AC charging current (rms) at inlet for Phase 2. Negative if
  # returning energy to grid.
  #
  # Unit: A. VSS:
  # Vehicle.Powertrain.TractionBattery.Charging.ChargeCurrent.Phase2
  # (sensor).
  phase2 @2 :Float64;
  # Current AC charging current (rms) at inlet for Phase 3. Negative if
  # returning energy to grid.
  #
  # Unit: A. VSS:
  # Vehicle.Powertrain.TractionBattery.Charging.ChargeCurrent.Phase3
  # (sensor).
  phase3 @3 :Float64;
}
