@0xeed7caf2e6150122;

# Code generated by protoc-gen-buffers. DO NOT EDIT.
# versions:
# 	protoc-gen-buffers dev
# 	protoc (unknown)
# source: protobuf/covesa/vss/propulsion/powertrain/v1/charge_sustaining.proto
#
# target: capnp
# field slots below are recorded in buffers.lock; edit the .proto, not this file
#
# https://github.com/the-protobuf-project/buffers
using Cxx = import "/capnp/c++.capnp";
$Cxx.namespace("protobuf::covesa::vss::propulsion::powertrain::v1");

# Signals related to Charge Sustaining (CS) mode operation.
#
# CS mode represents the range-extended operation where the internal
# combustion engine operates as a generator to maintain battery charge and
# provide extended driving range. During this mode, fuel consumption becomes
# the primary energy source metric.
#
# VSS: Vehicle.Powertrain.RangeExtender.ChargeSustaining.
#
# Reference: COVESA Vehicle Signal Specification.
# https://covesa.github.io/vehicle_signal_specification/
struct ChargeSustaining @0xafdb3f889fcc0f0a {
  # Current fuel economy during Charge Sustaining mode operation.
  #
  # This value represents the fuel efficiency when the engine is operating
  # as a generator to maintain battery charge. It differs from conventional
  # vehicle fuel economy because the engine is optimized to run at efficient
  # generator speeds rather than varying speeds for direct wheel propulsion.
  # The actual fuel economy in CS mode may be different from the vehicle's
  # rated CS mode fuel economy depending on driving conditions and power
  # demands.
  #
  # Unit: km/l. VSS:
  # Vehicle.Powertrain.RangeExtender.ChargeSustaining.FuelEconomy (sensor).
  fuelEconomy @0 :Float64;
  # Estimated remaining distance that can be traveled in Charge Sustaining
  # mode using available fuel.
  #
  # This range estimate is calculated based on the current fuel level and
  # recent fuel consumption patterns in CS mode. It represents the extended
  # range capability provided by the internal combustion engine. The total
  # vehicle range is the sum of CD mode range and CS mode range.
  #
  # Unit: m. VSS: Vehicle.Powertrain.RangeExtender.ChargeSustaining.Range
  # (sensor).
  rangeControl @1 :Int64;
}
