@0xf5193842cddfd598;

# Code generated by protoc-gen-buffers. DO NOT EDIT.
# versions:
# 	protoc-gen-buffers dev
# 	protoc (unknown)
# source: protobuf/covesa/vss/propulsion/powertrain/v1/dcdc.proto
#
# target: capnp
# field slots below are recorded in buffers.lock; edit the .proto, not this file
#
# https://github.com/the-protobuf-project/buffers
using Cxx = import "/capnp/c++.capnp";
$Cxx.namespace("protobuf::covesa::vss::propulsion::powertrain::v1");

# Properties related to DC/DC converter converting high voltage (from high
# voltage battery) to vehicle low voltage (supply voltage, typically 12
# Volts).
#
# VSS: Vehicle.Powertrain.TractionBattery.DCDC.
#
# Reference: COVESA Vehicle Signal Specification.
# https://covesa.github.io/vehicle_signal_specification/
struct Dcdc @0x89e4d267b05b5254 {
  # Electrical energy lost by power dissipation to heat inside DC/DC
  # converter.
  #
  # Unit: W. VSS: Vehicle.Powertrain.TractionBattery.DCDC.PowerLoss
  # (sensor).
  powerLoss @0 :Float64;
  # Current temperature of DC/DC converter converting battery high voltage
  # to vehicle low voltage (typically 12 Volts).
  #
  # Unit: Celsius. VSS: Vehicle.Powertrain.TractionBattery.DCDC.Temperature
  # (sensor).
  temperature @1 :Float64;
}
