@0x85058c4d94a8dc44;

# Code generated by protoc-gen-buffers. DO NOT EDIT.
# versions:
# 	protoc-gen-buffers dev
# 	protoc (unknown)
# source: protobuf/covesa/vss/propulsion/powertrain/v1/diesel_particulate_filter.proto
#
# target: capnp
# field slots below are recorded in buffers.lock; edit the .proto, not this file
#
# https://github.com/the-protobuf-project/buffers
using Cxx = import "/capnp/c++.capnp";
$Cxx.namespace("protobuf::covesa::vss::propulsion::powertrain::v1");

# Diesel Particulate Filter signals.
#
# VSS: Vehicle.Powertrain.CombustionEngine.DieselParticulateFilter.
#
# Reference: COVESA Vehicle Signal Specification.
# https://covesa.github.io/vehicle_signal_specification/
struct DieselParticulateFilter @0xae53fe403f00c5ae {
  # Inlet temperature of Diesel Particulate Filter.
  #
  # Unit: Celsius. VSS:
  # Vehicle.Powertrain.CombustionEngine.DieselParticulateFilter.InletTemperature
  # (sensor).
  inletTemperature @0 :Float64;
  # Outlet temperature of Diesel Particulate Filter.
  #
  # Unit: Celsius. VSS:
  # Vehicle.Powertrain.CombustionEngine.DieselParticulateFilter.OutletTemperature
  # (sensor).
  outletTemperature @1 :Float64;
  # Delta Pressure of Diesel Particulate Filter.
  #
  # Unit: Pa. VSS:
  # Vehicle.Powertrain.CombustionEngine.DieselParticulateFilter.DeltaPressure
  # (sensor).
  deltaPressure @2 :Float64;
}
