@0xab53713563a8fd79;

# Code generated by protoc-gen-buffers. DO NOT EDIT.
# versions:
# 	protoc-gen-buffers dev
# 	protoc (unknown)
# source: protobuf/covesa/vss/propulsion/powertrain/v1/engine_oil.proto
#
# target: capnp
# field slots below are recorded in buffers.lock; edit the .proto, not this file
#
# https://github.com/the-protobuf-project/buffers
using Cxx = import "/capnp/c++.capnp";
$Cxx.namespace("protobuf::covesa::vss::propulsion::powertrain::v1");

# Engine oil level.
#
# VSS: Vehicle.Powertrain.CombustionEngine.EngineOil.Level.
# (buffers.v1.enumeration).underlying asked for 32 bits. A Cap'n Proto enum is
# always 16, with no way to declare otherwise; the narrowing is honoured by
# the FlatBuffers target only.
enum EngineOilLevel @0xf1a06444c6bb8c1e {
  # Not specified.
  unspecified @0;
  # Critically low.
  criticallyLow @1;
  # Low.
  low @2;
  # Normal.
  normal @3;
  # High.
  high @4;
  # Critically high.
  criticallyHigh @5;
}

# Engine oil pressure status.
#
# VSS: Vehicle.Powertrain.CombustionEngine.EngineOil.PressureStatus.
# (buffers.v1.enumeration).underlying asked for 32 bits. A Cap'n Proto enum is
# always 16, with no way to declare otherwise; the narrowing is honoured by
# the FlatBuffers target only.
enum EngineOilPressureState @0xaff620c9d46873de {
  # Not specified.
  unspecified @0;
  # Normal.
  normal @1;
  # Warning.
  warning @2;
  # Alert.
  alert @3;
  # Error.
  error @4;
}

# Signals related to the engine oil
#
# VSS: Vehicle.Powertrain.CombustionEngine.EngineOil.
#
# Reference: COVESA Vehicle Signal Specification.
# https://covesa.github.io/vehicle_signal_specification/
struct EngineOil @0xf7eff4c56ab94937 {
  # Engine oil capacity in liters.
  #
  # Unit: l. VSS: Vehicle.Powertrain.CombustionEngine.EngineOil.Capacity
  # (attribute).
  capacity @0 :Float64;
  # Engine oil level.
  #
  # VSS: Vehicle.Powertrain.CombustionEngine.EngineOil.Level (sensor).
  level @1 :EngineOilLevel;
  # Remaining engine oil life in seconds. Negative values can be used to
  # indicate that lifetime has been exceeded.
  #
  # In addition to this a signal a vehicle can report remaining time to
  # service (including e.g. oil change) by Vehicle.Service.TimeToService.
  #
  # Unit: s. VSS:
  # Vehicle.Powertrain.CombustionEngine.EngineOil.LifeRemaining (sensor).
  lifeRemaining @2 :Int32;
  # EOT, Engine oil temperature.
  #
  # Unit: Celsius. VSS:
  # Vehicle.Powertrain.CombustionEngine.EngineOil.Temperature (sensor).
  temperature @3 :Float64;
  # Engine oil pressure status.
  #
  # VSS: Vehicle.Powertrain.CombustionEngine.EngineOil.PressureStatus
  # (sensor).
  pressureStatus @4 :EngineOilPressureState;
}
