@0x8ed902aaf1f462c4;

# Code generated by protoc-gen-buffers. DO NOT EDIT.
# versions:
# 	protoc-gen-buffers dev
# 	protoc (unknown)
# source: protobuf/covesa/vss/propulsion/powertrain/v1/fuel_system_types.proto
#
# target: capnp
# field slots below are recorded in buffers.lock; edit the .proto, not this file
#
# https://github.com/the-protobuf-project/buffers
using Cxx = import "/capnp/c++.capnp";
$Cxx.namespace("protobuf::covesa::vss::propulsion::powertrain::v1");

# High level information of fuel types supported
#
# VSS: Vehicle.Powertrain.FuelSystem.SupportedFuelTypes.
# (buffers.v1.enumeration).underlying asked for 32 bits. A Cap'n Proto enum is
# always 16, with no way to declare otherwise; the narrowing is honoured by
# the FlatBuffers target only.
enum FuelSystemSupportedFuelTypes @0xeafd6506e92d272b {
  # Not specified.
  unspecified @0;
  # Gasoline.
  gasoline @1;
  # Diesel.
  diesel @2;
  # E85.
  e85 @3;
  # Lpg.
  lpg @4;
  # Cng.
  cng @5;
  # Lng.
  lng @6;
  # H2.
  h2 @7;
  # Other.
  other @8;
}

# Detailed information on fuels supported by the vehicle. Identifiers
# originating from DIN EN 16942:2021-08, appendix B, with additional suffix
# for octane (RON) where relevant.
#
# VSS: Vehicle.Powertrain.FuelSystem.SupportedFuel.
# (buffers.v1.enumeration).underlying asked for 32 bits. A Cap'n Proto enum is
# always 16, with no way to declare otherwise; the narrowing is honoured by
# the FlatBuffers target only.
enum FuelSystemSupportedFuel @0xf5c2c3265d740cdb {
  # Not specified.
  unspecified @0;
  # E5 95.
  e595 @1;
  # E5 98.
  e598 @2;
  # E10 95.
  e1095 @3;
  # E10 98.
  e1098 @4;
  # E85.
  e85 @5;
  # B7.
  b7 @6;
  # B10.
  b10 @7;
  # B20.
  b20 @8;
  # B30.
  b30 @9;
  # B100.
  b100 @10;
  # Xtl.
  xtl @11;
  # Lpg.
  lpg @12;
  # Cng.
  cng @13;
  # Lng.
  lng @14;
  # H2.
  h2 @15;
  # Other.
  other @16;
}

# Defines the hybrid type of the vehicle.
#
# VSS: Vehicle.Powertrain.FuelSystem.HybridType.
# (buffers.v1.enumeration).underlying asked for 32 bits. A Cap'n Proto enum is
# always 16, with no way to declare otherwise; the narrowing is honoured by
# the FlatBuffers target only.
enum FuelSystemHybridType @0xb8fb0d22bfdd3f25 {
  # Not specified.
  unspecified @0;
  # Not specified.
  unknown @1;
  # Not applicable.
  notApplicable @2;
  # Stop start.
  stopStart @3;
  # Belt isg.
  beltIsg @4;
  # Cimg.
  cimg @5;
  # Phev.
  phev @6;
}

# Position of refuel port(s). First part indicates side of vehicle, second
# part relative position on that side.
#
# VSS: Vehicle.Powertrain.FuelSystem.RefuelPortPosition.
# (buffers.v1.enumeration).underlying asked for 32 bits. A Cap'n Proto enum is
# always 16, with no way to declare otherwise; the narrowing is honoured by
# the FlatBuffers target only.
enum FuelSystemRefuelPortPosition @0x9b9be67ec00ea112 {
  # Not specified.
  unspecified @0;
  # Front left.
  frontLeft @1;
  # Front middle.
  frontMiddle @2;
  # Front right.
  frontRight @3;
  # Rear left.
  rearLeft @4;
  # Rear middle.
  rearMiddle @5;
  # Rear right.
  rearRight @6;
  # Left front.
  leftFront @7;
  # Left middle.
  leftMiddle @8;
  # Left rear.
  leftRear @9;
  # Right front.
  rightFront @10;
  # Right middle.
  rightMiddle @11;
  # Right rear.
  rightRear @12;
}
