@0x9c493571ae21bdbd;

# Code generated by protoc-gen-buffers. DO NOT EDIT.
# versions:
# 	protoc-gen-buffers dev
# 	protoc (unknown)
# source: protobuf/covesa/vss/propulsion/powertrain/v1/maximum_charging_current.proto
#
# target: capnp
# field slots below are recorded in buffers.lock; edit the .proto, not this file
#
# https://github.com/the-protobuf-project/buffers
using Cxx = import "/capnp/c++.capnp";
$Cxx.namespace("protobuf::covesa::vss::propulsion::powertrain::v1");

# Maximum charging current that can be accepted by the system, as measured
# at the charging inlet.
#
# VSS: Vehicle.Powertrain.TractionBattery.Charging.MaximumChargingCurrent.
#
# Reference: COVESA Vehicle Signal Specification.
# https://covesa.github.io/vehicle_signal_specification/
struct MaximumChargingCurrent @0xc3b6939f8b815282 {
  # Maximum DC charging current at inlet that can be accepted by the system.
  #
  # Unit: A. VSS:
  # Vehicle.Powertrain.TractionBattery.Charging.MaximumChargingCurrent.DC
  # (sensor).
  dc @0 :Float64;
  # Maximum AC charging current (rms) at inlet for Phase 1 that can be
  # accepted by the system.
  #
  # Unit: A. VSS:
  # Vehicle.Powertrain.TractionBattery.Charging.MaximumChargingCurrent.Phase1
  # (sensor).
  phase1 @1 :Float64;
  # Maximum AC charging current (rms) at inlet for Phase 2 that can be
  # accepted by the system.
  #
  # Unit: A. VSS:
  # Vehicle.Powertrain.TractionBattery.Charging.MaximumChargingCurrent.Phase2
  # (sensor).
  phase2 @2 :Float64;
  # Maximum AC charging current (rms) at inlet for Phase 3 that can be
  # accepted by the system.
  #
  # Unit: A. VSS:
  # Vehicle.Powertrain.TractionBattery.Charging.MaximumChargingCurrent.Phase3
  # (sensor).
  phase3 @3 :Float64;
}
