@0xd67e006623b6fc8a;

# Code generated by protoc-gen-buffers. DO NOT EDIT.
# versions:
# 	protoc-gen-buffers dev
# 	protoc (unknown)
# source: protobuf/covesa/vss/propulsion/powertrain/v1/powertrain.proto
#
# target: capnp
# field slots below are recorded in buffers.lock; edit the .proto, not this file
#
# https://github.com/the-protobuf-project/buffers
using Cxx = import "/capnp/c++.capnp";
$Cxx.namespace("protobuf::covesa::vss::propulsion::powertrain::v1");

using CombustionEngine = import "/protobuf/covesa/vss/propulsion/powertrain/v1/combustion_engine.capnp";
using FuelSystem = import "/protobuf/covesa/vss/propulsion/powertrain/v1/fuel_system.capnp";
using RangeExtender = import "/protobuf/covesa/vss/propulsion/powertrain/v1/range_extender.capnp";
using TractionBattery = import "/protobuf/covesa/vss/propulsion/powertrain/v1/traction_battery.capnp";
using Transmission = import "/protobuf/covesa/vss/propulsion/powertrain/v1/transmission.capnp";
using Wellknown = import "/buffers/wellknown.capnp";

# Defines the powertrain type of the vehicle.
#
# VSS: Vehicle.Powertrain.Type.
# (buffers.v1.enumeration).underlying asked for 32 bits. A Cap'n Proto enum is
# always 16, with no way to declare otherwise; the narrowing is honoured by
# the FlatBuffers target only.
enum PowertrainType @0xb096b5d185c25869 {
  # Not specified.
  unspecified @0;
  # Combustion.
  combustion @1;
  # Hybrid.
  hybrid @2;
  # Electric.
  electric @3;
}

# Powertrain data for battery management, etc.
#
# VSS: Vehicle.Powertrain.
#
# A singleton child resource of Vehicle, AIP-156 <https://aip.dev/156>,
# named "vehicles/{vehicle}/powertrain". Its parent is a declared resource
# in protobuf.covesa.vss.vehicle.v1, which is what makes this pattern legal
# rather than a reference to a collection nothing can create.
#
# Reference: COVESA Vehicle Signal Specification.
# https://covesa.github.io/vehicle_signal_specification/
struct Powertrain @0xc16b013ad9a58c7d {
  # Resource name, "vehicles/{vehicle}/powertrain". Assigned by the server.
  name @0 :Text;
  # Server-assigned unique id.
  uid @1 :Text;
  # Weak validator for optimistic concurrency, AIP-154
  # <https://aip.dev/154>.
  etag @2 :Text;
  # When this resource was soft-deleted, unset while it is live. AIP-164
  # <https://aip.dev/164>.
  deleteTime @3 :Wellknown.Timestamp;
  # When a soft-deleted resource is purged for good. AIP-164
  # <https://aip.dev/164>.
  expireTime @4 :Wellknown.Timestamp;
  # When this resource was created.
  createTime @5 :Wellknown.Timestamp;
  # When this resource was last modified.
  updateTime @6 :Wellknown.Timestamp;
  # proto field 8 was removed and reserved; this holds its ordinal.
  removed8 @7 :Void;
  # proto field 9 was removed and reserved; this holds its ordinal.
  removed9 @8 :Void;
  # proto field 10 was removed and reserved; this holds its ordinal.
  removed10 @9 :Void;
  # proto field 11 was removed and reserved; this holds its ordinal.
  removed11 @10 :Void;
  # proto field 12 was removed and reserved; this holds its ordinal.
  removed12 @11 :Void;
  # proto field 13 was removed and reserved; this holds its ordinal.
  removed13 @12 :Void;
  # proto field 14 was removed and reserved; this holds its ordinal.
  removed14 @13 :Void;
  # proto field 15 was removed and reserved; this holds its ordinal.
  removed15 @14 :Void;
  # Engine-specific data, stopping at the bell housing.
  #
  # VSS: Vehicle.Powertrain.CombustionEngine.
  combustionEngine @15 :CombustionEngine.CombustionEngine;
  # Transmission-specific data, stopping at the drive shafts.
  #
  # VSS: Vehicle.Powertrain.Transmission.
  transmission @16 :Transmission.Transmission;
  # Battery Management data.
  #
  # VSS: Vehicle.Powertrain.TractionBattery.
  tractionBattery @17 :TractionBattery.TractionBattery;
  # Fuel system data.
  #
  # VSS: Vehicle.Powertrain.FuelSystem.
  fuelSystem @18 :FuelSystem.FuelSystem;
  # Extended Range Electric Vehicle (EREV) specific data.
  #
  # VSS: Vehicle.Powertrain.RangeExtender.
  rangeExtender @19 :RangeExtender.RangeExtender;
  # The accumulated energy from regenerative braking over lifetime.
  #
  # Unit: kWh. VSS: Vehicle.Powertrain.AccumulatedBrakingEnergy (sensor).
  accumulatedBrakingEnergy @20 :Float64;
  # Remaining range in meters using all energy sources available in the
  # vehicle.
  #
  # Unit: m. VSS: Vehicle.Powertrain.Range (sensor).
  rangeControl @21 :Int64;
  # Time remaining in seconds before all energy sources available in the
  # vehicle are empty.
  #
  # Unit: s. VSS: Vehicle.Powertrain.TimeRemaining (sensor).
  timeRemaining @22 :Int64;
  # Defines the powertrain type of the vehicle.
  #
  # For vehicles with a combustion engine (including hybrids) more detailed
  # information on fuels supported can be found in
  # FuelSystem.SupportedFuelTypes and FuelSystem.SupportedFuels.
  #
  # VSS: Vehicle.Powertrain.Type (attribute).
  typeControl @23 :PowertrainType;
  # Power optimization level for this branch/subsystem. A higher number
  # indicates more aggressive power optimization. Level 0 indicates that all
  # functionality is enabled, no power optimization enabled. Level 10
  # indicates most aggressive power optimization mode, only essential
  # functionality enabled.
  #
  # VSS: Vehicle.Powertrain.PowerOptimizeLevel (actuator).
  powerOptimizeLevel @24 :Int32;
  # Auto Power Optimization Flag When set to 'true', the system enables
  # automatic power optimization, dynamically adjusting the power
  # optimization level based on runtime conditions or features managed by
  # the OEM. When set to 'false', manual control of the power optimization
  # level is allowed.
  #
  # VSS: Vehicle.Powertrain.IsAutoPowerOptimize (actuator).
  isAutoPowerOptimize @25 :Bool;
}
