@0xe499638819ab6201;

# Code generated by protoc-gen-buffers. DO NOT EDIT.
# versions:
# 	protoc-gen-buffers dev
# 	protoc (unknown)
# source: protobuf/covesa/vss/propulsion/powertrain/v1/range_extender.proto
#
# target: capnp
# field slots below are recorded in buffers.lock; edit the .proto, not this file
#
# https://github.com/the-protobuf-project/buffers
using Cxx = import "/capnp/c++.capnp";
$Cxx.namespace("protobuf::covesa::vss::propulsion::powertrain::v1");

using ChargeDepleting = import "/protobuf/covesa/vss/propulsion/powertrain/v1/charge_depleting.capnp";
using ChargeSustaining = import "/protobuf/covesa/vss/propulsion/powertrain/v1/charge_sustaining.capnp";

# Current operating mode of the Extended Range Electric Vehicle.
#
# VSS: Vehicle.Powertrain.RangeExtender.OperatingMode.
# (buffers.v1.enumeration).underlying asked for 32 bits. A Cap'n Proto enum is
# always 16, with no way to declare otherwise; the narrowing is honoured by
# the FlatBuffers target only.
enum RangeExtenderOperatingMode @0xd5bef2252ccbc554 {
  # Not specified.
  unspecified @0;
  # Charge depleting.
  chargeDepleting @1;
  # Charge sustaining.
  chargeSustaining @2;
  # Blended.
  blended @3;
}

# Extended Range Electric Vehicle (EREV) specific data.
#
# VSS: Vehicle.Powertrain.RangeExtender.
#
# Reference: COVESA Vehicle Signal Specification.
# https://covesa.github.io/vehicle_signal_specification/
struct RangeExtender @0xb9f74ab502e0678e {
  # Current operating mode of the Extended Range Electric Vehicle.
  #
  # CHARGE_DEPLETING (CD) - Vehicle operates primarily on battery power,
  # battery SOC decreases. CHARGE_SUSTAINING (CS) - Engine operates as
  # generator to maintain battery charge level. BLENDED - Both battery and
  # engine are used simultaneously, typically during high power demands. The
  # mode transition typically occurs automatically based on battery state of
  # charge thresholds.
  #
  # VSS: Vehicle.Powertrain.RangeExtender.OperatingMode (sensor).
  operatingMode @0 :RangeExtenderOperatingMode;
  # Signals related to Charge Depleting (CD) mode operation.
  #
  # CD mode represents the electric-only or electric-primary operation of
  # the EREV. During this mode, the vehicle maximizes the use of battery
  # energy before the engine is engaged.
  #
  # VSS: Vehicle.Powertrain.RangeExtender.ChargeDepleting.
  chargeDepleting @1 :ChargeDepleting.ChargeDepleting;
  # Signals related to Charge Sustaining (CS) mode operation.
  #
  # CS mode represents the range-extended operation where the internal
  # combustion engine operates as a generator to maintain battery charge and
  # provide extended driving range. During this mode, fuel consumption
  # becomes the primary energy source metric.
  #
  # VSS: Vehicle.Powertrain.RangeExtender.ChargeSustaining.
  chargeSustaining @2 :ChargeSustaining.ChargeSustaining;
  # Combined fuel economy equivalent that accounts for both electric energy
  # and fuel consumption.
  #
  # This metric provides a unified measure of overall vehicle efficiency by
  # converting electric energy consumption to a fuel-equivalent value and
  # combining it with actual fuel consumption. The calculation typically
  # follows regulatory standards (such as EPA MPGe) that define the
  # equivalence between electrical energy and liquid fuel energy. For
  # example, EPA defines 33.7 kWh as equivalent to one gallon of gasoline.
  # This combined metric is useful for comparing EREV efficiency with
  # conventional vehicles and understanding the overall energy cost of
  # operation. The value is weighted based on the proportion of driving in
  # CD versus CS modes.
  #
  # Unit: km/l. VSS: Vehicle.Powertrain.RangeExtender.CombinedFuelEconomy
  # (sensor).
  combinedFuelEconomy @3 :Float64;
}
