@0x9c671df26ea74279;

# Code generated by protoc-gen-buffers. DO NOT EDIT.
# versions:
# 	protoc-gen-buffers dev
# 	protoc (unknown)
# source: protobuf/covesa/vss/propulsion/powertrain/v1/temperature.proto
#
# target: capnp
# field slots below are recorded in buffers.lock; edit the .proto, not this file
#
# https://github.com/the-protobuf-project/buffers
using Cxx = import "/capnp/c++.capnp";
$Cxx.namespace("protobuf::covesa::vss::propulsion::powertrain::v1");

# Temperature Information for the battery pack.
#
# VSS: Vehicle.Powertrain.TractionBattery.Temperature.
#
# Reference: COVESA Vehicle Signal Specification.
# https://covesa.github.io/vehicle_signal_specification/
struct Temperature @0xaa229af21797ed21 {
  # Current average temperature of the battery cells.
  #
  # Unit: Celsius. VSS:
  # Vehicle.Powertrain.TractionBattery.Temperature.Average (sensor).
  average @0 :Float64;
  # Current minimum temperature of the battery cells, i.e. temperature of
  # the coldest cell.
  #
  # Unit: Celsius. VSS: Vehicle.Powertrain.TractionBattery.Temperature.Min
  # (sensor).
  min @1 :Float64;
  # Current maximum temperature of the battery cells, i.e. temperature of
  # the hottest cell.
  #
  # Unit: Celsius. VSS: Vehicle.Powertrain.TractionBattery.Temperature.Max
  # (sensor).
  max @2 :Float64;
  # Array of cell temperatures. Length or array shall correspond to number
  # of cells in vehicle.
  #
  # Cells are identified by relative position in array.
  #
  # VSS: Vehicle.Powertrain.TractionBattery.Temperature.CellTemperature
  # (sensor).
  cellTemperature @3 :List(Float64);
}
