@0xbd0fa334b05ec6a0;

# Code generated by protoc-gen-buffers. DO NOT EDIT.
# versions:
# 	protoc-gen-buffers dev
# 	protoc (unknown)
# source: protobuf/covesa/vss/propulsion/powertrain/v1/timer.proto
#
# target: capnp
# field slots below are recorded in buffers.lock; edit the .proto, not this file
#
# https://github.com/the-protobuf-project/buffers
using Cxx = import "/capnp/c++.capnp";
$Cxx.namespace("protobuf::covesa::vss::propulsion::powertrain::v1");

using Wellknown = import "/buffers/wellknown.capnp";

# Defines timer mode for charging: INACTIVE - no timer set, charging may
# start as soon as battery is connected to a charger. START_TIME - charging
# shall start at Charging.Timer.Time. END_TIME - charging shall be finished
# (reach Charging.ChargeLimit) at Charging.Timer.Time. When charging is
# completed the vehicle shall change mode to 'inactive' or set a new
# Charging.Timer.Time. Charging shall start immediately if mode is
# 'starttime' or 'endtime' and Charging.Timer.Time is a time in the past.
#
# VSS: Vehicle.Powertrain.TractionBattery.Charging.Timer.Mode.
# (buffers.v1.enumeration).underlying asked for 32 bits. A Cap'n Proto enum is
# always 16, with no way to declare otherwise; the narrowing is honoured by
# the FlatBuffers target only.
enum TimerMode @0xd64e9a724cd492e4 {
  # Not specified.
  unspecified @0;
  # Inactive.
  inactive @1;
  # Start time.
  startTime @2;
  # End time.
  endTime @3;
}

# Properties related to timing of battery charging sessions.
#
# VSS: Vehicle.Powertrain.TractionBattery.Charging.Timer.
#
# Reference: COVESA Vehicle Signal Specification.
# https://covesa.github.io/vehicle_signal_specification/
struct Timer @0xe23f6b5dea34bbd4 {
  # Defines timer mode for charging: INACTIVE - no timer set, charging may
  # start as soon as battery is connected to a charger. START_TIME -
  # charging shall start at Charging.Timer.Time. END_TIME - charging shall
  # be finished (reach Charging.ChargeLimit) at Charging.Timer.Time. When
  # charging is completed the vehicle shall change mode to 'inactive' or set
  # a new Charging.Timer.Time. Charging shall start immediately if mode is
  # 'starttime' or 'endtime' and Charging.Timer.Time is a time in the past.
  #
  # VSS: Vehicle.Powertrain.TractionBattery.Charging.Timer.Mode (actuator).
  mode @0 :TimerMode;
  # Time for next charging-related action, formatted according to ISO 8601
  # with UTC time zone. Value has no significance if Charging.Timer.Mode is
  # 'inactive'.
  #
  # Unit: iso8601. VSS:
  # Vehicle.Powertrain.TractionBattery.Charging.Timer.Time (actuator).
  actionTime @1 :Wellknown.Timestamp;
}
