@0xff0f3b99fa2a0969;

# Code generated by protoc-gen-buffers. DO NOT EDIT.
# versions:
# 	protoc-gen-buffers dev
# 	protoc (unknown)
# source: protobuf/covesa/vss/propulsion/powertrain/v1/traction_battery.proto
#
# target: capnp
# field slots below are recorded in buffers.lock; edit the .proto, not this file
#
# https://github.com/the-protobuf-project/buffers
using Cxx = import "/capnp/c++.capnp";
$Cxx.namespace("protobuf::covesa::vss::propulsion::powertrain::v1");

using BatteryConditioning = import "/protobuf/covesa/vss/propulsion/powertrain/v1/battery_conditioning.capnp";
using CellVoltage = import "/protobuf/covesa/vss/propulsion/powertrain/v1/cell_voltage.capnp";
using Charging = import "/protobuf/covesa/vss/propulsion/powertrain/v1/charging.capnp";
using Date = import "/protobuf/covesa/vss/propulsion/powertrain/v1/date.capnp";
using Dcdc = import "/protobuf/covesa/vss/propulsion/powertrain/v1/dcdc.capnp";
using StateOfCharge = import "/protobuf/covesa/vss/propulsion/powertrain/v1/state_of_charge.capnp";
using Temperature = import "/protobuf/covesa/vss/propulsion/powertrain/v1/temperature.capnp";

# Battery Management data.
#
# VSS: Vehicle.Powertrain.TractionBattery.
#
# Reference: COVESA Vehicle Signal Specification.
# https://covesa.github.io/vehicle_signal_specification/
struct TractionBattery @0xd9e8a00789ff0c13 {
  # Battery Identification Number as assigned by OEM.
  #
  # This could be serial number, part number plus serial number, UUID, or
  # any other identifier that the OEM want to use to uniquely identify the
  # battery individual.
  #
  # VSS: Vehicle.Powertrain.TractionBattery.Id (attribute).
  id @0 :Text;
  # Production date of battery in ISO8601 format, e.g. YYYY-MM-DD.
  #
  # Unit: iso8601. VSS: Vehicle.Powertrain.TractionBattery.ProductionDate
  # (attribute).
  production @1 :Date.Date;
  # Current error codes related to the battery, if any.
  #
  # Error code format is not defined, it may be DTCs according to OBD II
  # (SAE-J2012DA_201812) standard ([P|C|B|U]XXXXX ) or any other format.
  #
  # VSS: Vehicle.Powertrain.TractionBattery.ErrorCodes (sensor).
  errorCodes @2 :List(Text);
  # Indicating if the power (positive terminator) of the traction battery is
  # connected to the powertrain.
  #
  # It might be possible to disconnect the traction battery used by an
  # electric powertrain. This is achieved by connectors, typically one for
  # plus and one for minus.
  #
  # VSS: Vehicle.Powertrain.TractionBattery.IsPowerConnected (sensor).
  isPowerConnected @3 :Bool;
  # Indicating if the ground (negative terminator) of the traction battery
  # is connected to the powertrain.
  #
  # It might be possible to disconnect the traction battery used by an
  # electric powertrain. This is achieved by connectors, typically one for
  # plus and one for minus.
  #
  # VSS: Vehicle.Powertrain.TractionBattery.IsGroundConnected (sensor).
  isGroundConnected @4 :Bool;
  # Temperature Information for the battery pack.
  #
  # VSS: Vehicle.Powertrain.TractionBattery.Temperature.
  temperature @5 :Temperature.Temperature;
  # Voltage information for cells in the battery pack.
  #
  # VSS: Vehicle.Powertrain.TractionBattery.CellVoltage.
  cellVoltage @6 :CellVoltage.CellVoltage;
  # Gross capacity of the battery.
  #
  # Unit: kWh. VSS: Vehicle.Powertrain.TractionBattery.GrossCapacity
  # (attribute).
  grossCapacity @7 :Int32;
  # Total net capacity of the battery considering aging.
  #
  # Unit: kWh. VSS: Vehicle.Powertrain.TractionBattery.NetCapacity (sensor).
  netCapacity @8 :Int32;
  # Calculated battery state of health at standard conditions.
  #
  # Exact formula is implementation dependent. Could be e.g. current
  # capacity at 20 degrees Celsius divided with original capacity at the
  # same temperature.
  #
  # Unit: percent. VSS: Vehicle.Powertrain.TractionBattery.StateOfHealth
  # (sensor).
  healthState @9 :Float64;
  # Information on the state of charge of the vehicle's high voltage
  # battery.
  #
  # VSS: Vehicle.Powertrain.TractionBattery.StateOfCharge.
  chargeState @10 :StateOfCharge.StateOfCharge;
  # Nominal Voltage of the battery.
  #
  # Nominal voltage typically refers to voltage of fully charged battery
  # when delivering rated capacity.
  #
  # Unit: V. VSS: Vehicle.Powertrain.TractionBattery.NominalVoltage
  # (attribute).
  nominalVoltage @11 :Int32;
  # Max allowed voltage of the battery, e.g. during charging.
  #
  # Unit: V. VSS: Vehicle.Powertrain.TractionBattery.MaxVoltage (attribute).
  maxVoltage @12 :Int32;
  # Current Voltage of the battery.
  #
  # Unit: V. VSS: Vehicle.Powertrain.TractionBattery.CurrentVoltage
  # (sensor).
  currentVoltage @13 :Float64;
  # Current current flowing in/out of battery. Positive = Current flowing in
  # to battery, e.g. during charging. Negative = Current flowing out of
  # battery, e.g. during driving.
  #
  # Unit: A. VSS: Vehicle.Powertrain.TractionBattery.CurrentCurrent
  # (sensor).
  currentCurrent @14 :Float64;
  # Current electrical energy flowing in/out of battery. Positive = Energy
  # flowing in to battery, e.g. during charging. Negative = Energy flowing
  # out of battery, e.g. during driving.
  #
  # Unit: W. VSS: Vehicle.Powertrain.TractionBattery.CurrentPower (sensor).
  currentPower @15 :Float64;
  # The accumulated energy delivered to the battery during charging over
  # lifetime of the battery.
  #
  # Unit: kWh. VSS:
  # Vehicle.Powertrain.TractionBattery.AccumulatedChargedEnergy (sensor).
  accumulatedChargedEnergy @16 :Float64;
  # The accumulated energy leaving HV battery for propulsion and auxiliary
  # loads over lifetime of the battery.
  #
  # Unit: kWh. VSS:
  # Vehicle.Powertrain.TractionBattery.AccumulatedConsumedEnergy (sensor).
  accumulatedConsumedEnergy @17 :Float64;
  # The accumulated charge throughput delivered to the battery during
  # charging over lifetime of the battery.
  #
  # Unit: Ah. VSS:
  # Vehicle.Powertrain.TractionBattery.AccumulatedChargedThroughput
  # (sensor).
  accumulatedChargedThroughput @18 :Float64;
  # The accumulated charge throughput leaving HV battery for propulsion and
  # auxiliary loads over lifetime of the battery.
  #
  # Unit: Ah. VSS:
  # Vehicle.Powertrain.TractionBattery.AccumulatedConsumedThroughput
  # (sensor).
  accumulatedConsumedThroughput @19 :Float64;
  # Electrical energy lost by power dissipation to heat inside the battery.
  #
  # Unit: W. VSS: Vehicle.Powertrain.TractionBattery.PowerLoss (sensor).
  powerLoss @20 :Float64;
  # Remaining range in meters using only battery.
  #
  # Unit: m. VSS: Vehicle.Powertrain.TractionBattery.Range (sensor).
  rangeControl @21 :Int64;
  # Time remaining in seconds before the battery is empty.
  #
  # Unit: s. VSS: Vehicle.Powertrain.TractionBattery.TimeRemaining (sensor).
  timeRemaining @22 :Int64;
  # Properties related to battery charging.
  #
  # VSS: Vehicle.Powertrain.TractionBattery.Charging.
  charging @23 :Charging.Charging;
  # Properties related to DC/DC converter converting high voltage (from high
  # voltage battery) to vehicle low voltage (supply voltage, typically 12
  # Volts).
  #
  # VSS: Vehicle.Powertrain.TractionBattery.DCDC.
  dcdc @24 :Dcdc.Dcdc;
  # Properties related to preparing the vehicle battery for charging or
  # driving.
  #
  # VSS: Vehicle.Powertrain.TractionBattery.BatteryConditioning.
  batteryConditioning @25 :BatteryConditioning.BatteryConditioning;
}
