@0xcb4370345ffd94dd;

# Code generated by protoc-gen-buffers. DO NOT EDIT.
# versions:
# 	protoc-gen-buffers dev
# 	protoc (unknown)
# source: protobuf/covesa/vss/propulsion/powertrain/v1/transmission_types.proto
#
# target: capnp
# field slots below are recorded in buffers.lock; edit the .proto, not this file
#
# https://github.com/the-protobuf-project/buffers
using Cxx = import "/capnp/c++.capnp";
$Cxx.namespace("protobuf::covesa::vss::propulsion::powertrain::v1");

# Transmission type.
#
# VSS: Vehicle.Powertrain.Transmission.Type.
# (buffers.v1.enumeration).underlying asked for 32 bits. A Cap'n Proto enum is
# always 16, with no way to declare otherwise; the narrowing is honoured by
# the FlatBuffers target only.
enum TransmissionType @0xeeb30cf5b30c4471 {
  # Not specified.
  unspecified @0;
  # Not specified.
  unknown @1;
  # Sequential.
  sequential @2;
  # H.
  h @3;
  # Automatic.
  automatic @4;
  # Dsg.
  dsg @5;
  # Cvt.
  cvt @6;
}

# Drive type.
#
# VSS: Vehicle.Powertrain.Transmission.DriveType.
# (buffers.v1.enumeration).underlying asked for 32 bits. A Cap'n Proto enum is
# always 16, with no way to declare otherwise; the narrowing is honoured by
# the FlatBuffers target only.
enum TransmissionDriveType @0xd83251061ae91380 {
  # Not specified.
  unspecified @0;
  # Not specified.
  unknown @1;
  # Forward wheel drive.
  forwardWheelDrive @2;
  # Rear wheel drive.
  rearWheelDrive @3;
  # All wheel drive.
  allWheelDrive @4;
}

# Current gearbox performance mode.
#
# VSS: Vehicle.Powertrain.Transmission.PerformanceMode.
# (buffers.v1.enumeration).underlying asked for 32 bits. A Cap'n Proto enum is
# always 16, with no way to declare otherwise; the narrowing is honoured by
# the FlatBuffers target only.
enum TransmissionPerformanceMode @0xa112ddd7b9abba81 {
  # Not specified.
  unspecified @0;
  # Normal.
  normal @1;
  # Sport.
  sport @2;
  # Economy.
  economy @3;
  # Snow.
  snow @4;
  # Rain.
  rain @5;
}

# Is the gearbox in automatic or manual (paddle) mode.
#
# VSS: Vehicle.Powertrain.Transmission.GearChangeMode.
# (buffers.v1.enumeration).underlying asked for 32 bits. A Cap'n Proto enum is
# always 16, with no way to declare otherwise; the narrowing is honoured by
# the FlatBuffers target only.
enum TransmissionGearChangeMode @0xe06ea77b3eb97dca {
  # Not specified.
  unspecified @0;
  # Manual.
  manual @1;
  # Automatic.
  automatic @2;
}
