@0xf583e493d46c9c2a;

# Code generated by protoc-gen-buffers. DO NOT EDIT.
# versions:
# 	protoc-gen-buffers dev
# 	protoc (unknown)
# source: protobuf/covesa/vss/platform/version_vss/v1/messages.proto
#
# target: capnp
# field slots below are recorded in buffers.lock; edit the .proto, not this file
#
# https://github.com/the-protobuf-project/buffers
using Cxx = import "/capnp/c++.capnp";
$Cxx.namespace("protobuf::covesa::vss::platform::version_vss::v1");

using VersionVss = import "/protobuf/covesa/vss/platform/version_vss/v1/version_vss.capnp";

# Request message for VersionVssService.GetVersionVss, AIP-131
# <https://aip.dev/131>.
struct GetVersionVssRequest @0xf022975b4133970f {
  # Name of the VersionVss to retrieve, "vehicles/{vehicle}/versionVss".
  # REQUIRED (AIP-203); Cap'n Proto cannot enforce it.
  name @0 :Text;
}

# Request message for VersionVssService.UpdateVersionVss, AIP-134
# <https://aip.dev/134>.
struct UpdateVersionVssRequest @0x9c970620eb5fad95 {
  # The VersionVss to update. Its name field identifies the resource.
  # REQUIRED (AIP-203); Cap'n Proto cannot enforce it.
  versionVss @0 :VersionVss.VersionVss;
  # Fields to update. An empty mask updates all mutable fields.
  #
  # Only an actuator is writable. A sensor or attribute named in the mask is
  # rejected: both are OUTPUT_ONLY, because a vehicle reports them and an
  # API cannot set them.
  updateMask @1 :List(Text);
}
