@0x81b96bd31d24715d;

# Code generated by protoc-gen-buffers. DO NOT EDIT.
# versions:
# 	protoc-gen-buffers dev
# 	protoc (unknown)
# source: protobuf/covesa/vss/platform/version_vss/v1/version_vss.proto
#
# target: capnp
# field slots below are recorded in buffers.lock; edit the .proto, not this file
#
# https://github.com/the-protobuf-project/buffers
using Cxx = import "/capnp/c++.capnp";
$Cxx.namespace("protobuf::covesa::vss::platform::version_vss::v1");

using Wellknown = import "/buffers/wellknown.capnp";

# Supported Version of VSS.
#
# VSS: Vehicle.VersionVSS.
#
# A singleton child resource of Vehicle, AIP-156 <https://aip.dev/156>,
# named "vehicles/{vehicle}/versionVss". Its parent is a declared resource
# in protobuf.covesa.vss.vehicle.v1, which is what makes this pattern legal
# rather than a reference to a collection nothing can create.
#
# Reference: COVESA Vehicle Signal Specification.
# https://covesa.github.io/vehicle_signal_specification/
struct VersionVss @0xb83854acc32d9be2 {
  # Resource name, "vehicles/{vehicle}/versionVss". Assigned by the server.
  name @0 :Text;
  # Server-assigned unique id.
  uid @1 :Text;
  # Weak validator for optimistic concurrency, AIP-154
  # <https://aip.dev/154>.
  etag @2 :Text;
  # When this resource was soft-deleted, unset while it is live. AIP-164
  # <https://aip.dev/164>.
  deleteTime @3 :Wellknown.Timestamp;
  # When a soft-deleted resource is purged for good. AIP-164
  # <https://aip.dev/164>.
  expireTime @4 :Wellknown.Timestamp;
  # When this resource was created.
  createTime @5 :Wellknown.Timestamp;
  # When this resource was last modified.
  updateTime @6 :Wellknown.Timestamp;
  # proto field 8 was removed and reserved; this holds its ordinal.
  removed8 @7 :Void;
  # proto field 9 was removed and reserved; this holds its ordinal.
  removed9 @8 :Void;
  # proto field 10 was removed and reserved; this holds its ordinal.
  removed10 @9 :Void;
  # proto field 11 was removed and reserved; this holds its ordinal.
  removed11 @10 :Void;
  # proto field 12 was removed and reserved; this holds its ordinal.
  removed12 @11 :Void;
  # proto field 13 was removed and reserved; this holds its ordinal.
  removed13 @12 :Void;
  # proto field 14 was removed and reserved; this holds its ordinal.
  removed14 @13 :Void;
  # proto field 15 was removed and reserved; this holds its ordinal.
  removed15 @14 :Void;
  # Supported Version of VSS - Major version.
  #
  # VSS: Vehicle.VersionVSS.Major (attribute).
  major @15 :Int64;
  # Supported Version of VSS - Minor version.
  #
  # VSS: Vehicle.VersionVSS.Minor (attribute).
  minor @16 :Int64;
  # Supported Version of VSS - Patch version.
  #
  # VSS: Vehicle.VersionVSS.Patch (attribute).
  patch @17 :Int64;
  # Label to further describe the version.
  #
  # COVESA VSS project typically use dev for latest master, and empty string
  # for released versions.
  #
  # VSS: Vehicle.VersionVSS.Label (attribute).
  label @18 :Text;
}
