@0xd0a4c68dd3962ed3;

# Code generated by protoc-gen-buffers. DO NOT EDIT.
# versions:
# 	protoc-gen-buffers dev
# 	protoc (unknown)
# source: protobuf/covesa/vss/motion/motion_management/v1/brake.proto
#
# target: capnp
# field slots below are recorded in buffers.lock; edit the .proto, not this file
#
# https://github.com/the-protobuf-project/buffers
using Cxx = import "/capnp/c++.capnp";
$Cxx.namespace("protobuf::covesa::vss::motion::motion_management::v1");

# MotionManagement related to braking (both frictions brakes and
# contribution from electric axles).
#
# VSS: Vehicle.MotionManagement.Brake.
#
# Reference: COVESA Vehicle Signal Specification.
# https://covesa.github.io/vehicle_signal_specification/
struct Brake @0x83d252eca2469d9d {
  # Maximum longitudinal brake force request (FxWhlSum). Sum of all tyre
  # longitudinal forces. Brake Force < 0N.
  #
  # Unit: N. VSS: Vehicle.MotionManagement.Brake.VehicleForceMaximum
  # (actuator).
  vehicleForceMaximum @0 :Int32;
  # Brake system internally calculated regenerative force limit at vehicle
  # level for eAxle actuation. Brake Force < 0N.
  #
  # Unit: N. VSS:
  # Vehicle.MotionManagement.Brake.VehicleForceElectricMinimumArbitrated
  # (sensor).
  vehicleForceElectricMinimumArbitrated @1 :Int32;
  # Regenerative brake force request (FxWhlSum). Sum of all tyre
  # longitudinal forces. Brake Force < 0N.
  #
  # Unit: N. VSS: Vehicle.MotionManagement.Brake.VehicleForceElectric
  # (actuator).
  vehicleForceElectric @2 :Int32;
  # Maximum distribution range request of FxWhlSum to front axle. 0% =
  # Complete longitudinal brake force shall be shifted to rear axle. 50% =
  # At most 50% shall be shifted to front axle. 100% = Complete longitudinal
  # brake force may be shifted to front axle.
  #
  # Unit: percent. VSS:
  # Vehicle.MotionManagement.Brake.VehicleForceDistributionFrontMaximum
  # (actuator).
  vehicleForceDistributionFrontMaximum @3 :Int32;
  # Minimum distribution range request of FxWhlSum to front axle. 0% =
  # Complete longitudinal brake force may be shifted to rear axle. 50% = At
  # least 50% shall be shifted to front axle. 100% = Complete longitudinal
  # brake force shall be shifted to front axle.
  #
  # Unit: percent. VSS:
  # Vehicle.MotionManagement.Brake.VehicleForceDistributionFrontMinimum
  # (actuator).
  vehicleForceDistributionFrontMinimum @4 :Int32;
}
