@0xe313498ec2e5e977;

# Code generated by protoc-gen-buffers. DO NOT EDIT.
# versions:
# 	protoc-gen-buffers dev
# 	protoc (unknown)
# source: protobuf/covesa/vss/motion/motion_management/v1/messages.proto
#
# target: capnp
# field slots below are recorded in buffers.lock; edit the .proto, not this file
#
# https://github.com/the-protobuf-project/buffers
using Cxx = import "/capnp/c++.capnp";
$Cxx.namespace("protobuf::covesa::vss::motion::motion_management::v1");

using MotionManagement = import "/protobuf/covesa/vss/motion/motion_management/v1/motion_management.capnp";

# Request message for MotionManagementService.GetMotionManagement, AIP-131
# <https://aip.dev/131>.
struct GetMotionManagementRequest @0xa73362fe78936a49 {
  # Name of the MotionManagement to retrieve,
  # "vehicles/{vehicle}/motionManagement".
  # REQUIRED (AIP-203); Cap'n Proto cannot enforce it.
  name @0 :Text;
}

# Request message for MotionManagementService.UpdateMotionManagement,
# AIP-134 <https://aip.dev/134>.
struct UpdateMotionManagementRequest @0xf1fdd96e3b4e4e50 {
  # The MotionManagement to update. Its name field identifies the resource.
  # REQUIRED (AIP-203); Cap'n Proto cannot enforce it.
  motionManagement @0 :MotionManagement.MotionManagement;
  # Fields to update. An empty mask updates all mutable fields.
  #
  # Only an actuator is writable. A sensor or attribute named in the mask is
  # rejected: both are OUTPUT_ONLY, because a vehicle reports them and an
  # API cannot set them.
  updateMask @1 :List(Text);
}
