@0x9216072588f09be1;

# Code generated by protoc-gen-buffers. DO NOT EDIT.
# versions:
# 	protoc-gen-buffers dev
# 	protoc (unknown)
# source: protobuf/covesa/vss/motion/motion_management/v1/row1.proto
#
# target: capnp
# field slots below are recorded in buffers.lock; edit the .proto, not this file
#
# https://github.com/the-protobuf-project/buffers
using Cxx = import "/capnp/c++.capnp";
$Cxx.namespace("protobuf::covesa::vss::motion::motion_management::v1");

# MotionManagement related to front axle.
#
# VSS: Vehicle.MotionManagement.Steering.Axle.Row1.
#
# Reference: COVESA Vehicle Signal Specification.
# https://covesa.github.io/vehicle_signal_specification/
struct Row1 @0xd2ed4c01cb26f740 {
  # Mode used for controlling position interface of axle steering actuator.
  # 0 indicates interface disabled. Other values activate vehicle specific
  # modes.
  #
  # VSS: Vehicle.MotionManagement.Steering.Axle.Row1.PositionTargetMode
  # (actuator).
  positionTargetMode @0 :Int32;
  # Mode used for controlling position offset interface of axle steering
  # actuator. 0 indicates interface disabled. Other values activate vehicle
  # specific modes.
  #
  # VSS:
  # Vehicle.MotionManagement.Steering.Axle.Row1.PositionOffsetTargetMode
  # (actuator).
  positionOffsetTargetMode @1 :Int32;
  # Represents the current position of the steering rack on axle steering
  # actuator. Positive values leads to a left turn of the vehicle (based on
  # ISO8855).
  #
  # Alternative signal to SteerAngle.
  #
  # Unit: mm. VSS: Vehicle.MotionManagement.Steering.Axle.Row1.RackPosition
  # (sensor).
  rackPosition @2 :Int32;
  # Rack position request to the axle steering actuator (external
  # set-point). Positive values lead to a left turn of the vehicle (based on
  # ISO8855).
  #
  # Alternative signal to SteerAngleTarget.
  #
  # Unit: mm. VSS:
  # Vehicle.MotionManagement.Steering.Axle.Row1.RackPositionTarget
  # (actuator).
  rackPositionTarget @3 :Int32;
  # Rack position offset request to the axle steering actuator (for
  # steer-by-wire), added to the actuator internal calculated set-point.
  # Positive values without internal calculated set point change lead to a
  # left movement of the vehicle (based on ISO8855).
  #
  # Alternative signal to SteerAngleOffsetTarget.
  #
  # Unit: mm. VSS:
  # Vehicle.MotionManagement.Steering.Axle.Row1.RackPositionOffsetTarget
  # (actuator).
  rackPositionOffsetTarget @4 :Int32;
  # Represents the current actuated steering angle of the steered wheels.
  # Signal orientation according ISO8855, single track model.
  #
  # Alternative signal to RackPosition.
  #
  # Unit: degrees. VSS:
  # Vehicle.MotionManagement.Steering.Axle.Row1.SteerAngle (sensor).
  steerAngle @5 :Int32;
  # Steer angle request to the axle steering actuator (external set-point).
  # Signal orientation according ISO8855, single track model.
  #
  # Alternative signal to RackPositionTarget.
  #
  # Unit: degrees. VSS:
  # Vehicle.MotionManagement.Steering.Axle.Row1.SteerAngleTarget (actuator).
  steerAngleTarget @6 :Int32;
  # Steer angle offset request to the axle steering actuator (for
  # steer-by-wire), added to the actuator internal calculated set-point.
  # Signal orientation according ISO8855, single track model.
  #
  # Alternative signal to RackPositionOffsetTarget.
  #
  # Unit: degrees. VSS:
  # Vehicle.MotionManagement.Steering.Axle.Row1.SteerAngleOffsetTarget
  # (actuator).
  steerAngleOffsetTarget @7 :Int32;
}
