@0xeb19b29aeddd76fe;

# Code generated by protoc-gen-buffers. DO NOT EDIT.
# versions:
# 	protoc-gen-buffers dev
# 	protoc (unknown)
# source: protobuf/covesa/vss/motion/motion_management/v1/row2.proto
#
# target: capnp
# field slots below are recorded in buffers.lock; edit the .proto, not this file
#
# https://github.com/the-protobuf-project/buffers
using Cxx = import "/capnp/c++.capnp";
$Cxx.namespace("protobuf::covesa::vss::motion::motion_management::v1");

# MotionManagement related to rear axle.
#
# VSS: Vehicle.MotionManagement.Steering.Axle.Row2.
#
# Reference: COVESA Vehicle Signal Specification.
# https://covesa.github.io/vehicle_signal_specification/
struct Row2 @0x8661dce9c52f52de {
  # Represents the current actuated steering angle of the steered wheels on
  # rear axle. Signal orientation according ISO8855, single track model.
  #
  # Unit: degrees. VSS:
  # Vehicle.MotionManagement.Steering.Axle.Row2.SteerAngle (sensor).
  steerAngle @0 :Int32;
  # Steer angle request to the rear axle steering actuator (external
  # set-point). Signal orientation according ISO8855, single track model.
  #
  # Unit: degrees. VSS:
  # Vehicle.MotionManagement.Steering.Axle.Row2.SteerAngleTarget (actuator).
  steerAngleTarget @1 :Int32;
  # Requested velocity for steer angle change. Signal orientation according
  # ISO8855. Optional signal to adapt rear wheel steering closed loop
  # control gain.
  #
  # Unit: degrees/s. VSS:
  # Vehicle.MotionManagement.Steering.Axle.Row2.SteerAngleVelocityTarget
  # (actuator).
  steerAngleVelocityTarget @2 :Int32;
}
