@0x947bfa9005c71d16;

# Code generated by protoc-gen-buffers. DO NOT EDIT.
# versions:
# 	protoc-gen-buffers dev
# 	protoc (unknown)
# source: protobuf/covesa/vss/motion/motion_management/v1/suspension.proto
#
# target: capnp
# field slots below are recorded in buffers.lock; edit the .proto, not this file
#
# https://github.com/the-protobuf-project/buffers
using Cxx = import "/capnp/c++.capnp";
$Cxx.namespace("protobuf::covesa::vss::motion::motion_management::v1");

# MotionManagement related to suspension.
#
# VSS: Vehicle.MotionManagement.Suspension.
#
# Reference: COVESA Vehicle Signal Specification.
# https://covesa.github.io/vehicle_signal_specification/
struct Suspension @0x8a7730513732fca9 {
  # Prioritization target for damping control 0% = damping control by
  # damping actuator (e.g. base functions) 100% = damping control by VMM
  # system (e.g. vehicle dynamics)
  #
  # Unit: percent. VSS:
  # Vehicle.MotionManagement.Suspension.DampingPrioTarget (actuator).
  dampingPrioTarget @0 :Int32;
  # Roll torque request on vehicle level. Signal orientation according to
  # ISO8855.
  #
  # Unit: Nm. VSS: Vehicle.MotionManagement.Suspension.RollTorqueTarget
  # (actuator).
  rollTorqueTarget @1 :Int32;
  # Prioritization target for anti-roll control 0% = anti-roll control by
  # anti-roll actuator (e.g. base function) 100% = anti-roll control by VMM
  # system (e.g. vehicle dynamics)
  #
  # Unit: percent. VSS: Vehicle.MotionManagement.Suspension.RollPrioTarget
  # (actuator).
  rollPrioTarget @2 :Int32;
  # Maximum distribution range request of roll torque to front axle. 0% =
  # Complete roll torque shall be shifted to rear axle 100% = Complete roll
  # torque may be shifted to front axle
  #
  # Unit: percent. VSS:
  # Vehicle.MotionManagement.Suspension.RollTorqueDistributionFrontMaximum
  # (actuator).
  rollTorqueDistributionFrontMaximum @3 :Int32;
  # Minimum distribution range request of roll torque to front axle. 0% =
  # Complete roll torque may be shifted to rear axle 100% = Complete roll
  # torque shall be shifted to front axle
  #
  # Unit: percent. VSS:
  # Vehicle.MotionManagement.Suspension.RollTorqueDistributionFrontMinimum
  # (actuator).
  rollTorqueDistributionFrontMinimum @4 :Int32;
}
