@0xe6b2872bb631e574;

# Code generated by protoc-gen-buffers. DO NOT EDIT.
# versions:
# 	protoc-gen-buffers dev
# 	protoc (unknown)
# source: protobuf/covesa/vss/exterior/direction_indicator/v1/direction_indicator.proto
#
# target: capnp
# field slots below are recorded in buffers.lock; edit the .proto, not this file
#
# https://github.com/the-protobuf-project/buffers
using Cxx = import "/capnp/c++.capnp";
$Cxx.namespace("protobuf::covesa::vss::exterior::direction_indicator::v1");

using Wellknown = import "/buffers/wellknown.capnp";

# Indicator lights.
#
# VSS: Vehicle.Body.Lights.DirectionIndicator.
#
# Instanced: Left, Right. The axes together name one occurrence, which is
# why each is a resource of its own rather than a repeated field.
#
# A child resource of Body, named
# "vehicles/{vehicle}/directionIndicators/{direction_indicator}". Its parent
# is a declared resource in protobuf.covesa.vss.exterior.body.v1, which is
# what makes this pattern legal rather than a reference to a collection
# nothing can create.
#
# Reference: COVESA Vehicle Signal Specification.
# https://covesa.github.io/vehicle_signal_specification/
struct DirectionIndicator @0x8215a338dd196188 {
  # Resource name,
  # "vehicles/{vehicle}/directionIndicators/{direction_indicator}". Assigned
  # by the server.
  name @0 :Text;
  # Server-assigned unique id.
  uid @1 :Text;
  # Weak validator for optimistic concurrency, AIP-154
  # <https://aip.dev/154>.
  etag @2 :Text;
  # When this resource was soft-deleted, unset while it is live. AIP-164
  # <https://aip.dev/164>.
  deleteTime @3 :Wellknown.Timestamp;
  # When a soft-deleted resource is purged for good. AIP-164
  # <https://aip.dev/164>.
  expireTime @4 :Wellknown.Timestamp;
  # When this resource was created.
  createTime @5 :Wellknown.Timestamp;
  # When this resource was last modified.
  updateTime @6 :Wellknown.Timestamp;
  # proto field 8 was removed and reserved; this holds its ordinal.
  removed8 @7 :Void;
  # proto field 9 was removed and reserved; this holds its ordinal.
  removed9 @8 :Void;
  # proto field 10 was removed and reserved; this holds its ordinal.
  removed10 @9 :Void;
  # proto field 11 was removed and reserved; this holds its ordinal.
  removed11 @10 :Void;
  # proto field 12 was removed and reserved; this holds its ordinal.
  removed12 @11 :Void;
  # proto field 13 was removed and reserved; this holds its ordinal.
  removed13 @12 :Void;
  # proto field 14 was removed and reserved; this holds its ordinal.
  removed14 @13 :Void;
  # proto field 15 was removed and reserved; this holds its ordinal.
  removed15 @14 :Void;
  # Indicates if light is signaling or off. True = signaling. False = Off.
  #
  # VSS: Vehicle.Body.Lights.DirectionIndicator.IsSignaling (actuator).
  isSignaling @15 :Bool;
  # Indicates if light is defect. True = Light is defect. False = Light has
  # no defect.
  #
  # VSS: Vehicle.Body.Lights.DirectionIndicator.IsDefect (sensor).
  isDefect @16 :Bool;
}
