@0x9d3f3ac97afefc02;

# Code generated by protoc-gen-buffers. DO NOT EDIT.
# versions:
# 	protoc-gen-buffers dev
# 	protoc (unknown)
# source: protobuf/covesa/vss/exterior/direction_indicator/v1/messages.proto
#
# target: capnp
# field slots below are recorded in buffers.lock; edit the .proto, not this file
#
# https://github.com/the-protobuf-project/buffers
using Cxx = import "/capnp/c++.capnp";
$Cxx.namespace("protobuf::covesa::vss::exterior::direction_indicator::v1");

using DirectionIndicator = import "/protobuf/covesa/vss/exterior/direction_indicator/v1/direction_indicator.capnp";

# Request message for DirectionIndicators.GetDirectionIndicator, AIP-131
# <https://aip.dev/131>.
struct GetDirectionIndicatorRequest @0xf43b71010622d915 {
  # Name of the DirectionIndicator to retrieve,
  # "vehicles/{vehicle}/directionIndicators/{direction_indicator}".
  # REQUIRED (AIP-203); Cap'n Proto cannot enforce it.
  name @0 :Text;
}

# Request message for DirectionIndicators.ListDirectionIndicators, AIP-132
# <https://aip.dev/132>.
struct ListDirectionIndicatorsRequest @0xcb6c623389483759 {
  # The Vehicle whose directionIndicators to list, "vehicles/{vehicle}".
  # REQUIRED (AIP-203); Cap'n Proto cannot enforce it.
  parent @0 :Text;
  # Maximum directionIndicators to return. Defaults to 50, capped at 1000.
  pageSize @1 :Int32;
  # Page token from a previous
  # ListDirectionIndicatorsResponse.next_page_token.
  pageToken @2 :Text;
  # Filter expression, AIP-160 <https://aip.dev/160>.
  filter @3 :Text;
  # Include soft-deleted directionIndicators. AIP-164 <https://aip.dev/164>.
  showDeleted @4 :Bool;
}

# Response message for DirectionIndicators.ListDirectionIndicators, AIP-132
# <https://aip.dev/132>.
struct ListDirectionIndicatorsResponse @0x9ac5d62cf5c56c74 {
  # The directionIndicators on this page.
  directionIndicators @0 :List(DirectionIndicator.DirectionIndicator);
  # Token for the next page, empty when this is the last page.
  nextPageToken @1 :Text;
}

# Request message for DirectionIndicators.CreateDirectionIndicator, AIP-133
# <https://aip.dev/133>.
struct CreateDirectionIndicatorRequest @0xf1661c6863a454d0 {
  # The Vehicle to create the DirectionIndicator under,
  # "vehicles/{vehicle}".
  # REQUIRED (AIP-203); Cap'n Proto cannot enforce it.
  parent @0 :Text;
  # The DirectionIndicator to create.
  # REQUIRED (AIP-203); Cap'n Proto cannot enforce it.
  directionIndicator @1 :DirectionIndicator.DirectionIndicator;
  # Client-assigned id, becoming the last segment of the resource name. The
  # server generates one when empty.
  directionIndicatorId @2 :Text;
}

# Request message for DirectionIndicators.UpdateDirectionIndicator, AIP-134
# <https://aip.dev/134>.
struct UpdateDirectionIndicatorRequest @0xf5ec3d1a166c88cc {
  # The DirectionIndicator to update. Its name field identifies the
  # resource.
  # REQUIRED (AIP-203); Cap'n Proto cannot enforce it.
  directionIndicator @0 :DirectionIndicator.DirectionIndicator;
  # Fields to update. An empty mask updates all mutable fields.
  #
  # Only an actuator is writable. A sensor or attribute named in the mask is
  # rejected: both are OUTPUT_ONLY, because a vehicle reports them and an
  # API cannot set them.
  updateMask @1 :List(Text);
}

# Request message for DirectionIndicators.DeleteDirectionIndicator, AIP-135
# <https://aip.dev/135>.
struct DeleteDirectionIndicatorRequest @0xd5fd5eabff485f91 {
  # Name of the DirectionIndicator to delete,
  # "vehicles/{vehicle}/directionIndicators/{direction_indicator}".
  # REQUIRED (AIP-203); Cap'n Proto cannot enforce it.
  name @0 :Text;
}

# Request message for DirectionIndicators.UndeleteDirectionIndicator,
# AIP-164 <https://aip.dev/164>.
struct UndeleteDirectionIndicatorRequest @0xfc5917516fdb50d0 {
  # Name of the soft-deleted DirectionIndicator to restore,
  # "vehicles/{vehicle}/directionIndicators/{direction_indicator}".
  # REQUIRED (AIP-203); Cap'n Proto cannot enforce it.
  name @0 :Text;
}
