@0xf6ee7413dd8383f1;

# Code generated by protoc-gen-buffers. DO NOT EDIT.
# versions:
# 	protoc-gen-buffers dev
# 	protoc (unknown)
# source: protobuf/covesa/vss/interior/occupant/v1/identifier.proto
#
# target: capnp
# field slots below are recorded in buffers.lock; edit the .proto, not this file
#
# https://github.com/the-protobuf-project/buffers
using Cxx = import "/capnp/c++.capnp";
$Cxx.namespace("protobuf::covesa::vss::interior::occupant::v1");

# Identifier attributes based on OAuth 2.0.
#
# VSS: Vehicle.Occupant.Identifier.
#
# Reference: COVESA Vehicle Signal Specification.
# https://covesa.github.io/vehicle_signal_specification/
struct Identity @0xf99557e0c81adb6c {
  # Subject for the authentication of the occupant e.g. UserID 7331677.
  #
  # VSS: Vehicle.Occupant.Identifier.Subject (sensor).
  subject @0 :Text;
  # Unique Issuer for the authentication of the occupant e.g.
  # https://accounts.funcorp.com.
  #
  # VSS: Vehicle.Occupant.Identifier.Issuer (sensor).
  issuer @1 :Text;
}
