@0xc5f5082c5e1f4943;

# Code generated by protoc-gen-buffers. DO NOT EDIT.
# versions:
# 	protoc-gen-buffers dev
# 	protoc (unknown)
# source: protobuf/covesa/vss/interior/occupant/v1/messages.proto
#
# target: capnp
# field slots below are recorded in buffers.lock; edit the .proto, not this file
#
# https://github.com/the-protobuf-project/buffers
using Cxx = import "/capnp/c++.capnp";
$Cxx.namespace("protobuf::covesa::vss::interior::occupant::v1");

using Occupant = import "/protobuf/covesa/vss/interior/occupant/v1/occupant.capnp";

# Request message for Occupants.GetOccupant, AIP-131 <https://aip.dev/131>.
struct GetOccupantRequest @0xf3b206d98b454fb1 {
  # Name of the Occupant to retrieve,
  # "vehicles/{vehicle}/occupants/{occupant}".
  # REQUIRED (AIP-203); Cap'n Proto cannot enforce it.
  name @0 :Text;
}

# Request message for Occupants.ListOccupants, AIP-132
# <https://aip.dev/132>.
struct ListOccupantsRequest @0x8c569ec3bc8d64a9 {
  # The Vehicle whose occupants to list, "vehicles/{vehicle}".
  # REQUIRED (AIP-203); Cap'n Proto cannot enforce it.
  parent @0 :Text;
  # Maximum occupants to return. Defaults to 50, capped at 1000.
  pageSize @1 :Int32;
  # Page token from a previous ListOccupantsResponse.next_page_token.
  pageToken @2 :Text;
  # Filter expression, AIP-160 <https://aip.dev/160>.
  filter @3 :Text;
  # Include soft-deleted occupants. AIP-164 <https://aip.dev/164>.
  showDeleted @4 :Bool;
}

# Response message for Occupants.ListOccupants, AIP-132
# <https://aip.dev/132>.
struct ListOccupantsResponse @0xd6349bf4e3ff8316 {
  # The occupants on this page.
  occupants @0 :List(Occupant.Occupant);
  # Token for the next page, empty when this is the last page.
  nextPageToken @1 :Text;
}

# Request message for Occupants.CreateOccupant, AIP-133
# <https://aip.dev/133>.
struct CreateOccupantRequest @0x8650f47f2eb3bb7c {
  # The Vehicle to create the Occupant under, "vehicles/{vehicle}".
  # REQUIRED (AIP-203); Cap'n Proto cannot enforce it.
  parent @0 :Text;
  # The Occupant to create.
  # REQUIRED (AIP-203); Cap'n Proto cannot enforce it.
  occupant @1 :Occupant.Occupant;
  # Client-assigned id, becoming the last segment of the resource name. The
  # server generates one when empty.
  occupantId @2 :Text;
}

# Request message for Occupants.UpdateOccupant, AIP-134
# <https://aip.dev/134>.
struct UpdateOccupantRequest @0xfd05709248c5fd48 {
  # The Occupant to update. Its name field identifies the resource.
  # REQUIRED (AIP-203); Cap'n Proto cannot enforce it.
  occupant @0 :Occupant.Occupant;
  # Fields to update. An empty mask updates all mutable fields.
  #
  # Only an actuator is writable. A sensor or attribute named in the mask is
  # rejected: both are OUTPUT_ONLY, because a vehicle reports them and an
  # API cannot set them.
  updateMask @1 :List(Text);
}

# Request message for Occupants.DeleteOccupant, AIP-135
# <https://aip.dev/135>.
struct DeleteOccupantRequest @0xdaf30bdb57ab77c7 {
  # Name of the Occupant to delete,
  # "vehicles/{vehicle}/occupants/{occupant}".
  # REQUIRED (AIP-203); Cap'n Proto cannot enforce it.
  name @0 :Text;
}

# Request message for Occupants.UndeleteOccupant, AIP-164
# <https://aip.dev/164>.
struct UndeleteOccupantRequest @0xf5f6d464517ed5f9 {
  # Name of the soft-deleted Occupant to restore,
  # "vehicles/{vehicle}/occupants/{occupant}".
  # REQUIRED (AIP-203); Cap'n Proto cannot enforce it.
  name @0 :Text;
}
