@0xc0df2ff411e4f95f;

# Code generated by protoc-gen-buffers. DO NOT EDIT.
# versions:
# 	protoc-gen-buffers dev
# 	protoc (unknown)
# source: protobuf/covesa/vss/interior/occupant/v1/mid_eye_gaze.proto
#
# target: capnp
# field slots below are recorded in buffers.lock; edit the .proto, not this file
#
# https://github.com/the-protobuf-project/buffers
using Cxx = import "/capnp/c++.capnp";
$Cxx.namespace("protobuf::covesa::vss::interior::occupant::v1");

# Direction from mid eye position to object driver is looking at.
#
# VSS: Vehicle.Occupant.MidEyeGaze.
#
# Reference: COVESA Vehicle Signal Specification.
# https://covesa.github.io/vehicle_signal_specification/
struct MidEyeGaze @0x95ff44847fe03d81 {
  # Mid eye azimuth gaze (right-hand rule) on vehicle sprung mass Z-axis as
  # defined by ISO 23150:2023 0 = Driver looking forward. Positive values =
  # Driver looking at something on the left side of driver. Negative values
  # = Driver looking at something on the right side of driver.
  #
  # Unit: degrees. VSS: Vehicle.Occupant.MidEyeGaze.Azimuth (sensor).
  azimuth @0 :Float64;
  # Elevation to observed object measured as angle between vehicle sprung
  # mass XY-plane as defined by ISO 23150:2023 at driver mid eye position
  # and object. 0 = Driver looking at something at same height as mid eye
  # position. Positive values = Driver looking at something above mid eye
  # position. Negative values = Driver looking at something below mid eye
  # position.
  #
  # Unit: degrees. VSS: Vehicle.Occupant.MidEyeGaze.Elevation (sensor).
  elevation @1 :Float64;
}
