@0x84d90818ac41d90b;

# Code generated by protoc-gen-buffers. DO NOT EDIT.
# versions:
# 	protoc-gen-buffers dev
# 	protoc (unknown)
# source: protobuf/covesa/vss/interior/occupant/v1/occupant.proto
#
# target: capnp
# field slots below are recorded in buffers.lock; edit the .proto, not this file
#
# https://github.com/the-protobuf-project/buffers
using Cxx = import "/capnp/c++.capnp";
$Cxx.namespace("protobuf::covesa::vss::interior::occupant::v1");

using HeadPosition = import "/protobuf/covesa/vss/interior/occupant/v1/head_position.capnp";
using Identifier = import "/protobuf/covesa/vss/interior/occupant/v1/identifier.capnp";
using MidEyeGaze = import "/protobuf/covesa/vss/interior/occupant/v1/mid_eye_gaze.capnp";
using Wellknown = import "/buffers/wellknown.capnp";

# Occupant (Driver or Passenger) data.
#
# VSS: Vehicle.Occupant.
#
# Instanced: Row1, Row2 × DriverSide, Middle, PassengerSide. The axes
# together name one occurrence, which is why each is a resource of its own
# rather than a repeated field.
#
# A child resource of Vehicle, named
# "vehicles/{vehicle}/occupants/{occupant}". Its parent is a declared
# resource in protobuf.covesa.vss.vehicle.v1, which is what makes this
# pattern legal rather than a reference to a collection nothing can create.
#
# Reference: COVESA Vehicle Signal Specification.
# https://covesa.github.io/vehicle_signal_specification/
struct Occupant @0x9760ab0c5ada7c6c {
  # Resource name, "vehicles/{vehicle}/occupants/{occupant}". Assigned by
  # the server.
  name @0 :Text;
  # Server-assigned unique id.
  uid @1 :Text;
  # Weak validator for optimistic concurrency, AIP-154
  # <https://aip.dev/154>.
  etag @2 :Text;
  # When this resource was soft-deleted, unset while it is live. AIP-164
  # <https://aip.dev/164>.
  deleteTime @3 :Wellknown.Timestamp;
  # When a soft-deleted resource is purged for good. AIP-164
  # <https://aip.dev/164>.
  expireTime @4 :Wellknown.Timestamp;
  # When this resource was created.
  createTime @5 :Wellknown.Timestamp;
  # When this resource was last modified.
  updateTime @6 :Wellknown.Timestamp;
  # proto field 8 was removed and reserved; this holds its ordinal.
  removed8 @7 :Void;
  # proto field 9 was removed and reserved; this holds its ordinal.
  removed9 @8 :Void;
  # proto field 10 was removed and reserved; this holds its ordinal.
  removed10 @9 :Void;
  # proto field 11 was removed and reserved; this holds its ordinal.
  removed11 @10 :Void;
  # proto field 12 was removed and reserved; this holds its ordinal.
  removed12 @11 :Void;
  # proto field 13 was removed and reserved; this holds its ordinal.
  removed13 @12 :Void;
  # proto field 14 was removed and reserved; this holds its ordinal.
  removed14 @13 :Void;
  # proto field 15 was removed and reserved; this holds its ordinal.
  removed15 @14 :Void;
  # Identifier attributes based on OAuth 2.0.
  #
  # VSS: Vehicle.Occupant.Identifier.
  identity @15 :Identifier.Identity;
  # The current position of the driver head on vehicle axis according to ISO
  # 23150:2023.
  #
  # VSS: Vehicle.Occupant.HeadPosition.
  headPosition @16 :HeadPosition.HeadPosition;
  # Direction from mid eye position to object driver is looking at.
  #
  # VSS: Vehicle.Occupant.MidEyeGaze.
  midEyeGaze @17 :MidEyeGaze.MidEyeGaze;
}
