// Copyright 2026 Srikanth Kandarpa.
// SPDX-License-Identifier: Apache-2.0

package docs

// page.go assembles one package's README: the chips at the top, the sections
// in order, and the provenance footer.
//
// The order is the order a reader needs it in. What the resource is and where
// it sits comes before what you can do to it, and a worked example comes
// before the field tables -- a reader who only wants to see the shape of a
// response should not have to scroll past 40 rows to find one.

import (
	"fmt"
	"strings"

	"github.com/oh-tarnished/coversa-protobuf/sync/describe"
	"github.com/oh-tarnished/coversa-protobuf/sync/model"
)

// packageDoc renders one package's README.
func (g *Generator) packageDoc(pkg *model.Package) string {
	var sb strings.Builder

	fmt.Fprintf(&sb, "# %s\n\n", pkg.ResourceName())
	g.chips(pkg, &sb)

	if doc := firstParagraph(describe.Message(pkg.ResourceName(), pkg.Root)); doc != "" {
		sb.WriteString(wrap(doc) + "\n\n")
	}
	fmt.Fprintf(&sb, "```\n%s\n```\n\n", pkg.Pattern)

	g.layout(pkg, &sb)
	g.example(pkg, &sb)
	g.resourceNames(pkg, &sb)
	g.signals(pkg, &sb)
	g.instances(pkg, &sb)
	g.methods(pkg, &sb)
	g.enums(pkg, &sb)
	g.footer(pkg, &sb)
	return sb.String()
}

// chips renders the shields.io badges.
//
// Each is a fact a reader would otherwise have to count: which VSS branch
// this is, whether it is a singleton, how many methods and signals it has.
// Linked, so a chip is a way in rather than only a label.
func (g *Generator) chips(pkg *model.Package, sb *strings.Builder) {
	shape, shapeDoc := "collection", "121"
	if pkg.Singleton() {
		shape, shapeDoc = "singleton", "156"
	}

	writable, readonly := g.signalSplit(pkg)
	chips := []struct{ label, text, colour, href string }{
		{"VSS", badge(g.M.Spec.VSS.Version), "0B6B5B",
			"https://github.com/COVESA/vehicle_signal_specification"},
		{"branch", badge(pkg.Root.FQN), "1D4ED8",
			"https://covesa.github.io/vehicle_signal_specification/"},
		{"shape", shape, "2B3172", "https://aip.dev/" + shapeDoc},
		{"RPCs", fmt.Sprint(len(g.methodSet(pkg))), "555", "#methods"},
		{"signals", fmt.Sprint(len(writable) + len(readonly)), "7A4A00", "#signals"},
		{"package", badge(pkg.ProtoPackage()), "444", "v1/"},
	}
	for _, c := range chips {
		fmt.Fprintf(sb, "[![%s](https://img.shields.io/badge/%s-%s-%s)](%s)\n",
			c.label, badge(c.label), c.text, c.colour, c.href)
	}
	sb.WriteString("\n")
}

// badge escapes a string for a shields.io path segment, where a dash is the
// field separator and an underscore is a space.
func badge(s string) string {
	s = strings.ReplaceAll(s, "_", "__")
	s = strings.ReplaceAll(s, "-", "--")
	return strings.ReplaceAll(s, " ", "_")
}

// footer records where the page came from.
func (g *Generator) footer(pkg *model.Package, sb *strings.Builder) {
	sb.WriteString("---\n\n")
	fmt.Fprintf(sb, "<sub>Generated by `just docs` from COVESA VSS `%s` (`%s`) and "+
		"VDM `%s` (`%s`). Do not edit by hand.<br>\nSource: [`%s`](v1/%s) · "+
		"[`service.proto`](v1/service.proto) · [`messages.proto`](v1/messages.proto)</sub>\n",
		g.M.Spec.VSS.Version, g.M.Spec.VSS.Short(),
		g.M.Spec.VDM.Version, g.M.Spec.VDM.Short(),
		model.TypeFile(pkg.Root.Name), model.TypeFile(pkg.Root.Name))
}

// wrap breaks a paragraph at 78 columns.
//
// The READMEs are read in a terminal as often as on GitHub, and an unwrapped
// paragraph is one long line in a pager. The tables are left alone: a wrapped
// row is a broken row.
func wrap(s string) string {
	var out []string
	line := ""
	for _, word := range strings.Fields(s) {
		if line == "" {
			line = word
			continue
		}
		if len(line)+1+len(word) > 78 {
			out = append(out, line)
			line = word
			continue
		}
		line += " " + word
	}
	if line != "" {
		out = append(out, line)
	}
	return strings.Join(out, "\n")
}
