@0x8687e3cbbd6d0316;

# Code generated by protoc-gen-buffers. DO NOT EDIT.
# versions:
# 	protoc-gen-buffers dev
# 	protoc (unknown)
# source: protobuf/covesa/vss/motion/chassis/v1/accelerator.proto
#
# target: capnp
# field slots below are recorded in buffers.lock; edit the .proto, not this file
#
# https://github.com/the-protobuf-project/buffers
using Cxx = import "/capnp/c++.capnp";
$Cxx.namespace("protobuf::covesa::vss::motion::chassis::v1");

# Accelerator signals
#
# VSS: Vehicle.Chassis.Accelerator.
#
# Reference: COVESA Vehicle Signal Specification.
# https://covesa.github.io/vehicle_signal_specification/
struct Accelerator @0x918b7bbe672a1c76 {
  # Accelerator pedal position as percent. 0 = Not depressed. 100 = Fully
  # depressed.
  #
  # Unit: percent. VSS: Vehicle.Chassis.Accelerator.PedalPosition (sensor).
  pedalPosition @0 :Int32;
}
