@0xdb65502981501320;

# Code generated by protoc-gen-buffers. DO NOT EDIT.
# versions:
# 	protoc-gen-buffers dev
# 	protoc (unknown)
# source: protobuf/covesa/vss/motion/chassis/v1/brake.proto
#
# target: capnp
# field slots below are recorded in buffers.lock; edit the .proto, not this file
#
# https://github.com/the-protobuf-project/buffers
using Cxx = import "/capnp/c++.capnp";
$Cxx.namespace("protobuf::covesa::vss::motion::chassis::v1");

# Brake system signals
#
# VSS: Vehicle.Chassis.Brake.
#
# Reference: COVESA Vehicle Signal Specification.
# https://covesa.github.io/vehicle_signal_specification/
struct Brake @0xcf23d54c9b30f64d {
  # Brake pedal position as percent. 0 = Not depressed. 100 = Fully
  # depressed.
  #
  # Unit: percent. VSS: Vehicle.Chassis.Brake.PedalPosition (sensor).
  pedalPosition @0 :Int32;
  # Indicates if emergency braking initiated by driver is detected. True =
  # Emergency braking detected. False = Emergency braking not detected.
  #
  # Detection of emergency braking can trigger Emergency Brake Assist (EBA)
  # to engage.
  #
  # VSS: Vehicle.Chassis.Brake.IsDriverEmergencyBrakingDetected (sensor).
  isDriverEmergencyBrakingDetected @1 :Bool;
}
