@0xb3642b0bb0587285;

# Code generated by protoc-gen-buffers. DO NOT EDIT.
# versions:
# 	protoc-gen-buffers dev
# 	protoc (unknown)
# source: protobuf/covesa/vss/motion/chassis/v1/messages.proto
#
# target: capnp
# field slots below are recorded in buffers.lock; edit the .proto, not this file
#
# https://github.com/the-protobuf-project/buffers
using Cxx = import "/capnp/c++.capnp";
$Cxx.namespace("protobuf::covesa::vss::motion::chassis::v1");

using Chassis = import "/protobuf/covesa/vss/motion/chassis/v1/chassis.capnp";

# Request message for ChassisSet.GetChassis, AIP-131 <https://aip.dev/131>.
struct GetChassisRequest @0xc78a9fe9ea6265fe {
  # Name of the Chassis to retrieve, "vehicles/{vehicle}/chassis".
  # REQUIRED (AIP-203); Cap'n Proto cannot enforce it.
  name @0 :Text;
}

# Request message for ChassisSet.UpdateChassis, AIP-134
# <https://aip.dev/134>.
struct UpdateChassisRequest @0xcf52f2faaeb138a8 {
  # The Chassis to update. Its name field identifies the resource.
  # REQUIRED (AIP-203); Cap'n Proto cannot enforce it.
  chassis @0 :Chassis.Chassis;
  # Fields to update. An empty mask updates all mutable fields.
  #
  # Only an actuator is writable. A sensor or attribute named in the mask is
  # rejected: both are OUTPUT_ONLY, because a vehicle reports them and an
  # API cannot set them.
  updateMask @1 :List(Text);
}
