@0xee8a8c7d8e2c31d3;

# Code generated by protoc-gen-buffers. DO NOT EDIT.
# versions:
# 	protoc-gen-buffers dev
# 	protoc (unknown)
# source: protobuf/covesa/vss/motion/chassis/v1/steering_wheel.proto
#
# target: capnp
# field slots below are recorded in buffers.lock; edit the .proto, not this file
#
# https://github.com/the-protobuf-project/buffers
using Cxx = import "/capnp/c++.capnp";
$Cxx.namespace("protobuf::covesa::vss::motion::chassis::v1");

# Steering wheel signals
#
# VSS: Vehicle.Chassis.SteeringWheel.
#
# Reference: COVESA Vehicle Signal Specification.
# https://covesa.github.io/vehicle_signal_specification/
struct SteeringWheel @0xfbc23c5ca18cfe3b {
  # Steering wheel angle. Positive = degrees to the left. Negative = degrees
  # to the right.
  #
  # Unit: degrees. VSS: Vehicle.Chassis.SteeringWheel.Angle (sensor).
  angle @0 :Int32;
  # Steering wheel column tilt. 0 = Lowest position. 100 = Highest position.
  #
  # Unit: percent. VSS: Vehicle.Chassis.SteeringWheel.Tilt (actuator).
  tilt @1 :Int32;
  # Steering wheel column extension from dashboard. 0 = Closest to
  # dashboard. 100 = Furthest from dashboard.
  #
  # Unit: percent. VSS: Vehicle.Chassis.SteeringWheel.Extension (actuator).
  extension @2 :Int32;
  # Heating or Cooling requsted for the Item. -100 = Maximum cooling, 0 =
  # Heating/cooling deactivated, 100 = Maximum heating.
  #
  # Unit: percent. VSS: Vehicle.Chassis.SteeringWheel.HeatingCooling
  # (actuator).
  heatingCooling @3 :Int32;
}
