@0xd69b53a73dc5105b;

# Code generated by protoc-gen-buffers. DO NOT EDIT.
# versions:
# 	protoc-gen-buffers dev
# 	protoc (unknown)
# source: protobuf/covesa/vdm/location/v1/location.proto
#
# target: capnp
# field slots below are recorded in buffers.lock; edit the .proto, not this file
#
# https://github.com/the-protobuf-project/buffers
using Cxx = import "/capnp/c++.capnp";
$Cxx.namespace("protobuf::covesa::vdm::location::v1");

using Wellknown = import "/buffers/wellknown.capnp";

# Location is a node of the COVESA Vehicle Signal Specification.
#
# VSS: ChargingStation.Location.
#
# A singleton child resource of ChargingStation, AIP-156
# <https://aip.dev/156>, named
# "chargingStations/{charging_station}/location". Its parent is a declared
# resource in protobuf.covesa.vdm.charging_station.v1, which is what makes
# this pattern legal rather than a reference to a collection nothing can
# create.
#
# Reference: COVESA Vehicle Signal Specification.
# https://covesa.github.io/vehicle_signal_specification/
struct Location @0x948db0ae153f87e3 {
  # Resource name, "chargingStations/{charging_station}/location". Assigned
  # by the server.
  name @0 :Text;
  # Server-assigned unique id.
  uid @1 :Text;
  # Weak validator for optimistic concurrency, AIP-154
  # <https://aip.dev/154>.
  etag @2 :Text;
  # When this resource was soft-deleted, unset while it is live. AIP-164
  # <https://aip.dev/164>.
  deleteTime @3 :Wellknown.Timestamp;
  # When a soft-deleted resource is purged for good. AIP-164
  # <https://aip.dev/164>.
  expireTime @4 :Wellknown.Timestamp;
  # When this resource was created.
  createTime @5 :Wellknown.Timestamp;
  # When this resource was last modified.
  updateTime @6 :Wellknown.Timestamp;
  # proto field 8 was removed and reserved; this holds its ordinal.
  removed8 @7 :Void;
  # proto field 9 was removed and reserved; this holds its ordinal.
  removed9 @8 :Void;
  # proto field 10 was removed and reserved; this holds its ordinal.
  removed10 @9 :Void;
  # proto field 11 was removed and reserved; this holds its ordinal.
  removed11 @10 :Void;
  # proto field 12 was removed and reserved; this holds its ordinal.
  removed12 @11 :Void;
  # proto field 13 was removed and reserved; this holds its ordinal.
  removed13 @12 :Void;
  # proto field 14 was removed and reserved; this holds its ordinal.
  removed14 @13 :Void;
  # proto field 15 was removed and reserved; this holds its ordinal.
  removed15 @14 :Void;
  # Street.
  #
  # VSS: ChargingStation.Location.Street (actuator).
  street @15 :Text;
  # City.
  #
  # VSS: ChargingStation.Location.City (actuator).
  city @16 :Text;
  # Administrative area.
  #
  # VSS: ChargingStation.Location.State (actuator).
  administrativeArea @17 :Text;
  # Region code.
  #
  # An ISO 3166-1 alpha-2 country code, e.g. "SE".
  #
  # A string rather than an enum, per AIP-143 <https://aip.dev/143>: the
  # code list belongs to ISO and changes without reference to this schema.
  #
  # VSS: ChargingStation.Location.Country (actuator).
  regionCode @18 :Text;
  # Zip code.
  #
  # VSS: ChargingStation.Location.ZipCode (actuator).
  zipCode @19 :Text;
}
