@0xfacedeaa73457897;

# Code generated by protoc-gen-buffers. DO NOT EDIT.
# versions:
# 	protoc-gen-buffers dev
# 	protoc (unknown)
# source: protobuf/covesa/vss/motion/chassis_axle_wheel/v1/brake.proto
#
# target: capnp
# field slots below are recorded in buffers.lock; edit the .proto, not this file
#
# https://github.com/the-protobuf-project/buffers
using Cxx = import "/capnp/c++.capnp";
$Cxx.namespace("protobuf::covesa::vss::motion::chassis_axle_wheel::v1");

# Brake signals for wheel
#
# VSS: Vehicle.Chassis.Axle.Wheel.Brake.
#
# Reference: COVESA Vehicle Signal Specification.
# https://covesa.github.io/vehicle_signal_specification/
struct Brake @0x83d90e6ddf2beaee {
  # Brake fluid level as percent. 0 = Empty. 100 = Full.
  #
  # Unit: percent. VSS: Vehicle.Chassis.Axle.Wheel.Brake.FluidLevel
  # (sensor).
  fluidLevel @0 :Int32;
  # Brake fluid level status. True = Brake fluid level low. False = Brake
  # fluid level OK.
  #
  # VSS: Vehicle.Chassis.Axle.Wheel.Brake.IsFluidLevelLow (sensor).
  isFluidLevelLow @1 :Bool;
  # Brake pad wear as percent. 0 = No Wear. 100 = Worn.
  #
  # Unit: percent. VSS: Vehicle.Chassis.Axle.Wheel.Brake.PadWear (sensor).
  padWear @2 :Int32;
  # Brake pad wear status. True = Worn. False = Not Worn.
  #
  # VSS: Vehicle.Chassis.Axle.Wheel.Brake.IsBrakesWorn (sensor).
  isBrakesWorn @3 :Bool;
}
