@0xc3e93fadb881f2d6;

# Code generated by protoc-gen-buffers. DO NOT EDIT.
# versions:
# 	protoc-gen-buffers dev
# 	protoc (unknown)
# source: protobuf/covesa/vss/motion/chassis_axle_wheel/v1/messages.proto
#
# target: capnp
# field slots below are recorded in buffers.lock; edit the .proto, not this file
#
# https://github.com/the-protobuf-project/buffers
using Cxx = import "/capnp/c++.capnp";
$Cxx.namespace("protobuf::covesa::vss::motion::chassis_axle_wheel::v1");

using ChassisAxleWheel = import "/protobuf/covesa/vss/motion/chassis_axle_wheel/v1/chassis_axle_wheel.capnp";

# Request message for ChassisAxleWheels.GetChassisAxleWheel, AIP-131
# <https://aip.dev/131>.
struct GetChassisAxleWheelRequest @0x86422e114f442494 {
  # Name of the ChassisAxleWheel to retrieve,
  # "vehicles/{vehicle}/chassisAxles/{chassis_axle}/wheels/{wheel}".
  # REQUIRED (AIP-203); Cap'n Proto cannot enforce it.
  name @0 :Text;
}

# Request message for ChassisAxleWheels.ListChassisAxleWheels, AIP-132
# <https://aip.dev/132>.
struct ListChassisAxleWheelsRequest @0x84c0f4b7df4a83db {
  # The ChassisAxle whose chassisAxleWheels to list,
  # "vehicles/{vehicle}/chassisAxles/{chassis_axle}".
  # REQUIRED (AIP-203); Cap'n Proto cannot enforce it.
  parent @0 :Text;
  # Maximum chassisAxleWheels to return. Defaults to 50, capped at 1000.
  pageSize @1 :Int32;
  # Page token from a previous
  # ListChassisAxleWheelsResponse.next_page_token.
  pageToken @2 :Text;
  # Filter expression, AIP-160 <https://aip.dev/160>.
  filter @3 :Text;
  # Include soft-deleted chassisAxleWheels. AIP-164 <https://aip.dev/164>.
  showDeleted @4 :Bool;
}

# Response message for ChassisAxleWheels.ListChassisAxleWheels, AIP-132
# <https://aip.dev/132>.
struct ListChassisAxleWheelsResponse @0xc04e42df2b3f409a {
  # The chassisAxleWheels on this page.
  chassisAxleWheels @0 :List(ChassisAxleWheel.ChassisAxleWheel);
  # Token for the next page, empty when this is the last page.
  nextPageToken @1 :Text;
}

# Request message for ChassisAxleWheels.CreateChassisAxleWheel, AIP-133
# <https://aip.dev/133>.
struct CreateChassisAxleWheelRequest @0xf4c6b555b5dd4447 {
  # The ChassisAxle to create the ChassisAxleWheel under,
  # "vehicles/{vehicle}/chassisAxles/{chassis_axle}".
  # REQUIRED (AIP-203); Cap'n Proto cannot enforce it.
  parent @0 :Text;
  # The ChassisAxleWheel to create.
  # REQUIRED (AIP-203); Cap'n Proto cannot enforce it.
  chassisAxleWheel @1 :ChassisAxleWheel.ChassisAxleWheel;
  # Client-assigned id, becoming the last segment of the resource name. The
  # server generates one when empty.
  chassisAxleWheelId @2 :Text;
}

# Request message for ChassisAxleWheels.UpdateChassisAxleWheel, AIP-134
# <https://aip.dev/134>.
struct UpdateChassisAxleWheelRequest @0xc22e5c7b0580f61f {
  # The ChassisAxleWheel to update. Its name field identifies the resource.
  # REQUIRED (AIP-203); Cap'n Proto cannot enforce it.
  chassisAxleWheel @0 :ChassisAxleWheel.ChassisAxleWheel;
  # Fields to update. An empty mask updates all mutable fields.
  #
  # Only an actuator is writable. A sensor or attribute named in the mask is
  # rejected: both are OUTPUT_ONLY, because a vehicle reports them and an
  # API cannot set them.
  updateMask @1 :List(Text);
}

# Request message for ChassisAxleWheels.DeleteChassisAxleWheel, AIP-135
# <https://aip.dev/135>.
struct DeleteChassisAxleWheelRequest @0x9a4c12202b0bcd2c {
  # Name of the ChassisAxleWheel to delete,
  # "vehicles/{vehicle}/chassisAxles/{chassis_axle}/wheels/{wheel}".
  # REQUIRED (AIP-203); Cap'n Proto cannot enforce it.
  name @0 :Text;
}

# Request message for ChassisAxleWheels.UndeleteChassisAxleWheel, AIP-164
# <https://aip.dev/164>.
struct UndeleteChassisAxleWheelRequest @0xef6be58bee2e004d {
  # Name of the soft-deleted ChassisAxleWheel to restore,
  # "vehicles/{vehicle}/chassisAxles/{chassis_axle}/wheels/{wheel}".
  # REQUIRED (AIP-203); Cap'n Proto cannot enforce it.
  name @0 :Text;
}
