@0xaca8fbc909e60982;

# Code generated by protoc-gen-buffers. DO NOT EDIT.
# versions:
# 	protoc-gen-buffers dev
# 	protoc (unknown)
# source: protobuf/covesa/vss/exterior/windshield/v1/messages.proto
#
# target: capnp
# field slots below are recorded in buffers.lock; edit the .proto, not this file
#
# https://github.com/the-protobuf-project/buffers
using Cxx = import "/capnp/c++.capnp";
$Cxx.namespace("protobuf::covesa::vss::exterior::windshield::v1");

using Windshield = import "/protobuf/covesa/vss/exterior/windshield/v1/windshield.capnp";

# Request message for Windshields.GetWindshield, AIP-131
# <https://aip.dev/131>.
struct GetWindshieldRequest @0x89bc5bc4ffa0d31c {
  # Name of the Windshield to retrieve,
  # "vehicles/{vehicle}/windshields/{windshield}".
  # REQUIRED (AIP-203); Cap'n Proto cannot enforce it.
  name @0 :Text;
}

# Request message for Windshields.ListWindshields, AIP-132
# <https://aip.dev/132>.
struct ListWindshieldsRequest @0xf75a6f35ed660dc0 {
  # The Vehicle whose windshields to list, "vehicles/{vehicle}".
  # REQUIRED (AIP-203); Cap'n Proto cannot enforce it.
  parent @0 :Text;
  # Maximum windshields to return. Defaults to 50, capped at 1000.
  pageSize @1 :Int32;
  # Page token from a previous ListWindshieldsResponse.next_page_token.
  pageToken @2 :Text;
  # Filter expression, AIP-160 <https://aip.dev/160>.
  filter @3 :Text;
  # Include soft-deleted windshields. AIP-164 <https://aip.dev/164>.
  showDeleted @4 :Bool;
}

# Response message for Windshields.ListWindshields, AIP-132
# <https://aip.dev/132>.
struct ListWindshieldsResponse @0xc8a805b0bb8daf71 {
  # The windshields on this page.
  windshields @0 :List(Windshield.Windshield);
  # Token for the next page, empty when this is the last page.
  nextPageToken @1 :Text;
}

# Request message for Windshields.CreateWindshield, AIP-133
# <https://aip.dev/133>.
struct CreateWindshieldRequest @0xe5cacc755df72234 {
  # The Vehicle to create the Windshield under, "vehicles/{vehicle}".
  # REQUIRED (AIP-203); Cap'n Proto cannot enforce it.
  parent @0 :Text;
  # The Windshield to create.
  # REQUIRED (AIP-203); Cap'n Proto cannot enforce it.
  windshield @1 :Windshield.Windshield;
  # Client-assigned id, becoming the last segment of the resource name. The
  # server generates one when empty.
  windshieldId @2 :Text;
}

# Request message for Windshields.UpdateWindshield, AIP-134
# <https://aip.dev/134>.
struct UpdateWindshieldRequest @0xe3cf16a62674b38e {
  # The Windshield to update. Its name field identifies the resource.
  # REQUIRED (AIP-203); Cap'n Proto cannot enforce it.
  windshield @0 :Windshield.Windshield;
  # Fields to update. An empty mask updates all mutable fields.
  #
  # Only an actuator is writable. A sensor or attribute named in the mask is
  # rejected: both are OUTPUT_ONLY, because a vehicle reports them and an
  # API cannot set them.
  updateMask @1 :List(Text);
}

# Request message for Windshields.DeleteWindshield, AIP-135
# <https://aip.dev/135>.
struct DeleteWindshieldRequest @0xc939eb28f8ba9b66 {
  # Name of the Windshield to delete,
  # "vehicles/{vehicle}/windshields/{windshield}".
  # REQUIRED (AIP-203); Cap'n Proto cannot enforce it.
  name @0 :Text;
}

# Request message for Windshields.UndeleteWindshield, AIP-164
# <https://aip.dev/164>.
struct UndeleteWindshieldRequest @0x8c7ab94f42db125e {
  # Name of the soft-deleted Windshield to restore,
  # "vehicles/{vehicle}/windshields/{windshield}".
  # REQUIRED (AIP-203); Cap'n Proto cannot enforce it.
  name @0 :Text;
}
