@0xebdd216d82061021;

# Code generated by protoc-gen-buffers. DO NOT EDIT.
# versions:
# 	protoc-gen-buffers dev
# 	protoc (unknown)
# source: protobuf/covesa/vss/exterior/windshield/v1/system_types.proto
#
# target: capnp
# field slots below are recorded in buffers.lock; edit the .proto, not this file
#
# https://github.com/the-protobuf-project/buffers
using Cxx = import "/capnp/c++.capnp";
$Cxx.namespace("protobuf::covesa::vss::exterior::windshield::v1");

# Requested mode of wiper system. STOP_HOLD means that the wipers shall move
# to position given by TargetPosition and then hold the position. WIPE means
# that wipers shall move to the position given by TargetPosition and then
# hold the position if no new TargetPosition is requested. PLANT_MODE means
# that wiping is disabled. Exact behavior is vehicle specific.
# EMERGENCY_STOP means that wiping shall be immediately stopped without
# holding the position.
#
# VSS: Vehicle.Body.Windshield.Wiping.System.Mode.
# (buffers.v1.enumeration).underlying asked for 32 bits. A Cap'n Proto enum is
# always 16, with no way to declare otherwise; the narrowing is honoured by
# the FlatBuffers target only.
enum SystemMode @0xdb25ed136cf10054 {
  # Not specified.
  unspecified @0;
  # Stop hold.
  stopHold @1;
  # Wipe.
  wipe @2;
  # Plant mode.
  plantMode @3;
  # Emergency stop.
  emergencyStop @4;
}
