@0x8235b1d80748b837;

# Code generated by protoc-gen-buffers. DO NOT EDIT.
# versions:
# 	protoc-gen-buffers dev
# 	protoc (unknown)
# source: protobuf/covesa/vss/exterior/windshield/v1/washer_fluid.proto
#
# target: capnp
# field slots below are recorded in buffers.lock; edit the .proto, not this file
#
# https://github.com/the-protobuf-project/buffers
using Cxx = import "/capnp/c++.capnp";
$Cxx.namespace("protobuf::covesa::vss::exterior::windshield::v1");

# Windshield washer fluid signals
#
# VSS: Vehicle.Body.Windshield.WasherFluid.
#
# Reference: COVESA Vehicle Signal Specification.
# https://covesa.github.io/vehicle_signal_specification/
struct WasherFluid @0xfce96f5d9c3a3d03 {
  # Low level indication for washer fluid. True = Level Low. False = Level
  # OK.
  #
  # VSS: Vehicle.Body.Windshield.WasherFluid.IsLevelLow (sensor).
  isLevelLow @0 :Bool;
  # Washer fluid level as a percent. 0 = Empty. 100 = Full.
  #
  # Unit: percent. VSS: Vehicle.Body.Windshield.WasherFluid.Level (sensor).
  level @1 :Int32;
}
