@0x96a7ce885b6e8717;

# Code generated by protoc-gen-buffers. DO NOT EDIT.
# versions:
# 	protoc-gen-buffers dev
# 	protoc (unknown)
# source: protobuf/covesa/vss/exterior/windshield/v1/windshield.proto
#
# target: capnp
# field slots below are recorded in buffers.lock; edit the .proto, not this file
#
# https://github.com/the-protobuf-project/buffers
using Cxx = import "/capnp/c++.capnp";
$Cxx.namespace("protobuf::covesa::vss::exterior::windshield::v1");

using WasherFluid = import "/protobuf/covesa/vss/exterior/windshield/v1/washer_fluid.capnp";
using Wellknown = import "/buffers/wellknown.capnp";
using Wiping = import "/protobuf/covesa/vss/exterior/windshield/v1/wiping.capnp";

# Windshield signals.
#
# VSS: Vehicle.Body.Windshield.
#
# Instanced: Front, Rear. The axes together name one occurrence, which is
# why each is a resource of its own rather than a repeated field.
#
# A child resource of Body, named
# "vehicles/{vehicle}/windshields/{windshield}". Its parent is a declared
# resource in protobuf.covesa.vss.exterior.body.v1, which is what makes this
# pattern legal rather than a reference to a collection nothing can create.
#
# Reference: COVESA Vehicle Signal Specification.
# https://covesa.github.io/vehicle_signal_specification/
struct Windshield @0xccc05049aa64ada6 {
  # Resource name, "vehicles/{vehicle}/windshields/{windshield}". Assigned
  # by the server.
  name @0 :Text;
  # Server-assigned unique id.
  uid @1 :Text;
  # Weak validator for optimistic concurrency, AIP-154
  # <https://aip.dev/154>.
  etag @2 :Text;
  # When this resource was soft-deleted, unset while it is live. AIP-164
  # <https://aip.dev/164>.
  deleteTime @3 :Wellknown.Timestamp;
  # When a soft-deleted resource is purged for good. AIP-164
  # <https://aip.dev/164>.
  expireTime @4 :Wellknown.Timestamp;
  # When this resource was created.
  createTime @5 :Wellknown.Timestamp;
  # When this resource was last modified.
  updateTime @6 :Wellknown.Timestamp;
  # proto field 8 was removed and reserved; this holds its ordinal.
  removed8 @7 :Void;
  # proto field 9 was removed and reserved; this holds its ordinal.
  removed9 @8 :Void;
  # proto field 10 was removed and reserved; this holds its ordinal.
  removed10 @9 :Void;
  # proto field 11 was removed and reserved; this holds its ordinal.
  removed11 @10 :Void;
  # proto field 12 was removed and reserved; this holds its ordinal.
  removed12 @11 :Void;
  # proto field 13 was removed and reserved; this holds its ordinal.
  removed13 @12 :Void;
  # proto field 14 was removed and reserved; this holds its ordinal.
  removed14 @13 :Void;
  # proto field 15 was removed and reserved; this holds its ordinal.
  removed15 @14 :Void;
  # Windshield wiper signals.
  #
  # VSS: Vehicle.Body.Windshield.Wiping.
  wiping @15 :Wiping.Wiping;
  # Windshield heater status. False - off, True - on.
  #
  # VSS: Vehicle.Body.Windshield.IsHeatingOn (actuator).
  isHeatingOn @16 :Bool;
  # Windshield washer fluid signals
  #
  # VSS: Vehicle.Body.Windshield.WasherFluid.
  washerFluid @17 :WasherFluid.WasherFluid;
}
