@0xe54afdfda6b6100c;

# Code generated by protoc-gen-buffers. DO NOT EDIT.
# versions:
# 	protoc-gen-buffers dev
# 	protoc (unknown)
# source: protobuf/covesa/vss/exterior/windshield/v1/wiping.proto
#
# target: capnp
# field slots below are recorded in buffers.lock; edit the .proto, not this file
#
# https://github.com/the-protobuf-project/buffers
using Cxx = import "/capnp/c++.capnp";
$Cxx.namespace("protobuf::covesa::vss::exterior::windshield::v1");

using System = import "/protobuf/covesa/vss/exterior/windshield/v1/system.capnp";

# Wiper mode requested by user/driver. INTERVAL indicates intermittent
# wiping, with fixed time interval between each wipe. RAIN_SENSOR indicates
# intermittent wiping based on rain intensity.
#
# VSS: Vehicle.Body.Windshield.Wiping.Mode.
# (buffers.v1.enumeration).underlying asked for 32 bits. A Cap'n Proto enum is
# always 16, with no way to declare otherwise; the narrowing is honoured by
# the FlatBuffers target only.
enum WipingMode @0xb6f1e34ae92990a6 {
  # Not specified.
  unspecified @0;
  # Off.
  off @1;
  # Slow.
  slow @2;
  # Medium.
  medium @3;
  # Fast.
  fast @4;
  # Interval.
  interval @5;
  # Rain sensor.
  rainSensor @6;
}

# Windshield wiper signals.
#
# VSS: Vehicle.Body.Windshield.Wiping.
#
# Reference: COVESA Vehicle Signal Specification.
# https://covesa.github.io/vehicle_signal_specification/
struct Wiping @0xcfca316d4507cab8 {
  # Wiper mode requested by user/driver. INTERVAL indicates intermittent
  # wiping, with fixed time interval between each wipe. RAIN_SENSOR
  # indicates intermittent wiping based on rain intensity.
  #
  # VSS: Vehicle.Body.Windshield.Wiping.Mode (actuator).
  mode @0 :WipingMode;
  # Relative intensity/sensitivity for interval and rain sensor mode as
  # requested by user/driver. Has no significance if Windshield.Wiping.Mode
  # is OFF/SLOW/MEDIUM/FAST 0 - wipers inactive. 1 - minimum intensity
  # (lowest frequency/sensitivity, longest interval). 2/3/4/... - higher
  # intensity (higher frequency/sensitivity, shorter interval). Maximum
  # value supported is vehicle specific.
  #
  # VSS: Vehicle.Body.Windshield.Wiping.Intensity (actuator).
  intensity @1 :Int32;
  # Signals to control behavior of wipers in detail. By default VSS expects
  # only one instance.
  #
  # These signals are typically not directly available to the user/driver of
  # the vehicle. The overlay in overlays/extensions/dual_wiper_systems.vspec
  # can be used to modify this branch to support two instances; Primary and
  # Secondary.
  #
  # VSS: Vehicle.Body.Windshield.Wiping.System.
  system @2 :System.System;
  # Wiper wear as percent. 0 = No Wear. 100 = Worn. Replacement required.
  # Method for calculating or estimating wiper wear is vehicle specific. For
  # windshields with multiple wipers the wear reported shall correspond to
  # the most worn wiper.
  #
  # Unit: percent. VSS: Vehicle.Body.Windshield.Wiping.WiperWear (sensor).
  wiperWear @3 :Int32;
  # Wiper wear status. True = Worn, Replacement recommended or required.
  # False = Not Worn.
  #
  # VSS: Vehicle.Body.Windshield.Wiping.IsWipersWorn (sensor).
  isWipersWorn @4 :Bool;
}
