@0x8e978abbbce2807e;

# Code generated by protoc-gen-buffers. DO NOT EDIT.
# versions:
# 	protoc-gen-buffers dev
# 	protoc (unknown)
# source: protobuf/covesa/vdm/charging_station/v1/messages.proto
#
# target: capnp
# field slots below are recorded in buffers.lock; edit the .proto, not this file
#
# https://github.com/the-protobuf-project/buffers
using Cxx = import "/capnp/c++.capnp";
$Cxx.namespace("protobuf::covesa::vdm::charging_station::v1");

using ChargingStation = import "/protobuf/covesa/vdm/charging_station/v1/charging_station.capnp";

# Request message for ChargingStations.GetChargingStation, AIP-131
# <https://aip.dev/131>.
struct GetChargingStationRequest @0xd1184dd33b6f9520 {
  # Name of the ChargingStation to retrieve,
  # "chargingStations/{charging_station}".
  # REQUIRED (AIP-203); Cap'n Proto cannot enforce it.
  name @0 :Text;
}

# Request message for ChargingStations.ListChargingStations, AIP-132
# <https://aip.dev/132>.
struct ListChargingStationsRequest @0xe52a50c53663c491 {
  # Maximum chargingStations to return. Defaults to 50, capped at 1000.
  pageSize @0 :Int32;
  # Page token from a previous ListChargingStationsResponse.next_page_token.
  pageToken @1 :Text;
  # Filter expression, AIP-160 <https://aip.dev/160>.
  filter @2 :Text;
  # Include soft-deleted chargingStations. AIP-164 <https://aip.dev/164>.
  showDeleted @3 :Bool;
}

# Response message for ChargingStations.ListChargingStations, AIP-132
# <https://aip.dev/132>.
struct ListChargingStationsResponse @0xcaa2d3e1645d3f13 {
  # The chargingStations on this page.
  chargingStations @0 :List(ChargingStation.ChargingStation);
  # Token for the next page, empty when this is the last page.
  nextPageToken @1 :Text;
}

# Request message for ChargingStations.CreateChargingStation, AIP-133
# <https://aip.dev/133>.
struct CreateChargingStationRequest @0xb4ced14994c43643 {
  # The ChargingStation to create.
  # REQUIRED (AIP-203); Cap'n Proto cannot enforce it.
  chargingStation @0 :ChargingStation.ChargingStation;
  # Client-assigned id, becoming the last segment of the resource name. The
  # server generates one when empty.
  chargingStationId @1 :Text;
}

# Request message for ChargingStations.UpdateChargingStation, AIP-134
# <https://aip.dev/134>.
struct UpdateChargingStationRequest @0x8fb94397e49aea6b {
  # The ChargingStation to update. Its name field identifies the resource.
  # REQUIRED (AIP-203); Cap'n Proto cannot enforce it.
  chargingStation @0 :ChargingStation.ChargingStation;
  # Fields to update. An empty mask updates all mutable fields.
  #
  # Only an actuator is writable. A sensor or attribute named in the mask is
  # rejected: both are OUTPUT_ONLY, because a vehicle reports them and an
  # API cannot set them.
  updateMask @1 :List(Text);
}

# Request message for ChargingStations.DeleteChargingStation, AIP-135
# <https://aip.dev/135>.
struct DeleteChargingStationRequest @0xf3682f91d1bcf00a {
  # Name of the ChargingStation to delete,
  # "chargingStations/{charging_station}".
  # REQUIRED (AIP-203); Cap'n Proto cannot enforce it.
  name @0 :Text;
}

# Request message for ChargingStations.UndeleteChargingStation, AIP-164
# <https://aip.dev/164>.
struct UndeleteChargingStationRequest @0xc331b0d7930ca9e3 {
  # Name of the soft-deleted ChargingStation to restore,
  # "chargingStations/{charging_station}".
  # REQUIRED (AIP-203); Cap'n Proto cannot enforce it.
  name @0 :Text;
}
