@0xba3c74d28b2a4754;

# Code generated by protoc-gen-buffers. DO NOT EDIT.
# versions:
# 	protoc-gen-buffers dev
# 	protoc (unknown)
# source: protobuf/covesa/vss/motion/brake_axle_wheel/v1/messages.proto
#
# target: capnp
# field slots below are recorded in buffers.lock; edit the .proto, not this file
#
# https://github.com/the-protobuf-project/buffers
using Cxx = import "/capnp/c++.capnp";
$Cxx.namespace("protobuf::covesa::vss::motion::brake_axle_wheel::v1");

using Wheel = import "/protobuf/covesa/vss/motion/brake_axle_wheel/v1/wheel.capnp";

# Request message for Wheels.GetWheel, AIP-131 <https://aip.dev/131>.
struct GetWheelRequest @0x9e59c4b75fd2e03d {
  # Name of the Wheel to retrieve,
  # "vehicles/{vehicle}/brakeAxles/{brake_axle}/wheels/{wheel}".
  # REQUIRED (AIP-203); Cap'n Proto cannot enforce it.
  name @0 :Text;
}

# Request message for Wheels.ListWheels, AIP-132 <https://aip.dev/132>.
struct ListWheelsRequest @0xd35ef28ed1473b7b {
  # The BrakeAxle whose wheels to list,
  # "vehicles/{vehicle}/brakeAxles/{brake_axle}".
  # REQUIRED (AIP-203); Cap'n Proto cannot enforce it.
  parent @0 :Text;
  # Maximum wheels to return. Defaults to 50, capped at 1000.
  pageSize @1 :Int32;
  # Page token from a previous ListWheelsResponse.next_page_token.
  pageToken @2 :Text;
  # Filter expression, AIP-160 <https://aip.dev/160>.
  filter @3 :Text;
  # Include soft-deleted wheels. AIP-164 <https://aip.dev/164>.
  showDeleted @4 :Bool;
}

# Response message for Wheels.ListWheels, AIP-132 <https://aip.dev/132>.
struct ListWheelsResponse @0xad7fd90f0db2998d {
  # The wheels on this page.
  wheels @0 :List(Wheel.Wheel);
  # Token for the next page, empty when this is the last page.
  nextPageToken @1 :Text;
}

# Request message for Wheels.CreateWheel, AIP-133 <https://aip.dev/133>.
struct CreateWheelRequest @0x89f53f7ca1345993 {
  # The BrakeAxle to create the Wheel under,
  # "vehicles/{vehicle}/brakeAxles/{brake_axle}".
  # REQUIRED (AIP-203); Cap'n Proto cannot enforce it.
  parent @0 :Text;
  # The Wheel to create.
  # REQUIRED (AIP-203); Cap'n Proto cannot enforce it.
  wheel @1 :Wheel.Wheel;
  # Client-assigned id, becoming the last segment of the resource name. The
  # server generates one when empty.
  wheelId @2 :Text;
}

# Request message for Wheels.UpdateWheel, AIP-134 <https://aip.dev/134>.
struct UpdateWheelRequest @0x85e38ec2b67ae401 {
  # The Wheel to update. Its name field identifies the resource.
  # REQUIRED (AIP-203); Cap'n Proto cannot enforce it.
  wheel @0 :Wheel.Wheel;
  # Fields to update. An empty mask updates all mutable fields.
  #
  # Only an actuator is writable. A sensor or attribute named in the mask is
  # rejected: both are OUTPUT_ONLY, because a vehicle reports them and an
  # API cannot set them.
  updateMask @1 :List(Text);
}

# Request message for Wheels.DeleteWheel, AIP-135 <https://aip.dev/135>.
struct DeleteWheelRequest @0xb525ce5c61d596d4 {
  # Name of the Wheel to delete,
  # "vehicles/{vehicle}/brakeAxles/{brake_axle}/wheels/{wheel}".
  # REQUIRED (AIP-203); Cap'n Proto cannot enforce it.
  name @0 :Text;
}

# Request message for Wheels.UndeleteWheel, AIP-164 <https://aip.dev/164>.
struct UndeleteWheelRequest @0xbe0d09af3a610e87 {
  # Name of the soft-deleted Wheel to restore,
  # "vehicles/{vehicle}/brakeAxles/{brake_axle}/wheels/{wheel}".
  # REQUIRED (AIP-203); Cap'n Proto cannot enforce it.
  name @0 :Text;
}
