@0xc51f326032db78d1;

# Code generated by protoc-gen-buffers. DO NOT EDIT.
# versions:
# 	protoc-gen-buffers dev
# 	protoc (unknown)
# source: protobuf/covesa/vdm/charging_session/v1/charging_session.proto
#
# target: capnp
# field slots below are recorded in buffers.lock; edit the .proto, not this file
#
# https://github.com/the-protobuf-project/buffers
using Cxx = import "/capnp/c++.capnp";
$Cxx.namespace("protobuf::covesa::vdm::charging_session::v1");

using Wellknown = import "/buffers/wellknown.capnp";

# ChargingSession is a node of the COVESA Vehicle Signal Specification.
#
# VSS: ChargingSession.
#
# A root resource, named "chargingSessions/{charging_session}".
#
# Reference: COVESA Vehicle Signal Specification.
# https://covesa.github.io/vehicle_signal_specification/
struct ChargingSession @0xc8873a09930ebdb3 {
  # Resource name, "chargingSessions/{charging_session}". Assigned by the
  # server.
  name @0 :Text;
  # Server-assigned unique id.
  uid @1 :Text;
  # Weak validator for optimistic concurrency, AIP-154
  # <https://aip.dev/154>.
  etag @2 :Text;
  # When this resource was soft-deleted, unset while it is live. AIP-164
  # <https://aip.dev/164>.
  deleteTime @3 :Wellknown.Timestamp;
  # When a soft-deleted resource is purged for good. AIP-164
  # <https://aip.dev/164>.
  expireTime @4 :Wellknown.Timestamp;
  # When this resource was created.
  createTime @5 :Wellknown.Timestamp;
  # When this resource was last modified.
  updateTime @6 :Wellknown.Timestamp;
  # proto field 8 was removed and reserved; this holds its ordinal.
  removed8 @7 :Void;
  # proto field 9 was removed and reserved; this holds its ordinal.
  removed9 @8 :Void;
  # proto field 10 was removed and reserved; this holds its ordinal.
  removed10 @9 :Void;
  # proto field 11 was removed and reserved; this holds its ordinal.
  removed11 @10 :Void;
  # proto field 12 was removed and reserved; this holds its ordinal.
  removed12 @11 :Void;
  # proto field 13 was removed and reserved; this holds its ordinal.
  removed13 @12 :Void;
  # proto field 14 was removed and reserved; this holds its ordinal.
  removed14 @13 :Void;
  # proto field 15 was removed and reserved; this holds its ordinal.
  removed15 @14 :Void;
  # Vehicle.
  #
  # VSS: ChargingSession.Vehicle (actuator).
  # REQUIRED (AIP-203); Cap'n Proto cannot enforce it.
  vehicle @15 :Text;
  # Customer.
  #
  # VSS: ChargingSession.Customer (actuator).
  # REQUIRED (AIP-203); Cap'n Proto cannot enforce it.
  customer @16 :Text;
  # Charging point.
  #
  # VSS: ChargingSession.ChargingPoint (actuator).
  # REQUIRED (AIP-203); Cap'n Proto cannot enforce it.
  chargingPoint @17 :Text;
  # Start time.
  #
  # VSS: ChargingSession.StartTime (actuator).
  startTime @18 :Wellknown.Timestamp;
  # End time.
  #
  # VSS: ChargingSession.EndTime (actuator).
  endTime @19 :Wellknown.Timestamp;
}
