@0xfc9fb1c6f9c87ff6;

# Code generated by protoc-gen-buffers. DO NOT EDIT.
# versions:
# 	protoc-gen-buffers dev
# 	protoc (unknown)
# source: protobuf/covesa/vss/interior/seat/v1/airbag.proto
#
# target: capnp
# field slots below are recorded in buffers.lock; edit the .proto, not this file
#
# https://github.com/the-protobuf-project/buffers
using Cxx = import "/capnp/c++.capnp";
$Cxx.namespace("protobuf::covesa::vss::interior::seat::v1");

# Airbag signals.
#
# VSS: Vehicle.Cabin.Seat.Airbag.
#
# Reference: COVESA Vehicle Signal Specification.
# https://covesa.github.io/vehicle_signal_specification/
struct Airbag @0x8606ae2d640c744d {
  # Airbag enabled status. True = Airbag enabled. False = Airbag not
  # enabled.
  #
  # VSS: Vehicle.Cabin.Seat.Airbag.IsEnabled (sensor).
  isEnabled @0 :Bool;
  # Airbag deployment status. True = Airbag deployed. False = Airbag not
  # deployed.
  #
  # VSS: Vehicle.Cabin.Seat.Airbag.IsDeployed (sensor).
  isDeployed @1 :Bool;
}
