@0xc911086f6f50e1ef;

# Code generated by protoc-gen-buffers. DO NOT EDIT.
# versions:
# 	protoc-gen-buffers dev
# 	protoc (unknown)
# source: protobuf/covesa/vss/interior/seat/v1/massage.proto
#
# target: capnp
# field slots below are recorded in buffers.lock; edit the .proto, not this file
#
# https://github.com/the-protobuf-project/buffers
using Cxx = import "/capnp/c++.capnp";
$Cxx.namespace("protobuf::covesa::vss::interior::seat::v1");

# Massage status.
#
# VSS: Vehicle.Cabin.Seat.Massage.Status.
# (buffers.v1.enumeration).underlying asked for 32 bits. A Cap'n Proto enum is
# always 16, with no way to declare otherwise; the narrowing is honoured by
# the FlatBuffers target only.
enum State @0x9d49635279fb7d67 {
  # Not specified.
  unspecified @0;
  # On.
  onValue @1;
  # Off.
  off @2;
}

# Massage related information for the seat.
#
# VSS: Vehicle.Cabin.Seat.Massage.
#
# Reference: COVESA Vehicle Signal Specification.
# https://covesa.github.io/vehicle_signal_specification/
struct Massage @0xbf37bca4593ecdde {
  # True if the seat have the massage capability
  #
  # VSS: Vehicle.Cabin.Seat.Massage.IsAvailable (attribute).
  isAvailable @0 :Bool;
  # Seat massage level. 0 = off. 100 = max massage.
  #
  # Unit: percent. VSS: Vehicle.Cabin.Seat.Massage.Level (actuator).
  level @1 :Int32;
  # Massage status.
  #
  # VSS: Vehicle.Cabin.Seat.Massage.Status (sensor).
  activation @2 :State;
  # Type of massage.
  #
  # OEMs may define a list of identifiers for supported massage types using
  # the allowed keyword
  #
  # VSS: Vehicle.Cabin.Seat.Massage.SupportedTypes (attribute).
  supportedTypes @3 :List(Text);
  # Type of massage active.
  #
  # OEMs may define a list of identifiers for supported massage types using
  # the allowed keyword
  #
  # VSS: Vehicle.Cabin.Seat.Massage.TypeActive (actuator).
  typeActive @4 :Text;
}
