@0xb6d627375d4a1297;

# Code generated by protoc-gen-buffers. DO NOT EDIT.
# versions:
# 	protoc-gen-buffers dev
# 	protoc (unknown)
# source: protobuf/covesa/vss/interior/seat/v1/messages.proto
#
# target: capnp
# field slots below are recorded in buffers.lock; edit the .proto, not this file
#
# https://github.com/the-protobuf-project/buffers
using Cxx = import "/capnp/c++.capnp";
$Cxx.namespace("protobuf::covesa::vss::interior::seat::v1");

using Seat = import "/protobuf/covesa/vss/interior/seat/v1/seat.capnp";

# Request message for Seats.GetSeat, AIP-131 <https://aip.dev/131>.
struct GetSeatRequest @0xa803767de75ee8bb {
  # Name of the Seat to retrieve, "vehicles/{vehicle}/seats/{seat}".
  # REQUIRED (AIP-203); Cap'n Proto cannot enforce it.
  name @0 :Text;
}

# Request message for Seats.ListSeats, AIP-132 <https://aip.dev/132>.
struct ListSeatsRequest @0xdb0adbca129f58c8 {
  # The Vehicle whose seats to list, "vehicles/{vehicle}".
  # REQUIRED (AIP-203); Cap'n Proto cannot enforce it.
  parent @0 :Text;
  # Maximum seats to return. Defaults to 50, capped at 1000.
  pageSize @1 :Int32;
  # Page token from a previous ListSeatsResponse.next_page_token.
  pageToken @2 :Text;
  # Filter expression, AIP-160 <https://aip.dev/160>.
  filter @3 :Text;
  # Include soft-deleted seats. AIP-164 <https://aip.dev/164>.
  showDeleted @4 :Bool;
}

# Response message for Seats.ListSeats, AIP-132 <https://aip.dev/132>.
struct ListSeatsResponse @0xb4b62821fa57ac0f {
  # The seats on this page.
  seats @0 :List(Seat.Seat);
  # Token for the next page, empty when this is the last page.
  nextPageToken @1 :Text;
}

# Request message for Seats.CreateSeat, AIP-133 <https://aip.dev/133>.
struct CreateSeatRequest @0x90470b3c073478e9 {
  # The Vehicle to create the Seat under, "vehicles/{vehicle}".
  # REQUIRED (AIP-203); Cap'n Proto cannot enforce it.
  parent @0 :Text;
  # The Seat to create.
  # REQUIRED (AIP-203); Cap'n Proto cannot enforce it.
  seat @1 :Seat.Seat;
  # Client-assigned id, becoming the last segment of the resource name. The
  # server generates one when empty.
  seatId @2 :Text;
}

# Request message for Seats.UpdateSeat, AIP-134 <https://aip.dev/134>.
struct UpdateSeatRequest @0xb0cc1c796b27bcc9 {
  # The Seat to update. Its name field identifies the resource.
  # REQUIRED (AIP-203); Cap'n Proto cannot enforce it.
  seat @0 :Seat.Seat;
  # Fields to update. An empty mask updates all mutable fields.
  #
  # Only an actuator is writable. A sensor or attribute named in the mask is
  # rejected: both are OUTPUT_ONLY, because a vehicle reports them and an
  # API cannot set them.
  updateMask @1 :List(Text);
}

# Request message for Seats.DeleteSeat, AIP-135 <https://aip.dev/135>.
struct DeleteSeatRequest @0xc3ae91094087642e {
  # Name of the Seat to delete, "vehicles/{vehicle}/seats/{seat}".
  # REQUIRED (AIP-203); Cap'n Proto cannot enforce it.
  name @0 :Text;
}

# Request message for Seats.UndeleteSeat, AIP-164 <https://aip.dev/164>.
struct UndeleteSeatRequest @0xd4a35f19c71fff91 {
  # Name of the soft-deleted Seat to restore,
  # "vehicles/{vehicle}/seats/{seat}".
  # REQUIRED (AIP-203); Cap'n Proto cannot enforce it.
  name @0 :Text;
}
