@0xfba2e921dff63651;

# Code generated by protoc-gen-buffers. DO NOT EDIT.
# versions:
# 	protoc-gen-buffers dev
# 	protoc (unknown)
# source: protobuf/covesa/vss/interior/seat/v1/seat.proto
#
# target: capnp
# field slots below are recorded in buffers.lock; edit the .proto, not this file
#
# https://github.com/the-protobuf-project/buffers
using Cxx = import "/capnp/c++.capnp";
$Cxx.namespace("protobuf::covesa::vss::interior::seat::v1");

using Airbag = import "/protobuf/covesa/vss/interior/seat/v1/airbag.capnp";
using Backrest = import "/protobuf/covesa/vss/interior/seat/v1/backrest.capnp";
using Headrest = import "/protobuf/covesa/vss/interior/seat/v1/headrest.capnp";
using Massage = import "/protobuf/covesa/vss/interior/seat/v1/massage.capnp";
using NeckScarf = import "/protobuf/covesa/vss/interior/seat/v1/neck_scarf.capnp";
using SeatTypes = import "/protobuf/covesa/vss/interior/seat/v1/seat_types.capnp";
using Seating = import "/protobuf/covesa/vss/interior/seat/v1/seating.capnp";
using Wellknown = import "/buffers/wellknown.capnp";

# All seats.
#
# VSS: Vehicle.Cabin.Seat.
#
# Instanced: Row1, Row2 × DriverSide, Middle, PassengerSide. The axes
# together name one occurrence, which is why each is a resource of its own
# rather than a repeated field.
#
# A child resource of Cabin, named "vehicles/{vehicle}/seats/{seat}". Its
# parent is a declared resource in protobuf.covesa.vss.interior.cabin.v1,
# which is what makes this pattern legal rather than a reference to a
# collection nothing can create.
#
# Reference: COVESA Vehicle Signal Specification.
# https://covesa.github.io/vehicle_signal_specification/
struct Seat @0xd1551f85bd9eb3b6 {
  # Resource name, "vehicles/{vehicle}/seats/{seat}". Assigned by the
  # server.
  name @0 :Text;
  # Server-assigned unique id.
  uid @1 :Text;
  # Weak validator for optimistic concurrency, AIP-154
  # <https://aip.dev/154>.
  etag @2 :Text;
  # When this resource was soft-deleted, unset while it is live. AIP-164
  # <https://aip.dev/164>.
  deleteTime @3 :Wellknown.Timestamp;
  # When a soft-deleted resource is purged for good. AIP-164
  # <https://aip.dev/164>.
  expireTime @4 :Wellknown.Timestamp;
  # When this resource was created.
  createTime @5 :Wellknown.Timestamp;
  # When this resource was last modified.
  updateTime @6 :Wellknown.Timestamp;
  # proto field 8 was removed and reserved; this holds its ordinal.
  removed8 @7 :Void;
  # proto field 9 was removed and reserved; this holds its ordinal.
  removed9 @8 :Void;
  # proto field 10 was removed and reserved; this holds its ordinal.
  removed10 @9 :Void;
  # proto field 11 was removed and reserved; this holds its ordinal.
  removed11 @10 :Void;
  # proto field 12 was removed and reserved; this holds its ordinal.
  removed12 @11 :Void;
  # proto field 13 was removed and reserved; this holds its ordinal.
  removed13 @12 :Void;
  # proto field 14 was removed and reserved; this holds its ordinal.
  removed14 @13 :Void;
  # proto field 15 was removed and reserved; this holds its ordinal.
  removed15 @14 :Void;
  # Occupancy status of the seat.
  #
  # VSS: Vehicle.Cabin.Seat.OccupancyStatus (sensor).
  occupancyStatus @15 :SeatTypes.OccupancyState;
  # Is the belt engaged.
  #
  # VSS: Vehicle.Cabin.Seat.IsBelted (sensor).
  isBelted @16 :Bool;
  # Seat belt position on vehicle z-axis. Position is relative within
  # available movable range of the seat belt. 0 = Lowermost position
  # supported.
  #
  # Unit: mm. VSS: Vehicle.Cabin.Seat.SeatBeltHeight (actuator).
  seatBeltHeight @17 :Int32;
  # Massage related information for the seat.
  #
  # VSS: Vehicle.Cabin.Seat.Massage.
  massage @18 :Massage.Massage;
  # Seat position on vehicle x-axis. Position is relative to the frontmost
  # position supported by the seat. 0 = Frontmost position supported.
  #
  # Unit: mm. VSS: Vehicle.Cabin.Seat.Position (actuator).
  position @19 :Int32;
  # Seat position on vehicle z-axis. Position is relative within available
  # movable range of the seating. 0 = Lowermost position supported.
  #
  # Unit: mm. VSS: Vehicle.Cabin.Seat.Height (actuator).
  height @20 :Int32;
  # Tilting of seat (seating and backrest) relative to vehicle x-axis. 0 =
  # seat bottom is flat, seat bottom and vehicle x-axis are parallel.
  # Positive degrees = seat tilted backwards, seat x-axis tilted upward,
  # seat z-axis is tilted backward.
  #
  # In VSS it is assumed that tilting a seat affects both seating (seat
  # bottom) and backrest, i.e. the angle between seating and backrest will
  # not be affected when changing Tilt.
  #
  # Unit: degrees. VSS: Vehicle.Cabin.Seat.Tilt (actuator).
  tilt @21 :Float64;
  # Describes signals related to the backrest of the seat.
  #
  # VSS: Vehicle.Cabin.Seat.Backrest.
  backrest @22 :Backrest.Backrest;
  # Describes signals related to the seat bottom of the seat.
  #
  # Seating is here considered as the part of the seat that supports the
  # thighs. Additional cushions (if any) for support of lower legs is not
  # covered by this branch.
  #
  # VSS: Vehicle.Cabin.Seat.Seating.
  seating @23 :Seating.Seating;
  # Headrest settings.
  #
  # VSS: Vehicle.Cabin.Seat.Headrest.
  headrest @24 :Headrest.Headrest;
  # Airbag signals.
  #
  # VSS: Vehicle.Cabin.Seat.Airbag.
  airbag @25 :Airbag.Airbag;
  # NeckScarf settings.
  #
  # VSS: Vehicle.Cabin.Seat.NeckScarf.
  neckScarf @26 :NeckScarf.NeckScarf;
  # Warmer switch for Seat heater.
  #
  # Affects the property (HeatingCooling).
  #
  # VSS: Vehicle.Cabin.Seat.IsWarmerSwitchEngaged (actuator).
  isWarmerSwitchEngaged @27 :Bool;
  # Cooler switch for Seat heater.
  #
  # Affects the property (HeatingCooling).
  #
  # VSS: Vehicle.Cabin.Seat.IsCoolerSwitchEngaged (actuator).
  isCoolerSwitchEngaged @28 :Bool;
  # Seat forward switch engaged.
  #
  # Affects the property (Position).
  #
  # VSS: Vehicle.Cabin.Seat.IsForwardSwitchEngaged (actuator).
  isForwardSwitchEngaged @29 :Bool;
  # Seat backward switch engaged.
  #
  # Affects the property (Position).
  #
  # VSS: Vehicle.Cabin.Seat.IsBackwardSwitchEngaged (actuator).
  isBackwardSwitchEngaged @30 :Bool;
  # Seat up switch engaged.
  #
  # Affects the property (Height).
  #
  # VSS: Vehicle.Cabin.Seat.IsUpSwitchEngaged (actuator).
  isUpSwitchEngaged @31 :Bool;
  # Seat down switch engaged.
  #
  # Affects the property (Height).
  #
  # VSS: Vehicle.Cabin.Seat.IsDownSwitchEngaged (actuator).
  isDownSwitchEngaged @32 :Bool;
  # Tilt forward switch engaged.
  #
  # Affects the property (Tilt).
  #
  # VSS: Vehicle.Cabin.Seat.IsTiltForwardSwitchEngaged (actuator).
  isTiltForwardSwitchEngaged @33 :Bool;
  # Tilt backward switch engaged.
  #
  # Affects the property (Tilt).
  #
  # VSS: Vehicle.Cabin.Seat.IsTiltBackwardSwitchEngaged (actuator).
  isTiltBackwardSwitchEngaged @34 :Bool;
  # Increase massage level switch engaged.
  #
  # Affects the property (Massage.Level).
  #
  # VSS: Vehicle.Cabin.Seat.IsIncreaseMassageLevelSwitchEngaged (actuator).
  isIncreaseMassageLevelSwitchEngaged @35 :Bool;
  # Decrease massage level switch engaged.
  #
  # Affects the property (Massage.Level).
  #
  # VSS: Vehicle.Cabin.Seat.IsDecreaseMassageLevelSwitchEngaged (actuator).
  isDecreaseMassageLevelSwitchEngaged @36 :Bool;
  # Heating or Cooling requsted for the Item. -100 = Maximum cooling, 0 =
  # Heating/cooling deactivated, 100 = Maximum heating.
  #
  # Unit: percent. VSS: Vehicle.Cabin.Seat.HeatingCooling (actuator).
  heatingCooling @37 :Int32;
}
