@0xc7466cefba6d7dab;

# Code generated by protoc-gen-buffers. DO NOT EDIT.
# versions:
# 	protoc-gen-buffers dev
# 	protoc (unknown)
# source: protobuf/covesa/vss/interior/seat/v1/seat_types.proto
#
# target: capnp
# field slots below are recorded in buffers.lock; edit the .proto, not this file
#
# https://github.com/the-protobuf-project/buffers
using Cxx = import "/capnp/c++.capnp";
$Cxx.namespace("protobuf::covesa::vss::interior::seat::v1");

# Occupancy status of the seat.
#
# VSS: Vehicle.Cabin.Seat.OccupancyStatus.
# (buffers.v1.enumeration).underlying asked for 32 bits. A Cap'n Proto enum is
# always 16, with no way to declare otherwise; the narrowing is honoured by
# the FlatBuffers target only.
enum OccupancyState @0xc2cfc7c8e1542859 {
  # Not specified.
  unspecified @0;
  # Not specified.
  unknown @1;
  # Occupied.
  occupied @2;
  # Empty.
  empty @3;
}
