// Copyright 2026 The Protobuf Project authors.
// SPDX-License-Identifier: Apache-2.0

package main

// spec.go reads sync/spec.yaml, the pin naming which revision of the COVESA
// Vehicle Data Model this schema was generated from.
//
// Dated rather than numbered, the way the Model Context Protocol versions its
// specification: the upstream model publishes no release numbers, so a
// version invented here would mean nothing, where a date is directly
// comparable against the source repository's history.
//
// The pin is read rather than assumed so that the revision travels with the
// output. Every generated file's banner names it, which makes "which spec is
// this from?" answerable from any single file a consumer happens to be
// holding, rather than only from this repository's git history.

import (
	"fmt"
	"os"
	"strings"
)

// Spec is the contents of sync/spec.yaml.
type Spec struct {
	// Version is the revision date, YYYY-MM-DD. It is the date of Commit.
	Version string
	// Commit is the upstream revision actually read. The authority: Version
	// is a label for it, and `just spec` checks the two agree.
	Commit string
	// Source is the upstream repository.
	Source string
	// Path is where the specification is checked out, relative to the
	// repository root.
	Path string
}

// Short renders the commit at the length git logs it.
func (s Spec) Short() string {
	if len(s.Commit) > 7 {
		return s.Commit[:7]
	}
	return s.Commit
}

// LoadSpec reads the pin.
//
// Hand-parsed rather than unmarshalled: the file is four scalar keys, and a
// YAML dependency would be the only one this generator has. Anything it does
// not recognise is an error, per rule 14 -- a typo in a key must not silently
// leave a field empty and stamp an empty revision into 276 files.
func LoadSpec(path string) (Spec, error) {
	raw, err := os.ReadFile(path)
	if err != nil {
		return Spec{}, err
	}
	var s Spec
	for n, line := range strings.Split(string(raw), "\n") {
		text := strings.TrimSpace(line)
		if text == "" || strings.HasPrefix(text, "#") {
			continue
		}
		key, value, ok := strings.Cut(text, ":")
		if !ok {
			return Spec{}, fmt.Errorf("%s:%d: not a key/value line: %q", path, n+1, text)
		}
		value = strings.TrimSpace(value)
		switch strings.TrimSpace(key) {
		case "version":
			s.Version = value
		case "commit":
			s.Commit = value
		case "source":
			s.Source = value
		case "path":
			s.Path = value
		default:
			return Spec{}, fmt.Errorf("%s:%d: unknown key %q", path, n+1, key)
		}
	}
	for _, f := range []struct{ name, value string }{
		{"version", s.Version}, {"commit", s.Commit},
		{"source", s.Source}, {"path", s.Path},
	} {
		if f.value == "" {
			return Spec{}, fmt.Errorf("%s: %s is empty", path, f.name)
		}
	}
	if len(s.Version) != 10 || strings.Count(s.Version, "-") != 2 {
		return Spec{}, fmt.Errorf("%s: version %q is not a YYYY-MM-DD date", path, s.Version)
	}
	return s, nil
}

// banner is the header every generated file carries.
//
// One function rather than the same three lines written out in each emitter,
// so the revision cannot appear in one target's output and not another's.
func (s Spec) banner() string {
	return "// Copyright 2026 The Protobuf Project authors.\n" +
		"// SPDX-License-Identifier: Apache-2.0\n" +
		"//\n" +
		"// Generated by sync from the COVESA Vehicle Data Model,\n" +
		"// spec revision " + s.Version + " (" + s.Short() + "). DO NOT EDIT.\n" +
		"//\n" +
		"// Regenerate with: just sync\n" +
		"// Revision history: docs/spec.md\n\n"
}
