@0xf0764c87b80038ec;

# Code generated by protoc-gen-buffers. DO NOT EDIT.
# versions:
# 	protoc-gen-buffers dev
# 	protoc (unknown)
# source: protobuf/covesa/vss/motion/suspension_axle_wheel/v1/messages.proto
#
# target: capnp
# field slots below are recorded in buffers.lock; edit the .proto, not this file
#
# https://github.com/the-protobuf-project/buffers
using Cxx = import "/capnp/c++.capnp";
$Cxx.namespace("protobuf::covesa::vss::motion::suspension_axle_wheel::v1");

using SuspensionAxleWheel = import "/protobuf/covesa/vss/motion/suspension_axle_wheel/v1/suspension_axle_wheel.capnp";

# Request message for SuspensionAxleWheels.GetSuspensionAxleWheel, AIP-131
# <https://aip.dev/131>.
struct GetSuspensionAxleWheelRequest @0xe2fbaffb3ee8a1db {
  # Name of the SuspensionAxleWheel to retrieve,
  # "vehicles/{vehicle}/suspensionAxles/{suspension_axle}/wheels/{wheel}".
  # REQUIRED (AIP-203); Cap'n Proto cannot enforce it.
  name @0 :Text;
}

# Request message for SuspensionAxleWheels.ListSuspensionAxleWheels, AIP-132
# <https://aip.dev/132>.
struct ListSuspensionAxleWheelsRequest @0xbb70ebb49b21bd9b {
  # The SuspensionAxle whose suspensionAxleWheels to list,
  # "vehicles/{vehicle}/suspensionAxles/{suspension_axle}".
  # REQUIRED (AIP-203); Cap'n Proto cannot enforce it.
  parent @0 :Text;
  # Maximum suspensionAxleWheels to return. Defaults to 50, capped at 1000.
  pageSize @1 :Int32;
  # Page token from a previous
  # ListSuspensionAxleWheelsResponse.next_page_token.
  pageToken @2 :Text;
  # Filter expression, AIP-160 <https://aip.dev/160>.
  filter @3 :Text;
  # Include soft-deleted suspensionAxleWheels. AIP-164
  # <https://aip.dev/164>.
  showDeleted @4 :Bool;
}

# Response message for SuspensionAxleWheels.ListSuspensionAxleWheels,
# AIP-132 <https://aip.dev/132>.
struct ListSuspensionAxleWheelsResponse @0xf4c4103bcf188b47 {
  # The suspensionAxleWheels on this page.
  suspensionAxleWheels @0 :List(SuspensionAxleWheel.SuspensionAxleWheel);
  # Token for the next page, empty when this is the last page.
  nextPageToken @1 :Text;
}

# Request message for SuspensionAxleWheels.CreateSuspensionAxleWheel,
# AIP-133 <https://aip.dev/133>.
struct CreateSuspensionAxleWheelRequest @0xd0393a37893bf504 {
  # The SuspensionAxle to create the SuspensionAxleWheel under,
  # "vehicles/{vehicle}/suspensionAxles/{suspension_axle}".
  # REQUIRED (AIP-203); Cap'n Proto cannot enforce it.
  parent @0 :Text;
  # The SuspensionAxleWheel to create.
  # REQUIRED (AIP-203); Cap'n Proto cannot enforce it.
  suspensionAxleWheel @1 :SuspensionAxleWheel.SuspensionAxleWheel;
  # Client-assigned id, becoming the last segment of the resource name. The
  # server generates one when empty.
  suspensionAxleWheelId @2 :Text;
}

# Request message for SuspensionAxleWheels.UpdateSuspensionAxleWheel,
# AIP-134 <https://aip.dev/134>.
struct UpdateSuspensionAxleWheelRequest @0xf1a883d752792ac9 {
  # The SuspensionAxleWheel to update. Its name field identifies the
  # resource.
  # REQUIRED (AIP-203); Cap'n Proto cannot enforce it.
  suspensionAxleWheel @0 :SuspensionAxleWheel.SuspensionAxleWheel;
  # Fields to update. An empty mask updates all mutable fields.
  #
  # Only an actuator is writable. A sensor or attribute named in the mask is
  # rejected: both are OUTPUT_ONLY, because a vehicle reports them and an
  # API cannot set them.
  updateMask @1 :List(Text);
}

# Request message for SuspensionAxleWheels.DeleteSuspensionAxleWheel,
# AIP-135 <https://aip.dev/135>.
struct DeleteSuspensionAxleWheelRequest @0x85b4d467dcae45cb {
  # Name of the SuspensionAxleWheel to delete,
  # "vehicles/{vehicle}/suspensionAxles/{suspension_axle}/wheels/{wheel}".
  # REQUIRED (AIP-203); Cap'n Proto cannot enforce it.
  name @0 :Text;
}

# Request message for SuspensionAxleWheels.UndeleteSuspensionAxleWheel,
# AIP-164 <https://aip.dev/164>.
struct UndeleteSuspensionAxleWheelRequest @0x9babf8bfa07161e3 {
  # Name of the soft-deleted SuspensionAxleWheel to restore,
  # "vehicles/{vehicle}/suspensionAxles/{suspension_axle}/wheels/{wheel}".
  # REQUIRED (AIP-203); Cap'n Proto cannot enforce it.
  name @0 :Text;
}
