// Copyright 2026 The Protobuf Project authors.
// SPDX-License-Identifier: Apache-2.0

// Package spec reads the pins naming which revisions this schema was
// generated from.
//
// # Two sources
//
// The vehicle tree comes from the COVESA Vehicle Signal Specification, in its
// own `.vspec` format. Everything COVESA defines outside the vehicle --
// people, charging stations, sessions -- comes from the Vehicle Data Model,
// in GraphQL SDL. Each is pinned separately because each moves separately.
//
// # Why the revisions are dated
//
// Dated, not numbered, the way the Model Context Protocol versions its
// specification. Neither upstream publishes release numbers a reader could
// place against anything, so a version invented here would mean nothing. A
// date is directly comparable against the source history, and it sorts.
//
// # Why they are read rather than assumed
//
// Both travel with the output: every generated file's banner names them,
// which makes "which specifications is this from?" answerable from any single
// .proto a consumer happens to be holding.
package spec

import (
	"fmt"
	"os"
	"strings"

	"gopkg.in/yaml.v3"
)

// dateLen is the length of a YYYY-MM-DD version string.
const dateLen = 10

// Source is one pinned upstream specification.
type Source struct {
	// Version is the revision date, YYYY-MM-DD. It is the date of Commit.
	Version string `yaml:"version"`

	// Commit is the upstream revision actually read. The authority: Version
	// is a human-placeable label for it, and scripts/check-spec.sh verifies
	// the two agree with the checked-out submodule.
	Commit string `yaml:"commit"`

	// Source is the upstream repository.
	Source string `yaml:"source"`

	// Path is what the generator reads, relative to the repository root: a
	// file for VSS, a directory for VDM.
	Path string `yaml:"path"`
}

// Short renders the commit at the length git logs it.
func (s Source) Short() string {
	const shortLen = 7
	if len(s.Commit) > shortLen {
		return s.Commit[:shortLen]
	}
	return s.Commit
}

// Spec is the contents of sync/spec.yaml.
type Spec struct {
	VSS Source `yaml:"vss"`
	VDM Source `yaml:"vdm"`
}

// Banner is the header every generated file carries.
//
// One function rather than the same lines repeated in each emitter, so a
// revision cannot appear in one target's output and not another's. Both
// sources are named, because a file may draw on either.
func (s Spec) Banner() string {
	return "// Copyright 2026 The Protobuf Project authors.\n" +
		"// SPDX-License-Identifier: Apache-2.0\n" +
		"//\n" +
		"// Generated by sync from the COVESA Vehicle Signal Specification,\n" +
		"// revision " + s.VSS.Version + " (" + s.VSS.Short() + "), and the\n" +
		"// Vehicle Data Model, revision " + s.VDM.Version + " (" + s.VDM.Short() + ").\n" +
		"// DO NOT EDIT.\n" +
		"//\n" +
		"// Regenerate with: just sync\n" +
		"// Revision history: docs/spec.md\n\n"
}

// Load reads the pins at path.
//
// Strict: a key the schema does not know is an error rather than a field left
// empty, because an empty revision stamped into every banner is a claim
// nothing else can see is false.
func Load(path string) (Spec, error) {
	raw, err := os.ReadFile(path)
	if err != nil {
		return Spec{}, err
	}

	decoder := yaml.NewDecoder(strings.NewReader(string(raw)))
	decoder.KnownFields(true)

	var s Spec
	if err := decoder.Decode(&s); err != nil {
		return Spec{}, fmt.Errorf("%s: %w", path, err)
	}
	for name, src := range map[string]Source{"vss": s.VSS, "vdm": s.VDM} {
		if err := src.validate(name); err != nil {
			return Spec{}, fmt.Errorf("%s: %w", path, err)
		}
	}
	return s, nil
}

// validate reports a pin missing a field or carrying a malformed date.
func (s Source) validate(name string) error {
	for _, f := range []struct{ key, value string }{
		{"version", s.Version}, {"commit", s.Commit},
		{"source", s.Source}, {"path", s.Path},
	} {
		if f.value == "" {
			return fmt.Errorf("%s.%s is empty", name, f.key)
		}
	}
	if len(s.Version) != dateLen || strings.Count(s.Version, "-") != 2 {
		return fmt.Errorf("%s.version %q is not a YYYY-MM-DD date", name, s.Version)
	}
	return nil
}
