@0x8307e881e35c9813;

# Code generated by protoc-gen-buffers. DO NOT EDIT.
# versions:
# 	protoc-gen-buffers dev
# 	protoc (unknown)
# source: protobuf/covesa/vss/motion/brake_axle/v1/brake_axle.proto
#
# target: capnp
# field slots below are recorded in buffers.lock; edit the .proto, not this file
#
# https://github.com/the-protobuf-project/buffers
using Cxx = import "/capnp/c++.capnp";
$Cxx.namespace("protobuf::covesa::vss::motion::brake_axle::v1");

using Wellknown = import "/buffers/wellknown.capnp";

# MotionManagement for brake actuation for a specific electric axle.
#
# VSS: Vehicle.MotionManagement.Brake.Axle.
#
# Instanced: Row1, Row2. The axes together name one occurrence, which is why
# each is a resource of its own rather than a repeated field.
#
# A child resource of MotionManagement, named
# "vehicles/{vehicle}/brakeAxles/{brake_axle}". Its parent is a declared
# resource in protobuf.covesa.vss.motion.motion_management.v1, which is what
# makes this pattern legal rather than a reference to a collection nothing
# can create.
#
# Reference: COVESA Vehicle Signal Specification.
# https://covesa.github.io/vehicle_signal_specification/
struct BrakeAxle @0xcfa23bfc9c60a34c {
  # Resource name, "vehicles/{vehicle}/brakeAxles/{brake_axle}". Assigned by
  # the server.
  name @0 :Text;
  # Server-assigned unique id.
  uid @1 :Text;
  # Weak validator for optimistic concurrency, AIP-154
  # <https://aip.dev/154>.
  etag @2 :Text;
  # When this resource was soft-deleted, unset while it is live. AIP-164
  # <https://aip.dev/164>.
  deleteTime @3 :Wellknown.Timestamp;
  # When a soft-deleted resource is purged for good. AIP-164
  # <https://aip.dev/164>.
  expireTime @4 :Wellknown.Timestamp;
  # When this resource was created.
  createTime @5 :Wellknown.Timestamp;
  # When this resource was last modified.
  updateTime @6 :Wellknown.Timestamp;
  # proto field 8 was removed and reserved; this holds its ordinal.
  removed8 @7 :Void;
  # proto field 9 was removed and reserved; this holds its ordinal.
  removed9 @8 :Void;
  # proto field 10 was removed and reserved; this holds its ordinal.
  removed10 @9 :Void;
  # proto field 11 was removed and reserved; this holds its ordinal.
  removed11 @10 :Void;
  # proto field 12 was removed and reserved; this holds its ordinal.
  removed12 @11 :Void;
  # proto field 13 was removed and reserved; this holds its ordinal.
  removed13 @12 :Void;
  # proto field 14 was removed and reserved; this holds its ordinal.
  removed14 @13 :Void;
  # proto field 15 was removed and reserved; this holds its ordinal.
  removed15 @14 :Void;
  # Limit for regenerative brake torque at given axle. Brake Torque < 0Nm.
  #
  # Unit: Nm. VSS: Vehicle.MotionManagement.Brake.Axle.TorqueElectricMinimum
  # (actuator).
  torqueElectricMinimum @15 :Int32;
  # Maximum absolute wheel torque difference between left and right wheel
  # for friction brake.
  #
  # Unit: Nm. VSS:
  # Vehicle.MotionManagement.Brake.Axle.TorqueFrictionDifferenceMaximum
  # (actuator).
  torqueFrictionDifferenceMaximum @16 :Int32;
  # Maximum distribution range of the friction brake request on the axle to
  # the right wheel. 0% = Complete friction torque shall be shifted to the
  # left wheel. 50% = At most 50% friction torque may be shifted to the
  # right wheel. 100% = Complete friction torque may be shifted to the right
  # wheel.
  #
  # Unit: percent. VSS:
  # Vehicle.MotionManagement.Brake.Axle.TorqueDistributionFrictionRightMaximum
  # (actuator).
  torqueDistributionFrictionRightMaximum @17 :Int32;
  # Minimum distribution range of the friction brake request on the axle to
  # the right wheel. 0% = Complete friction torque may be shifted to the
  # left wheel. 50% = At least 50% friction torque shall be shifted to the
  # right wheel. 100% = Complete friction torque shall be shifted to the
  # right wheel.
  #
  # Unit: percent. VSS:
  # Vehicle.MotionManagement.Brake.Axle.TorqueDistributionFrictionRightMinimum
  # (actuator).
  torqueDistributionFrictionRightMinimum @18 :Int32;
}
