@0xb7e5967571c6e7aa;

# Code generated by protoc-gen-buffers. DO NOT EDIT.
# versions:
# 	protoc-gen-buffers dev
# 	protoc (unknown)
# source: protobuf/covesa/vss/motion/brake_axle/v1/messages.proto
#
# target: capnp
# field slots below are recorded in buffers.lock; edit the .proto, not this file
#
# https://github.com/the-protobuf-project/buffers
using Cxx = import "/capnp/c++.capnp";
$Cxx.namespace("protobuf::covesa::vss::motion::brake_axle::v1");

using BrakeAxle = import "/protobuf/covesa/vss/motion/brake_axle/v1/brake_axle.capnp";

# Request message for BrakeAxles.GetBrakeAxle, AIP-131
# <https://aip.dev/131>.
struct GetBrakeAxleRequest @0x8faa5d76bfb8d926 {
  # Name of the BrakeAxle to retrieve,
  # "vehicles/{vehicle}/brakeAxles/{brake_axle}".
  # REQUIRED (AIP-203); Cap'n Proto cannot enforce it.
  name @0 :Text;
}

# Request message for BrakeAxles.ListBrakeAxles, AIP-132
# <https://aip.dev/132>.
struct ListBrakeAxlesRequest @0xd6b9ebf9f6883a8c {
  # The Vehicle whose brakeAxles to list, "vehicles/{vehicle}".
  # REQUIRED (AIP-203); Cap'n Proto cannot enforce it.
  parent @0 :Text;
  # Maximum brakeAxles to return. Defaults to 50, capped at 1000.
  pageSize @1 :Int32;
  # Page token from a previous ListBrakeAxlesResponse.next_page_token.
  pageToken @2 :Text;
  # Filter expression, AIP-160 <https://aip.dev/160>.
  filter @3 :Text;
  # Include soft-deleted brakeAxles. AIP-164 <https://aip.dev/164>.
  showDeleted @4 :Bool;
}

# Response message for BrakeAxles.ListBrakeAxles, AIP-132
# <https://aip.dev/132>.
struct ListBrakeAxlesResponse @0xe007b2dba3d1d35b {
  # The brakeAxles on this page.
  brakeAxles @0 :List(BrakeAxle.BrakeAxle);
  # Token for the next page, empty when this is the last page.
  nextPageToken @1 :Text;
}

# Request message for BrakeAxles.CreateBrakeAxle, AIP-133
# <https://aip.dev/133>.
struct CreateBrakeAxleRequest @0x920138969e273b67 {
  # The Vehicle to create the BrakeAxle under, "vehicles/{vehicle}".
  # REQUIRED (AIP-203); Cap'n Proto cannot enforce it.
  parent @0 :Text;
  # The BrakeAxle to create.
  # REQUIRED (AIP-203); Cap'n Proto cannot enforce it.
  brakeAxle @1 :BrakeAxle.BrakeAxle;
  # Client-assigned id, becoming the last segment of the resource name. The
  # server generates one when empty.
  brakeAxleId @2 :Text;
}

# Request message for BrakeAxles.UpdateBrakeAxle, AIP-134
# <https://aip.dev/134>.
struct UpdateBrakeAxleRequest @0xbf6a51ecdf798d65 {
  # The BrakeAxle to update. Its name field identifies the resource.
  # REQUIRED (AIP-203); Cap'n Proto cannot enforce it.
  brakeAxle @0 :BrakeAxle.BrakeAxle;
  # Fields to update. An empty mask updates all mutable fields.
  #
  # Only an actuator is writable. A sensor or attribute named in the mask is
  # rejected: both are OUTPUT_ONLY, because a vehicle reports them and an
  # API cannot set them.
  updateMask @1 :List(Text);
}

# Request message for BrakeAxles.DeleteBrakeAxle, AIP-135
# <https://aip.dev/135>.
struct DeleteBrakeAxleRequest @0xcdf8d2cc64b0e145 {
  # Name of the BrakeAxle to delete,
  # "vehicles/{vehicle}/brakeAxles/{brake_axle}".
  # REQUIRED (AIP-203); Cap'n Proto cannot enforce it.
  name @0 :Text;
}

# Request message for BrakeAxles.UndeleteBrakeAxle, AIP-164
# <https://aip.dev/164>.
struct UndeleteBrakeAxleRequest @0xdbba3892466f17ed {
  # Name of the soft-deleted BrakeAxle to restore,
  # "vehicles/{vehicle}/brakeAxles/{brake_axle}".
  # REQUIRED (AIP-203); Cap'n Proto cannot enforce it.
  name @0 :Text;
}
