@0x99c71a7d3d1ebba3;

# Code generated by protoc-gen-buffers. DO NOT EDIT.
# versions:
# 	protoc-gen-buffers dev
# 	protoc (unknown)
# source: protobuf/covesa/vss/interior/driver/v1/driver.proto
#
# target: capnp
# field slots below are recorded in buffers.lock; edit the .proto, not this file
#
# https://github.com/the-protobuf-project/buffers
using Cxx = import "/capnp/c++.capnp";
$Cxx.namespace("protobuf::covesa::vss::interior::driver::v1");

using Wellknown = import "/buffers/wellknown.capnp";

# Driver data.
#
# VSS: Vehicle.Driver.
#
# A singleton child resource of Vehicle, AIP-156 <https://aip.dev/156>,
# named "vehicles/{vehicle}/driver". Its parent is a declared resource in
# protobuf.covesa.vss.vehicle.v1, which is what makes this pattern legal
# rather than a reference to a collection nothing can create.
#
# Reference: COVESA Vehicle Signal Specification.
# https://covesa.github.io/vehicle_signal_specification/
struct Driver @0x83d2238bf0035c3f {
  # Resource name, "vehicles/{vehicle}/driver". Assigned by the server.
  name @0 :Text;
  # Server-assigned unique id.
  uid @1 :Text;
  # Weak validator for optimistic concurrency, AIP-154
  # <https://aip.dev/154>.
  etag @2 :Text;
  # When this resource was soft-deleted, unset while it is live. AIP-164
  # <https://aip.dev/164>.
  deleteTime @3 :Wellknown.Timestamp;
  # When a soft-deleted resource is purged for good. AIP-164
  # <https://aip.dev/164>.
  expireTime @4 :Wellknown.Timestamp;
  # When this resource was created.
  createTime @5 :Wellknown.Timestamp;
  # When this resource was last modified.
  updateTime @6 :Wellknown.Timestamp;
  # proto field 8 was removed and reserved; this holds its ordinal.
  removed8 @7 :Void;
  # proto field 9 was removed and reserved; this holds its ordinal.
  removed9 @8 :Void;
  # proto field 10 was removed and reserved; this holds its ordinal.
  removed10 @9 :Void;
  # proto field 11 was removed and reserved; this holds its ordinal.
  removed11 @10 :Void;
  # proto field 12 was removed and reserved; this holds its ordinal.
  removed12 @11 :Void;
  # proto field 13 was removed and reserved; this holds its ordinal.
  removed13 @12 :Void;
  # proto field 14 was removed and reserved; this holds its ordinal.
  removed14 @13 :Void;
  # proto field 15 was removed and reserved; this holds its ordinal.
  removed15 @14 :Void;
  # Distraction level of the driver, which can be evaluated by multiple
  # factors e.g. driving situation, acoustical or optical signals inside the
  # cockpit, ongoing phone calls.
  #
  # Unit: percent. VSS: Vehicle.Driver.DistractionLevel (sensor).
  distractionLevel @15 :Float64;
  # Has driver the eyes on road or not?
  #
  # VSS: Vehicle.Driver.IsEyesOnRoad (sensor).
  isEyesOnRoad @16 :Bool;
  # Are the driver's hands on the steering wheel or not?
  #
  # VSS: Vehicle.Driver.IsHandsOnWheel (sensor).
  isHandsOnWheel @17 :Bool;
  # Probability of attentiveness of the driver.
  #
  # Unit: percent. VSS: Vehicle.Driver.AttentiveProbability (sensor).
  attentiveProbability @18 :Float64;
  # Fatigue level of the driver, which can be evaluated by multiple factors
  # e.g. trip time, behaviour of steering, eye status.
  #
  # Unit: percent. VSS: Vehicle.Driver.FatigueLevel (sensor).
  fatigueLevel @19 :Float64;
  # Heart rate of the driver.
  #
  # Unit: bpm. VSS: Vehicle.Driver.HeartRate (sensor).
  heartRate @20 :Int32;
}
