@0xaf21cad66a766956;

# Code generated by protoc-gen-buffers. DO NOT EDIT.
# versions:
# 	protoc-gen-buffers dev
# 	protoc (unknown)
# source: protobuf/covesa/vss/interior/driver/v1/messages.proto
#
# target: capnp
# field slots below are recorded in buffers.lock; edit the .proto, not this file
#
# https://github.com/the-protobuf-project/buffers
using Cxx = import "/capnp/c++.capnp";
$Cxx.namespace("protobuf::covesa::vss::interior::driver::v1");

using Driver = import "/protobuf/covesa/vss/interior/driver/v1/driver.capnp";

# Request message for Drivers.GetDriver, AIP-131 <https://aip.dev/131>.
struct GetDriverRequest @0xabb6174e2333aee0 {
  # Name of the Driver to retrieve, "vehicles/{vehicle}/driver".
  # REQUIRED (AIP-203); Cap'n Proto cannot enforce it.
  name @0 :Text;
}

# Request message for Drivers.UpdateDriver, AIP-134 <https://aip.dev/134>.
struct UpdateDriverRequest @0x93fbee50e9a48343 {
  # The Driver to update. Its name field identifies the resource.
  # REQUIRED (AIP-203); Cap'n Proto cannot enforce it.
  driver @0 :Driver.Driver;
  # Fields to update. An empty mask updates all mutable fields.
  #
  # Only an actuator is writable. A sensor or attribute named in the mask is
  # rejected: both are OUTPUT_ONLY, because a vehicle reports them and an
  # API cannot set them.
  updateMask @1 :List(Text);
}
