@0xa337555692dc721a;

# Code generated by protoc-gen-buffers. DO NOT EDIT.
# versions:
# 	protoc-gen-buffers dev
# 	protoc (unknown)
# source: protobuf/covesa/vss/assistance/adas/v1/adas.proto
#
# target: capnp
# field slots below are recorded in buffers.lock; edit the .proto, not this file
#
# https://github.com/the-protobuf-project/buffers
using Cxx = import "/capnp/c++.capnp";
$Cxx.namespace("protobuf::covesa::vss::assistance::adas::v1");

using Abs = import "/protobuf/covesa/vss/assistance/adas/v1/abs.capnp";
using AdasTypes = import "/protobuf/covesa/vss/assistance/adas/v1/adas_types.capnp";
using CruiseControl = import "/protobuf/covesa/vss/assistance/adas/v1/cruise_control.capnp";
using Dms = import "/protobuf/covesa/vss/assistance/adas/v1/dms.capnp";
using Eba = import "/protobuf/covesa/vss/assistance/adas/v1/eba.capnp";
using Ebd = import "/protobuf/covesa/vss/assistance/adas/v1/ebd.capnp";
using Esc = import "/protobuf/covesa/vss/assistance/adas/v1/esc.capnp";
using LaneDepartureDetection = import "/protobuf/covesa/vss/assistance/adas/v1/lane_departure_detection.capnp";
using Tcs = import "/protobuf/covesa/vss/assistance/adas/v1/tcs.capnp";
using Wellknown = import "/buffers/wellknown.capnp";

# All Advanced Driver Assist Systems data.
#
# VSS: Vehicle.ADAS.
#
# A singleton child resource of Vehicle, AIP-156 <https://aip.dev/156>,
# named "vehicles/{vehicle}/adas". Its parent is a declared resource in
# protobuf.covesa.vss.vehicle.v1, which is what makes this pattern legal
# rather than a reference to a collection nothing can create.
#
# Reference: COVESA Vehicle Signal Specification.
# https://covesa.github.io/vehicle_signal_specification/
struct Adas @0xb8c4816b44a61884 {
  # Resource name, "vehicles/{vehicle}/adas". Assigned by the server.
  name @0 :Text;
  # Server-assigned unique id.
  uid @1 :Text;
  # Weak validator for optimistic concurrency, AIP-154
  # <https://aip.dev/154>.
  etag @2 :Text;
  # When this resource was soft-deleted, unset while it is live. AIP-164
  # <https://aip.dev/164>.
  deleteTime @3 :Wellknown.Timestamp;
  # When a soft-deleted resource is purged for good. AIP-164
  # <https://aip.dev/164>.
  expireTime @4 :Wellknown.Timestamp;
  # When this resource was created.
  createTime @5 :Wellknown.Timestamp;
  # When this resource was last modified.
  updateTime @6 :Wellknown.Timestamp;
  # proto field 8 was removed and reserved; this holds its ordinal.
  removed8 @7 :Void;
  # proto field 9 was removed and reserved; this holds its ordinal.
  removed9 @8 :Void;
  # proto field 10 was removed and reserved; this holds its ordinal.
  removed10 @9 :Void;
  # proto field 11 was removed and reserved; this holds its ordinal.
  removed11 @10 :Void;
  # proto field 12 was removed and reserved; this holds its ordinal.
  removed12 @11 :Void;
  # proto field 13 was removed and reserved; this holds its ordinal.
  removed13 @12 :Void;
  # proto field 14 was removed and reserved; this holds its ordinal.
  removed14 @13 :Void;
  # proto field 15 was removed and reserved; this holds its ordinal.
  removed15 @14 :Void;
  # Indicates the currently active level of driving automation according to
  # the SAE J3016 (Taxonomy and Definitions for Terms Related to Driving
  # Automation Systems for On-Road Motor Vehicles).
  #
  # Complies with https://www.sae.org/standards/content/j3016_202104/ and
  # https://www.sae.org/blog/sae-j3016-update. Level 5 and 4 ADS (Automated
  # driving system) disengage, if appropriate, only after it achieves a
  # minimal risk condition or a driver is performing the DDT. Level 3 ADS
  # disengages either an appropriate time after issuing a request to
  # intervene or immediately upon user request. Level 2 DAS (Driving
  # automation system) disengages immediately upon driver request. However,
  # since many Level 2 DAS, often termed "Level 2.5", warn the driver
  # shortly before reaching their operational limits, the VSS also supports
  # the DISENGAGING state for SAE_2. Nevertheless, it should be noted that
  # the SAE J3016 states that it is incorrect to describe driving automation
  # features using fractional levels.
  #
  # VSS: Vehicle.ADAS.ActiveAutonomyLevel (sensor).
  activeAutonomyLevel @15 :AdasTypes.ActiveAutonomyLevel;
  # Indicates the highest level of driving automation according to the SAE
  # J3016 taxonomy the vehicle is capable of.
  #
  # VSS: Vehicle.ADAS.SupportedAutonomyLevel (attribute).
  supportedAutonomyLevel @16 :AdasTypes.SupportedAutonomyLevel;
  # Signals from Cruise Control system.
  #
  # VSS: Vehicle.ADAS.CruiseControl.
  cruiseControl @17 :CruiseControl.CruiseControl;
  # Signals from Lane Departure Detection System.
  #
  # VSS: Vehicle.ADAS.LaneDepartureDetection.
  laneDepartureDetection @18 :LaneDepartureDetection.LaneDepartureDetection;
  # Antilock Braking System signals.
  #
  # VSS: Vehicle.ADAS.ABS.
  abs @19 :Abs.Abs;
  # Traction Control System signals.
  #
  # VSS: Vehicle.ADAS.TCS.
  tcs @20 :Tcs.Tcs;
  # Electronic Stability Control System signals.
  #
  # VSS: Vehicle.ADAS.ESC.
  esc @21 :Esc.Esc;
  # Electronic Brakeforce Distribution (EBD) System signals.
  #
  # VSS: Vehicle.ADAS.EBD.
  ebd @22 :Ebd.Ebd;
  # Emergency Brake Assist (EBA) System signals.
  #
  # VSS: Vehicle.ADAS.EBA.
  eba @23 :Eba.Eba;
  # Driver Monitoring System signals.
  #
  # VSS: Vehicle.ADAS.DMS.
  dms @24 :Dms.Dms;
  # Power optimization level for this branch/subsystem. A higher number
  # indicates more aggressive power optimization. Level 0 indicates that all
  # functionality is enabled, no power optimization enabled. Level 10
  # indicates most aggressive power optimization mode, only essential
  # functionality enabled.
  #
  # VSS: Vehicle.ADAS.PowerOptimizeLevel (actuator).
  powerOptimizeLevel @25 :Int32;
  # Auto Power Optimization Flag When set to 'true', the system enables
  # automatic power optimization, dynamically adjusting the power
  # optimization level based on runtime conditions or features managed by
  # the OEM. When set to 'false', manual control of the power optimization
  # level is allowed.
  #
  # VSS: Vehicle.ADAS.IsAutoPowerOptimize (actuator).
  isAutoPowerOptimize @26 :Bool;
}
