@0xf02587b1dafe77e4;

# Code generated by protoc-gen-buffers. DO NOT EDIT.
# versions:
# 	protoc-gen-buffers dev
# 	protoc (unknown)
# source: protobuf/covesa/vss/assistance/adas/v1/adas_types.proto
#
# target: capnp
# field slots below are recorded in buffers.lock; edit the .proto, not this file
#
# https://github.com/the-protobuf-project/buffers
using Cxx = import "/capnp/c++.capnp";
$Cxx.namespace("protobuf::covesa::vss::assistance::adas::v1");

# Indicates the currently active level of driving automation according to
# the SAE J3016 (Taxonomy and Definitions for Terms Related to Driving
# Automation Systems for On-Road Motor Vehicles).
#
# VSS: Vehicle.ADAS.ActiveAutonomyLevel.
# (buffers.v1.enumeration).underlying asked for 32 bits. A Cap'n Proto enum is
# always 16, with no way to declare otherwise; the narrowing is honoured by
# the FlatBuffers target only.
enum ActiveAutonomyLevel @0x87ab75a67996794a {
  # Not specified.
  unspecified @0;
  # Sae 0.
  sae0 @1;
  # Sae 1.
  sae1 @2;
  # Sae 2 disengaging.
  sae2Disengaging @3;
  # Sae 2.
  sae2 @4;
  # Sae 3 disengaging.
  sae3Disengaging @5;
  # Sae 3.
  sae3 @6;
  # Sae 4 disengaging.
  sae4Disengaging @7;
  # Sae 4.
  sae4 @8;
  # Sae 5 disengaging.
  sae5Disengaging @9;
  # Sae 5.
  sae5 @10;
}

# Indicates the highest level of driving automation according to the SAE
# J3016 taxonomy the vehicle is capable of.
#
# VSS: Vehicle.ADAS.SupportedAutonomyLevel.
# (buffers.v1.enumeration).underlying asked for 32 bits. A Cap'n Proto enum is
# always 16, with no way to declare otherwise; the narrowing is honoured by
# the FlatBuffers target only.
enum SupportedAutonomyLevel @0xdc65d44f82514ac2 {
  # Not specified.
  unspecified @0;
  # Sae 0.
  sae0 @1;
  # Sae 1.
  sae1 @2;
  # Sae 2.
  sae2 @3;
  # Sae 3.
  sae3 @4;
  # Sae 4.
  sae4 @5;
  # Sae 5.
  sae5 @6;
}
