@0x86bc62fd78cfd4ff;

# Code generated by protoc-gen-buffers. DO NOT EDIT.
# versions:
# 	protoc-gen-buffers dev
# 	protoc (unknown)
# source: protobuf/covesa/vss/assistance/adas/v1/eba.proto
#
# target: capnp
# field slots below are recorded in buffers.lock; edit the .proto, not this file
#
# https://github.com/the-protobuf-project/buffers
using Cxx = import "/capnp/c++.capnp";
$Cxx.namespace("protobuf::covesa::vss::assistance::adas::v1");

# Emergency Brake Assist (EBA) System signals.
#
# VSS: Vehicle.ADAS.EBA.
#
# Reference: COVESA Vehicle Signal Specification.
# https://covesa.github.io/vehicle_signal_specification/
struct Eba @0xd6cfcb41d068596a {
  # Indicates if EBA is enabled. True = Enabled. False = Disabled.
  #
  # VSS: Vehicle.ADAS.EBA.IsEnabled (actuator).
  isEnabled @0 :Bool;
  # Indicates if EBA incurred an error condition. True = Error. False = No
  # Error.
  #
  # VSS: Vehicle.ADAS.EBA.IsError (sensor).
  isError @1 :Bool;
  # Indicates if EBA is currently regulating brake pressure. True = Engaged.
  # False = Not Engaged.
  #
  # VSS: Vehicle.ADAS.EBA.IsEngaged (sensor).
  isEngaged @2 :Bool;
}
