@0xa2a386b177c06312;

# Code generated by protoc-gen-buffers. DO NOT EDIT.
# versions:
# 	protoc-gen-buffers dev
# 	protoc (unknown)
# source: protobuf/covesa/vss/assistance/adas/v1/ebd.proto
#
# target: capnp
# field slots below are recorded in buffers.lock; edit the .proto, not this file
#
# https://github.com/the-protobuf-project/buffers
using Cxx = import "/capnp/c++.capnp";
$Cxx.namespace("protobuf::covesa::vss::assistance::adas::v1");

# Electronic Brakeforce Distribution (EBD) System signals.
#
# VSS: Vehicle.ADAS.EBD.
#
# Reference: COVESA Vehicle Signal Specification.
# https://covesa.github.io/vehicle_signal_specification/
struct Ebd @0xf4cff8e67b5e22c8 {
  # Indicates if EBD is enabled. True = Enabled. False = Disabled.
  #
  # VSS: Vehicle.ADAS.EBD.IsEnabled (actuator).
  isEnabled @0 :Bool;
  # Indicates if EBD incurred an error condition. True = Error. False = No
  # Error.
  #
  # VSS: Vehicle.ADAS.EBD.IsError (sensor).
  isError @1 :Bool;
  # Indicates if EBD is currently regulating vehicle brakeforce
  # distribution. True = Engaged. False = Not Engaged.
  #
  # VSS: Vehicle.ADAS.EBD.IsEngaged (sensor).
  isEngaged @2 :Bool;
}
