@0xa9906c8699a46fe3;

# Code generated by protoc-gen-buffers. DO NOT EDIT.
# versions:
# 	protoc-gen-buffers dev
# 	protoc (unknown)
# source: protobuf/covesa/vss/assistance/adas/v1/lane_departure_detection.proto
#
# target: capnp
# field slots below are recorded in buffers.lock; edit the .proto, not this file
#
# https://github.com/the-protobuf-project/buffers
using Cxx = import "/capnp/c++.capnp";
$Cxx.namespace("protobuf::covesa::vss::assistance::adas::v1");

# Signals from Lane Departure Detection System.
#
# VSS: Vehicle.ADAS.LaneDepartureDetection.
#
# Reference: COVESA Vehicle Signal Specification.
# https://covesa.github.io/vehicle_signal_specification/
struct LaneDepartureDetection @0xda81d15ab577994b {
  # Indicates if lane departure detection system is enabled. True = Enabled.
  # False = Disabled.
  #
  # VSS: Vehicle.ADAS.LaneDepartureDetection.IsEnabled (actuator).
  isEnabled @0 :Bool;
  # Indicates if lane departure detection registered a lane departure.
  #
  # VSS: Vehicle.ADAS.LaneDepartureDetection.IsWarning (sensor).
  isWarning @1 :Bool;
  # Indicates if lane departure system incurred an error condition. True =
  # Error. False = No Error.
  #
  # VSS: Vehicle.ADAS.LaneDepartureDetection.IsError (sensor).
  isError @2 :Bool;
}
