@0xd6504297c77d52bc;

# Code generated by protoc-gen-buffers. DO NOT EDIT.
# versions:
# 	protoc-gen-buffers dev
# 	protoc (unknown)
# source: protobuf/covesa/vss/assistance/adas/v1/service.proto
#
# target: capnp
# field slots below are recorded in buffers.lock; edit the .proto, not this file
#
# https://github.com/the-protobuf-project/buffers
using Cxx = import "/capnp/c++.capnp";
$Cxx.namespace("protobuf::covesa::vss::assistance::adas::v1");

using Adas = import "/protobuf/covesa/vss/assistance/adas/v1/adas.capnp";
using Messages = import "/protobuf/covesa/vss/assistance/adas/v1/messages.capnp";

# AdasService manages the Adas branch of a vehicle.
#
# A **singleton**, AIP-156 <https://aip.dev/156>: a vehicle has exactly one,
# its name has no id segment, and it cannot be created or deleted
# independently of the vehicle. Get and Update are the whole surface.
#
# Reference: COVESA Vehicle Signal Specification.
# https://covesa.github.io/vehicle_signal_specification/
interface AdasService @0xcd6cb536841d2cd3 {
  # Retrieves one Adas.
  #
  # GET /v1/{name=vehicles/*/adas}
  #
  # Safe and idempotent. Read the `etag` here and pass it back on update to
  # make the write conditional.
  #
  # NOT_FOUND no such Adas
  # INVALID_ARGUMENT name does not match the resource pattern
  # PERMISSION_DENIED caller may not read it
  # AIP-131 standard method.
  getAdas @0 (request :Messages.GetAdasRequest) -> (response :Adas.Adas);

  # Updates a Adas.
  #
  # PATCH /v1/{adas.name=vehicles/*/adas}
  # body: the Adas itself
  #
  # A partial update: only fields named in `update_mask` are written. An
  # empty mask writes every mutable field, which will clear anything the
  # caller left unset -- pass a mask unless that is the intent.
  #
  # **Only an actuator is writable.** VSS marks each signal an attribute, a
  # sensor or an actuator; the first two are OUTPUT_ONLY here, because a
  # vehicle reports them and no API call can change them. A mask naming one
  # is rejected rather than silently ignored.
  #
  # Idempotent. Pass the `etag` read from Get to make the write conditional.
  #
  # NOT_FOUND no such Adas
  # ABORTED etag does not match the stored resource
  # INVALID_ARGUMENT mask names an unknown, immutable or read-only field
  # PERMISSION_DENIED caller may not modify it
  # AIP-134 standard method.
  updateAdas @1 (request :Messages.UpdateAdasRequest) -> (response :Adas.Adas);
}
