@0xd374d7a30cc06d35;

# Code generated by protoc-gen-buffers. DO NOT EDIT.
# versions:
# 	protoc-gen-buffers dev
# 	protoc (unknown)
# source: protobuf/covesa/vss/assistance/adas/v1/tcs.proto
#
# target: capnp
# field slots below are recorded in buffers.lock; edit the .proto, not this file
#
# https://github.com/the-protobuf-project/buffers
using Cxx = import "/capnp/c++.capnp";
$Cxx.namespace("protobuf::covesa::vss::assistance::adas::v1");

# Traction Control System signals.
#
# VSS: Vehicle.ADAS.TCS.
#
# Reference: COVESA Vehicle Signal Specification.
# https://covesa.github.io/vehicle_signal_specification/
struct Tcs @0xd5beac2430d7cdb5 {
  # Indicates if TCS is enabled. True = Enabled. False = Disabled.
  #
  # VSS: Vehicle.ADAS.TCS.IsEnabled (actuator).
  isEnabled @0 :Bool;
  # Indicates if TCS incurred an error condition. True = Error. False = No
  # Error.
  #
  # VSS: Vehicle.ADAS.TCS.IsError (sensor).
  isError @1 :Bool;
  # Indicates if TCS is currently regulating traction. True = Engaged. False
  # = Not Engaged.
  #
  # VSS: Vehicle.ADAS.TCS.IsEngaged (sensor).
  isEngaged @2 :Bool;
}
