@0xd1e906a7597d978b;

# Code generated by protoc-gen-buffers. DO NOT EDIT.
# versions:
# 	protoc-gen-buffers dev
# 	protoc (unknown)
# source: protobuf/covesa/vss/propulsion/electric_motor/v1/electric_motor.proto
#
# target: capnp
# field slots below are recorded in buffers.lock; edit the .proto, not this file
#
# https://github.com/the-protobuf-project/buffers
using Cxx = import "/capnp/c++.capnp";
$Cxx.namespace("protobuf::covesa::vss::propulsion::electric_motor::v1");

using EngineCoolant = import "/protobuf/covesa/vss/propulsion/electric_motor/v1/engine_coolant.capnp";
using Wellknown = import "/buffers/wellknown.capnp";

# Electric Motor specific data.
#
# Instance Front to be used if the vehicle has a motor located at the front
# of the vehicle, serving front and possibly also rear axle. Instance Rear
# to be used if the vehicle has a motor located at the rear of the vehicle,
# serving rear and possiblsy also front axle. Instances with Left/Right
# intended to be used if vehicle has separate motors for left and right
# side.
#
# VSS: Vehicle.Powertrain.ElectricMotor.
#
# Instanced: Front, Rear, FrontLeft, FrontRight, RearLeft, RearRight. The
# axes together name one occurrence, which is why each is a resource of its
# own rather than a repeated field.
#
# A child resource of Powertrain, named
# "vehicles/{vehicle}/electricMotors/{electric_motor}". Its parent is a
# declared resource in protobuf.covesa.vss.propulsion.powertrain.v1, which
# is what makes this pattern legal rather than a reference to a collection
# nothing can create.
#
# Reference: COVESA Vehicle Signal Specification.
# https://covesa.github.io/vehicle_signal_specification/
struct ElectricMotor @0xad1012d7e945d8c5 {
  # Resource name, "vehicles/{vehicle}/electricMotors/{electric_motor}".
  # Assigned by the server.
  name @0 :Text;
  # Server-assigned unique id.
  uid @1 :Text;
  # Weak validator for optimistic concurrency, AIP-154
  # <https://aip.dev/154>.
  etag @2 :Text;
  # When this resource was soft-deleted, unset while it is live. AIP-164
  # <https://aip.dev/164>.
  deleteTime @3 :Wellknown.Timestamp;
  # When a soft-deleted resource is purged for good. AIP-164
  # <https://aip.dev/164>.
  expireTime @4 :Wellknown.Timestamp;
  # When this resource was created.
  createTime @5 :Wellknown.Timestamp;
  # When this resource was last modified.
  updateTime @6 :Wellknown.Timestamp;
  # proto field 8 was removed and reserved; this holds its ordinal.
  removed8 @7 :Void;
  # proto field 9 was removed and reserved; this holds its ordinal.
  removed9 @8 :Void;
  # proto field 10 was removed and reserved; this holds its ordinal.
  removed10 @9 :Void;
  # proto field 11 was removed and reserved; this holds its ordinal.
  removed11 @10 :Void;
  # proto field 12 was removed and reserved; this holds its ordinal.
  removed12 @11 :Void;
  # proto field 13 was removed and reserved; this holds its ordinal.
  removed13 @12 :Void;
  # proto field 14 was removed and reserved; this holds its ordinal.
  removed14 @13 :Void;
  # proto field 15 was removed and reserved; this holds its ordinal.
  removed15 @14 :Void;
  # Engine code designation, as specified by vehicle manufacturer.
  #
  # VSS: Vehicle.Powertrain.ElectricMotor.EngineCode (attribute).
  engineCode @15 :Text;
  # Peak power, in kilowatts, that motor(s) can generate.
  #
  # Unit: kW. VSS: Vehicle.Powertrain.ElectricMotor.MaxPower (attribute).
  maxPower @16 :Int32;
  # Peak power, in newton meter, that the motor(s) can generate.
  #
  # Unit: Nm. VSS: Vehicle.Powertrain.ElectricMotor.MaxTorque (attribute).
  maxTorque @17 :Int32;
  # Peak regen/brake power, in kilowatts, that motor(s) can generate.
  #
  # Unit: kW. VSS: Vehicle.Powertrain.ElectricMotor.MaxRegenPower
  # (attribute).
  maxRegenPower @18 :Int32;
  # Peak regen/brake torque, in newton meter, that the motor(s) can
  # generate.
  #
  # Unit: Nm. VSS: Vehicle.Powertrain.ElectricMotor.MaxRegenTorque
  # (attribute).
  maxRegenTorque @19 :Int32;
  # Motor rotational speed measured as rotations per minute. Negative values
  # indicate reverse driving mode.
  #
  # Unit: rpm. VSS: Vehicle.Powertrain.ElectricMotor.Speed (sensor).
  speed @20 :Float64;
  # Accumulated time during engine lifetime when the vehicule state's is
  # 'READY'.
  #
  # Vehicles may define their READY state.
  #
  # Unit: h. VSS: Vehicle.Powertrain.ElectricMotor.TimeInUse (sensor).
  usageDuration @21 :Wellknown.Duration;
  # Motor temperature.
  #
  # Unit: Celsius. VSS: Vehicle.Powertrain.ElectricMotor.Temperature
  # (sensor).
  temperature @22 :Float64;
  # Signals related to the engine coolant (if applicable).
  #
  # VSS: Vehicle.Powertrain.ElectricMotor.EngineCoolant.
  engineCoolant @23 :EngineCoolant.EngineCoolant;
  # Current motor power output. Negative values indicate regen mode.
  #
  # Unit: kW. VSS: Vehicle.Powertrain.ElectricMotor.Power (sensor).
  power @24 :Int32;
  # Current motor torque. Negative values indicate regen mode.
  #
  # Unit: Nm. VSS: Vehicle.Powertrain.ElectricMotor.Torque (sensor).
  torque @25 :Int32;
}
