@0xa318b20d1fb432dd;

# Code generated by protoc-gen-buffers. DO NOT EDIT.
# versions:
# 	protoc-gen-buffers dev
# 	protoc (unknown)
# source: protobuf/covesa/vss/motion/acceleration/v1/acceleration.proto
#
# target: capnp
# field slots below are recorded in buffers.lock; edit the .proto, not this file
#
# https://github.com/the-protobuf-project/buffers
using Cxx = import "/capnp/c++.capnp";
$Cxx.namespace("protobuf::covesa::vss::motion::acceleration::v1");

using Wellknown = import "/buffers/wellknown.capnp";

# Spatial acceleration. Axis definitions according to ISO 8855.
#
# VSS: Vehicle.Acceleration.
#
# A singleton child resource of Vehicle, AIP-156 <https://aip.dev/156>,
# named "vehicles/{vehicle}/acceleration". Its parent is a declared resource
# in protobuf.covesa.vss.vehicle.v1, which is what makes this pattern legal
# rather than a reference to a collection nothing can create.
#
# Reference: COVESA Vehicle Signal Specification.
# https://covesa.github.io/vehicle_signal_specification/
struct Acceleration @0xd083436b898749c7 {
  # Resource name, "vehicles/{vehicle}/acceleration". Assigned by the
  # server.
  name @0 :Text;
  # Server-assigned unique id.
  uid @1 :Text;
  # Weak validator for optimistic concurrency, AIP-154
  # <https://aip.dev/154>.
  etag @2 :Text;
  # When this resource was soft-deleted, unset while it is live. AIP-164
  # <https://aip.dev/164>.
  deleteTime @3 :Wellknown.Timestamp;
  # When a soft-deleted resource is purged for good. AIP-164
  # <https://aip.dev/164>.
  expireTime @4 :Wellknown.Timestamp;
  # When this resource was created.
  createTime @5 :Wellknown.Timestamp;
  # When this resource was last modified.
  updateTime @6 :Wellknown.Timestamp;
  # proto field 8 was removed and reserved; this holds its ordinal.
  removed8 @7 :Void;
  # proto field 9 was removed and reserved; this holds its ordinal.
  removed9 @8 :Void;
  # proto field 10 was removed and reserved; this holds its ordinal.
  removed10 @9 :Void;
  # proto field 11 was removed and reserved; this holds its ordinal.
  removed11 @10 :Void;
  # proto field 12 was removed and reserved; this holds its ordinal.
  removed12 @11 :Void;
  # proto field 13 was removed and reserved; this holds its ordinal.
  removed13 @12 :Void;
  # proto field 14 was removed and reserved; this holds its ordinal.
  removed14 @13 :Void;
  # proto field 15 was removed and reserved; this holds its ordinal.
  removed15 @14 :Void;
  # Vehicle acceleration in X (longitudinal acceleration).
  #
  # Unit: m/s^2. VSS: Vehicle.Acceleration.Longitudinal (sensor).
  longitudinal @15 :Float64;
  # Vehicle acceleration in Y (lateral acceleration).
  #
  # Unit: m/s^2. VSS: Vehicle.Acceleration.Lateral (sensor).
  lateral @16 :Float64;
  # Vehicle acceleration in Z (vertical acceleration).
  #
  # Unit: m/s^2. VSS: Vehicle.Acceleration.Vertical (sensor).
  vertical @17 :Float64;
}
