@0xe357df1077810b1b;

# Code generated by protoc-gen-buffers. DO NOT EDIT.
# versions:
# 	protoc-gen-buffers dev
# 	protoc (unknown)
# source: protobuf/covesa/vss/motion/acceleration/v1/service.proto
#
# target: capnp
# field slots below are recorded in buffers.lock; edit the .proto, not this file
#
# https://github.com/the-protobuf-project/buffers
using Cxx = import "/capnp/c++.capnp";
$Cxx.namespace("protobuf::covesa::vss::motion::acceleration::v1");

using Acceleration = import "/protobuf/covesa/vss/motion/acceleration/v1/acceleration.capnp";
using Messages = import "/protobuf/covesa/vss/motion/acceleration/v1/messages.capnp";

# Accelerations manages the Acceleration branch of a vehicle.
#
# A **singleton**, AIP-156 <https://aip.dev/156>: a vehicle has exactly one,
# its name has no id segment, and it cannot be created or deleted
# independently of the vehicle. Get and Update are the whole surface.
#
# Reference: COVESA Vehicle Signal Specification.
# https://covesa.github.io/vehicle_signal_specification/
interface Accelerations @0x8aa7bded4da3d2e6 {
  # Retrieves one Acceleration.
  #
  # GET /v1/{name=vehicles/*/acceleration}
  #
  # Safe and idempotent. Read the `etag` here and pass it back on update to
  # make the write conditional.
  #
  # NOT_FOUND no such Acceleration
  # INVALID_ARGUMENT name does not match the resource pattern
  # PERMISSION_DENIED caller may not read it
  # AIP-131 standard method.
  getAcceleration @0 (request :Messages.GetAccelerationRequest) -> (response :Acceleration.Acceleration);

  # Updates a Acceleration.
  #
  # PATCH /v1/{acceleration.name=vehicles/*/acceleration}
  # body: the Acceleration itself
  #
  # A partial update: only fields named in `update_mask` are written. An
  # empty mask writes every mutable field, which will clear anything the
  # caller left unset -- pass a mask unless that is the intent.
  #
  # **Only an actuator is writable.** VSS marks each signal an attribute, a
  # sensor or an actuator; the first two are OUTPUT_ONLY here, because a
  # vehicle reports them and no API call can change them. A mask naming one
  # is rejected rather than silently ignored.
  #
  # Idempotent. Pass the `etag` read from Get to make the write conditional.
  #
  # NOT_FOUND no such Acceleration
  # ABORTED etag does not match the stored resource
  # INVALID_ARGUMENT mask names an unknown, immutable or read-only field
  # PERMISSION_DENIED caller may not modify it
  # AIP-134 standard method.
  updateAcceleration @1 (request :Messages.UpdateAccelerationRequest) -> (response :Acceleration.Acceleration);
}
