@0xe917c2a5448b4563;

# Code generated by protoc-gen-buffers. DO NOT EDIT.
# versions:
# 	protoc-gen-buffers dev
# 	protoc (unknown)
# source: protobuf/covesa/vss/exterior/body/v1/body.proto
#
# target: capnp
# field slots below are recorded in buffers.lock; edit the .proto, not this file
#
# https://github.com/the-protobuf-project/buffers
using Cxx = import "/capnp/c++.capnp";
$Cxx.namespace("protobuf::covesa::vss::exterior::body::v1");

using Hood = import "/protobuf/covesa/vss/exterior/body/v1/hood.capnp";
using Horn = import "/protobuf/covesa/vss/exterior/body/v1/horn.capnp";
using Lights = import "/protobuf/covesa/vss/exterior/body/v1/lights.capnp";
using Raindetection = import "/protobuf/covesa/vss/exterior/body/v1/raindetection.capnp";
using Wellknown = import "/buffers/wellknown.capnp";

# All body components.
#
# VSS: Vehicle.Body.
#
# A singleton child resource of Vehicle, AIP-156 <https://aip.dev/156>,
# named "vehicles/{vehicle}/body". Its parent is a declared resource in
# protobuf.covesa.vss.vehicle.v1, which is what makes this pattern legal
# rather than a reference to a collection nothing can create.
#
# Reference: COVESA Vehicle Signal Specification.
# https://covesa.github.io/vehicle_signal_specification/
struct Body @0xb6feb23f4f08da47 {
  # Resource name, "vehicles/{vehicle}/body". Assigned by the server.
  name @0 :Text;
  # Server-assigned unique id.
  uid @1 :Text;
  # Weak validator for optimistic concurrency, AIP-154
  # <https://aip.dev/154>.
  etag @2 :Text;
  # When this resource was soft-deleted, unset while it is live. AIP-164
  # <https://aip.dev/164>.
  deleteTime @3 :Wellknown.Timestamp;
  # When a soft-deleted resource is purged for good. AIP-164
  # <https://aip.dev/164>.
  expireTime @4 :Wellknown.Timestamp;
  # When this resource was created.
  createTime @5 :Wellknown.Timestamp;
  # When this resource was last modified.
  updateTime @6 :Wellknown.Timestamp;
  # proto field 8 was removed and reserved; this holds its ordinal.
  removed8 @7 :Void;
  # proto field 9 was removed and reserved; this holds its ordinal.
  removed9 @8 :Void;
  # proto field 10 was removed and reserved; this holds its ordinal.
  removed10 @9 :Void;
  # proto field 11 was removed and reserved; this holds its ordinal.
  removed11 @10 :Void;
  # proto field 12 was removed and reserved; this holds its ordinal.
  removed12 @11 :Void;
  # proto field 13 was removed and reserved; this holds its ordinal.
  removed13 @12 :Void;
  # proto field 14 was removed and reserved; this holds its ordinal.
  removed14 @13 :Void;
  # proto field 15 was removed and reserved; this holds its ordinal.
  removed15 @14 :Void;
  # Body type code as defined by ISO 3779.
  #
  # VSS: Vehicle.Body.BodyType (attribute).
  bodyType @15 :Text;
  # Hood status. Start position for Hood is Closed.
  #
  # The hood is the hinged cover over the engine compartment of a motor
  # vehicles. Depending on vehicle, it can be either in the front or back of
  # the vehicle. Luggage compartments are in VSS called trunks, even if they
  # are located at the front of the vehicle.
  #
  # VSS: Vehicle.Body.Hood.
  hood @16 :Hood.Hood;
  # Horn signals.
  #
  # VSS: Vehicle.Body.Horn.
  horn @17 :Horn.Horn;
  # Rain sensor signals.
  #
  # VSS: Vehicle.Body.Raindetection.
  raindetection @18 :Raindetection.Raindetection;
  # Exterior lights.
  #
  # VSS: Vehicle.Body.Lights.
  lights @19 :Lights.Lights;
  # Rear spoiler position, 0% = Spoiler fully stowed. 100% = Spoiler fully
  # exposed.
  #
  # Unit: percent. VSS: Vehicle.Body.RearMainSpoilerPosition (actuator).
  rearMainSpoilerPosition @20 :Float64;
  # Power optimization level for this branch/subsystem. A higher number
  # indicates more aggressive power optimization. Level 0 indicates that all
  # functionality is enabled, no power optimization enabled. Level 10
  # indicates most aggressive power optimization mode, only essential
  # functionality enabled.
  #
  # VSS: Vehicle.Body.PowerOptimizeLevel (actuator).
  powerOptimizeLevel @21 :Int32;
  # Auto Power Optimization Flag When set to 'true', the system enables
  # automatic power optimization, dynamically adjusting the power
  # optimization level based on runtime conditions or features managed by
  # the OEM. When set to 'false', manual control of the power optimization
  # level is allowed.
  #
  # VSS: Vehicle.Body.IsAutoPowerOptimize (actuator).
  isAutoPowerOptimize @22 :Bool;
}
