@0x8d585520bd20e602;

# Code generated by protoc-gen-buffers. DO NOT EDIT.
# versions:
# 	protoc-gen-buffers dev
# 	protoc (unknown)
# source: protobuf/covesa/vss/exterior/body/v1/brake.proto
#
# target: capnp
# field slots below are recorded in buffers.lock; edit the .proto, not this file
#
# https://github.com/the-protobuf-project/buffers
using Cxx = import "/capnp/c++.capnp";
$Cxx.namespace("protobuf::covesa::vss::exterior::body::v1");

# Indicates if break-light is active. INACTIVE means lights are off. ACTIVE
# means lights are on. ADAPTIVE means that break-light is indicating
# emergency-breaking.
#
# VSS: Vehicle.Body.Lights.Brake.IsActive.
# (buffers.v1.enumeration).underlying asked for 32 bits. A Cap'n Proto enum is
# always 16, with no way to declare otherwise; the narrowing is honoured by
# the FlatBuffers target only.
enum IsActive @0xab1c2408809e2273 {
  # Not specified.
  unspecified @0;
  # Inactive.
  inactive @1;
  # Active.
  active @2;
  # Adaptive.
  adaptive @3;
}

# Brake lights.
#
# VSS: Vehicle.Body.Lights.Brake.
#
# Reference: COVESA Vehicle Signal Specification.
# https://covesa.github.io/vehicle_signal_specification/
struct Brake @0xc303bd4328342fc0 {
  # Indicates if break-light is active. INACTIVE means lights are off.
  # ACTIVE means lights are on. ADAPTIVE means that break-light is
  # indicating emergency-breaking.
  #
  # VSS: Vehicle.Body.Lights.Brake.IsActive (actuator).
  isActive @0 :IsActive;
  # Indicates if light is defect. True = Light is defect. False = Light has
  # no defect.
  #
  # VSS: Vehicle.Body.Lights.Brake.IsDefect (sensor).
  isDefect @1 :Bool;
}
