@0xfeb4a7f516c26f35;

# Code generated by protoc-gen-buffers. DO NOT EDIT.
# versions:
# 	protoc-gen-buffers dev
# 	protoc (unknown)
# source: protobuf/covesa/vss/exterior/body/v1/hazard.proto
#
# target: capnp
# field slots below are recorded in buffers.lock; edit the .proto, not this file
#
# https://github.com/the-protobuf-project/buffers
using Cxx = import "/capnp/c++.capnp";
$Cxx.namespace("protobuf::covesa::vss::exterior::body::v1");

# Hazard lights.
#
# VSS: Vehicle.Body.Lights.Hazard.
#
# Reference: COVESA Vehicle Signal Specification.
# https://covesa.github.io/vehicle_signal_specification/
struct Hazard @0xf0a672553217dc2b {
  # Indicates if light is signaling or off. True = signaling. False = Off.
  #
  # VSS: Vehicle.Body.Lights.Hazard.IsSignaling (actuator).
  isSignaling @0 :Bool;
  # Indicates if light is defect. True = Light is defect. False = Light has
  # no defect.
  #
  # VSS: Vehicle.Body.Lights.Hazard.IsDefect (sensor).
  isDefect @1 :Bool;
}
