@0xf8bc7cfdf3a10b0d;

# Code generated by protoc-gen-buffers. DO NOT EDIT.
# versions:
# 	protoc-gen-buffers dev
# 	protoc (unknown)
# source: protobuf/covesa/vss/exterior/body/v1/horn.proto
#
# target: capnp
# field slots below are recorded in buffers.lock; edit the .proto, not this file
#
# https://github.com/the-protobuf-project/buffers
using Cxx = import "/capnp/c++.capnp";
$Cxx.namespace("protobuf::covesa::vss::exterior::body::v1");

# Horn signals.
#
# VSS: Vehicle.Body.Horn.
#
# Reference: COVESA Vehicle Signal Specification.
# https://covesa.github.io/vehicle_signal_specification/
struct Horn @0xf703f14f7ac5ccb3 {
  # Horn active or inactive. True = Active. False = Inactive.
  #
  # VSS: Vehicle.Body.Horn.IsActive (actuator).
  isActive @0 :Bool;
}
