@0xb522eea54875bf2c;

# Code generated by protoc-gen-buffers. DO NOT EDIT.
# versions:
# 	protoc-gen-buffers dev
# 	protoc (unknown)
# source: protobuf/covesa/vss/exterior/body/v1/license_plate.proto
#
# target: capnp
# field slots below are recorded in buffers.lock; edit the .proto, not this file
#
# https://github.com/the-protobuf-project/buffers
using Cxx = import "/capnp/c++.capnp";
$Cxx.namespace("protobuf::covesa::vss::exterior::body::v1");

# License plate lights.
#
# VSS: Vehicle.Body.Lights.LicensePlate.
#
# Reference: COVESA Vehicle Signal Specification.
# https://covesa.github.io/vehicle_signal_specification/
struct LicensePlate @0xb48bd754e5d007e5 {
  # Indicates if light is on or off. True = On. False = Off.
  #
  # VSS: Vehicle.Body.Lights.LicensePlate.IsOn (actuator).
  isOn @0 :Bool;
  # Indicates if light is defect. True = Light is defect. False = Light has
  # no defect.
  #
  # VSS: Vehicle.Body.Lights.LicensePlate.IsDefect (sensor).
  isDefect @1 :Bool;
}
