@0xb157e4d77092c8b3;

# Code generated by protoc-gen-buffers. DO NOT EDIT.
# versions:
# 	protoc-gen-buffers dev
# 	protoc (unknown)
# source: protobuf/covesa/vss/exterior/body/v1/lights.proto
#
# target: capnp
# field slots below are recorded in buffers.lock; edit the .proto, not this file
#
# https://github.com/the-protobuf-project/buffers
using Cxx = import "/capnp/c++.capnp";
$Cxx.namespace("protobuf::covesa::vss::exterior::body::v1");

using Backup = import "/protobuf/covesa/vss/exterior/body/v1/backup.capnp";
using Brake = import "/protobuf/covesa/vss/exterior/body/v1/brake.capnp";
using Hazard = import "/protobuf/covesa/vss/exterior/body/v1/hazard.capnp";
using LicensePlate = import "/protobuf/covesa/vss/exterior/body/v1/license_plate.capnp";
using Parking = import "/protobuf/covesa/vss/exterior/body/v1/parking.capnp";
using Running = import "/protobuf/covesa/vss/exterior/body/v1/running.capnp";

# Status of the vehicle main light switch.
#
# VSS: Vehicle.Body.Lights.LightSwitch.
# (buffers.v1.enumeration).underlying asked for 32 bits. A Cap'n Proto enum is
# always 16, with no way to declare otherwise; the narrowing is honoured by
# the FlatBuffers target only.
enum LightSwitch @0xd199fa39b4a7a958 {
  # Not specified.
  unspecified @0;
  # Off.
  off @1;
  # Position.
  position @2;
  # Daytime running lights.
  daytimeRunningLights @3;
  # Auto.
  auto @4;
  # Beam.
  beam @5;
}

# Exterior lights.
#
# VSS: Vehicle.Body.Lights.
#
# Reference: COVESA Vehicle Signal Specification.
# https://covesa.github.io/vehicle_signal_specification/
struct Lights @0x9b9119a6d3e77321 {
  # Status of the vehicle main light switch.
  #
  # A vehicle typically does not support all alternatives. Which lights that
  # actually are lit may vary according to vehicle configuration and local
  # legislation. OFF is typically indicated by 0. POSITION is typically
  # indicated by ISO 7000 symbol 0456. DAYTIME_RUNNING_LIGHTS (DRL) can be
  # indicated by ISO 7000 symbol 2611. AUTO indicates that vehicle
  # automatically selects suitable lights. BEAM is typically indicated by
  # ISO 7000 symbol 0083.
  #
  # VSS: Vehicle.Body.Lights.LightSwitch (actuator).
  lightSwitch @0 :LightSwitch;
  # Status of the high beam switch. True = high beam enabled. False = high
  # beam not enabled.
  #
  # This signal indicates the status of the switch and does not indicate if
  # low or high beam actually are on. That typically depends on vehicle
  # logic and other signals like Lights.LightSwitch and
  # Vehicle.LowVoltageSystemState.
  #
  # VSS: Vehicle.Body.Lights.IsHighBeamSwitchOn (actuator).
  isHighBeamSwitchOn @1 :Bool;
  # Daytime running lights (DRL).
  #
  # VSS: Vehicle.Body.Lights.Running.
  running @2 :Running.Running;
  # Backup lights.
  #
  # VSS: Vehicle.Body.Lights.Backup.
  backup @3 :Backup.Backup;
  # Parking lights.
  #
  # VSS: Vehicle.Body.Lights.Parking.
  parking @4 :Parking.Parking;
  # License plate lights.
  #
  # VSS: Vehicle.Body.Lights.LicensePlate.
  licensePlate @5 :LicensePlate.LicensePlate;
  # Brake lights.
  #
  # VSS: Vehicle.Body.Lights.Brake.
  brake @6 :Brake.Brake;
  # Hazard lights.
  #
  # VSS: Vehicle.Body.Lights.Hazard.
  hazard @7 :Hazard.Hazard;
}
