@0xd40f85cdb28c3b0c;

# Code generated by protoc-gen-buffers. DO NOT EDIT.
# versions:
# 	protoc-gen-buffers dev
# 	protoc (unknown)
# source: protobuf/covesa/vss/exterior/body/v1/messages.proto
#
# target: capnp
# field slots below are recorded in buffers.lock; edit the .proto, not this file
#
# https://github.com/the-protobuf-project/buffers
using Cxx = import "/capnp/c++.capnp";
$Cxx.namespace("protobuf::covesa::vss::exterior::body::v1");

using Body = import "/protobuf/covesa/vss/exterior/body/v1/body.capnp";

# Request message for Bodies.GetBody, AIP-131 <https://aip.dev/131>.
struct GetBodyRequest @0xe94e504ca4e5dac6 {
  # Name of the Body to retrieve, "vehicles/{vehicle}/body".
  # REQUIRED (AIP-203); Cap'n Proto cannot enforce it.
  name @0 :Text;
}

# Request message for Bodies.UpdateBody, AIP-134 <https://aip.dev/134>.
struct UpdateBodyRequest @0xc25ed7734680bb11 {
  # The Body to update. Its name field identifies the resource.
  # REQUIRED (AIP-203); Cap'n Proto cannot enforce it.
  body @0 :Body.Body;
  # Fields to update. An empty mask updates all mutable fields.
  #
  # Only an actuator is writable. A sensor or attribute named in the mask is
  # rejected: both are OUTPUT_ONLY, because a vehicle reports them and an
  # API cannot set them.
  updateMask @1 :List(Text);
}
