@0x8d1e0f86ca7d3da4;

# Code generated by protoc-gen-buffers. DO NOT EDIT.
# versions:
# 	protoc-gen-buffers dev
# 	protoc (unknown)
# source: protobuf/covesa/vss/exterior/body/v1/raindetection.proto
#
# target: capnp
# field slots below are recorded in buffers.lock; edit the .proto, not this file
#
# https://github.com/the-protobuf-project/buffers
using Cxx = import "/capnp/c++.capnp";
$Cxx.namespace("protobuf::covesa::vss::exterior::body::v1");

# Rain sensor signals.
#
# VSS: Vehicle.Body.Raindetection.
#
# Reference: COVESA Vehicle Signal Specification.
# https://covesa.github.io/vehicle_signal_specification/
struct Raindetection @0xe6340c877771bf46 {
  # Rain intensity. 0 = Dry, No Rain. 100 = Covered.
  #
  # Unit: percent. VSS: Vehicle.Body.Raindetection.Intensity (sensor).
  intensity @0 :Int32;
}
