@0xf1fdbc53ff0a3d8c;

# Code generated by protoc-gen-buffers. DO NOT EDIT.
# versions:
# 	protoc-gen-buffers dev
# 	protoc (unknown)
# source: protobuf/covesa/vss/exterior/body/v1/running.proto
#
# target: capnp
# field slots below are recorded in buffers.lock; edit the .proto, not this file
#
# https://github.com/the-protobuf-project/buffers
using Cxx = import "/capnp/c++.capnp";
$Cxx.namespace("protobuf::covesa::vss::exterior::body::v1");

# Daytime running lights (DRL).
#
# VSS: Vehicle.Body.Lights.Running.
#
# Reference: COVESA Vehicle Signal Specification.
# https://covesa.github.io/vehicle_signal_specification/
struct Running @0x8851eeca53c547cb {
  # Indicates if light is on or off. True = On. False = Off.
  #
  # VSS: Vehicle.Body.Lights.Running.IsOn (actuator).
  isOn @0 :Bool;
  # Indicates if light is defect. True = Light is defect. False = Light has
  # no defect.
  #
  # VSS: Vehicle.Body.Lights.Running.IsDefect (sensor).
  isDefect @1 :Bool;
}
