@0xbc88e222f143c8ce;

# Code generated by protoc-gen-buffers. DO NOT EDIT.
# versions:
# 	protoc-gen-buffers dev
# 	protoc (unknown)
# source: protobuf/covesa/vss/interior/door/v1/door.proto
#
# target: capnp
# field slots below are recorded in buffers.lock; edit the .proto, not this file
#
# https://github.com/the-protobuf-project/buffers
using Cxx = import "/capnp/c++.capnp";
$Cxx.namespace("protobuf::covesa::vss::interior::door::v1");

using Shade = import "/protobuf/covesa/vss/interior/door/v1/shade.capnp";
using Wellknown = import "/buffers/wellknown.capnp";
using Window = import "/protobuf/covesa/vss/interior/door/v1/window.capnp";

# Switch controlling sliding action such as window, sunroof, or blind.
#
# VSS: Vehicle.Cabin.Door.Switch.
# (buffers.v1.enumeration).underlying asked for 32 bits. A Cap'n Proto enum is
# always 16, with no way to declare otherwise; the narrowing is honoured by
# the FlatBuffers target only.
enum DoorSwitch @0x884d08da57266262 {
  # Not specified.
  unspecified @0;
  # Inactive.
  inactive @1;
  # Close.
  close @2;
  # Open.
  open @3;
  # One shot close.
  oneShotClose @4;
  # One shot open.
  oneShotOpen @5;
}

# All doors, including windows and switches.
#
# VSS: Vehicle.Cabin.Door.
#
# Instanced: Row1, Row2 × DriverSide, PassengerSide. The axes together name
# one occurrence, which is why each is a resource of its own rather than a
# repeated field.
#
# A child resource of Cabin, named "vehicles/{vehicle}/doors/{door}". Its
# parent is a declared resource in protobuf.covesa.vss.interior.cabin.v1,
# which is what makes this pattern legal rather than a reference to a
# collection nothing can create.
#
# Reference: COVESA Vehicle Signal Specification.
# https://covesa.github.io/vehicle_signal_specification/
struct Door @0x97e4f0868b6ea065 {
  # Resource name, "vehicles/{vehicle}/doors/{door}". Assigned by the
  # server.
  name @0 :Text;
  # Server-assigned unique id.
  uid @1 :Text;
  # Weak validator for optimistic concurrency, AIP-154
  # <https://aip.dev/154>.
  etag @2 :Text;
  # When this resource was soft-deleted, unset while it is live. AIP-164
  # <https://aip.dev/164>.
  deleteTime @3 :Wellknown.Timestamp;
  # When a soft-deleted resource is purged for good. AIP-164
  # <https://aip.dev/164>.
  expireTime @4 :Wellknown.Timestamp;
  # When this resource was created.
  createTime @5 :Wellknown.Timestamp;
  # When this resource was last modified.
  updateTime @6 :Wellknown.Timestamp;
  # proto field 8 was removed and reserved; this holds its ordinal.
  removed8 @7 :Void;
  # proto field 9 was removed and reserved; this holds its ordinal.
  removed9 @8 :Void;
  # proto field 10 was removed and reserved; this holds its ordinal.
  removed10 @9 :Void;
  # proto field 11 was removed and reserved; this holds its ordinal.
  removed11 @10 :Void;
  # proto field 12 was removed and reserved; this holds its ordinal.
  removed12 @11 :Void;
  # proto field 13 was removed and reserved; this holds its ordinal.
  removed13 @12 :Void;
  # proto field 14 was removed and reserved; this holds its ordinal.
  removed14 @13 :Void;
  # proto field 15 was removed and reserved; this holds its ordinal.
  removed15 @14 :Void;
  # Door window status. Start position for Window is Closed.
  #
  # VSS: Vehicle.Cabin.Door.Window.
  window @15 :Window.Window;
  # Is door child lock active. True = Door cannot be opened from inside.
  # False = Door can be opened from inside.
  #
  # VSS: Vehicle.Cabin.Door.IsChildLockActive (sensor).
  isChildLockActive @16 :Bool;
  # Side window shade. Open = Retracted, Closed = Deployed. Start position
  # for Shade is Open/Retracted.
  #
  # VSS: Vehicle.Cabin.Door.Shade.
  shade @17 :Shade.Shade;
  # Is item locked or unlocked. True = Locked. False = Unlocked.
  #
  # VSS: Vehicle.Cabin.Door.IsLocked (actuator).
  isLocked @18 :Bool;
  # Is item open or closed? True = Fully or partially open. False = Fully
  # closed.
  #
  # VSS: Vehicle.Cabin.Door.IsOpen (actuator).
  isOpen @19 :Bool;
  # Item position. 0 = Start position 100 = End position.
  #
  # Relationship between Open/Close and Start/End position is item
  # dependent.
  #
  # Unit: percent. VSS: Vehicle.Cabin.Door.Position (actuator).
  position @20 :Int32;
  # Switch controlling sliding action such as window, sunroof, or blind.
  #
  # VSS: Vehicle.Cabin.Door.Switch (actuator).
  switchControl @21 :DoorSwitch;
}
