@0x85492b39c983ee5c;

# Code generated by protoc-gen-buffers. DO NOT EDIT.
# versions:
# 	protoc-gen-buffers dev
# 	protoc (unknown)
# source: protobuf/covesa/vss/exterior/trailer/v1/messages.proto
#
# target: capnp
# field slots below are recorded in buffers.lock; edit the .proto, not this file
#
# https://github.com/the-protobuf-project/buffers
using Cxx = import "/capnp/c++.capnp";
$Cxx.namespace("protobuf::covesa::vss::exterior::trailer::v1");

using Trailer = import "/protobuf/covesa/vss/exterior/trailer/v1/trailer.capnp";

# Request message for Trailers.GetTrailer, AIP-131 <https://aip.dev/131>.
struct GetTrailerRequest @0x81f8eb530cb6b14d {
  # Name of the Trailer to retrieve, "vehicles/{vehicle}/trailer".
  # REQUIRED (AIP-203); Cap'n Proto cannot enforce it.
  name @0 :Text;
}

# Request message for Trailers.UpdateTrailer, AIP-134 <https://aip.dev/134>.
struct UpdateTrailerRequest @0xc453896e455b5a4b {
  # The Trailer to update. Its name field identifies the resource.
  # REQUIRED (AIP-203); Cap'n Proto cannot enforce it.
  trailer @0 :Trailer.Trailer;
  # Fields to update. An empty mask updates all mutable fields.
  #
  # Only an actuator is writable. A sensor or attribute named in the mask is
  # rejected: both are OUTPUT_ONLY, because a vehicle reports them and an
  # API cannot set them.
  updateMask @1 :List(Text);
}
