@0xb0348f122d3fc702;

# Code generated by protoc-gen-buffers. DO NOT EDIT.
# versions:
# 	protoc-gen-buffers dev
# 	protoc (unknown)
# source: protobuf/covesa/vss/platform/control_unit/v1/can.proto
#
# target: capnp
# field slots below are recorded in buffers.lock; edit the .proto, not this file
#
# https://github.com/the-protobuf-project/buffers
using Cxx = import "/capnp/c++.capnp";
$Cxx.namespace("protobuf::covesa::vss::platform::control_unit::v1");

# CAN network attributes and signals
#
# VSS: Vehicle.ControlUnit.Health.Network.CAN.
#
# Reference: COVESA Vehicle Signal Specification.
# https://covesa.github.io/vehicle_signal_specification/
struct Can @0xb3c76fce65fba9f5 {
  # Network status. True = No network problems detected. False = Network
  # problems detected.
  #
  # VSS: Vehicle.ControlUnit.Health.Network.CAN.IsNetworkOK (sensor).
  isNetworkOk @0 :Bool;
}
