@0xe84b27d9b749d01c;

# Code generated by protoc-gen-buffers. DO NOT EDIT.
# versions:
# 	protoc-gen-buffers dev
# 	protoc (unknown)
# source: protobuf/covesa/vss/platform/control_unit/v1/eth.proto
#
# target: capnp
# field slots below are recorded in buffers.lock; edit the .proto, not this file
#
# https://github.com/the-protobuf-project/buffers
using Cxx = import "/capnp/c++.capnp";
$Cxx.namespace("protobuf::covesa::vss::platform::control_unit::v1");

# Ethernet network attributes and signals
#
# VSS: Vehicle.ControlUnit.Health.Network.ETH.
#
# Reference: COVESA Vehicle Signal Specification.
# https://covesa.github.io/vehicle_signal_specification/
struct Eth @0x98fc1392a83af599 {
  # Network status. True = No network problems detected. False = Network
  # problems detected.
  #
  # VSS: Vehicle.ControlUnit.Health.Network.ETH.IsNetworkOK (sensor).
  isNetworkOk @0 :Bool;
}
