@0xfe3253306c268ba0;

# Code generated by protoc-gen-buffers. DO NOT EDIT.
# versions:
# 	protoc-gen-buffers dev
# 	protoc (unknown)
# source: protobuf/covesa/vss/platform/control_unit/v1/resources.proto
#
# target: capnp
# field slots below are recorded in buffers.lock; edit the .proto, not this file
#
# https://github.com/the-protobuf-project/buffers
using Cxx = import "/capnp/c++.capnp";
$Cxx.namespace("protobuf::covesa::vss::platform::control_unit::v1");

using Utilization = import "/protobuf/covesa/vss/platform/control_unit/v1/utilization.capnp";

# Resources attributes and signals
#
# VSS: Vehicle.ControlUnit.Health.Resources.
#
# Reference: COVESA Vehicle Signal Specification.
# https://covesa.github.io/vehicle_signal_specification/
struct Resources @0xe3114254eb77ce76 {
  # Power consumption
  #
  # Unit: W. VSS: Vehicle.ControlUnit.Health.Resources.Power (sensor).
  power @0 :Float64;
  # Instance temperature
  #
  # Unit: Celsius. VSS: Vehicle.ControlUnit.Health.Resources.Temperature
  # (sensor).
  temperature @1 :Float64;
  # Resources utilization branch
  #
  # VSS: Vehicle.ControlUnit.Health.Resources.Utilization.
  utilization @2 :Utilization.Utilization;
}
