@0xd32ffdc899b97e16;

# Code generated by protoc-gen-buffers. DO NOT EDIT.
# versions:
# 	protoc-gen-buffers dev
# 	protoc (unknown)
# source: protobuf/covesa/vss/platform/control_unit/v1/sw_supervision.proto
#
# target: capnp
# field slots below are recorded in buffers.lock; edit the .proto, not this file
#
# https://github.com/the-protobuf-project/buffers
using Cxx = import "/capnp/c++.capnp";
$Cxx.namespace("protobuf::covesa::vss::platform::control_unit::v1");

# SW supervision attributes and signals
#
# VSS: Vehicle.ControlUnit.Health.SWSupervision.
#
# Reference: COVESA Vehicle Signal Specification.
# https://covesa.github.io/vehicle_signal_specification/
struct SwSupervision @0xabbe7d89a55d2253 {
  # Whether the alive supervision was triggered
  #
  # VSS: Vehicle.ControlUnit.Health.SWSupervision.IsAliveTriggered (sensor).
  isAliveTriggered @0 :Bool;
  # Whether the deadline supervision was triggered
  #
  # VSS: Vehicle.ControlUnit.Health.SWSupervision.IsDeadlineTriggered
  # (sensor).
  isDeadlineTriggered @1 :Bool;
  # Whether the logical supervision was triggered
  #
  # VSS: Vehicle.ControlUnit.Health.SWSupervision.IsLogicalTriggered
  # (sensor).
  isLogicalTriggered @2 :Bool;
  # Whether the watchdog deadline was triggered
  #
  # VSS: Vehicle.ControlUnit.Health.SWSupervision.IsWatchdogTriggered
  # (sensor).
  isWatchdogTriggered @3 :Bool;
}
