@0xf350abd321168cf9;

# Code generated by protoc-gen-buffers. DO NOT EDIT.
# versions:
# 	protoc-gen-buffers dev
# 	protoc (unknown)
# source: protobuf/covesa/vss/platform/control_unit/v1/utilization.proto
#
# target: capnp
# field slots below are recorded in buffers.lock; edit the .proto, not this file
#
# https://github.com/the-protobuf-project/buffers
using Cxx = import "/capnp/c++.capnp";
$Cxx.namespace("protobuf::covesa::vss::platform::control_unit::v1");

# Resources utilization branch
#
# VSS: Vehicle.ControlUnit.Health.Resources.Utilization.
#
# Reference: COVESA Vehicle Signal Specification.
# https://covesa.github.io/vehicle_signal_specification/
struct Utilization @0xb096fa00eddbfcae {
  # CPU utilization
  #
  # Unit: percent. VSS: Vehicle.ControlUnit.Health.Resources.Utilization.CPU
  # (sensor).
  cpu @0 :Float64;
  # Memory utilization
  #
  # Unit: percent. VSS:
  # Vehicle.ControlUnit.Health.Resources.Utilization.Memory (sensor).
  memory @1 :Float64;
}
