@0xd46875c1d2569fe8;

# Code generated by protoc-gen-buffers. DO NOT EDIT.
# versions:
# 	protoc-gen-buffers dev
# 	protoc (unknown)
# source: protobuf/covesa/vss/motion/orientation/v1/messages.proto
#
# target: capnp
# field slots below are recorded in buffers.lock; edit the .proto, not this file
#
# https://github.com/the-protobuf-project/buffers
using Cxx = import "/capnp/c++.capnp";
$Cxx.namespace("protobuf::covesa::vss::motion::orientation::v1");

using Orientation = import "/protobuf/covesa/vss/motion/orientation/v1/orientation.capnp";

# Request message for Orientations.GetOrientation, AIP-131
# <https://aip.dev/131>.
struct GetOrientationRequest @0xb799a7141a333b9f {
  # Name of the Orientation to retrieve, "vehicles/{vehicle}/orientation".
  # REQUIRED (AIP-203); Cap'n Proto cannot enforce it.
  name @0 :Text;
}

# Request message for Orientations.UpdateOrientation, AIP-134
# <https://aip.dev/134>.
struct UpdateOrientationRequest @0xcb845e7399eab688 {
  # The Orientation to update. Its name field identifies the resource.
  # REQUIRED (AIP-203); Cap'n Proto cannot enforce it.
  orientation @0 :Orientation.Orientation;
  # Fields to update. An empty mask updates all mutable fields.
  #
  # Only an actuator is writable. A sensor or attribute named in the mask is
  # rejected: both are OUTPUT_ONLY, because a vehicle reports them and an
  # API cannot set them.
  updateMask @1 :List(Text);
}
