@0x870952f7dd4fb069;

# Code generated by protoc-gen-buffers. DO NOT EDIT.
# versions:
# 	protoc-gen-buffers dev
# 	protoc (unknown)
# source: protobuf/covesa/vss/interior/ambient_light/v1/ambient_light.proto
#
# target: capnp
# field slots below are recorded in buffers.lock; edit the .proto, not this file
#
# https://github.com/the-protobuf-project/buffers
using Cxx = import "/capnp/c++.capnp";
$Cxx.namespace("protobuf::covesa::vss::interior::ambient_light::v1");

using Wellknown = import "/buffers/wellknown.capnp";

# Decorative coloured light inside the cabin, usually mounted on the door,
# ceiling, etc.
#
# VSS: Vehicle.Cabin.Light.AmbientLight.
#
# Instanced: Row1, Row2 × DriverSide, PassengerSide. The axes together name
# one occurrence, which is why each is a resource of its own rather than a
# repeated field.
#
# A child resource of Cabin, named
# "vehicles/{vehicle}/ambientLights/{ambient_light}". Its parent is a
# declared resource in protobuf.covesa.vss.interior.cabin.v1, which is what
# makes this pattern legal rather than a reference to a collection nothing
# can create.
#
# Reference: COVESA Vehicle Signal Specification.
# https://covesa.github.io/vehicle_signal_specification/
struct AmbientLight @0xf258d4684fa8525d {
  # Resource name, "vehicles/{vehicle}/ambientLights/{ambient_light}".
  # Assigned by the server.
  name @0 :Text;
  # Server-assigned unique id.
  uid @1 :Text;
  # Weak validator for optimistic concurrency, AIP-154
  # <https://aip.dev/154>.
  etag @2 :Text;
  # When this resource was soft-deleted, unset while it is live. AIP-164
  # <https://aip.dev/164>.
  deleteTime @3 :Wellknown.Timestamp;
  # When a soft-deleted resource is purged for good. AIP-164
  # <https://aip.dev/164>.
  expireTime @4 :Wellknown.Timestamp;
  # When this resource was created.
  createTime @5 :Wellknown.Timestamp;
  # When this resource was last modified.
  updateTime @6 :Wellknown.Timestamp;
  # proto field 8 was removed and reserved; this holds its ordinal.
  removed8 @7 :Void;
  # proto field 9 was removed and reserved; this holds its ordinal.
  removed9 @8 :Void;
  # proto field 10 was removed and reserved; this holds its ordinal.
  removed10 @9 :Void;
  # proto field 11 was removed and reserved; this holds its ordinal.
  removed11 @10 :Void;
  # proto field 12 was removed and reserved; this holds its ordinal.
  removed12 @11 :Void;
  # proto field 13 was removed and reserved; this holds its ordinal.
  removed13 @12 :Void;
  # proto field 14 was removed and reserved; this holds its ordinal.
  removed14 @13 :Void;
  # proto field 15 was removed and reserved; this holds its ordinal.
  removed15 @14 :Void;
  # Indicates whether the light is turned on. True = On, False = Off.
  #
  # VSS: Vehicle.Cabin.Light.AmbientLight.IsLightOn (actuator).
  isLightOn @15 :Bool;
  # How much of the maximum possible brightness of the light is used. 1 =
  # Maximum attenuation, 100 = No attenuation (i.e. full brightness).
  #
  # Minimum value cannot be zero as on/off is controlled by the actuator
  # IsLightOn. V4.0 moved from Cabin.Lights.AmbientLight.Intensity to enable
  # individual control of lights via the SingleConfigurableLight.vspec.
  #
  # Unit: percent. VSS: Vehicle.Cabin.Light.AmbientLight.Intensity
  # (actuator).
  intensity @16 :Int32;
  # Hexadecimal color code represented as a 3-byte RGB (i.e. Red, Green, and
  # Blue) value preceded by a hash symbol "#". Allowed range "#000000" to
  # "#FFFFFF".
  #
  # For example; "#C0C0C0" = Silver, "#FFD700" = Gold, "#000000" = Black,
  # "#FFFFFF" = White, etc.
  #
  # VSS: Vehicle.Cabin.Light.AmbientLight.Color (actuator).
  color @17 :Text;
}
