@0xb8b2a74c139dc2c3;

# Code generated by protoc-gen-buffers. DO NOT EDIT.
# versions:
# 	protoc-gen-buffers dev
# 	protoc (unknown)
# source: protobuf/covesa/vss/interior/ambient_light/v1/messages.proto
#
# target: capnp
# field slots below are recorded in buffers.lock; edit the .proto, not this file
#
# https://github.com/the-protobuf-project/buffers
using Cxx = import "/capnp/c++.capnp";
$Cxx.namespace("protobuf::covesa::vss::interior::ambient_light::v1");

using AmbientLight = import "/protobuf/covesa/vss/interior/ambient_light/v1/ambient_light.capnp";

# Request message for AmbientLights.GetAmbientLight, AIP-131
# <https://aip.dev/131>.
struct GetAmbientLightRequest @0xfc1540b43c0f07ec {
  # Name of the AmbientLight to retrieve,
  # "vehicles/{vehicle}/ambientLights/{ambient_light}".
  # REQUIRED (AIP-203); Cap'n Proto cannot enforce it.
  name @0 :Text;
}

# Request message for AmbientLights.ListAmbientLights, AIP-132
# <https://aip.dev/132>.
struct ListAmbientLightsRequest @0xa9062df930b96e69 {
  # The Vehicle whose ambientLights to list, "vehicles/{vehicle}".
  # REQUIRED (AIP-203); Cap'n Proto cannot enforce it.
  parent @0 :Text;
  # Maximum ambientLights to return. Defaults to 50, capped at 1000.
  pageSize @1 :Int32;
  # Page token from a previous ListAmbientLightsResponse.next_page_token.
  pageToken @2 :Text;
  # Filter expression, AIP-160 <https://aip.dev/160>.
  filter @3 :Text;
  # Include soft-deleted ambientLights. AIP-164 <https://aip.dev/164>.
  showDeleted @4 :Bool;
}

# Response message for AmbientLights.ListAmbientLights, AIP-132
# <https://aip.dev/132>.
struct ListAmbientLightsResponse @0xecb53a61321fb747 {
  # The ambientLights on this page.
  ambientLights @0 :List(AmbientLight.AmbientLight);
  # Token for the next page, empty when this is the last page.
  nextPageToken @1 :Text;
}

# Request message for AmbientLights.CreateAmbientLight, AIP-133
# <https://aip.dev/133>.
struct CreateAmbientLightRequest @0xc78c8e0a5554e2b4 {
  # The Vehicle to create the AmbientLight under, "vehicles/{vehicle}".
  # REQUIRED (AIP-203); Cap'n Proto cannot enforce it.
  parent @0 :Text;
  # The AmbientLight to create.
  # REQUIRED (AIP-203); Cap'n Proto cannot enforce it.
  ambientLight @1 :AmbientLight.AmbientLight;
  # Client-assigned id, becoming the last segment of the resource name. The
  # server generates one when empty.
  ambientLightId @2 :Text;
}

# Request message for AmbientLights.UpdateAmbientLight, AIP-134
# <https://aip.dev/134>.
struct UpdateAmbientLightRequest @0xe26faead0d80a987 {
  # The AmbientLight to update. Its name field identifies the resource.
  # REQUIRED (AIP-203); Cap'n Proto cannot enforce it.
  ambientLight @0 :AmbientLight.AmbientLight;
  # Fields to update. An empty mask updates all mutable fields.
  #
  # Only an actuator is writable. A sensor or attribute named in the mask is
  # rejected: both are OUTPUT_ONLY, because a vehicle reports them and an
  # API cannot set them.
  updateMask @1 :List(Text);
}

# Request message for AmbientLights.DeleteAmbientLight, AIP-135
# <https://aip.dev/135>.
struct DeleteAmbientLightRequest @0xe2735c3dbd684be5 {
  # Name of the AmbientLight to delete,
  # "vehicles/{vehicle}/ambientLights/{ambient_light}".
  # REQUIRED (AIP-203); Cap'n Proto cannot enforce it.
  name @0 :Text;
}

# Request message for AmbientLights.UndeleteAmbientLight, AIP-164
# <https://aip.dev/164>.
struct UndeleteAmbientLightRequest @0x8270b88e882ccedb {
  # Name of the soft-deleted AmbientLight to restore,
  # "vehicles/{vehicle}/ambientLights/{ambient_light}".
  # REQUIRED (AIP-203); Cap'n Proto cannot enforce it.
  name @0 :Text;
}
